Repository dotnet/aspire, pull requests merged in 2024-12, with the labels that each got.

#6862 YARP Service discovery: do not set host header unless explicitly set in config
  src/Microsoft.Extensions.ServiceDiscovery.Yarp/ServiceDiscoveryDestinationResolver.cs
  tests/Microsoft.Extensions.ServiceDiscovery.Yarp.Tests/YarpServiceDiscoveryTests.cs
Labels: area-service-discovery

#6883 Support Arch Linux default path for dapr cli
  src/Aspire.Hosting.Dapr/DaprDistributedApplicationLifecycleHook.cs
Labels: community-contribution

#6827 Fix duplicate message rendering
  src/Components/Aspire.RabbitMQ.Client/RabbitMQEventSourceLogForwarder.cs
  tests/Aspire.RabbitMQ.Client.Tests/AspireRabbitMQLoggingTests.cs
Labels: community-contribution

#6880 Handle missing settings.json for Codespaces/Devcontainers
  .devcontainer/contributing/devcontainer.json
  src/Aspire.Hosting/Dashboard/DashboardLifecycleHook.cs
  src/Aspire.Hosting/Devcontainers/DevcontainerPortForwardingLifecycleHook.cs
  src/Aspire.Hosting/Devcontainers/DevcontainerSettingsWriter.cs
  src/Aspire.Hosting/DistributedApplicationBuilder.cs
  tests/Aspire.Hosting.Tests/Dashboard/DashboardLifecycleHookTests.cs
Labels: area-tooling

#6836 Remove inner exception from RMQ Logger when empty
  src/Components/Aspire.RabbitMQ.Client/RabbitMQEventSourceLogForwarder.cs
  tests/Aspire.RabbitMQ.Client.Tests/AspireRabbitMQLoggingTests.cs
Labels: community-contribution

#6917 Fix typo in DevContainers Extension link in machine requirements documentation
  docs/machine-requirements.md
Labels: community-contribution

#6312 Fix broken tests when running Config Schema Generator on .NET 9
  Directory.Packages.props
  eng/Versions.props
  src/Tools/ConfigurationSchemaGenerator/ConfigSchemaEmitter.cs
  src/Tools/ConfigurationSchemaGenerator/ConfigurationSchemaGenerator.csproj
  tests/ConfigurationSchemaGenerator.Tests/ConfigurationSchemaGenerator.Tests.csproj
Labels: community-contribution

#6893 Improvements to setting dashboard culture
  src/Aspire.Dashboard/Components/Dialogs/SettingsDialog.razor.cs
  src/Aspire.Dashboard/DashboardEndpointsBuilder.cs
  src/Aspire.Dashboard/DashboardWebApplication.cs
  src/Aspire.Dashboard/Utils/GlobalizationHelpers.cs
  tests/Aspire.Dashboard.Tests/GlobalizationHelpersTests.cs
Labels: area-dashboard

#6923 Consistent language order in dropdown
  src/Aspire.Dashboard/Components/Dialogs/SettingsDialog.razor.cs
Labels: area-dashboard

#6922 Improve command notification to show result if toast has closed
  src/Aspire.Dashboard/Model/DashboardCommandExecutor.cs
  src/Aspire.Dashboard/Utils/DashboardUIHelpers.cs
Labels: area-dashboard

#6900 Make opening visualizer the default grid value action
  src/Aspire.Dashboard/Components/Controls/Chart/PlotlyChart.razor.cs
  src/Aspire.Dashboard/Components/Controls/GridValue.razor
  src/Aspire.Dashboard/Components/Controls/GridValue.razor.cs
  src/Aspire.Dashboard/Components/Controls/GridValue.razor.css
  src/Aspire.Dashboard/Components/Controls/PropertyGrid.razor
  src/Aspire.Dashboard/Components/Controls/PropertyGrid.razor.cs
  src/Aspire.Dashboard/Components/Layout/MainLayout.razor.cs
  src/Aspire.Dashboard/Components/Pages/Resources.razor
  src/Aspire.Dashboard/Components/ResourcesGridColumns/SourceColumnDisplay.razor
  src/Aspire.Dashboard/Extensions/FluentUIExtensions.cs
  src/Aspire.Dashboard/Model/ResourceEndpointHelpers.cs
  src/Aspire.Dashboard/Model/ResourceSourceViewModel.cs
  src/Aspire.Dashboard/wwwroot/js/app.js
  tests/Aspire.Dashboard.Tests/Model/ResourceSourceViewModelTests.cs
Labels: area-dashboard

#6929 Add IServiceProvider to Nats Client Extensions
  src/Components/Aspire.NATS.Net/AspireNatsClientExtensions.cs
  src/Components/Aspire.NATS.Net/PublicAPI.Unshipped.txt
  tests/Aspire.NATS.Net.Tests/NatsClientPublicApiTests.cs
Labels: community-contribution

#6957 Fix menu icon alignment
  src/Aspire.Dashboard/Components/Controls/AspireMenuButton.razor
Labels: area-dashboard

#6938 Add Aspire metadata to MongoClient
  src/Components/Aspire.MongoDB.Driver/AspireMongoDBDriverExtensions.cs
Labels: community-contribution
