Repository dotnet/aspire, pull requests merged in 2024-07, with the labels that each got.

#4695 Setting minimum TLS to 1.2 by default
  src/Aspire.Hosting.Azure.Storage/AzureStorageExtensions.cs
  tests/Aspire.Hosting.Tests/Azure/AzureBicepResourceTests.cs
Labels: needs-area-label, community-contribution

#4668 Expose IServiceProvider on DistributedApplicationExecutionContext.
  src/Aspire.Hosting/DistributedApplicationBuilder.cs
  src/Aspire.Hosting/DistributedApplicationExecutionContext.cs
  src/Aspire.Hosting/DistributedApplicationExecutionContextOptions.cs
  src/Aspire.Hosting/PublicAPI.Unshipped.txt
  tests/Aspire.Hosting.Tests/Utils/EnvironmentVariableEvaluator.cs
  tests/Aspire.Hosting.Tests/WithEnvironmentTests.cs
Labels: area-app-model

#4743 Remove code coverage validation
  eng/pipelines/templates/VerifyCoverageReport.yml
Labels: area-engineering-systems

#4742 [ci] Fix internal build
  eng/pipelines/templates/BuildAndTest.yml
Labels: area-engineering-systems

#4633 Update repo Issue templates
  .github/ISSUE_TEMPLATE/10_bug_report.yml
  .github/ISSUE_TEMPLATE/20_feature-request.yml
  .github/ISSUE_TEMPLATE/30_api-proposal.md
  .github/ISSUE_TEMPLATE/config.yml
Labels: area-engineering-systems

#4726 [tests] Some Playwright related fixes
  tests/Aspire.Workload.Tests/EmptyTemplateRunTests.cs
  tests/Aspire.Workload.Tests/PerTestFrameworkTemplatesTests.cs
  tests/Aspire.Workload.Tests/StarterTemplateProjectNamesTests.cs
  tests/Aspire.Workload.Tests/StarterTemplateRunTestsBase.cs
  tests/Aspire.Workload.Tests/TemplateTests.cs
  tests/Aspire.Workload.Tests/WorkloadTestsBase.cs
  tests/Shared/Playwright/PlaywrightProvider.cs
  tests/Shared/WorkloadTesting/BuildEnvironment.cs
  tests/Shared/WorkloadTesting/EnvironmentVariables.cs
Labels: area-components

#4756 coalesce aws updates
  .github/dependabot.yml
Labels: area-engineering-systems

#4745 Bump Polly to 8.4.1
  .github/dependabot.yml
  Directory.Packages.props
Labels: area-codeflow, community-contribution

#4661 Use uniform convention for naming and annotating DCP objects with regards to OTEL
  src/Aspire.Dashboard/Components/Pages/ConsoleLogs.razor.cs
  src/Aspire.Dashboard/Model/Otlp/ApplicationsSelectHelpers.cs
  src/Aspire.Dashboard/Model/ResourceViewModel.cs
  src/Aspire.Dashboard/Otlp/Model/OtlpApplication.cs
  src/Aspire.Dashboard/ResourceService/DashboardClient.cs
  src/Aspire.Hosting/Dcp/ApplicationExecutor.cs
  src/Aspire.Hosting/Dcp/DcpVersion.cs
  src/Aspire.Hosting/Dcp/Model/ModelCommon.cs
  src/Aspire.Hosting/Dcp/ResourceLogSource.cs
  src/Aspire.Hosting/OtlpConfigurationExtensions.cs
  tests/Aspire.Dashboard.Tests/Model/ApplicationsSelectHelpersTests.cs
  tests/Aspire.Hosting.Tests/Azure/AzureBicepResourceTests.cs
  tests/Aspire.Hosting.Tests/Dapr/DaprTests.cs
  tests/Aspire.Hosting.Tests/Dashboard/DashboardResourceTests.cs
  tests/Aspire.Hosting.Tests/Dcp/ApplicationExecutorTests.cs
  tests/Aspire.Hosting.Tests/DistributedApplicationTests.cs
  tests/Aspire.Hosting.Tests/Helpers/KubernetesHelper.cs
  tests/Aspire.Hosting.Tests/KestrelConfigTests.cs
  tests/Aspire.Hosting.Tests/Milvus/AddMilvusTests.cs
  tests/Aspire.Hosting.Tests/MongoDB/AddMongoDBTests.cs
  tests/Aspire.Hosting.Tests/MySql/AddMySqlTests.cs
  tests/Aspire.Hosting.Tests/Oracle/AddOracleDatabaseTests.cs
  tests/Aspire.Hosting.Tests/Postgres/AddPostgresTests.cs
  tests/Aspire.Hosting.Tests/ProjectResourceTests.cs
  tests/Aspire.Hosting.Tests/Qdrant/AddQdrantTests.cs
  tests/Aspire.Hosting.Tests/Redis/AddRedisTests.cs
  tests/Aspire.Hosting.Tests/SqlServer/AddSqlServerTests.cs
  tests/Aspire.Hosting.Tests/Utils/TestServiceProvider.cs
  tests/Aspire.Hosting.Tests/WithEndpointTests.cs
  tests/Aspire.Hosting.Tests/WithEnvironmentTests.cs
  tests/Aspire.Hosting.Tests/WithReferenceTests.cs
Labels: area-app-model

#4772 Add WithDataVolume for AzureEventHubs emulator
  src/Aspire.Hosting.Azure.EventHubs/AzureEventHubsExtensions.cs
  src/Aspire.Hosting.Azure.EventHubs/PublicAPI.Unshipped.txt
  tests/Aspire.Hosting.Tests/Azure/AzureEventHubsExtensionsTests.cs
  tests/Aspire.Hosting.Tests/Azure/AzureResourceExtensionsTests.cs
Labels: area-components

#4758 [tests] Add E2E tests for EF SqlServer, and EF Cosmos
  tests/Aspire.EndToEnd.Tests/IntegrationServicesFixture.cs
  tests/Aspire.EndToEnd.Tests/IntegrationServicesTests.cs
  tests/testproject/Common/TestResourceNames.cs
  tests/testproject/Directory.Packages.Helix.props
  tests/testproject/TestProject.AppHost/TestProgram.cs
  tests/testproject/TestProject.IntegrationServiceA/Cosmos/EFCoreCosmosDbContext.cs
  tests/testproject/TestProject.IntegrationServiceA/Cosmos/EFCoreCosmosExtensions.cs
  tests/testproject/TestProject.IntegrationServiceA/Program.cs
  tests/testproject/TestProject.IntegrationServiceA/SqlServer/EFCoreSqlServerExtensions.cs
  tests/testproject/TestProject.IntegrationServiceA/SqlServer/SqlServerDbContext.cs
  tests/testproject/TestProject.IntegrationServiceA/TestProject.IntegrationServiceA.csproj
Labels: area-app-model, testing ☑️

#4780 Update dependabot.yml
  .github/dependabot.yml
Labels: area-engineering-systems

#4787 Fix Azurite support (#4279)
  src/Aspire.Hosting.Azure.Storage/AzureStorageExtensions.cs
Labels: area-components, Servicing-consider

#4698 Use composite key from OTEL service name and instance id
  src/Aspire.Dashboard/Components/Controls/Chart/ChartContainer.razor.cs
  src/Aspire.Dashboard/Components/Controls/ResourceSelect.razor
  src/Aspire.Dashboard/Components/Pages/ConsoleLogs.razor.cs
  src/Aspire.Dashboard/Components/Pages/Metrics.razor
  src/Aspire.Dashboard/Components/Pages/Metrics.razor.cs
  src/Aspire.Dashboard/Components/Pages/StructuredLogs.razor.cs
  src/Aspire.Dashboard/Components/Pages/TraceDetail.razor.cs
  src/Aspire.Dashboard/Components/Pages/Traces.razor.cs
  src/Aspire.Dashboard/Components/ResourcesGridColumns/UnreadLogErrorsBadge.razor.cs
  src/Aspire.Dashboard/Model/Otlp/ApplicationsSelectHelpers.cs
  src/Aspire.Dashboard/Model/ResourceTypeDetails.cs
  src/Aspire.Dashboard/Model/ResourceViewModel.cs
  src/Aspire.Dashboard/Model/StructuredLogsViewModel.cs
  src/Aspire.Dashboard/Model/TracesViewModel.cs
  src/Aspire.Dashboard/Otlp/Model/OtlpApplication.cs
  src/Aspire.Dashboard/Otlp/Model/OtlpHelpers.cs
  src/Aspire.Dashboard/Otlp/Storage/ApplicationKey.cs
  src/Aspire.Dashboard/Otlp/Storage/GetInstrumentRequest.cs
  src/Aspire.Dashboard/Otlp/Storage/GetLogsContext.cs
  src/Aspire.Dashboard/Otlp/Storage/GetTracesRequest.cs
  src/Aspire.Dashboard/Otlp/Storage/Subscription.cs
  src/Aspire.Dashboard/Otlp/Storage/TelemetryRepository.cs
  tests/Aspire.Dashboard.Tests/Model/ApplicationsSelectHelpersTests.cs
  tests/Aspire.Dashboard.Tests/TelemetryRepositoryTests/ApplicationKeyTests.cs
  tests/Aspire.Dashboard.Tests/TelemetryRepositoryTests/ApplicationTests.cs
  tests/Aspire.Dashboard.Tests/TelemetryRepositoryTests/LogTests.cs
  tests/Aspire.Dashboard.Tests/TelemetryRepositoryTests/MetricsTests.cs
  tests/Aspire.Dashboard.Tests/TelemetryRepositoryTests/TraceTests.cs
Labels: area-dashboard, area-telemetry

#4790 [ci] Enable source-index for the repo
  eng/pipelines/azure-pipelines.yml
Labels: area-engineering-systems

#4764 Telemetry name improvements
  src/Aspire.Dashboard/Model/ResourceOutgoingPeerResolver.cs
  src/Aspire.Dashboard/Model/ResourceViewModel.cs
  src/Aspire.Dashboard/Otlp/Model/OtlpApplication.cs
  src/Aspire.Dashboard/Otlp/Storage/ApplicationKey.cs
  src/Aspire.Dashboard/Otlp/Storage/TelemetryRepository.cs
  tests/Aspire.Dashboard.Tests/ResourceOutgoingPeerResolverTests.cs
  tests/Aspire.Dashboard.Tests/TelemetryRepositoryTests/ApplicationTests.cs
  tests/Aspire.Dashboard.Tests/TelemetryRepositoryTests/TraceTests.cs
Labels: area-dashboard, area-telemetry

#4789 Display more info when local orchestrator check fails with unexpected error
  src/Aspire.Hosting/Dcp/DcpDependencyCheck.cs
  src/Aspire.Hosting/Properties/Resources.Designer.cs
  src/Aspire.Hosting/Properties/Resources.resx
  src/Aspire.Hosting/Properties/xlf/Resources.cs.xlf
  src/Aspire.Hosting/Properties/xlf/Resources.de.xlf
  src/Aspire.Hosting/Properties/xlf/Resources.es.xlf
  src/Aspire.Hosting/Properties/xlf/Resources.fr.xlf
  src/Aspire.Hosting/Properties/xlf/Resources.it.xlf
  src/Aspire.Hosting/Properties/xlf/Resources.ja.xlf
  src/Aspire.Hosting/Properties/xlf/Resources.ko.xlf
  src/Aspire.Hosting/Properties/xlf/Resources.pl.xlf
  src/Aspire.Hosting/Properties/xlf/Resources.pt-BR.xlf
  src/Aspire.Hosting/Properties/xlf/Resources.ru.xlf
  src/Aspire.Hosting/Properties/xlf/Resources.tr.xlf
  src/Aspire.Hosting/Properties/xlf/Resources.zh-Hans.xlf
  src/Aspire.Hosting/Properties/xlf/Resources.zh-Hant.xlf
Labels: area-orchestrator

#4327 Pass IServiceProvider to configureBuilder of AddKafkaConsumer and AddKafkaProducer
  src/Components/Aspire.Confluent.Kafka/AspireKafkaConsumerExtensions.cs
  src/Components/Aspire.Confluent.Kafka/AspireKafkaProducerExtensions.cs
  src/Components/Aspire.Confluent.Kafka/PublicAPI.Unshipped.txt
  tests/Aspire.Confluent.Kafka.Tests/ConsumerConfigurationTests.cs
  tests/Aspire.Confluent.Kafka.Tests/ProducerConfigurationTests.cs
Labels: area-components, community-contribution

#4815 Insert the "Select a Resource" option in console logs after sort
  src/Aspire.Dashboard/Components/Pages/ConsoleLogs.razor.cs
Labels: area-dashboard

#4816 Update project template package versions to latest
  src/Aspire.ProjectTemplates/templates/aspire-mstest/Aspire.Tests.1.csproj
  src/Aspire.ProjectTemplates/templates/aspire-nunit/Aspire.Tests.1.csproj
  src/Aspire.ProjectTemplates/templates/aspire-starter/Aspire-StarterApplication.1.Tests/Aspire-StarterApplication.1.Tests.csproj
  src/Aspire.ProjectTemplates/templates/aspire-xunit/Aspire.Tests.1.csproj
Labels: area-templates

#4818 Update Plotly to 2.32.0
  src/Aspire.Dashboard/Components/App.razor
  src/Aspire.Dashboard/wwwroot/js/plotly-2.26.0.min.js
  src/Aspire.Dashboard/wwwroot/js/plotly-2.32.0.min.js
Labels: area-dashboard, area-telemetry

#4817 Don't log dashboard client cancellation error during dispose
  src/Aspire.Dashboard/ResourceService/DashboardClient.cs
Labels: area-dashboard

#4386 Add sample dashboard playwright test
  eng/pipelines/templates/BuildAndTest.yml
  src/Aspire.Dashboard/DashboardWebApplication.cs
  tests/Aspire.Dashboard.Tests/Aspire.Dashboard.Tests.csproj
  tests/Aspire.Dashboard.Tests/Integration/Playwright/AppBarTests.cs
  tests/Aspire.Dashboard.Tests/Integration/Playwright/DashboardServerFixture.cs
  tests/Aspire.Dashboard.Tests/Integration/Playwright/MockDashboardClient.cs
  tests/Aspire.Dashboard.Tests/Integration/Playwright/PlaywrightFixture.cs
  tests/Aspire.Dashboard.Tests/Integration/Playwright/PlaywrightTestsBase.cs
  tests/Shared/Playwright/PlaywrightProvider.cs
Labels: area-dashboard

#4829 Disable broken Containers tests
  tests/Aspire.Hosting.Containers.Tests/WithDockerfileTests.cs
Labels: area-app-model

#4832 Fix WithDockerfileTests container start failures.
  tests/Aspire.Hosting.Containers.Tests/WithDockerfileTests.cs
Labels: area-app-model

#4797 Update resource endpoints to always display at least one endpoint inline
  src/Aspire.Dashboard/Components/ResourcesGridColumns/EndpointsColumnDisplay.razor
  src/Aspire.Dashboard/Components/ResourcesGridColumns/EndpointsColumnDisplay.razor.css
  tests/Aspire.Workload.Tests/StarterTemplateRunTestsBase.cs
  tests/Aspire.Workload.Tests/WorkloadTestsBase.cs
  tests/Shared/WorkloadTesting/BuildEnvironment.cs
Labels: area-dashboard

#4468 Split redis tests into separate test assembly
  Aspire.sln
  src/Aspire.Hosting.Garnet/GarnetBuilderExtensions.cs
  src/Aspire.Hosting.Redis/Aspire.Hosting.Redis.csproj
  src/Aspire.Hosting.Redis/RedisBuilderExtensions.cs
  src/Aspire.Hosting.Valkey/ValkeyBuilderExtensions.cs
  tests/Aspire.Hosting.Containers.Tests/ContainerResourceBuilderTests.cs
  tests/Aspire.Hosting.Redis.Tests/AddRedisTests.cs
  tests/Aspire.Hosting.Redis.Tests/Aspire.Hosting.Redis.Tests.csproj
  tests/Aspire.Hosting.Redis.Tests/RedisFunctionalTests.cs
  tests/Aspire.Hosting.Tests/Aspire.Hosting.Tests.csproj
  tests/Aspire.Hosting.Tests/ManifestGenerationTests.cs
  tests/Aspire.Hosting.Tests/Utils/DockerUtils.cs
  tests/Aspire.Hosting.Tests/Utils/TestServiceProvider.cs
Labels: area-components

#4847 Remove dependency on dockerhub in Hosting.Redis.Tests
  tests/Aspire.Hosting.Redis.Tests/RedisFunctionalTests.cs
  tests/Aspire.Hosting.Tests/Utils/TestDistributedApplicationBuilder.cs
  tests/Aspire.StackExchange.Redis.Tests/RedisContainerFixture.cs
Labels: area-components

#4838 [tests] Enable playwright tests on linux
  tests/Aspire.Workload.Tests/EmptyTemplateRunTests.cs
  tests/Aspire.Workload.Tests/StarterTemplateRunTestsBase.cs
  tests/helix/send-to-helix-inner.proj
Labels: area-dashboard, testing ☑️

#4836 Use init with Blazor dependency injections
  src/Aspire.Dashboard/Components/Controls/Chart/ChartContainer.razor.cs
  src/Aspire.Dashboard/Components/Controls/SummaryDetailsView.razor.cs
  src/Aspire.Dashboard/Components/Controls/UserProfile.razor.cs
  src/Aspire.Dashboard/Components/Dialogs/FilterDialog.razor.cs
  src/Aspire.Dashboard/Components/Dialogs/SettingsDialog.razor.cs
  src/Aspire.Dashboard/Components/Pages/Login.razor.cs
  src/Aspire.Dashboard/Components/Pages/Metrics.razor.cs
  src/Aspire.Dashboard/Components/Pages/StructuredLogs.razor.cs
  src/Aspire.Dashboard/Components/Pages/TraceDetail.razor.cs
  src/Aspire.Dashboard/Components/Pages/Traces.razor.cs
  src/Aspire.Dashboard/Components/ResourcesGridColumns/StartTimeColumnDisplay.razor
Labels: area-dashboard

#4835 Write exception details with dashboard error logs
  src/Aspire.Hosting/Dashboard/DashboardLifecycleHook.cs
Labels: area-dashboard, area-app-model

#4848 Remove dependency on dockerhub in tests
  src/Aspire.Hosting.Valkey/ValkeyContainerImageTags.cs
  tests/Aspire.Components.Common.Tests/TestConstants.cs
  tests/Aspire.Hosting.Tests/ManifestGenerationTests.cs
  tests/Aspire.Hosting.Tests/Utils/TestDistributedApplicationBuilder.cs
  tests/Aspire.Milvus.Client.Tests/MilvusContainerFixture.cs
  tests/Aspire.MongoDB.Driver.Tests/MongoDbContainerFixture.cs
  tests/Aspire.MySqlConnector.Tests/MySqlContainerFixture.cs
  tests/Aspire.NATS.Net.Tests/NatsContainerFixture.cs
  tests/Aspire.Npgsql.Tests/PostgreSQLContainerFixture.cs
  tests/Aspire.RabbitMQ.Client.Tests/RabbitMQContainerFixture.cs
  tests/Aspire.StackExchange.Redis.Tests/RedisContainerFixture.cs
  tests/testproject/TestProject.AppHost/TestProgram.cs
Labels: needs-area-label, testing ☑️

#4837 Get endpoints column popup title from resource
  src/Aspire.Dashboard/Components/ResourcesGridColumns/EndpointsColumnDisplay.razor
  src/Aspire.Dashboard/Components/ResourcesGridColumns/EndpointsColumnDisplay.razor.cs
  src/Aspire.Dashboard/Resources/Columns.Designer.cs
  src/Aspire.Dashboard/Resources/Columns.resx
  src/Aspire.Dashboard/Resources/xlf/Columns.cs.xlf
  src/Aspire.Dashboard/Resources/xlf/Columns.de.xlf
  src/Aspire.Dashboard/Resources/xlf/Columns.es.xlf
  src/Aspire.Dashboard/Resources/xlf/Columns.fr.xlf
  src/Aspire.Dashboard/Resources/xlf/Columns.it.xlf
  src/Aspire.Dashboard/Resources/xlf/Columns.ja.xlf
  src/Aspire.Dashboard/Resources/xlf/Columns.ko.xlf
  src/Aspire.Dashboard/Resources/xlf/Columns.pl.xlf
  src/Aspire.Dashboard/Resources/xlf/Columns.pt-BR.xlf
  src/Aspire.Dashboard/Resources/xlf/Columns.ru.xlf
  src/Aspire.Dashboard/Resources/xlf/Columns.tr.xlf
  src/Aspire.Dashboard/Resources/xlf/Columns.zh-Hans.xlf
  src/Aspire.Dashboard/Resources/xlf/Columns.zh-Hant.xlf
Labels: area-dashboard

#4679 New WithEndpointsInEnvironment method
  src/Aspire.Hosting/ApplicationModel/EndpointEnvironmentInjectionFilterAnnotation.cs
  src/Aspire.Hosting/ApplicationModel/ProjectResource.cs
  src/Aspire.Hosting/ProjectResourceBuilderExtensions.cs
  src/Aspire.Hosting/PublicAPI.Unshipped.txt
  tests/Aspire.Hosting.Tests/Dcp/ApplicationExecutorTests.cs
  tests/Aspire.Hosting.Tests/KestrelConfigTests.cs
  tests/Aspire.Hosting.Tests/ProjectResourceTests.cs
  tests/Aspire.Hosting.Tests/WithEndpointTests.cs
Labels: area-app-model, community-contribution

#4795 ConfigSchemaGenerator: Ignore case and support named options
  src/Tools/ConfigurationSchemaGenerator/ConfigSchemaEmitter.cs
  tests/ConfigurationSchemaGenerator.Tests/GeneratorTests.cs
Labels: area-components, community-contribution

#4858 Update .NET SDK to 8.0.303
  global.json
Labels: area-components

#4861 Add doc on updating the container registry
  docs/updating-container-registry.md
Labels: needs-area-label

#4857 Load plotly as a module on metrics page
  src/Aspire.Dashboard/Components/App.razor
  src/Aspire.Dashboard/Components/Controls/Chart/ChartBase.cs
  src/Aspire.Dashboard/Components/Controls/Chart/PlotlyChart.razor.cs
  src/Aspire.Dashboard/wwwroot/js/app-metrics.js
  src/Aspire.Dashboard/wwwroot/js/app.js
  tests/Aspire.Dashboard.Components.Tests/Controls/PlotlyChartTests.cs
Labels: area-dashboard, area-telemetry

#4860 add TSA config
  .config/PoliCheckExclusions.xml
  .config/tsaoptions.json
  eng/pipelines/azure-pipelines.yml
Labels: area-engineering-systems

#4876 Make credscan run clean
  .config/CredScanSuppressions.json
  tests/Shared/TestCertificates/README.md
Labels: area-meta

#4888 Load theme JavaScript module earlier from HTML
  src/Aspire.Dashboard/Components/App.razor
  src/Aspire.Dashboard/Components/Dialogs/SettingsDialog.razor.cs
  src/Aspire.Dashboard/Components/Layout/MainLayout.razor.cs
  src/Aspire.Dashboard/wwwroot/js/app-theme.js
Labels: area-dashboard

#4798 Order endpoints in resource details
  src/Aspire.Dashboard/Components/Pages/Resources.razor.cs
  src/Aspire.Dashboard/Model/ResourceEndpointHelpers.cs
  tests/Aspire.Dashboard.Tests/Model/ResourceEndpointHelpersTests.cs
Labels: area-dashboard

#4841 Add cgmanifest.json for templates dependencies
  src/Aspire.ProjectTemplates/cgmanifest.json
Labels: area-templates

#4911 Update runtime, aspnetcore, and extensions versions in a single dependabot PR
  .github/dependabot.yml
Labels: area-codeflow

#4862 Extract Aspire.Hosting.PostgreSQL.Tests project
  Aspire.sln
  src/Aspire.Hosting.PostgreSQL/Aspire.Hosting.PostgreSQL.csproj
  src/Shared/SecretsStore.cs
  tests/Aspire.Hosting.PostgreSQL.Tests/AddPostgresTests.cs
  tests/Aspire.Hosting.PostgreSQL.Tests/Aspire.Hosting.PostgreSQL.Tests.csproj
  tests/Aspire.Hosting.PostgreSQL.Tests/PostgresFunctionalTests.cs
  tests/Aspire.Hosting.Tests/Aspire.Hosting.Tests.csproj
Labels: area-components

#4799 Add notification that structured log and trace limits have been exceeded
  playground/Stress/Stress.ApiService/Program.cs
  playground/Stress/Stress.ApiService/TraceCreator.cs
  src/Aspire.Dashboard/Components/Pages/StructuredLogs.razor.cs
  src/Aspire.Dashboard/Components/Pages/Traces.razor.cs
  src/Aspire.Dashboard/Otlp/Storage/TelemetryRepository.cs
  src/Aspire.Dashboard/Resources/StructuredLogs.Designer.cs
  src/Aspire.Dashboard/Resources/StructuredLogs.resx
  src/Aspire.Dashboard/Resources/Traces.Designer.cs
  src/Aspire.Dashboard/Resources/Traces.resx
  src/Aspire.Dashboard/Resources/xlf/StructuredLogs.cs.xlf
  src/Aspire.Dashboard/Resources/xlf/StructuredLogs.de.xlf
  src/Aspire.Dashboard/Resources/xlf/StructuredLogs.es.xlf
  src/Aspire.Dashboard/Resources/xlf/StructuredLogs.fr.xlf
  src/Aspire.Dashboard/Resources/xlf/StructuredLogs.it.xlf
  src/Aspire.Dashboard/Resources/xlf/StructuredLogs.ja.xlf
  src/Aspire.Dashboard/Resources/xlf/StructuredLogs.ko.xlf
  src/Aspire.Dashboard/Resources/xlf/StructuredLogs.pl.xlf
  src/Aspire.Dashboard/Resources/xlf/StructuredLogs.pt-BR.xlf
  src/Aspire.Dashboard/Resources/xlf/StructuredLogs.ru.xlf
  src/Aspire.Dashboard/Resources/xlf/StructuredLogs.tr.xlf
  src/Aspire.Dashboard/Resources/xlf/StructuredLogs.zh-Hans.xlf
  src/Aspire.Dashboard/Resources/xlf/StructuredLogs.zh-Hant.xlf
  src/Aspire.Dashboard/Resources/xlf/Traces.cs.xlf
  src/Aspire.Dashboard/Resources/xlf/Traces.de.xlf
  src/Aspire.Dashboard/Resources/xlf/Traces.es.xlf
  src/Aspire.Dashboard/Resources/xlf/Traces.fr.xlf
  src/Aspire.Dashboard/Resources/xlf/Traces.it.xlf
  src/Aspire.Dashboard/Resources/xlf/Traces.ja.xlf
  src/Aspire.Dashboard/Resources/xlf/Traces.ko.xlf
  src/Aspire.Dashboard/Resources/xlf/Traces.pl.xlf
  src/Aspire.Dashboard/Resources/xlf/Traces.pt-BR.xlf
  src/Aspire.Dashboard/Resources/xlf/Traces.ru.xlf
  src/Aspire.Dashboard/Resources/xlf/Traces.tr.xlf
  src/Aspire.Dashboard/Resources/xlf/Traces.zh-Hans.xlf
  src/Aspire.Dashboard/Resources/xlf/Traces.zh-Hant.xlf
  src/Aspire.Dashboard/wwwroot/css/app.css
Labels: area-dashboard

#4922 Revert "[tests] Enable playwright tests on linux (#4838)"
  tests/Aspire.Hosting.Qdrant.Tests/QdrantFunctionalTests.cs
  tests/Aspire.Workload.Tests/EmptyTemplateRunTests.cs
  tests/Aspire.Workload.Tests/StarterTemplateRunTestsBase.cs
  tests/helix/send-to-helix-inner.proj
Labels: testing ☑️

#4910 Extract Aspire.Hosting.Kafka.Tests project
  Aspire.sln
  tests/Aspire.EndToEnd.Tests/IntegrationServicesFixture.cs
  tests/Aspire.EndToEnd.Tests/IntegrationServicesTests.cs
  tests/Aspire.Hosting.Kafka.Tests/AddKafkaTests.cs
  tests/Aspire.Hosting.Kafka.Tests/Aspire.Hosting.Kafka.Tests.csproj
  tests/Aspire.Hosting.Kafka.Tests/KafkaFunctionalTests.cs
  tests/Aspire.Hosting.Tests/Aspire.Hosting.Tests.csproj
  tests/Aspire.Hosting.Tests/ManifestGenerationTests.cs
  tests/testproject/Common/TestResourceNames.cs
  tests/testproject/TestProject.AppHost/TestProgram.cs
  tests/testproject/TestProject.AppHost/TestProject.AppHost.csproj
  tests/testproject/TestProject.IntegrationServiceA/Kafka/KafkaExtensions.cs
  tests/testproject/TestProject.IntegrationServiceA/Program.cs
  tests/testproject/TestProject.IntegrationServiceA/TestProject.IntegrationServiceA.csproj
Labels: area-components

#4882 Add en-GB to supported Dashboard cultures
  src/Aspire.Dashboard/DashboardWebApplication.cs
Labels: area-dashboard, community-contribution

#4564 Persist selected application in the Traces page
  src/Aspire.Dashboard/Components/Pages/Traces.razor
  src/Aspire.Dashboard/Components/Pages/Traces.razor.cs
Labels: area-dashboard, community-contribution

#4932 Add resilience to Kafka functional tests
  tests/Aspire.Hosting.Kafka.Tests/KafkaFunctionalTests.cs
Labels: area-app-model

#4930 Extract Aspire.Hosting.Valkey.Tests project
  Aspire.sln
  tests/Aspire.EndToEnd.Tests/IntegrationServicesFixture.cs
  tests/Aspire.EndToEnd.Tests/IntegrationServicesTests.cs
  tests/Aspire.Hosting.Kafka.Tests/KafkaFunctionalTests.cs
  tests/Aspire.Hosting.PostgreSQL.Tests/PostgresFunctionalTests.cs
  tests/Aspire.Hosting.Qdrant.Tests/QdrantFunctionalTests.cs
  tests/Aspire.Hosting.Redis.Tests/RedisFunctionalTests.cs
  tests/Aspire.Hosting.Tests/Aspire.Hosting.Tests.csproj
  tests/Aspire.Hosting.Tests/ManifestGenerationTests.cs
  tests/Aspire.Hosting.Valkey.Tests/AddValkeyTests.cs
  tests/Aspire.Hosting.Valkey.Tests/Aspire.Hosting.Valkey.Tests.csproj
  tests/Aspire.Hosting.Valkey.Tests/ValkeyFunctionalTests.cs
  tests/testproject/Common/TestResourceNames.cs
  tests/testproject/TestProject.AppHost/TestProgram.cs
  tests/testproject/TestProject.AppHost/TestProject.AppHost.csproj
  tests/testproject/TestProject.IntegrationServiceA/Program.cs
  tests/testproject/TestProject.IntegrationServiceA/Valkey/ValkeyExtensions.cs
Labels: area-components

#4915 Extract Aspire.Hosting.Python.Tests project
  Aspire.sln
  tests/Aspire.Hosting.Python.Tests/AddPythonProjectTests.cs
  tests/Aspire.Hosting.Python.Tests/Aspire.Hosting.Python.Tests.csproj
  tests/Aspire.Hosting.Tests/Aspire.Hosting.Tests.csproj
  tests/Aspire.Hosting.Tests/Utils/TestDistributedApplicationBuilder.cs
Labels: area-components

#4805 Add span links to dashboard UI
  playground/Stress/Stress.ApiService/TraceCreator.cs
  src/Aspire.Dashboard/Components/Controls/Chart/ChartBase.cs
  src/Aspire.Dashboard/Components/Controls/Chart/PlotlyChart.razor.cs
  src/Aspire.Dashboard/Components/Controls/SpanDetails.razor
  src/Aspire.Dashboard/Components/Controls/SpanDetails.razor.cs
  src/Aspire.Dashboard/Components/Controls/SpanDetails.razor.css
  src/Aspire.Dashboard/Components/Dialogs/ExemplarsDialog.razor.cs
  src/Aspire.Dashboard/Components/Pages/TraceDetail.razor.cs
  src/Aspire.Dashboard/Model/MetricsHelpers.cs
  src/Aspire.Dashboard/Model/SpanDetailsViewModel.cs
  src/Aspire.Dashboard/Model/SpanLinkViewModel.cs
  src/Aspire.Dashboard/Otlp/Model/OtlpSpan.cs
  src/Aspire.Dashboard/Otlp/Model/OtlpSpanLink.cs
  src/Aspire.Dashboard/Otlp/Storage/TelemetryRepository.cs
  src/Aspire.Dashboard/Resources/ControlsStrings.Designer.cs
  src/Aspire.Dashboard/Resources/ControlsStrings.resx
  src/Aspire.Dashboard/Resources/xlf/ControlsStrings.cs.xlf
  src/Aspire.Dashboard/Resources/xlf/ControlsStrings.de.xlf
  src/Aspire.Dashboard/Resources/xlf/ControlsStrings.es.xlf
  src/Aspire.Dashboard/Resources/xlf/ControlsStrings.fr.xlf
  src/Aspire.Dashboard/Resources/xlf/ControlsStrings.it.xlf
  src/Aspire.Dashboard/Resources/xlf/ControlsStrings.ja.xlf
  src/Aspire.Dashboard/Resources/xlf/ControlsStrings.ko.xlf
  src/Aspire.Dashboard/Resources/xlf/ControlsStrings.pl.xlf
  src/Aspire.Dashboard/Resources/xlf/ControlsStrings.pt-BR.xlf
  src/Aspire.Dashboard/Resources/xlf/ControlsStrings.ru.xlf
  src/Aspire.Dashboard/Resources/xlf/ControlsStrings.tr.xlf
  src/Aspire.Dashboard/Resources/xlf/ControlsStrings.zh-Hans.xlf
  src/Aspire.Dashboard/Resources/xlf/ControlsStrings.zh-Hant.xlf
  src/Shared/CircularBuffer.cs
  tests/Aspire.Dashboard.Tests/CircularBufferTests.cs
  tests/Aspire.Dashboard.Tests/TelemetryRepositoryTests/TestHelpers.cs
  tests/Aspire.Dashboard.Tests/TelemetryRepositoryTests/TraceTests.cs
Labels: area-dashboard, area-telemetry

#4934 Fix metrics page
  src/Aspire.Dashboard/Components/Controls/Chart/ChartContainer.razor
Labels: area-dashboard

#4927 Add producer-consumer telemetry example to stress app
  playground/Stress/Stress.ApiService/ProducerConsumer.cs
  playground/Stress/Stress.ApiService/Program.cs
Labels: area-telemetry

#4935 Revert change to always display first endpoint
  src/Aspire.Dashboard/Components/ResourcesGridColumns/EndpointsColumnDisplay.razor
  src/Aspire.Dashboard/Components/ResourcesGridColumns/EndpointsColumnDisplay.razor.css
  tests/Aspire.Workload.Tests/WorkloadTestsBase.cs
Labels: area-dashboard

#4892 Create hover tokens for grid row hover effect
  src/Aspire.Dashboard/Components/Controls/PropertyGrid.razor
  src/Aspire.Dashboard/Components/Controls/ResourceDetails.razor
  src/Aspire.Dashboard/Components/Pages/Resources.razor
  src/Aspire.Dashboard/Components/Pages/StructuredLogs.razor
  src/Aspire.Dashboard/Components/Pages/TraceDetail.razor
  src/Aspire.Dashboard/Components/Pages/TraceDetail.razor.css
  src/Aspire.Dashboard/Components/Pages/Traces.razor
  src/Aspire.Dashboard/wwwroot/css/app.css
  src/Aspire.Dashboard/wwwroot/js/app-theme.js
  tests/Aspire.Workload.Tests/WorkloadTestsBase.cs
Labels: area-dashboard

#4774 DisableLocalAuth for AppConfig.
  playground/cdk/CdkSample.AppHost/appConfig.module.bicep
  playground/cdk/CdkSample.AppHost/storage.module.bicep
  src/Aspire.Hosting.Azure.AppConfiguration/AzureAppConfigurationExtensions.cs
  tests/Aspire.Hosting.Tests/Azure/AzureBicepResourceTests.cs
Labels: area-app-model, area-deployment, azure

#4923 [tests] Extract support for building tests outside the repo into re-usable props+targets
  Directory.Build.props
  tests/Aspire.EndToEnd.Tests/Aspire.EndToEnd.Tests.csproj
  tests/Aspire.EndToEnd.Tests/IntegrationServicesFixture.cs
  tests/Aspire.EndToEnd.Tests/README.md
  tests/Aspire.Hosting.Tests/Aspire.Hosting.Tests.csproj
  tests/Aspire.Hosting.Tests/Directory.Build.props
  tests/Aspire.Hosting.Tests/Directory.Build.targets
  tests/Aspire.Workload.Tests/Aspire.Workload.Tests.csproj
  tests/Directory.Build.props
  tests/Directory.Build.targets
  tests/Shared/Aspire.Workload.Testing.targets
  tests/Shared/EmptyProject.proj
  tests/Shared/RepoTesting/Aspire.RepoTesting.props
  tests/Shared/RepoTesting/Aspire.RepoTesting.targets
  tests/Shared/RepoTesting/Directory.Build.props
  tests/Shared/RepoTesting/Directory.Build.targets
  tests/Shared/RepoTesting/Directory.Packages.Helix.props
  tests/Shared/RepoTesting/Directory.Packages.props
  tests/Shared/RepoTesting/README.md
  tests/Shared/WorkloadTesting/Aspire.Shared.WorkloadTesting.targets
  tests/Shared/WorkloadTesting/AspireProject.cs
  tests/Shared/WorkloadTesting/BuildEnvironment.cs
  tests/Shared/WorkloadTesting/EnvironmentVariables.cs
  tests/Shared/WorkloadTesting/data/EndPointWriterHook_cs
  tests/Shared/WorkloadTesting/data/nuget8.config
  tests/Shared/nuget-with-package-source-mapping.config
  tests/TestingAppHost1/TestingAppHost1.AppHost/Directory.Build.props
  tests/TestingAppHost1/TestingAppHost1.AppHost/Directory.Build.targets
  tests/testproject/Directory.Build.Helix.targets
  tests/testproject/Directory.Build.props
  tests/testproject/Directory.Build.targets
  tests/testproject/Directory.Packages.props
  tests/testproject/TestProject.AppHost/Directory.Build.props
  tests/testproject/TestProject.AppHost/Directory.Build.targets
  tests/testproject/TestProject.AppHost/TestProject.AppHost.csproj
  tests/testproject/TestProject.IntegrationServiceA/TestProject.IntegrationServiceA.csproj
Labels: area-components, testing ☑️

#4953 Fixing README for Azure SQL hosting package
  src/Aspire.Hosting.Azure.Sql/README.md
Labels: needs-area-label, community-contribution

#4951 Fix Aspire.Hosting.Tests build on VS
  tests/Aspire.Hosting.Tests/Aspire.Hosting.Tests.csproj
Labels: area-components

#4430 add elasticsearch hosting
  Aspire.sln
  Directory.Packages.props
  playground/Elasticsearch/Elasticsearch.ApiService/Elasticsearch.ApiService.csproj
  playground/Elasticsearch/Elasticsearch.ApiService/Models/Person.cs
  playground/Elasticsearch/Elasticsearch.ApiService/Program.cs
  playground/Elasticsearch/Elasticsearch.ApiService/Properties/launchSettings.json
  playground/Elasticsearch/Elasticsearch.ApiService/appsettings.Development.json
  playground/Elasticsearch/Elasticsearch.ApiService/appsettings.json
  playground/Elasticsearch/Elasticsearch.AppHost/Directory.Build.props
  playground/Elasticsearch/Elasticsearch.AppHost/Directory.Build.targets
  playground/Elasticsearch/Elasticsearch.AppHost/Elasticsearch.AppHost.csproj
  playground/Elasticsearch/Elasticsearch.AppHost/Program.cs
  playground/Elasticsearch/Elasticsearch.AppHost/Properties/launchSettings.json
  playground/Elasticsearch/Elasticsearch.AppHost/appsettings.Development.json
  playground/Elasticsearch/Elasticsearch.AppHost/appsettings.json
  playground/Elasticsearch/Elasticsearch.AppHost/aspire-manifest.json
  src/Aspire.Hosting.Elasticsearch/Aspire.Hosting.Elasticsearch.csproj
  src/Aspire.Hosting.Elasticsearch/ElasticsearchBuilderExtensions.cs
  src/Aspire.Hosting.Elasticsearch/ElasticsearchContainerImageTags.cs
  src/Aspire.Hosting.Elasticsearch/ElasticsearchResource.cs
  src/Aspire.Hosting.Elasticsearch/PublicAPI.Shipped.txt
  src/Aspire.Hosting.Elasticsearch/PublicAPI.Unshipped.txt
  src/Components/Aspire.Elastic.Clients.Elasticsearch/Aspire.Elastic.Clients.Elasticsearch.csproj
  src/Components/Aspire.Elastic.Clients.Elasticsearch/AspireElasticClientsElasticsearchExtensions.cs
  src/Components/Aspire.Elastic.Clients.Elasticsearch/AssemblyInfo.cs
  src/Components/Aspire.Elastic.Clients.Elasticsearch/ConfigurationSchema.json
  src/Components/Aspire.Elastic.Clients.Elasticsearch/ElasticClientsElasticsearchSettings.cs
  src/Components/Aspire.Elastic.Clients.Elasticsearch/ElasticsearchHealthCheck.cs
  src/Components/Aspire.Elastic.Clients.Elasticsearch/PublicAPI.Shipped.txt
  src/Components/Aspire.Elastic.Clients.Elasticsearch/PublicAPI.Unshipped.txt
  src/Components/Aspire.Elastic.Clients.Elasticsearch/README.md
  src/Components/Aspire_Components_Progress.md
  src/Components/Telemetry.md
  src/Shared/Elastic_logo.png
  tests/Aspire.Elastic.Clients.Elasticsearch.Tests/Aspire.Elastic.Clients.Elasticsearch.Tests.csproj
  tests/Aspire.Elastic.Clients.Elasticsearch.Tests/AspireElasticClientExtensionsTest.cs
  tests/Aspire.Elastic.Clients.Elasticsearch.Tests/ConfigurationTests.cs
  tests/Aspire.Elastic.Clients.Elasticsearch.Tests/ConformanceTests.cs
  tests/Aspire.Elastic.Clients.Elasticsearch.Tests/ElasticsearchContainerFixture.cs
  tests/Aspire.Hosting.Elasticsearch.Tests/AddElasticsearchTests.cs
  tests/Aspire.Hosting.Elasticsearch.Tests/Aspire.Hosting.Elasticsearch.Tests.csproj
  tests/Aspire.Hosting.Elasticsearch.Tests/ElasticsearchFunctionalTests.cs
  tests/Aspire.Hosting.Tests/ManifestGenerationTests.cs
  tests/Shared/RepoTesting/Directory.Packages.Helix.props
Labels: area-app-model, area-components, community-contribution

#4936 Limit number of console log messages retained in dashboard process
  src/Aspire.Dashboard/Authentication/OpenIdConnect/AuthorizationPolicyBuilderExtensions.cs
  src/Aspire.Dashboard/Components/Controls/LogViewer.razor.cs
  src/Aspire.Dashboard/Components/Pages/ConsoleLogs.razor.cs
  src/Aspire.Dashboard/Configuration/DashboardOptions.cs
  src/Aspire.Dashboard/Configuration/ValidateDashboardOptions.cs
  src/Aspire.Dashboard/ConsoleLogs/LogEntries.cs
  src/Aspire.Dashboard/Model/LogViewerViewModel.cs
  src/Aspire.Dashboard/README.md
  src/Shared/DashboardConfigNames.cs
  tests/Aspire.Dashboard.Tests/ConsoleLogsTests/LogEntriesTests.cs
  tests/Aspire.Dashboard.Tests/DashboardOptionsTests.cs
Labels: area-dashboard

#4289 Add Keycloak component
  Aspire.sln
  Directory.Packages.props
  eng/Versions.props
  playground/keycloak/Keycloak.ApiService/Keycloak.ApiService.csproj
  playground/keycloak/Keycloak.ApiService/Program.cs
  playground/keycloak/Keycloak.ApiService/Properties/launchSettings.json
  playground/keycloak/Keycloak.ApiService/appsettings.Development.json
  playground/keycloak/Keycloak.ApiService/appsettings.json
  playground/keycloak/Keycloak.AppHost/Directory.Build.props
  playground/keycloak/Keycloak.AppHost/Directory.Build.targets
  playground/keycloak/Keycloak.AppHost/Keycloak.AppHost.csproj
  playground/keycloak/Keycloak.AppHost/Program.cs
  playground/keycloak/Keycloak.AppHost/Properties/launchSettings.json
  playground/keycloak/Keycloak.AppHost/appsettings.Development.json
  playground/keycloak/Keycloak.AppHost/appsettings.json
  playground/keycloak/Keycloak.Web/AuthorizationHandler.cs
  playground/keycloak/Keycloak.Web/Components/App.razor
  playground/keycloak/Keycloak.Web/Components/Layout/LoginDisplay.razor
  playground/keycloak/Keycloak.Web/Components/Layout/MainLayout.razor
  playground/keycloak/Keycloak.Web/Components/Layout/MainLayout.razor.css
  playground/keycloak/Keycloak.Web/Components/Layout/NavMenu.razor
  playground/keycloak/Keycloak.Web/Components/Layout/NavMenu.razor.css
  playground/keycloak/Keycloak.Web/Components/Pages/Error.razor
  playground/keycloak/Keycloak.Web/Components/Pages/Home.razor
  playground/keycloak/Keycloak.Web/Components/Routes.razor
  playground/keycloak/Keycloak.Web/Components/_Imports.razor
  playground/keycloak/Keycloak.Web/Keycloak.Web.csproj
  playground/keycloak/Keycloak.Web/LoginLogoutEndpointRouteBuilderExtensions.cs
  playground/keycloak/Keycloak.Web/Program.cs
  playground/keycloak/Keycloak.Web/Properties/launchSettings.json
  playground/keycloak/Keycloak.Web/WeatherApiClient.cs
  playground/keycloak/Keycloak.Web/appsettings.Development.json
  playground/keycloak/Keycloak.Web/appsettings.json
  playground/keycloak/Keycloak.Web/wwwroot/app.css
  playground/keycloak/Keycloak.Web/wwwroot/bootstrap/bootstrap.min.css
  playground/keycloak/Keycloak.Web/wwwroot/bootstrap/bootstrap.min.css.map
  playground/keycloak/Keycloak.Web/wwwroot/favicon.png
  playground/keycloak/README.md
  playground/keycloak/realms/weathershop-realm.json
  src/Aspire.Hosting.Keycloak/Aspire.Hosting.Keycloak.csproj
  src/Aspire.Hosting.Keycloak/KeycloakContainerImageTags.cs
  src/Aspire.Hosting.Keycloak/KeycloakResource.cs
  src/Aspire.Hosting.Keycloak/KeycloakResourceBuilderExtensions.cs
  src/Aspire.Hosting.Keycloak/PublicAPI.Shipped.txt
  src/Aspire.Hosting.Keycloak/PublicAPI.Unshipped.txt
  src/Aspire.Hosting.Keycloak/README.md
  src/Aspire.Hosting/Aspire.Hosting.csproj
  src/Components/Aspire.Keycloak.Authentication/Aspire.Keycloak.Authentication.csproj
  src/Components/Aspire.Keycloak.Authentication/AspireKeycloakExtensions.cs
  src/Components/Aspire.Keycloak.Authentication/PublicAPI.Shipped.txt
  src/Components/Aspire.Keycloak.Authentication/PublicAPI.Unshipped.txt
  src/Components/Aspire.Keycloak.Authentication/README.md
  tests/Aspire.Hosting.Keycloak.Tests/.runsettings
  tests/Aspire.Hosting.Keycloak.Tests/Aspire.Hosting.Keycloak.Tests.csproj
  tests/Aspire.Hosting.Keycloak.Tests/KeycloakResourceBuilderTests.cs
  tests/Aspire.Hosting.Tests/Aspire.Hosting.Tests.csproj
  tests/Aspire.Keycloak.Authentication.Tests/Aspire.Keycloak.Authentication.Tests.csproj
  tests/Aspire.Keycloak.Authentication.Tests/AspireKeycloakExtensionTests.cs
Labels: area-components, community-contribution

#4744 Disabling key access for storage by default.
  src/Aspire.Hosting.Azure.Storage/AzureStorageExtensions.cs
  tests/Aspire.Hosting.Tests/Azure/AzureBicepResourceTests.cs
Labels: area-app-model, community-contribution, security 🔐

#4926 Add test for PostgresServerResource.WithInitBindMount
  src/Aspire.Hosting.PostgreSQL/Aspire.Hosting.PostgreSQL.csproj
  tests/Aspire.Hosting.PostgreSQL.Tests/Aspire.Hosting.PostgreSQL.Tests.csproj
  tests/Aspire.Hosting.PostgreSQL.Tests/PostgresFunctionalTests.cs
  tests/Aspire.Hosting.Tests/Aspire.Hosting.Tests.csproj
Labels: area-components

#4950 Update to Azure.AI.OpenAI 2.0.0-beta.2
  Directory.Packages.props
  playground/OpenAIEndToEnd/OpenAIEndToEnd.WebStory/Components/Pages/Home.razor
  src/Components/Aspire.Azure.AI.OpenAI/Aspire.Azure.AI.OpenAI.csproj
  src/Components/Aspire.Azure.AI.OpenAI/AspireAzureOpenAIExtensions.cs
  src/Components/Aspire.Azure.AI.OpenAI/AssemblyInfo.cs
  src/Components/Aspire.Azure.AI.OpenAI/ConfigurationSchema.json
  src/Components/Aspire.Azure.AI.OpenAI/PublicAPI.Unshipped.txt
  src/Components/Aspire.Azure.AI.OpenAI/README.md
  tests/Aspire.Azure.AI.OpenAI.Tests/AspireAzureAIOpenAIExtensionsTests.cs
  tests/Aspire.Azure.AI.OpenAI.Tests/ConformanceTests.cs
Labels: area-components

#4969 Skip Aspire.Hosting.Elasticsearch.Tests.ElasticsearchFunctionalTestsWithDataVolumeShouldPersistStateBetweenUsages/WithDataBindMountShouldPersistStateBetweenUsages tests failing CI
  tests/Aspire.Hosting.Elasticsearch.Tests/ElasticsearchFunctionalTests.cs
Labels: area-app-model

#4948 Various fixes for span links UI
  src/Aspire.Dashboard/Components/Controls/PropertyGrid.razor
  src/Aspire.Dashboard/Components/Controls/PropertyGrid.razor.cs
  src/Aspire.Dashboard/Components/Controls/SpanDetails.razor
Labels: area-dashboard

#4957 Clear log messages when disposed
  src/Aspire.Dashboard/Components/Controls/LogViewer.razor.cs
  src/Aspire.Dashboard/ConsoleLogs/LogEntries.cs
  tests/Aspire.Dashboard.Tests/ConsoleLogsTests/LogEntriesTests.cs
Labels: area-dashboard

#4967 Null out resource name when application is changed
  src/Aspire.Dashboard/Components/Controls/LogViewer.razor.cs
Labels: area-dashboard

#4939 Don't display browser tooltip for error icon
  src/Aspire.Dashboard/Components/ResourcesGridColumns/LogMessageColumnDisplay.razor
Labels: area-dashboard

#4978 Fix resources title position
  src/Aspire.Dashboard/Components/Layout/AspirePageContentLayout.razor.css
  src/Aspire.Dashboard/Components/Pages/Resources.razor.css
Labels: area-dashboard

#4985 Remove testuser from Keycloak playground realm
  playground/keycloak/README.md
  playground/keycloak/realms/weathershop-realm.json
Labels: needs-area-label, community-contribution

#4971 Update OpenAIEndToEnd app
  playground/OpenAIEndToEnd/OpenAIEndToEnd.AppHost/Program.cs
  playground/OpenAIEndToEnd/OpenAIEndToEnd.WebStory/Components/Pages/Home.razor
Labels: area-components

#4986 Enable TSA upload
  eng/pipelines/azure-pipelines.yml
Labels: area-engineering-systems

#4988 Follow up from Keycloak PR
  Aspire.sln
  src/Aspire.Hosting/Aspire.Hosting.csproj
  tests/Aspire.Hosting.Keycloak.Tests/KeycloakResourceBuilderTests.cs
  tests/Aspire.Hosting.Tests/Aspire.Hosting.Tests.csproj
Labels: area-components

#4989 [release/8.1] Enable full signing and stable package versions
  eng/Versions.props
  eng/pipelines/azure-pipelines.yml
  eng/pipelines/common-variables.yml
  src/Aspire.Hosting.Azure.WebPubSub/Aspire.Hosting.Azure.WebPubSub.csproj
  src/Directory.Build.targets
  tests/Aspire.EndToEnd.Tests/Aspire.EndToEnd.Tests.csproj
  tests/Shared/Aspire.Workload.Testing.targets
  tests/Shared/RepoTesting/Directory.Packages.Helix.props
Labels: needs-area-label

#4990 Update dependencies
  Directory.Packages.props
  eng/Versions.props
  tests/Aspire.Elastic.Clients.Elasticsearch.Tests/ElasticsearchContainerFixture.cs
Labels: area-components

#4997 Fix Elasticsearch Client Component Readme
  src/Components/Aspire.Elastic.Clients.Elasticsearch/README.md
Labels: area-components, community-contribution

#4530 Add ```GetEnvironmentVariableValuesAsync``` method to ResourceExtensions
  src/Aspire.Hosting/ApplicationModel/ResourceExtensions.cs
  src/Aspire.Hosting/PublicAPI.Unshipped.txt
  tests/Aspire.Hosting.Tests/ResourceExtensionsTests.cs
Labels: area-app-model, community-contribution

#5006 Remove WithBuildSecret(FileInfo).
  playground/withdockerfile/WithDockerfile.AppHost/Program.cs
  playground/withdockerfile/WithDockerfile.AppHost/qots/Dockerfile
  src/Aspire.Hosting/ContainerResourceBuilderExtensions.cs
  src/Aspire.Hosting/PublicAPI.Unshipped.txt
  tests/Aspire.Hosting.Containers.Tests/WithDockerfileTests.cs
Labels: area-app-model

#5005 [release/8.1] Backport: Add ```GetEnvironmentVariableValuesAsync``` method to ResourceExtens…
  src/Aspire.Hosting/ApplicationModel/ResourceExtensions.cs
  src/Aspire.Hosting/PublicAPI.Unshipped.txt
  tests/Aspire.Hosting.Tests/ResourceExtensionsTests.cs
Labels: area-app-model

#4994 Branding updates for 8.1.1
  eng/Versions.props
Labels: area-codeflow

#5008 Use replica set name for OTEL service when replicas > 1
  src/Aspire.Hosting/Dcp/ApplicationExecutor.cs
  tests/Aspire.Hosting.Tests/Dcp/ApplicationExecutorTests.cs
Labels: area-dashboard

#4875 Extract Aspire.Hosting.Milvus.Tests project
  Aspire.sln
  tests/Aspire.EndToEnd.Tests/IntegrationServicesFixture.cs
  tests/Aspire.EndToEnd.Tests/IntegrationServicesTests.cs
  tests/Aspire.Hosting.Milvus.Tests/AddMilvusTests.cs
  tests/Aspire.Hosting.Milvus.Tests/Aspire.Hosting.Milvus.Tests.csproj
  tests/Aspire.Hosting.Milvus.Tests/MilvusFunctionalTests.cs
  tests/Aspire.Hosting.Tests/Aspire.Hosting.Tests.csproj
  tests/Aspire.Hosting.Tests/ManifestGenerationTests.cs
  tests/testproject/Common/TestResourceNames.cs
  tests/testproject/TestProject.AppHost/TestProgram.cs
  tests/testproject/TestProject.AppHost/TestProject.AppHost.csproj
  tests/testproject/TestProject.IntegrationServiceA/Milvus/MilvusExtensions.cs
  tests/testproject/TestProject.IntegrationServiceA/Program.cs
  tests/testproject/TestProject.IntegrationServiceA/TestProject.IntegrationServiceA.csproj
Labels: area-codeflow, community-contribution

#4992 make policheck nearly clean
  .config/PoliCheckExclusions.xml
  playground/AzureSearchEndToEnd/AzureSearch.ApiService/Program.cs
  playground/AzureSearchEndToEnd/AzureSearch.ApiService/hotels.json
Labels: area-engineering-systems

#5021 Add value formatting to stress playground app
  playground/Stress/Stress.ApiService/Program.cs
  playground/Stress/Stress.ApiService/Stress.ApiService.csproj
  playground/Stress/Stress.ApiService/content/books.xml
  playground/Stress/Stress.ApiService/content/example.json
Labels: area-dashboard

#5023 Update StructuredLogs to use LogFilter fields
  src/Aspire.Dashboard/Components/Pages/StructuredLogs.razor.cs
Labels: area-dashboard, community-contribution

#5024 Add IResourceWithServiceDiscovery interface to PythonProjectResource.
  src/Aspire.Hosting.Python/PythonProjectResource.cs
Labels: area-app-model

#5032 Merge branch release/8.1 into main
  src/Aspire.Hosting.Azure.WebPubSub/Aspire.Hosting.Azure.WebPubSub.csproj
  src/Directory.Build.targets
  tests/Shared/Aspire.Workload.Testing.targets
Labels: area-codeflow

#5013 Extract Aspire.Hosting.Azure.Tests
  Aspire.sln
  src/Aspire.Hosting.Azure.AppConfiguration/Aspire.Hosting.Azure.AppConfiguration.csproj
  src/Aspire.Hosting.Azure.ApplicationInsights/Aspire.Hosting.Azure.ApplicationInsights.csproj
  src/Aspire.Hosting.Azure.CognitiveServices/Aspire.Hosting.Azure.CognitiveServices.csproj
  src/Aspire.Hosting.Azure.CosmosDB/Aspire.Hosting.Azure.CosmosDB.csproj
  src/Aspire.Hosting.Azure.CosmosDB/AzureCosmosDBEmulatorConnectionString.cs
  src/Aspire.Hosting.Azure.CosmosDB/AzureCosmosDBResource.cs
  src/Aspire.Hosting.Azure.KeyVault/Aspire.Hosting.Azure.KeyVault.csproj
  src/Aspire.Hosting.Azure.OperationalInsights/Aspire.Hosting.Azure.OperationalInsights.csproj
  src/Aspire.Hosting.Azure.PostgreSQL/Aspire.Hosting.Azure.PostgreSQL.csproj
  src/Aspire.Hosting.Azure.Redis/Aspire.Hosting.Azure.Redis.csproj
  src/Aspire.Hosting.Azure.Search/Aspire.Hosting.Azure.Search.csproj
  src/Aspire.Hosting.Azure.ServiceBus/Aspire.Hosting.Azure.ServiceBus.csproj
  src/Aspire.Hosting.Azure.SignalR/Aspire.Hosting.Azure.SignalR.csproj
  src/Aspire.Hosting.Azure.Sql/Aspire.Hosting.Azure.Sql.csproj
  src/Aspire.Hosting.Azure.Storage/Aspire.Hosting.Azure.Storage.csproj
  src/Aspire.Hosting.Azure.Storage/AzureStorageEmulatorConnectionString.cs
  src/Aspire.Hosting.Azure.Storage/AzureStorageResource.cs
  src/Aspire.Hosting.Azure.WebPubSub/Aspire.Hosting.Azure.WebPubSub.csproj
  src/Aspire.Hosting.Azure/Aspire.Hosting.Azure.csproj
  src/Aspire.Hosting.Azure/Exceptions.cs
  tests/Aspire.Hosting.Azure.Tests/Aspire.Hosting.Azure.Tests.csproj
  tests/Aspire.Hosting.Azure.Tests/AzureBicepProvisionerTests.cs
  tests/Aspire.Hosting.Azure.Tests/AzureBicepResourceTests.cs
  tests/Aspire.Hosting.Azure.Tests/AzureEventHubsExtensionsTests.cs
  tests/Aspire.Hosting.Azure.Tests/AzureResourceExtensionsTests.cs
  tests/Aspire.Hosting.Azure.Tests/AzureSchemaTests.cs
  tests/Aspire.Hosting.Azure.Tests/ResourceGroupNameHelpersTests.cs
  tests/Aspire.Hosting.Tests.SharedShim/Aspire.Hosting.Tests.SharedShim.csproj
  tests/Aspire.Hosting.Tests/Aspire.Hosting.Tests.csproj
  tests/Aspire.Hosting.Tests/Schema/SchemaTests.cs
  tests/Aspire.Hosting.Tests/Utils/VolumeNameGeneratorTests.cs
Labels: area-components

#5058 [tests] Work around sqlserver 2022-latest latest image breaking with testcontainers
  tests/Aspire.Microsoft.Data.SqlClient.Tests/SqlServerContainerFixture.cs
Labels: area-components, testing ☑️

#5063 Update to FluentUI 4.9.3
  Directory.Packages.props
Labels: area-components

#5046 Add test meter to stress app with meter and instrument tags
  playground/Stress/Stress.ApiService/Program.cs
  playground/Stress/Stress.ApiService/TestMetrics.cs
Labels: area-dashboard

#4976 Improve overflow with OverflowItemFixed.Ellipsis
  playground/Stress/Stress.ApiService/Program.cs
  src/Aspire.Dashboard/Components/Controls/Chart/ChartFilters.razor
  src/Aspire.Dashboard/Components/Controls/Chart/ChartFilters.razor.css
  src/Aspire.Dashboard/Components/ResourcesGridColumns/EndpointsColumnDisplay.razor
  src/Aspire.Dashboard/wwwroot/css/app.css
Labels: area-dashboard

#5038 Add structured logs test for querystring parameters
  src/Aspire.Dashboard/Aspire.Dashboard.csproj
  src/Aspire.Dashboard/Components/Controls/SummaryDetailsView.razor.cs
  src/Aspire.Dashboard/Components/Pages/ConsoleLogs.razor.cs
  src/Aspire.Dashboard/Components/Pages/IPageWithSessionAndUrlState.cs
  src/Aspire.Dashboard/Components/Pages/Metrics.razor.cs
  src/Aspire.Dashboard/Components/Pages/StructuredLogs.razor.cs
  src/Aspire.Dashboard/Components/Pages/Traces.razor.cs
  src/Aspire.Dashboard/DashboardWebApplication.cs
  src/Aspire.Dashboard/Model/BrowserStorage/BrowserStorageBase.cs
  src/Aspire.Dashboard/Model/BrowserStorage/IBrowserStorage.cs
  src/Aspire.Dashboard/Model/BrowserStorage/ILocalStorage.cs
  src/Aspire.Dashboard/Model/BrowserStorage/ISessionStorage.cs
  src/Aspire.Dashboard/Model/BrowserStorage/LocalBrowserStorage.cs
  src/Aspire.Dashboard/Model/BrowserStorage/SessionBrowserStorage.cs
  src/Aspire.Dashboard/Model/BrowserStorage/StorageResult.cs
  src/Aspire.Dashboard/Utils/IBrowserStorageExtensions.cs
  tests/Aspire.Dashboard.Components.Tests/Controls/PlotlyChartTests.cs
  tests/Aspire.Dashboard.Components.Tests/Controls/StructuredLogsTests.cs
  tests/Aspire.Dashboard.Components.Tests/Shared/TestInstrumentUnitResolver.cs
  tests/Aspire.Dashboard.Components.Tests/Shared/TestLocalStorage.cs
  tests/Aspire.Dashboard.Components.Tests/Shared/TestSessionStorage.cs
  tests/Aspire.Dashboard.Components.Tests/Shared/TestTimeProvider.cs
Labels: area-dashboard

#5031 Avoid dispose race on metrics page
  src/Aspire.Dashboard/Components/Controls/Chart/ChartBase.cs
  src/Aspire.Dashboard/Components/Controls/Chart/MetricTable.razor
  src/Aspire.Dashboard/Components/Controls/Chart/MetricTable.razor.cs
  src/Aspire.Dashboard/Components/Controls/Chart/PlotlyChart.razor.cs
  src/Aspire.Dashboard/wwwroot/js/app-metrics.js
Labels: area-dashboard

#5070 Use meter attributes on metrics page
  playground/Stress/Stress.ApiService/Program.cs
  src/Aspire.Dashboard/Otlp/Model/OtlpHelpers.cs
  src/Aspire.Dashboard/Otlp/Model/OtlpInstrument.cs
  src/Aspire.Dashboard/Otlp/Model/OtlpMeter.cs
  tests/Aspire.Dashboard.Tests/TelemetryRepositoryTests/MetricsTests.cs
Labels: area-dashboard, area-telemetry

#5075 Clean up ChartBase
  src/Aspire.Dashboard/Components/Controls/Chart/ChartBase.cs
Labels: area-dashboard

#5084 Fix Azure Storage `RunAsEmulator`
  src/Aspire.Hosting.Azure.Storage/AzureStorageExtensions.cs
  tests/Aspire.Hosting.Azure.Tests/Aspire.Hosting.Azure.Tests.csproj
  tests/Aspire.Hosting.Azure.Tests/AzureStorageEmulatorFunctionalTests.cs
Labels: area-codeflow

#5082 Rename DCP command-line args.
  src/Aspire.Hosting/Dcp/DcpOptions.cs
  src/Aspire.Hosting/DistributedApplicationBuilder.cs
  tests/Aspire.Hosting.Tests/Dcp/DcpCliArgsTests.cs
Labels: area-app-model

#5048 CA1062#Aspire.Hosting.Redis
  src/Aspire.Hosting.Redis/RedisBuilderExtensions.cs
  src/Aspire.Hosting.Redis/RedisCommanderConfigWriterHook.cs
  tests/Aspire.Hosting.Redis.Tests/RedisPublicApiTests.cs
Labels: area-app-model, community-contribution

#4871 Extract Aspire.Hosting.Garnet.Tests project
  Aspire.sln
  tests/Aspire.EndToEnd.Tests/IntegrationServicesFixture.cs
  tests/Aspire.EndToEnd.Tests/IntegrationServicesTests.cs
  tests/Aspire.Hosting.Garnet.Tests/AddGarnetTests.cs
  tests/Aspire.Hosting.Garnet.Tests/Aspire.Hosting.Garnet.Tests.csproj
  tests/Aspire.Hosting.Garnet.Tests/GarnetFunctionalTests.cs
  tests/Aspire.Hosting.Tests/Aspire.Hosting.Tests.csproj
  tests/Aspire.Hosting.Tests/ManifestGenerationTests.cs
  tests/testproject/Common/TestResourceNames.cs
  tests/testproject/TestProject.AppHost/TestProgram.cs
  tests/testproject/TestProject.AppHost/TestProject.AppHost.csproj
  tests/testproject/TestProject.AppHost/aspire-manifest.json
  tests/testproject/TestProject.IntegrationServiceA/Garnet/GarnetExtensions.cs
  tests/testproject/TestProject.IntegrationServiceA/Program.cs
Labels: area-app-model, community-contribution, testing ☑️

#5069 CI: run helix, and non-helix tests in separate jobs
  eng/pipelines/azure-pipelines-public.yml
  eng/pipelines/templates/BuildAndTest.yml
  eng/pipelines/templates/VerifyCoverageReport.yml
Labels: area-engineering-systems, testing ☑️

#5002 Extract Aspire.Hosting.Nats.Tests project
  Aspire.sln
  tests/Aspire.Hosting.Nats.Tests/AddNatsTests.cs
  tests/Aspire.Hosting.Nats.Tests/AppEvent.cs
  tests/Aspire.Hosting.Nats.Tests/Aspire.Hosting.Nats.Tests.csproj
  tests/Aspire.Hosting.Nats.Tests/NatsFunctionalTests.cs
  tests/Aspire.Hosting.Tests/Aspire.Hosting.Tests.csproj
Labels: area-app-model, community-contribution, testing ☑️

#5114 [tests] Use test container registry for RabbitMQ testcontainer
  tests/Aspire.RabbitMQ.Client.Tests/AspireRabbitMQLoggingTests.cs
Labels: area-components, testing ☑️

#4908 Identify replica sets based on owner info provided by DCP, group applications by their replica set in resource dropdowns, add tests for console logs application resource grouping
  src/Aspire.Dashboard/Components/Controls/ResourceSelect.razor
  src/Aspire.Dashboard/Components/Controls/ResourceSelectOptionTemplate.razor
  src/Aspire.Dashboard/Components/Pages/ConsoleLogs.razor.cs
  src/Aspire.Dashboard/Model/Otlp/ApplicationsSelectHelpers.cs
  src/Aspire.Dashboard/Model/ResourceTypeDetails.cs
  src/Aspire.Dashboard/Otlp/Model/OtlpApplicationType.cs
  src/Aspire.Dashboard/Resources/ControlsStrings.Designer.cs
  src/Aspire.Dashboard/Resources/ControlsStrings.resx
  src/Aspire.Dashboard/Resources/xlf/ControlsStrings.cs.xlf
  src/Aspire.Dashboard/Resources/xlf/ControlsStrings.de.xlf
  src/Aspire.Dashboard/Resources/xlf/ControlsStrings.es.xlf
  src/Aspire.Dashboard/Resources/xlf/ControlsStrings.fr.xlf
  src/Aspire.Dashboard/Resources/xlf/ControlsStrings.it.xlf
  src/Aspire.Dashboard/Resources/xlf/ControlsStrings.ja.xlf
  src/Aspire.Dashboard/Resources/xlf/ControlsStrings.ko.xlf
  src/Aspire.Dashboard/Resources/xlf/ControlsStrings.pl.xlf
  src/Aspire.Dashboard/Resources/xlf/ControlsStrings.pt-BR.xlf
  src/Aspire.Dashboard/Resources/xlf/ControlsStrings.ru.xlf
  src/Aspire.Dashboard/Resources/xlf/ControlsStrings.tr.xlf
  src/Aspire.Dashboard/Resources/xlf/ControlsStrings.zh-Hans.xlf
  src/Aspire.Dashboard/Resources/xlf/ControlsStrings.zh-Hant.xlf
  src/Aspire.Dashboard/wwwroot/css/app.css
  src/Aspire.Hosting/Dashboard/DashboardServiceData.cs
  src/Aspire.Hosting/Dashboard/proto/resource_service.proto
  src/Aspire.Hosting/PublicAPI.Unshipped.txt
  src/Shared/StringComparers.cs
  tests/Aspire.Dashboard.Tests/ConsoleLogsTests/CreateResourceSelectModelsTests.cs
  tests/Aspire.Dashboard.Tests/Model/ApplicationsSelectHelpersTests.cs
  tests/Aspire.Hosting.Tests/Dashboard/ResourcePublisherTests.cs
Labels: area-dashboard

#5121 CA1062#Aspire.Hosting.Redis#Path-1
  tests/Aspire.Hosting.Redis.Tests/RedisPublicApiTests.cs
Labels: area-codeflow, community-contribution

#5118 Add test to cover WithReference usage with Python projects.
  tests/Aspire.Hosting.Python.Tests/AddPythonProjectTests.cs
Labels: area-app-model

#5081 Add support for multiple ANSI arguments to AnsiParser
  playground/Stress/Stress.ApiService/ConsoleStresser.cs
  src/Aspire.Dashboard/Components/Controls/LogViewer.razor.css
  src/Aspire.Dashboard/ConsoleLogs/AnsiParser.cs
  tests/Aspire.Dashboard.Tests/ConsoleLogsTests/AnsiParserTests.cs
Labels: area-dashboard, community-contribution

#3727 Add visible labels to resource select component and filter dialog
  src/Aspire.Dashboard/Components/Controls/Chart/ChartFilters.razor
  src/Aspire.Dashboard/Components/Controls/ResourceSelect.razor
  src/Aspire.Dashboard/Components/Controls/ResourceSelect.razor.cs
  src/Aspire.Dashboard/Components/Dialogs/FilterDialog.razor
  src/Aspire.Dashboard/Components/Pages/ConsoleLogs.razor
  src/Aspire.Dashboard/Components/Pages/ConsoleLogs.razor.cs
  src/Aspire.Dashboard/Components/Pages/Metrics.razor.cs
  src/Aspire.Dashboard/Components/Pages/StructuredLogs.razor.cs
  src/Aspire.Dashboard/Components/Pages/Traces.razor.cs
  src/Aspire.Dashboard/Resources/ControlsStrings.Designer.cs
  src/Aspire.Dashboard/Resources/ControlsStrings.resx
  src/Aspire.Dashboard/Resources/Dialogs.Designer.cs
  src/Aspire.Dashboard/Resources/Dialogs.resx
  src/Aspire.Dashboard/Resources/StructuredLogs.Designer.cs
  src/Aspire.Dashboard/Resources/StructuredLogs.resx
  src/Aspire.Dashboard/Resources/xlf/ControlsStrings.cs.xlf
  src/Aspire.Dashboard/Resources/xlf/ControlsStrings.de.xlf
  src/Aspire.Dashboard/Resources/xlf/ControlsStrings.es.xlf
  src/Aspire.Dashboard/Resources/xlf/ControlsStrings.fr.xlf
  src/Aspire.Dashboard/Resources/xlf/ControlsStrings.it.xlf
  src/Aspire.Dashboard/Resources/xlf/ControlsStrings.ja.xlf
  src/Aspire.Dashboard/Resources/xlf/ControlsStrings.ko.xlf
  src/Aspire.Dashboard/Resources/xlf/ControlsStrings.pl.xlf
  src/Aspire.Dashboard/Resources/xlf/ControlsStrings.pt-BR.xlf
  src/Aspire.Dashboard/Resources/xlf/ControlsStrings.ru.xlf
  src/Aspire.Dashboard/Resources/xlf/ControlsStrings.tr.xlf
  src/Aspire.Dashboard/Resources/xlf/ControlsStrings.zh-Hans.xlf
  src/Aspire.Dashboard/Resources/xlf/ControlsStrings.zh-Hant.xlf
  src/Aspire.Dashboard/Resources/xlf/Dialogs.cs.xlf
  src/Aspire.Dashboard/Resources/xlf/Dialogs.de.xlf
  src/Aspire.Dashboard/Resources/xlf/Dialogs.es.xlf
  src/Aspire.Dashboard/Resources/xlf/Dialogs.fr.xlf
  src/Aspire.Dashboard/Resources/xlf/Dialogs.it.xlf
  src/Aspire.Dashboard/Resources/xlf/Dialogs.ja.xlf
  src/Aspire.Dashboard/Resources/xlf/Dialogs.ko.xlf
  src/Aspire.Dashboard/Resources/xlf/Dialogs.pl.xlf
  src/Aspire.Dashboard/Resources/xlf/Dialogs.pt-BR.xlf
  src/Aspire.Dashboard/Resources/xlf/Dialogs.ru.xlf
  src/Aspire.Dashboard/Resources/xlf/Dialogs.tr.xlf
  src/Aspire.Dashboard/Resources/xlf/Dialogs.zh-Hans.xlf
  src/Aspire.Dashboard/Resources/xlf/Dialogs.zh-Hant.xlf
  src/Aspire.Dashboard/Resources/xlf/StructuredLogs.cs.xlf
  src/Aspire.Dashboard/Resources/xlf/StructuredLogs.de.xlf
  src/Aspire.Dashboard/Resources/xlf/StructuredLogs.es.xlf
  src/Aspire.Dashboard/Resources/xlf/StructuredLogs.fr.xlf
  src/Aspire.Dashboard/Resources/xlf/StructuredLogs.it.xlf
  src/Aspire.Dashboard/Resources/xlf/StructuredLogs.ja.xlf
  src/Aspire.Dashboard/Resources/xlf/StructuredLogs.ko.xlf
  src/Aspire.Dashboard/Resources/xlf/StructuredLogs.pl.xlf
  src/Aspire.Dashboard/Resources/xlf/StructuredLogs.pt-BR.xlf
  src/Aspire.Dashboard/Resources/xlf/StructuredLogs.ru.xlf
  src/Aspire.Dashboard/Resources/xlf/StructuredLogs.tr.xlf
  src/Aspire.Dashboard/Resources/xlf/StructuredLogs.zh-Hans.xlf
  src/Aspire.Dashboard/Resources/xlf/StructuredLogs.zh-Hant.xlf
  src/Aspire.Dashboard/wwwroot/css/app.css
Labels: area-dashboard

#5128 Fix typo in ServiceBus README example
  src/Components/Aspire.Azure.Messaging.ServiceBus/README.md
  src/Components/Aspire.Azure.Storage.Blobs/README.md
  src/Components/Aspire.Azure.Storage.Queues/README.md
Labels: area-components, community-contribution

#5122 Remove injected view model services for metrics/console logs
  src/Aspire.Dashboard/Components/Controls/Chart/ChartContainer.razor
  src/Aspire.Dashboard/Components/Controls/Chart/ChartContainer.razor.cs
  src/Aspire.Dashboard/Components/Controls/Chart/ChartFilters.razor
  src/Aspire.Dashboard/Components/Controls/Chart/ChartFilters.razor.cs
  src/Aspire.Dashboard/Components/Controls/Chart/MetricTable.razor
  src/Aspire.Dashboard/Components/Controls/Chart/MetricTable.razor.cs
  src/Aspire.Dashboard/Components/Controls/LogViewer.razor
  src/Aspire.Dashboard/Components/Controls/LogViewer.razor.cs
  src/Aspire.Dashboard/Components/Layout/AspirePageContentLayout.razor
  src/Aspire.Dashboard/Components/Pages/ConsoleLogs.razor.cs
  src/Aspire.Dashboard/DashboardWebApplication.cs
  src/Aspire.Dashboard/Model/CurrentChartViewModel.cs
  src/Aspire.Dashboard/Model/LogViewerViewModel.cs
  src/Aspire.Dashboard/Resources/ControlsStrings.Designer.cs
  src/Aspire.Dashboard/Resources/ControlsStrings.resx
  src/Aspire.Dashboard/Resources/xlf/ControlsStrings.cs.xlf
  src/Aspire.Dashboard/Resources/xlf/ControlsStrings.de.xlf
  src/Aspire.Dashboard/Resources/xlf/ControlsStrings.es.xlf
  src/Aspire.Dashboard/Resources/xlf/ControlsStrings.fr.xlf
  src/Aspire.Dashboard/Resources/xlf/ControlsStrings.it.xlf
  src/Aspire.Dashboard/Resources/xlf/ControlsStrings.ja.xlf
  src/Aspire.Dashboard/Resources/xlf/ControlsStrings.ko.xlf
  src/Aspire.Dashboard/Resources/xlf/ControlsStrings.pl.xlf
  src/Aspire.Dashboard/Resources/xlf/ControlsStrings.pt-BR.xlf
  src/Aspire.Dashboard/Resources/xlf/ControlsStrings.ru.xlf
  src/Aspire.Dashboard/Resources/xlf/ControlsStrings.tr.xlf
  src/Aspire.Dashboard/Resources/xlf/ControlsStrings.zh-Hans.xlf
  src/Aspire.Dashboard/Resources/xlf/ControlsStrings.zh-Hant.xlf
Labels: area-dashboard
