Repository dotnet/aspire, pull requests merged in 2024-08, with the labels that each got.

#5132 [python] Emit virtual environment path in exception
  src/Aspire.Hosting.Python/VirtualEnvironment.cs
Labels: area-app-model

#5041 Disabling AOAI resource key access by default.
  src/Aspire.Hosting.Azure.CognitiveServices/AzureOpenAIExtensions.cs
  tests/Aspire.Hosting.Azure.Tests/AzureBicepResourceTests.cs
Labels: area-app-model, community-contribution

#5130 Extract Aspire.Hosting.RabbitMQ.Tests project
  Aspire.sln
  tests/Aspire.EndToEnd.Tests/IntegrationServicesFixture.cs
  tests/Aspire.EndToEnd.Tests/IntegrationServicesTests.cs
  tests/Aspire.Hosting.RabbitMQ.Tests/AddRabbitMQTests.cs
  tests/Aspire.Hosting.RabbitMQ.Tests/Aspire.Hosting.RabbitMQ.Tests.csproj
  tests/Aspire.Hosting.RabbitMQ.Tests/RabbitMQFunctionalTests.cs
  tests/Aspire.Hosting.Tests/Aspire.Hosting.Tests.csproj
  tests/Aspire.Hosting.Tests/ManifestGenerationTests.cs
  tests/testproject/Common/TestResourceNames.cs
  tests/testproject/TestProject.AppHost/TestProgram.cs
  tests/testproject/TestProject.AppHost/TestProject.AppHost.csproj
  tests/testproject/TestProject.IntegrationServiceA/Program.cs
  tests/testproject/TestProject.IntegrationServiceA/RabbitMQ/RabbitMQExtensions.cs
  tests/testproject/TestProject.IntegrationServiceA/TestProject.IntegrationServiceA.csproj
Labels: area-components

#5099 Adding public API test coverage for Aspire.Hosting.Qdrant
  src/Aspire.Hosting.Qdrant/QdrantBuilderExtensions.cs
  tests/Aspire.Hosting.Qdrant.Tests/QdrantPublicApiTests.cs
Labels: area-app-model, community-contribution

#5133 Fix up first column unit on trace detail
  src/Aspire.Dashboard/Components/Pages/TraceDetail.razor
  src/Aspire.Dashboard/Otlp/Model/DurationFormatter.cs
  tests/Aspire.Dashboard.Tests/DurationFormatterTests.cs
Labels: area-dashboard

#5083 Preserve selected instrument when switching resources
  src/Aspire.Dashboard/Components/Controls/ResourceSelect.razor
  src/Aspire.Dashboard/Components/Controls/ResourceSelect.razor.cs
  src/Aspire.Dashboard/Components/Pages/Metrics.razor.cs
  tests/Aspire.Dashboard.Components.Tests/Aspire.Dashboard.Components.Tests.csproj
  tests/Aspire.Dashboard.Components.Tests/Controls/PlotlyChartTests.cs
  tests/Aspire.Dashboard.Components.Tests/Pages/MetricsTests.cs
  tests/Aspire.Dashboard.Components.Tests/Pages/StructuredLogsTests.cs
  tests/Aspire.Dashboard.Components.Tests/Shared/MetricsSetupHelpers.cs
  tests/Aspire.Dashboard.Components.Tests/Shared/TestConstants.cs
  tests/Aspire.Dashboard.Components.Tests/Shared/TestInstrumentUnitResolver.cs
  tests/Aspire.Dashboard.Components.Tests/Shared/TestLocalStorage.cs
  tests/Aspire.Dashboard.Components.Tests/Shared/TestSessionStorage.cs
  tests/Aspire.Dashboard.Components.Tests/Shared/TestTimeProvider.cs
  tests/Aspire.Dashboard.Tests/Aspire.Dashboard.Tests.csproj
  tests/Aspire.Dashboard.Tests/Integration/OtlpHttpServiceTests.cs
  tests/Aspire.Dashboard.Tests/TelemetryRepositoryTests/ApplicationTests.cs
  tests/Aspire.Dashboard.Tests/TelemetryRepositoryTests/LogTests.cs
  tests/Aspire.Dashboard.Tests/TelemetryRepositoryTests/MetricsTests.cs
  tests/Aspire.Dashboard.Tests/TelemetryRepositoryTests/TraceTests.cs
  tests/Shared/Telemetry/TelemetryTestHelpers.cs
Labels: area-dashboard

#5000 View details with row click
  src/Aspire.Dashboard/Components/Controls/GridValue.razor
  src/Aspire.Dashboard/Components/Pages/Resources.razor
  src/Aspire.Dashboard/Components/Pages/Resources.razor.cs
  src/Aspire.Dashboard/Components/Pages/StructuredLogs.razor
  src/Aspire.Dashboard/Components/Pages/StructuredLogs.razor.cs
  src/Aspire.Dashboard/Components/Pages/TraceDetail.razor
  src/Aspire.Dashboard/Components/Pages/TraceDetail.razor.css
  src/Aspire.Dashboard/Components/Pages/Traces.razor
  src/Aspire.Dashboard/Components/ResourcesGridColumns/EndpointsColumnDisplay.razor
  src/Aspire.Dashboard/Components/ResourcesGridColumns/UnreadLogErrorsBadge.razor
  src/Aspire.Dashboard/Components/_Imports.razor
  src/Aspire.Dashboard/Extensions/ComponentExtensions.cs
  src/Aspire.Dashboard/wwwroot/css/app.css
Labels: area-dashboard

#5155 Correct the path of the TestShop.AppHost
  playground/TestShop/TestShop.sln
Labels: area-codeflow

#5146 Fix typos
  playground/AWS/AWS.AppHost/app-resources.template
  src/Aspire.Dashboard/Components/Controls/ResourceDetails.razor.cs
  src/Aspire.Dashboard/Components/Pages/Resources.razor.cs
  src/Aspire.Dashboard/ConsoleLogs/AnsiParser.cs
  src/Aspire.Dashboard/Model/ResourceEndpointHelpers.cs
  src/Aspire.Dashboard/Otlp/Http/OtlpHttpEndpointsBuilder.cs
  src/Aspire.Hosting.AWS/README.md
  src/Aspire.Hosting.Azure.AppConfiguration/AzureAppConfigurationExtensions.cs
  src/Aspire.Hosting.Azure.OperationalInsights/README.md
  src/Aspire.Hosting.Azure/AzureBicepResourceExtensions.cs
  src/Aspire.Hosting.Azure/Provisioning/Provisioners/AzureProvisioner.cs
  src/Aspire.Hosting.Dapr/IDistributedApplicationComponentBuilderExtensions.cs
  src/Aspire.Hosting.Elasticsearch/ElasticsearchBuilderExtensions.cs
  src/Aspire.Hosting/ApplicationModel/CustomResourceSnapshot.cs
  src/Aspire.Hosting/ApplicationModel/ResourceNotificationService.cs
  src/Aspire.Hosting/Dashboard/TransportOptionsValidator.cs
  src/Aspire.Hosting/Dcp/Model/Container.cs
  src/Aspire.Hosting/Dcp/Model/Network.cs
  src/Aspire.Hosting/DistributedApplicationResourceBuilder.cs
  src/Components/Aspire.Microsoft.EntityFrameworkCore.Cosmos/README.md
  src/Grafana/README.md
  src/Schema/aspire-8.0.json
  src/Tools/ConfigurationSchemaGenerator/RuntimeSource/Configuration.Binder/Specs/InterceptorInfo.cs
  tests/Aspire.Dashboard.Tests/Model/ResourceEndpointHelpersTests.cs
  tests/Aspire.Hosting.Testing.Tests/ResourceLoggerForwarderServiceTests.cs
  tests/Aspire.Hosting.Tests/ResourceNotificationTests.cs
Labels: area-components

#5159 Adding public API test coverage Aspire.Hosting.Kafka
  src/Aspire.Hosting.Kafka/KafkaBuilderExtensions.cs
  tests/Aspire.Hosting.Kafka.Tests/KafkaPublicApiTests.cs
Labels: area-app-model, community-contribution

#5152 Adding public API test coverage for Aspire.Hosting.Milvus
  src/Aspire.Hosting.Milvus/MilvusBuilderExtensions.cs
  tests/Aspire.Hosting.Milvus.Tests/MilvusPublicApiTests.cs
Labels: area-app-model, community-contribution

#5079 Fix Elasticsearch Failing Tests
  tests/Aspire.Hosting.Elasticsearch.Tests/ElasticsearchFunctionalTests.cs
Labels: area-app-model, community-contribution

#4086 Add Dapr sidecar port environment variables
  src/Aspire.Hosting.Dapr/DaprDistributedApplicationLifecycleHook.cs
  tests/Aspire.Hosting.Tests/Dapr/DaprTests.cs
Labels: area-app-model, community-contribution

#5153 Adding public API test coverage for Aspire.Hosting.RabbitMQ
  src/Aspire.Hosting.RabbitMQ/RabbitMQBuilderExtensions.cs
  tests/Aspire.Hosting.RabbitMQ.Tests/RabbitMQPublicApiTests.cs
Labels: area-app-model, community-contribution

#5123 Redirect to homepage if login page is requested when token auth is not enabled
  Directory.Packages.props
  eng/Versions.props
  src/Aspire.Dashboard/Model/ValidateTokenMiddleware.cs
  tests/Aspire.Dashboard.Tests/Aspire.Dashboard.Tests.csproj
  tests/Aspire.Dashboard.Tests/Middleware/ValidateTokenMiddlewareTests.cs
Labels: area-dashboard

#5125 Ensure docker build log are streamed back to apphost.
  tests/Aspire.Hosting.Containers.Tests/Aspire.Hosting.Containers.Tests.csproj
  tests/Aspire.Hosting.Containers.Tests/WithDockerfileTests.cs
Labels: area-components

#4463 Filter additionals records from dns srv response
  src/Microsoft.Extensions.ServiceDiscovery.Dns/DnsSrvServiceEndpointProvider.cs
  tests/Microsoft.Extensions.ServiceDiscovery.Dns.Tests/DnsSrvServiceEndpointResolverTests.cs
Labels: area-service-discovery, community-contribution

#5187 [tests] Fix some flaky tests in Aspire.Hosting.Azure.Tests
  tests/Aspire.Hosting.Tests/Schema/SchemaTests.cs
  tests/Aspire.Hosting.Tests/Utils/ManifestUtils.cs
Labels: area-app-model

#5173 Fix configuration binding
  src/Aspire.Dashboard/Configuration/DashboardOptions.cs
  src/Aspire.Dashboard/Configuration/ValidateDashboardOptions.cs
  src/Aspire.Dashboard/ResourceService/DashboardClient.cs
  src/Shared/DashboardConfigNames.cs
  tests/Aspire.Dashboard.Tests/DashboardOptionsTests.cs
  tests/Aspire.Dashboard.Tests/Integration/StartupTests.cs
Labels: bug, area-dashboard

#5017 Extract Aspire.Hosting.MongoDB.Tests project
  Aspire.sln
  tests/Aspire.EndToEnd.Tests/IntegrationServicesFixture.cs
  tests/Aspire.EndToEnd.Tests/IntegrationServicesTests.cs
  tests/Aspire.Hosting.MongoDB.Tests/AddMongoDBTests.cs
  tests/Aspire.Hosting.MongoDB.Tests/Aspire.Hosting.MongoDB.Tests.csproj
  tests/Aspire.Hosting.MongoDB.Tests/MongoDbFunctionalTests.cs
  tests/Aspire.Hosting.Tests/Aspire.Hosting.Tests.csproj
  tests/Aspire.Hosting.Tests/ManifestGenerationTests.cs
  tests/testproject/Common/TestResourceNames.cs
  tests/testproject/TestProject.AppHost/TestProgram.cs
  tests/testproject/TestProject.AppHost/aspire-manifest.json
  tests/testproject/TestProject.IntegrationServiceA/MongoDB/MongoDBExtensions.cs
  tests/testproject/TestProject.IntegrationServiceA/MongoDB/Movie.cs
  tests/testproject/TestProject.IntegrationServiceA/Program.cs
  tests/testproject/TestProject.IntegrationServiceA/TestProject.IntegrationServiceA.csproj
Labels: area-app-model, community-contribution, testing ☑️

#5202 Disable failing Azure Key Vault health check tests
  tests/Aspire.Azure.Security.KeyVault.Tests/ConformanceTests.cs
Labels: area-components, testing ☑️

#5156 Adding public API test coverage for Aspire.Hosting.MySql
  src/Aspire.Hosting.MySql/MySqlBuilderExtensions.cs
  tests/Aspire.Hosting.MySql.Tests/MySqlPublicApiTests.cs
Labels: area-components, community-contribution

#5169 Adding public API test coverage for Aspire.Elastic.Clients.Elasticsearch
  src/Components/Aspire.Elastic.Clients.Elasticsearch/AspireElasticClientsElasticsearchExtensions.cs
  tests/Aspire.Elastic.Clients.Elasticsearch.Tests/ElasticsearchClientPublicApiTests.cs
Labels: area-components, community-contribution

#5204 [ci] Bump dcp-dependency check timeout to 3 minutes on the build machine
  eng/pipelines/templates/BuildAndTest.yml
Labels: area-engineering-systems, testing ☑️

#5193 [tests] Add resource logging to `Aspire.Hosting.*` tests
  src/Aspire.Hosting.Testing/ResourceLoggerForwarderService.cs
  tests/Aspire.Dashboard.Components.Tests/Pages/MetricsTests.cs
  tests/Aspire.Hosting.Azure.Tests/AzureStorageEmulatorFunctionalTests.cs
  tests/Aspire.Hosting.Elasticsearch.Tests/ElasticsearchFunctionalTests.cs
  tests/Aspire.Hosting.Garnet.Tests/GarnetFunctionalTests.cs
  tests/Aspire.Hosting.Kafka.Tests/KafkaFunctionalTests.cs
  tests/Aspire.Hosting.Milvus.Tests/MilvusFunctionalTests.cs
  tests/Aspire.Hosting.MongoDB.Tests/Aspire.Hosting.MongoDB.Tests.csproj
  tests/Aspire.Hosting.MongoDB.Tests/MongoDbFunctionalTests.cs
  tests/Aspire.Hosting.MySql.Tests/Aspire.Hosting.MySql.Tests.csproj
  tests/Aspire.Hosting.MySql.Tests/MySqlFunctionalTests.cs
  tests/Aspire.Hosting.Nats.Tests/NatsFunctionalTests.cs
  tests/Aspire.Hosting.PostgreSQL.Tests/Aspire.Hosting.PostgreSQL.Tests.csproj
  tests/Aspire.Hosting.PostgreSQL.Tests/PostgresFunctionalTests.cs
  tests/Aspire.Hosting.Python.Tests/AddPythonProjectTests.cs
  tests/Aspire.Hosting.Qdrant.Tests/QdrantFunctionalTests.cs
  tests/Aspire.Hosting.RabbitMQ.Tests/RabbitMQFunctionalTests.cs
  tests/Aspire.Hosting.Redis.Tests/RedisFunctionalTests.cs
  tests/Aspire.Hosting.Tests/Aspire.Hosting.Tests.csproj
  tests/Aspire.Hosting.Tests/Utils/TestDistributedApplicationBuilder.cs
  tests/Aspire.Hosting.Valkey.Tests/ValkeyFunctionalTests.cs
Labels: area-components

#5170 Adding public API test coverage for Aspire.Milvus.Client
  src/Components/Aspire.Milvus.Client/AspireMilvusExtensions.cs
  tests/Aspire.Milvus.Client.Tests/MilvusClientPublicApiTests.cs
Labels: area-components, community-contribution

#5177 Add CORS to OTLP HTTP endpoint
  src/Aspire.Dashboard/Configuration/DashboardOptions.cs
  src/Aspire.Dashboard/DashboardWebApplication.cs
  src/Aspire.Dashboard/Otlp/Http/OtlpHttpEndpointsBuilder.cs
  src/Shared/DashboardConfigNames.cs
  tests/Aspire.Dashboard.Tests/Integration/OtlpCorsHttpServiceTests.cs
  tests/Aspire.Dashboard.Tests/Integration/StartupTests.cs
Labels: area-dashboard, area-telemetry

#5172 Add certificate allow list configuration
  src/Aspire.Dashboard/Configuration/DashboardOptions.cs
  src/Aspire.Dashboard/Configuration/ValidateDashboardOptions.cs
  src/Aspire.Dashboard/DashboardWebApplication.cs
  src/Shared/DashboardConfigNames.cs
  tests/Aspire.Dashboard.Tests/DashboardOptionsTests.cs
  tests/Aspire.Dashboard.Tests/Integration/OtlpGrpcServiceTests.cs
  tests/Aspire.Dashboard.Tests/Integration/StartupTests.cs
Labels: area-dashboard, security 🔐

#5145 Better malformed launchsettings error
  src/Aspire.Hosting/LaunchProfileExtensions.cs
  tests/Aspire.Hosting.Tests/ProjectResourceTests.cs
Labels: area-app-model

#5142 Extract Aspire.Hosting.NodeJs.Tests project
  Aspire.sln
  tests/Aspire.Components.Common.Tests/FileUtil.cs
  tests/Aspire.Hosting.NodeJs.Tests/AddNodeAppTests.cs
  tests/Aspire.Hosting.NodeJs.Tests/Aspire.Hosting.NodeJs.Tests.csproj
  tests/Aspire.Hosting.NodeJs.Tests/NodeAppFixture.cs
  tests/Aspire.Hosting.NodeJs.Tests/NodeFunctionalTests.cs
  tests/Aspire.Hosting.Tests/Aspire.Hosting.Tests.csproj
  tests/Aspire.Hosting.Tests/DistributedApplicationTests.cs
  tests/Aspire.Hosting.Tests/ManifestGenerationTests.cs
  tests/Aspire.Hosting.Tests/TestProgramFixture.cs
  tests/testproject/TestProject.AppHost/Program.cs
  tests/testproject/TestProject.AppHost/TestProgram.cs
  tests/testproject/TestProject.AppHost/TestProject.AppHost.csproj
  tests/testproject/nodeapp/Dockerfile
  tests/testproject/nodeapp/app.js
  tests/testproject/nodeapp/package.json
Labels: area-components

#4682 Add support for installing latest build from main to scripts and update docs.
  docs/using-latest-daily.md
  eng/installLatestFromReleaseBranch.ps1
  eng/installLatestFromReleaseBranch.sh
Labels: area-engineering-systems

#5151 Move tooltip position in login to top for a11y
  src/Aspire.Dashboard/Components/Pages/Login.razor
Labels: area-dashboard

#5206 Remove deprecated resource service protocol fields/types
  src/Aspire.Hosting/Dashboard/proto/resource_service.proto
Labels: area-dashboard, needs-author-action

#5216 Fix TestBuilderTests flakyness
  tests/Aspire.Hosting.Testing.Tests/TestingBuilderTests.cs
  tests/Aspire.Hosting.Testing.Tests/TestingFactoryTests.cs
  tests/Aspire.Hosting.Tests/DistributedApplicationTests.cs
  tests/Aspire.Hosting.Tests/Utils/LoggerNotificationExtensions.cs
Labels: area-components

#5120 Update dependency versions
  Directory.Packages.props
Labels: area-codeflow

#5143 Add support for all cultures corresponding to localizations we have
  src/Aspire.Dashboard/DashboardWebApplication.cs
  tests/Aspire.Dashboard.Tests/GlobalizationTests.cs
Labels: area-dashboard

#5218 Aspire.Hosting.Testing: Improve error message when loading
  playground/CosmosEndToEnd/CosmosEndToEnd.AppHost/Properties/launchSettings.json
  src/Aspire.Hosting.Testing/DistributedApplicationFactory.cs
Labels: area-app-testing

#5224 Use unique ID for each Plotly chart in the DOM
  src/Aspire.Dashboard/Components/Controls/Chart/PlotlyChart.razor
  src/Aspire.Dashboard/Components/Controls/Chart/PlotlyChart.razor.cs
  src/Aspire.Dashboard/Components/Pages/Metrics.razor.css
  tests/Aspire.Dashboard.Components.Tests/Controls/PlotlyChartTests.cs
Labels: area-dashboard, area-dashboard-metrics

#5215 [tests] Move more tests to helix by overriding dcp path from assembly metadata
  eng/pipelines/templates/BuildAndTest.yml
  src/Aspire.Hosting/Dcp/DcpOptions.cs
  tests/Aspire.Dashboard.Tests/Aspire.Dashboard.Tests.csproj
  tests/Aspire.Elastic.Clients.Elasticsearch.Tests/Aspire.Elastic.Clients.Elasticsearch.Tests.csproj
  tests/Aspire.EndToEnd.Tests/Aspire.EndToEnd.Tests.csproj
  tests/Aspire.Hosting.Containers.Tests/Aspire.Hosting.Containers.Tests.csproj
  tests/Aspire.Hosting.Keycloak.Tests/Aspire.Hosting.Keycloak.Tests.csproj
  tests/Aspire.Hosting.Milvus.Tests/AddMilvusTests.cs
  tests/Aspire.Hosting.Qdrant.Tests/AddQdrantTests.cs
  tests/Aspire.Hosting.Testing.Tests/Aspire.Hosting.Testing.Tests.csproj
  tests/Aspire.Hosting.Tests/Aspire.Hosting.Tests.csproj
  tests/Aspire.Keycloak.Authentication.Tests/Aspire.Keycloak.Authentication.Tests.csproj
  tests/Aspire.Microsoft.Data.SqlClient.Tests/Aspire.Microsoft.Data.SqlClient.Tests.csproj
  tests/Aspire.Microsoft.EntityFrameworkCore.SqlServer.Tests/Aspire.Microsoft.EntityFrameworkCore.SqlServer.Tests.csproj
  tests/Aspire.Milvus.Client.Tests/Aspire.Milvus.Client.Tests.csproj
  tests/Aspire.MongoDB.Driver.Tests/Aspire.MongoDB.Driver.Tests.csproj
  tests/Aspire.MySqlConnector.Tests/Aspire.MySqlConnector.Tests.csproj
  tests/Aspire.NATS.Net.Tests/Aspire.NATS.Net.Tests.csproj
  tests/Aspire.Npgsql.EntityFrameworkCore.PostgreSQL.Tests/Aspire.Npgsql.EntityFrameworkCore.PostgreSQL.Tests.csproj
  tests/Aspire.Npgsql.Tests/Aspire.Npgsql.Tests.csproj
  tests/Aspire.Pomelo.EntityFrameworkCore.MySql.Tests/Aspire.Pomelo.EntityFrameworkCore.MySql.Tests.csproj
  tests/Aspire.Qdrant.Client.Tests/Aspire.Qdrant.Client.Tests.csproj
  tests/Aspire.RabbitMQ.Client.Tests/Aspire.RabbitMQ.Client.Tests.csproj
  tests/Aspire.Seq.Tests/Aspire.Seq.Tests.csproj
  tests/Aspire.StackExchange.Redis.DistributedCaching.Tests/Aspire.StackExchange.Redis.DistributedCaching.Tests.csproj
  tests/Aspire.StackExchange.Redis.OutputCaching.Tests/Aspire.StackExchange.Redis.OutputCaching.Tests.csproj
  tests/Aspire.StackExchange.Redis.Tests/Aspire.StackExchange.Redis.Tests.csproj
  tests/Aspire.Workload.Tests/Aspire.Workload.Tests.csproj
  tests/Directory.Build.targets
  tests/Shared/RepoTesting/Aspire.RepoTesting.targets
  tests/helix/send-to-helix-basictests.targets
  tests/helix/send-to-helix-endtoendtests.targets
  tests/helix/send-to-helix-inner.proj
  tests/helix/send-to-helix-workloadtests.targets
Labels: area-components

#4078 Oracle OpenTelemetry support
  Aspire.sln
  Directory.Packages.props
  playground/OracleEndToEnd/OracleEndToEnd.ApiService/OracleEndToEnd.ApiService.csproj
  playground/OracleEndToEnd/OracleEndToEnd.ApiService/OracleEndToEnd.ApiService.http
  playground/OracleEndToEnd/OracleEndToEnd.ApiService/Program.cs
  playground/OracleEndToEnd/OracleEndToEnd.ApiService/Properties/launchSettings.json
  playground/OracleEndToEnd/OracleEndToEnd.ApiService/appsettings.Development.json
  playground/OracleEndToEnd/OracleEndToEnd.ApiService/appsettings.json
  playground/OracleEndToEnd/OracleEndToEnd.AppHost/OracleEndToEnd.AppHost.csproj
  playground/OracleEndToEnd/OracleEndToEnd.AppHost/Program.cs
  playground/OracleEndToEnd/OracleEndToEnd.AppHost/Properties/launchSettings.json
  playground/OracleEndToEnd/OracleEndToEnd.AppHost/appsettings.Development.json
  playground/OracleEndToEnd/OracleEndToEnd.AppHost/appsettings.json
  playground/OracleEndToEnd/OracleEndToEnd.AppHost/aspire-manifest.json
  src/Components/Aspire.Oracle.EntityFrameworkCore/Aspire.Oracle.EntityFrameworkCore.csproj
  src/Components/Aspire.Oracle.EntityFrameworkCore/AspireOracleEFCoreExtensions.cs
  src/Components/Aspire.Oracle.EntityFrameworkCore/ConfigurationSchema.json
  src/Components/Aspire.Oracle.EntityFrameworkCore/OracleEntityFrameworkCoreSettings.cs
  src/Components/Aspire.Oracle.EntityFrameworkCore/PublicAPI.Unshipped.txt
  src/Components/Aspire.Oracle.EntityFrameworkCore/README.md
  src/Components/Aspire_Components_Progress.md
  src/Components/Telemetry.md
  tests/Aspire.Oracle.EntityFrameworkCore.Tests/Aspire.Oracle.EntityFrameworkCore.Tests.csproj
  tests/Aspire.Oracle.EntityFrameworkCore.Tests/AspireOracleEFCoreDatabaseExtensionsTests.cs
  tests/Aspire.Oracle.EntityFrameworkCore.Tests/ConformanceTests.cs
  tests/Aspire.Oracle.EntityFrameworkCore.Tests/ConformanceTests_TypeSpecificConfig.cs
  tests/Aspire.Oracle.EntityFrameworkCore.Tests/EnrichOracleDatabaseTests.cs
  tests/Aspire.Oracle.EntityFrameworkCore.Tests/OracleContainerFixture.cs
  tests/Aspire.Oracle.EntityFrameworkCore.Tests/TestDbContext.cs
Labels: area-components, community-contribution

#5056 Extract Aspire.Hosting.SqlServer.Tests project
  Aspire.sln
  src/Aspire.Hosting.SqlServer/SqlServerBuilderExtensions.cs
  tests/Aspire.EndToEnd.Tests/IntegrationServicesFixture.cs
  tests/Aspire.EndToEnd.Tests/IntegrationServicesTests.cs
  tests/Aspire.Hosting.SqlServer.Tests/AddSqlServerTests.cs
  tests/Aspire.Hosting.SqlServer.Tests/Aspire.Hosting.SqlServer.Tests.csproj
  tests/Aspire.Hosting.SqlServer.Tests/SqlServerFunctionalTests.cs
  tests/Aspire.Hosting.SqlServer.Tests/TestDbContext.cs
  tests/Aspire.Hosting.Tests/Aspire.Hosting.Tests.csproj
  tests/Aspire.Hosting.Tests/DistributedApplicationTests.cs
  tests/Aspire.Hosting.Tests/ManifestGenerationTests.cs
  tests/testproject/Common/TestResourceNames.cs
  tests/testproject/TestProject.AppHost/TestProgram.cs
  tests/testproject/TestProject.AppHost/TestProject.AppHost.csproj
  tests/testproject/TestProject.IntegrationServiceA/Cosmos/EFCoreCosmosDbContext.cs
  tests/testproject/TestProject.IntegrationServiceA/Program.cs
  tests/testproject/TestProject.IntegrationServiceA/SqlServer/EFCoreSqlServerExtensions.cs
  tests/testproject/TestProject.IntegrationServiceA/SqlServer/SqlServerDbContext.cs
  tests/testproject/TestProject.IntegrationServiceA/SqlServer/SqlServerExtensions.cs
  tests/testproject/TestProject.IntegrationServiceA/TestProject.IntegrationServiceA.csproj
Labels: area-app-model, community-contribution, testing ☑️

#5212 Enable CORS for with OTLP HTTP endpoint and add playground app
  Aspire.sln
  playground/BrowserTelemetry/BrowserTelemetry.AppHost/BrowserTelemetry.AppHost.csproj
  playground/BrowserTelemetry/BrowserTelemetry.AppHost/Program.cs
  playground/BrowserTelemetry/BrowserTelemetry.AppHost/Properties/launchSettings.json
  playground/BrowserTelemetry/BrowserTelemetry.AppHost/appsettings.Development.json
  playground/BrowserTelemetry/BrowserTelemetry.AppHost/appsettings.json
  playground/BrowserTelemetry/BrowserTelemetry.Web/BrowserTelemetry.Web.csproj
  playground/BrowserTelemetry/BrowserTelemetry.Web/Pages/Index.cshtml
  playground/BrowserTelemetry/BrowserTelemetry.Web/Pages/Index.cshtml.cs
  playground/BrowserTelemetry/BrowserTelemetry.Web/Pages/Shared/_Layout.cshtml
  playground/BrowserTelemetry/BrowserTelemetry.Web/Pages/Shared/_Layout.cshtml.css
  playground/BrowserTelemetry/BrowserTelemetry.Web/Pages/_ViewImports.cshtml
  playground/BrowserTelemetry/BrowserTelemetry.Web/Pages/_ViewStart.cshtml
  playground/BrowserTelemetry/BrowserTelemetry.Web/Program.cs
  playground/BrowserTelemetry/BrowserTelemetry.Web/Properties/launchSettings.json
  playground/BrowserTelemetry/BrowserTelemetry.Web/Scripts/index.js
  playground/BrowserTelemetry/BrowserTelemetry.Web/appsettings.Development.json
  playground/BrowserTelemetry/BrowserTelemetry.Web/appsettings.json
  playground/BrowserTelemetry/BrowserTelemetry.Web/package-lock.json
  playground/BrowserTelemetry/BrowserTelemetry.Web/package.json
  playground/BrowserTelemetry/BrowserTelemetry.Web/webpack.config.js
  playground/BrowserTelemetry/BrowserTelemetry.Web/wwwroot/css/site.css
  playground/BrowserTelemetry/BrowserTelemetry.Web/wwwroot/favicon.ico
  playground/BrowserTelemetry/BrowserTelemetry.Web/wwwroot/scripts/bundle.js
  playground/BrowserTelemetry/BrowserTelemetry.Web/wwwroot/scripts/bundle.js.LICENSE.txt
  spelling.dic
  src/Aspire.Dashboard/Components/Pages/TraceDetail.razor
  src/Aspire.Dashboard/DashboardWebApplication.cs
  src/Aspire.Dashboard/Otlp/Http/OtlpHttpEndpointsBuilder.cs
  src/Aspire.Dashboard/Otlp/Model/OtlpTrace.cs
  src/Aspire.Hosting/ApplicationModel/AllocatedEndpoint.cs
  src/Aspire.Hosting/Dashboard/DashboardLifecycleHook.cs
  tests/Aspire.Dashboard.Tests/TelemetryRepositoryTests/TraceTests.cs
  tests/Aspire.Hosting.Tests/Dashboard/DashboardResourceTests.cs
Labels: area-dashboard, area-telemetry

#5225 Adding public API test coverage for Microsoft.Extensions.ServiceDiscovery.Dns
  src/Microsoft.Extensions.ServiceDiscovery.Dns/ServiceDiscoveryDnsServiceCollectionExtensions.cs
  tests/Microsoft.Extensions.ServiceDiscovery.Dns.Tests/DnsServicePublicApiTests.cs
Labels: area-service-discovery, community-contribution

#5164 Fix component governance alerts
  Directory.Packages.props
  src/Components/Aspire.Azure.AI.OpenAI/Aspire.Azure.AI.OpenAI.csproj
  src/Components/Aspire.Azure.Data.Tables/Aspire.Azure.Data.Tables.csproj
  src/Components/Aspire.Azure.Messaging.EventHubs/Aspire.Azure.Messaging.EventHubs.csproj
  src/Components/Aspire.Azure.Messaging.ServiceBus/Aspire.Azure.Messaging.ServiceBus.csproj
  src/Components/Aspire.Azure.Messaging.WebPubSub/Aspire.Azure.Messaging.WebPubSub.csproj
  src/Components/Aspire.Azure.Search.Documents/Aspire.Azure.Search.Documents.csproj
  src/Components/Aspire.Azure.Security.KeyVault/Aspire.Azure.Security.KeyVault.csproj
  src/Components/Aspire.Azure.Storage.Blobs/Aspire.Azure.Storage.Blobs.csproj
  src/Components/Aspire.Azure.Storage.Queues/Aspire.Azure.Storage.Queues.csproj
  src/Components/Aspire.Microsoft.Azure.Cosmos/Aspire.Microsoft.Azure.Cosmos.csproj
  src/Components/Aspire.Microsoft.Data.SqlClient/Aspire.Microsoft.Data.SqlClient.csproj
  src/Components/Aspire.Microsoft.EntityFrameworkCore.Cosmos/Aspire.Microsoft.EntityFrameworkCore.Cosmos.csproj
Labels: area-components

#5208 [tests] Add `Aspire.Playground.Tests`
  Aspire.sln
  playground/AzureStorageEndToEnd/AzureStorageEndToEnd.AppHost/Program.cs
  playground/CosmosEndToEnd/CosmosEndToEnd.AppHost/Program.cs
  playground/CustomResources/CustomResources.AppHost/Program.cs
  playground/DatabaseMigration/DatabaseMigration.AppHost/Program.cs
  playground/Directory.Build.props
  playground/Directory.Build.targets
  playground/Directory.Packages.props
  playground/Elasticsearch/Elasticsearch.ApiService/Program.cs
  playground/Elasticsearch/Elasticsearch.AppHost/Program.cs
  playground/ParameterEndToEnd/ParameterEndToEnd.AppHost/Program.cs
  playground/PostgresEndToEnd/PostgresEndToEnd.ApiService/Program.cs
  playground/PostgresEndToEnd/PostgresEndToEnd.AppHost/Program.cs
  playground/ProxylessEndToEnd/ProxylessEndToEnd.ApiService/Program.cs
  playground/ProxylessEndToEnd/ProxylessEndToEnd.AppHost/Program.cs
  playground/SqlServerEndToEnd/SqlServerEndToEnd.ApiService/Program.cs
  playground/SqlServerEndToEnd/SqlServerEndToEnd.AppHost/Program.cs
  playground/Stress/Stress.AppHost/Program.cs
  playground/TestShop/ApiGateway/ApiGateway.csproj
  playground/TestShop/BasketService/BasketService.csproj
  playground/TestShop/CatalogDb/CatalogDb.csproj
  playground/TestShop/CatalogService/CatalogService.csproj
  playground/TestShop/MyFrontend/MyFrontend.csproj
  playground/TestShop/OrderProcessor/OrderProcessor.csproj
  playground/TestShop/TestShop.AppHost/Program.cs
  playground/TestShop/TestShop.ServiceDefaults/Extensions.cs
  playground/TestShop/TestShop.ServiceDefaults/TestShop.ServiceDefaults.csproj
  playground/TestShop/TestShop.sln
  playground/dapr/ServiceA/DaprServiceA.csproj
  playground/dapr/ServiceB/DaprServiceB.csproj
  playground/kafka/KafkaBasic.AppHost/Program.cs
  playground/mongo/Mongo.ApiService/Program.cs
  playground/mongo/Mongo.AppHost/Program.cs
  playground/mysql/MySql.ApiService/Program.cs
  playground/nats/Nats.ApiService/Program.cs
  playground/nats/Nats.Backend/Program.cs
  playground/orleans/Orleans.AppHost/Program.cs
  playground/seq/Seq.ApiService/Program.cs
  playground/seq/Seq.AppHost/Program.cs
  playground/withdockerfile/WithDockerfile.AppHost/Program.cs
  tests/Aspire.Playground.Tests/.runsettings
  tests/Aspire.Playground.Tests/AppHostTests.cs
  tests/Aspire.Playground.Tests/Aspire.Playground.Tests.csproj
  tests/Aspire.Playground.Tests/Infrastructure/DistributedApplicationExtensions.cs
  tests/Aspire.Playground.Tests/Infrastructure/DistributedApplicationTestFactory.cs
  tests/Aspire.Playground.Tests/Infrastructure/ResourceExtensions.cs
  tests/Aspire.Playground.Tests/README.md
  tests/Directory.Build.props
  tests/Shared/WorkloadTesting/EnvironmentVariables.cs
  tests/helix/send-to-helix-buildonhelixtests.targets
  tests/helix/send-to-helix-ci.proj
  tests/helix/send-to-helix-inner.proj
  tests/helix/send-to-helix-workloadtests.targets
Labels: area-engineering-systems, testing ☑️

#5241 Adding public API test coverage for Aspire.Hosting.SqlServer
  src/Aspire.Hosting.SqlServer/SqlServerBuilderExtensions.cs
  src/Aspire.Hosting.SqlServer/SqlServerDatabaseResource.cs
  tests/Aspire.Hosting.SqlServer.Tests/SqlServerPublicApiTests.cs
Labels: needs-area-label, community-contribution

#5171 Adding public API test coverage for Aspire.MongoDB.Driver
  src/Components/Aspire.MongoDB.Driver/AspireMongoDBDriverExtensions.cs
  tests/Aspire.MongoDB.Driver.Tests/MongoDBDriverPublicApiTests.cs
Labels: area-components, community-contribution

#5144 Adding public API test coverage for Aspire.Hosting.Keycloak
  src/Aspire.Hosting.Keycloak/KeycloakResource.cs
  src/Aspire.Hosting.Keycloak/KeycloakResourceBuilderExtensions.cs
  tests/Aspire.Hosting.Keycloak.Tests/KeycloakPublicApiTests.cs
Labels: area-app-model, community-contribution, testing ☑️

#5244 [tests] Add CosmosEndToEnd to playground tests
  playground/CosmosEndToEnd/CosmosEndToEnd.ApiService/Program.cs
  tests/Aspire.Playground.Tests/AppHostTests.cs
  tests/Aspire.Playground.Tests/Aspire.Playground.Tests.csproj
Labels: area-components

#5243 [tests] Addressing review feedback for Aspire.Playground.Tests
  playground/Directory.Build.targets
  tests/Aspire.Playground.Tests/AppHostTests.cs
  tests/Aspire.Playground.Tests/Aspire.Playground.Tests.csproj
Labels: testing ☑️

#5245 Quarantine AppBarTests.AppBar_Change_Theme
  tests/Aspire.Dashboard.Tests/Integration/Playwright/AppBarTests.cs
Labels: area-codeflow, testing ☑️

#5233 Improve notification loop exit
  tests/Aspire.Hosting.Testing.Tests/TestingFactoryTests.cs
  tests/Aspire.Hosting.Tests/Utils/LoggerNotificationExtensions.cs
Labels: area-app-model

#5018 Add viewer for long strings in GridValue
  src/Aspire.Dashboard/Components/App.razor
  src/Aspire.Dashboard/Components/Controls/GridValue.razor
  src/Aspire.Dashboard/Components/Controls/GridValue.razor.cs
  src/Aspire.Dashboard/Components/Controls/GridValue.razor.css
  src/Aspire.Dashboard/Components/Controls/LogViewer.razor
  src/Aspire.Dashboard/Components/Controls/LogViewer.razor.css
  src/Aspire.Dashboard/Components/Controls/PropertyGrid.razor
  src/Aspire.Dashboard/Components/Controls/ResourceDetails.razor
  src/Aspire.Dashboard/Components/Dialogs/TextVisualizerDialog.razor
  src/Aspire.Dashboard/Components/Dialogs/TextVisualizerDialog.razor.cs
  src/Aspire.Dashboard/Components/Dialogs/TextVisualizerDialog.razor.css
  src/Aspire.Dashboard/Components/Dialogs/TextVisualizerDialog.razor.js
  src/Aspire.Dashboard/Components/Layout/MainLayout.razor
  src/Aspire.Dashboard/Components/Layout/MainLayout.razor.cs
  src/Aspire.Dashboard/Components/ResourcesGridColumns/LogMessageColumnDisplay.razor
  src/Aspire.Dashboard/Components/ResourcesGridColumns/SourceColumnDisplay.razor
  src/Aspire.Dashboard/DashboardWebApplication.cs
  src/Aspire.Dashboard/Extensions/FluentUIExtensions.cs
  src/Aspire.Dashboard/Model/TextVisualizerDialogViewModel.cs
  src/Aspire.Dashboard/Model/ThemeManager.cs
  src/Aspire.Dashboard/Resources/Dialogs.Designer.cs
  src/Aspire.Dashboard/Resources/Dialogs.resx
  src/Aspire.Dashboard/Resources/xlf/Dialogs.cs.xlf
  src/Aspire.Dashboard/Resources/xlf/Dialogs.de.xlf
  src/Aspire.Dashboard/Resources/xlf/Dialogs.es.xlf
  src/Aspire.Dashboard/Resources/xlf/Dialogs.fr.xlf
  src/Aspire.Dashboard/Resources/xlf/Dialogs.it.xlf
  src/Aspire.Dashboard/Resources/xlf/Dialogs.ja.xlf
  src/Aspire.Dashboard/Resources/xlf/Dialogs.ko.xlf
  src/Aspire.Dashboard/Resources/xlf/Dialogs.pl.xlf
  src/Aspire.Dashboard/Resources/xlf/Dialogs.pt-BR.xlf
  src/Aspire.Dashboard/Resources/xlf/Dialogs.ru.xlf
  src/Aspire.Dashboard/Resources/xlf/Dialogs.tr.xlf
  src/Aspire.Dashboard/Resources/xlf/Dialogs.zh-Hans.xlf
  src/Aspire.Dashboard/Resources/xlf/Dialogs.zh-Hant.xlf
  src/Aspire.Dashboard/wwwroot/css/app.css
  src/Aspire.Dashboard/wwwroot/css/highlight.css
  src/Aspire.Dashboard/wwwroot/js/app-theme.js
  src/Aspire.Dashboard/wwwroot/js/app.js
  src/Aspire.Dashboard/wwwroot/js/highlight-11.10.0.min.js
  src/Shared/StringComparers.cs
  tests/Aspire.Dashboard.Components.Tests/Controls/TextVisualizerDialogTests.cs
  tests/Aspire.Dashboard.Components.Tests/Shared/MetricsSetupHelpers.cs
  tests/Aspire.Dashboard.Components.Tests/Shared/TestEffectiveThemeResolver.cs
Labels: area-dashboard

#4869 Escape braces in ReferenceExpression.AppendFormatted()
  src/Aspire.Hosting/ApplicationModel/ReferenceExpression.cs
  tests/Aspire.Hosting.Tests/ReferenceExpressionTests.cs
Labels: area-app-model, community-contribution

#5259 Use key as text visualizer title in property grids
  src/Aspire.Dashboard/Components/Controls/GridValue.razor
  src/Aspire.Dashboard/Components/Controls/GridValue.razor.cs
  src/Aspire.Dashboard/Components/Controls/PropertyGrid.razor
  src/Aspire.Dashboard/Components/Dialogs/TextVisualizerDialog.razor
  src/Aspire.Dashboard/wwwroot/css/app.css
Labels: area-dashboard

#5273 [ci] Disable failing Aspire.Playground.Tests
  tests/Aspire.Playground.Tests/Aspire.Playground.Tests.csproj
  tests/helix/send-to-helix-ci.proj
Labels: area-components

#5269 playground.BrowserTelemetry: avoid using npm on ci/windows
  playground/BrowserTelemetry/BrowserTelemetry.Web/BrowserTelemetry.Web.csproj
Labels: area-engineering-systems

#5251 Improve reliability of `AppHostTests.TestEndpointsReturnOk`
  tests/Aspire.Hosting.MySql.Tests/MySqlFunctionalTests.cs
  tests/Aspire.Hosting.Tests/Utils/LoggerNotificationExtensions.cs
  tests/Aspire.Playground.Tests/AppHostTests.cs
  tests/Aspire.Playground.Tests/Aspire.Playground.Tests.csproj
Labels: area-components

#5253 [ci] Avoid duplicating trx file on helix, and copy it for playground tests also
  tests/helix/send-to-helix-basictests.targets
  tests/helix/send-to-helix-buildonhelixtests.targets
  tests/helix/send-to-helix-endtoendtests.targets
  tests/helix/send-to-helix-workloadtests.targets
Labels: area-engineering-systems, testing ☑️

#5271 [tests] Try to fix random failures on playground tests build
  playground/AzureSearchEndToEnd/AzureSearch.AppHost/Program.cs
  playground/BrowserTelemetry/BrowserTelemetry.AppHost/Program.cs
  playground/Directory.Build.targets
  playground/OpenAIEndToEnd/OpenAIEndToEnd.AppHost/Program.cs
  playground/OracleEndToEnd/OracleEndToEnd.AppHost/Program.cs
  playground/bicep/BicepSample.AppHost/Program.cs
  playground/cdk/CdkSample.AppHost/Program.cs
  playground/dapr/Dapr.AppHost/Program.cs
Labels: area-components

#5270 [tests] Bump timeout for Aspire.Hosting.Elasticsearch.Tests to 20 mins
  tests/helix/send-to-helix-basictests.targets
Labels: area-components, testing ☑️

#5272 Use test container registry with Oracle
  tests/Aspire.Oracle.EntityFrameworkCore.Tests/OracleContainerFixture.cs
Labels: area-components

#5249 Improve stability of Valkey functional tests
  tests/Aspire.Hosting.Valkey.Tests/ValkeyFunctionalTests.cs
Labels: area-app-model

#5280 Clean some project files
  src/Aspire.Hosting.Elasticsearch/Aspire.Hosting.Elasticsearch.csproj
  tests/Aspire.Hosting.Tests/Aspire.Hosting.Tests.csproj
Labels: area-components

#5276 [tests] Re-enable Aspire.Playground.Tests
  tests/Aspire.Playground.Tests/Aspire.Playground.Tests.csproj
  tests/helix/send-to-helix-ci.proj
Labels: testing ☑️

#5235 Adds improved default auth to Milvus
  playground/milvus/MilvusPlayground.ApiService/Properties/launchSettings.json
  playground/milvus/MilvusPlayground.AppHost/Program.cs
  src/Aspire.Hosting.Milvus/MilvusBuilderExtensions.cs
  src/Aspire.Hosting.Milvus/MilvusContainerImageTags.cs
  src/Aspire.Hosting.Milvus/MilvusServerResource.cs
  src/Aspire.Hosting.Milvus/PublicAPI.Unshipped.txt
  tests/Aspire.Hosting.Milvus.Tests/AddMilvusTests.cs
  tests/Aspire.Hosting.Milvus.Tests/MilvusFunctionalTests.cs
  tests/Aspire.Hosting.Milvus.Tests/MilvusPublicApiTests.cs
Labels: area-app-model

#5281 Extract Aspire.Hosting.AWS.Tests
  Aspire.sln
  src/Aspire.Hosting.AWS/Aspire.Hosting.AWS.csproj
  tests/Aspire.Hosting.AWS.Tests/AWSCloudFormationResourceTests.cs
  tests/Aspire.Hosting.AWS.Tests/AWSSchemaTests.cs
  tests/Aspire.Hosting.AWS.Tests/Aspire.Hosting.AWS.Tests.csproj
  tests/Aspire.Hosting.AWS.Tests/StackOutputReferenceTests.cs
  tests/Aspire.Hosting.Tests/Aspire.Hosting.Tests.csproj
  tests/Aspire.Hosting.Tests/Schema/SchemaTests.cs
Labels: area-app-model, testing ☑️

#5220 Hosting.Keycloak: Fix `importDirectory` param validation in `WithRealmImport`
  src/Aspire.Hosting.Keycloak/KeycloakResourceBuilderExtensions.cs
  tests/Aspire.Hosting.Keycloak.Tests/KeycloakPublicApiTests.cs
  tests/Aspire.Playground.Tests/AppHostTests.cs
  tests/Aspire.Playground.Tests/Aspire.Playground.Tests.csproj
  tests/Shared/RepoTesting/Directory.Packages.Helix.props
Labels: area-app-model

#5201 Adding public API test coverage for Aspire.Hosting.MongoDB
  src/Aspire.Hosting.MongoDB/MongoDBBuilderExtensions.cs
  src/Aspire.Hosting.MongoDB/MongoDBDatabaseResource.cs
  tests/Aspire.Hosting.MongoDB.Tests/MongoDBPublicApiTests.cs
Labels: area-app-model, community-contribution

#5168 Adding public API test coverage for Microsoft.Extensions.ServiceDiscovery.Yarp
  src/Microsoft.Extensions.ServiceDiscovery.Yarp/ServiceDiscoveryReverseProxyServiceCollectionExtensions.cs
  tests/Microsoft.Extensions.ServiceDiscovery.Yarp.Tests/YarpServiceDiscoveryPublicApiTests.cs
Labels: area-app-model, community-contribution, testing ☑️

#5286 Traces UI update to add color and move timestamp
  src/Aspire.Dashboard/Components/Pages/Traces.razor
Labels: area-dashboard

#5161 Adding public API test coverage Aspire.Hosting.NodeJs
  src/Aspire.Hosting.NodeJs/NodeAppResource.cs
  src/Aspire.Hosting.NodeJs/NodeExtensions.cs
  tests/Aspire.Hosting.NodeJs.Tests/NodeJsPublicApiTests.cs
Labels: area-components, community-contribution

#5261 Add connection-level security to frontend
  src/Aspire.Dashboard/Authentication/AspirePolicyEvaluator.cs
  src/Aspire.Dashboard/Authentication/Connection/ConnectionType.cs
  src/Aspire.Dashboard/Authentication/Connection/ConnectionTypeAuthenticationHandler.cs
  src/Aspire.Dashboard/Authentication/Connection/ConnectionTypeMiddleware.cs
  src/Aspire.Dashboard/Authentication/Connection/IConnectionTypeFeature.cs
  src/Aspire.Dashboard/Authentication/Connection/ListenOptionsConnectionTypeExtensions.cs
  src/Aspire.Dashboard/Authentication/FrontendCompositeAuthenticationHandler.cs
  src/Aspire.Dashboard/Authentication/OtlpCompositeAuthenticationHandler.cs
  src/Aspire.Dashboard/Authentication/OtlpConnection/ListenOptionsOtlpExtensions.cs
  src/Aspire.Dashboard/Authentication/OtlpConnection/OtlpConnectionAuthenticationHandler.cs
  src/Aspire.Dashboard/DashboardWebApplication.cs
  src/Aspire.Dashboard/Model/BrowserSecurityHeadersMiddleware.cs
  tests/Aspire.Dashboard.Tests/BrowserSecurityHeadersMiddlewareTests.cs
  tests/Aspire.Dashboard.Tests/Integration/FrontendBrowserTokenAuthTests.cs
  tests/Aspire.Dashboard.Tests/Integration/FrontendOpenIdConnectAuthTests.cs
  tests/Aspire.Dashboard.Tests/Integration/OtlpHttpServiceTests.cs
Labels: area-dashboard

#5149 Adding public API test coverage for Aspire.Hosting.PostgreSQL
  src/Aspire.Hosting.PostgreSQL/PgAdminConfigWriterHook.cs
  src/Aspire.Hosting.PostgreSQL/PgAdminContainerResource.cs
  src/Aspire.Hosting.PostgreSQL/PostgresBuilderExtensions.cs
  src/Aspire.Hosting.PostgreSQL/PostgresDatabaseResource.cs
  src/Aspire.Hosting.PostgreSQL/PostgresServerResource.cs
  tests/Aspire.Hosting.PostgreSQL.Tests/PostgrePublicApiTests.cs
Labels: area-app-model, community-contribution, testing ☑️

#5160 Adding public API test coverage for Aspire.Hosting.Garnet
  src/Aspire.Hosting.Garnet/GarnetBuilderExtensions.cs
  src/Aspire.Hosting.Garnet/GarnetResource.cs
  tests/Aspire.Hosting.Garnet.Tests/GarnetPublicApiTests.cs
Labels: area-app-model, community-contribution, testing ☑️

#5252 [tests] Add more playground apps to tests
  docs/updating-container-registry.md
  playground/ParameterEndToEnd/ParameterEndToEnd.ApiService/Program.cs
  src/Aspire.Hosting.MySql/MySqlBuilderExtensions.cs
  tests/Aspire.Playground.Tests/.runsettings
  tests/Aspire.Playground.Tests/AppHostTests.cs
  tests/Aspire.Playground.Tests/Aspire.Playground.Tests.csproj
  tests/Aspire.Playground.Tests/Infrastructure/DistributedApplicationExtensions.cs
  tests/Aspire.Playground.Tests/Infrastructure/DistributedApplicationTestFactory.cs
  tests/helix/send-to-helix-buildonhelixtests.targets
Labels: area-components, testing ☑️

#5150 Support filtering telemetry to all instances of a resource
  src/Aspire.Dashboard/Components/Controls/Chart/ChartBase.cs
  src/Aspire.Dashboard/Components/Controls/Chart/ChartContainer.razor
  src/Aspire.Dashboard/Components/Controls/Chart/ChartContainer.razor.cs
  src/Aspire.Dashboard/Components/Controls/Chart/ChartFilters.razor
  src/Aspire.Dashboard/Components/Controls/Chart/ChartFilters.razor.cs
  src/Aspire.Dashboard/Components/Controls/Chart/MetricTable.razor.cs
  src/Aspire.Dashboard/Components/Controls/ResourceSelect.razor
  src/Aspire.Dashboard/Components/Controls/ResourceSelect.razor.cs
  src/Aspire.Dashboard/Components/Pages/Metrics.razor
  src/Aspire.Dashboard/Components/Pages/Metrics.razor.cs
  src/Aspire.Dashboard/Components/Pages/StructuredLogs.razor
  src/Aspire.Dashboard/Components/Pages/StructuredLogs.razor.cs
  src/Aspire.Dashboard/Components/Pages/Traces.razor
  src/Aspire.Dashboard/Components/Pages/Traces.razor.cs
  src/Aspire.Dashboard/Model/DefaultInstrumentUnitResolver.cs
  src/Aspire.Dashboard/Model/ExemplarsDialogViewModel.cs
  src/Aspire.Dashboard/Model/IInstrumentUnitResolver.cs
  src/Aspire.Dashboard/Model/InstrumentViewModel.cs
  src/Aspire.Dashboard/Model/Otlp/ApplicationsSelectHelpers.cs
  src/Aspire.Dashboard/Model/ResourceTypeDetails.cs
  src/Aspire.Dashboard/Otlp/Model/OtlpApplication.cs
  src/Aspire.Dashboard/Otlp/Model/OtlpInstrument.cs
  src/Aspire.Dashboard/Otlp/Storage/ApplicationKey.cs
  src/Aspire.Dashboard/Otlp/Storage/TelemetryRepository.cs
  tests/Aspire.Dashboard.Components.Tests/Controls/PlotlyChartTests.cs
  tests/Aspire.Dashboard.Components.Tests/Shared/TestInstrumentUnitResolver.cs
  tests/Aspire.Dashboard.Tests/Model/ApplicationsSelectHelpersTests.cs
  tests/Aspire.Dashboard.Tests/TelemetryRepositoryTests/ApplicationTests.cs
  tests/Aspire.Dashboard.Tests/TelemetryRepositoryTests/LogTests.cs
  tests/Aspire.Dashboard.Tests/TelemetryRepositoryTests/MetricsTests.cs
  tests/Aspire.Dashboard.Tests/TelemetryRepositoryTests/TraceTests.cs
Labels: area-dashboard, area-telemetry

#5223 .NET Aspire Eventing API
  .editorconfig
  src/Aspire.Hosting.Azure.EventHubs/AzureEventHubsEmulatorConfigWriterHook.cs
  src/Aspire.Hosting.Azure.EventHubs/AzureEventHubsExtensions.cs
  src/Aspire.Hosting.Kafka/KafkaBuilderExtensions.cs
  src/Aspire.Hosting.Kafka/KafkaUIConfigWriterHook.cs
  src/Aspire.Hosting.MySql/MySqlBuilderExtensions.cs
  src/Aspire.Hosting.MySql/PhpMyAdminConfigWriterHook.cs
  src/Aspire.Hosting.PostgreSQL/PgAdminConfigWriterHook.cs
  src/Aspire.Hosting.PostgreSQL/PostgresBuilderExtensions.cs
  src/Aspire.Hosting.PostgreSQL/PublicAPI.Unshipped.txt
  src/Aspire.Hosting.Redis/RedisBuilderExtensions.cs
  src/Aspire.Hosting.Redis/RedisCommanderConfigWriterHook.cs
  src/Aspire.Hosting/ApplicationModel/AfterEndpointsAllocatedEvent.cs
  src/Aspire.Hosting/ApplicationModel/AfterResourcesCreatedEvent.cs
  src/Aspire.Hosting/ApplicationModel/BeforeStartEvent.cs
  src/Aspire.Hosting/BuiltInDistributedApplicationEventSubscriptionHandlers.cs
  src/Aspire.Hosting/Dashboard/DashboardManifestExclusionHook.cs
  src/Aspire.Hosting/Dcp/ApplicationExecutor.cs
  src/Aspire.Hosting/DistributedApplication.cs
  src/Aspire.Hosting/DistributedApplicationBuilder.cs
  src/Aspire.Hosting/Eventing/DistributedApplicationEventSubscription.cs
  src/Aspire.Hosting/Eventing/DistributedApplicationEventing.cs
  src/Aspire.Hosting/Eventing/IDistributedApplicationEvent.cs
  src/Aspire.Hosting/Eventing/IDistributedApplicationEventing.cs
  src/Aspire.Hosting/IDistributedApplicationBuilder.cs
  src/Aspire.Hosting/Lifecycle/ContainerRegistryHook.cs
  src/Aspire.Hosting/PublicAPI.Unshipped.txt
  src/Aspire.Hosting/Publishing/Http2TransportMutationHook.cs
  tests/Aspire.Hosting.MySql.Tests/AddMySqlTests.cs
  tests/Aspire.Hosting.PostgreSQL.Tests/AddPostgresTests.cs
  tests/Aspire.Hosting.PostgreSQL.Tests/PostgrePublicApiTests.cs
  tests/Aspire.Hosting.Redis.Tests/AddRedisTests.cs
  tests/Aspire.Hosting.Redis.Tests/Aspire.Hosting.Redis.Tests.csproj
  tests/Aspire.Hosting.Redis.Tests/RedisPublicApiTests.cs
  tests/Aspire.Hosting.Tests/Dcp/ApplicationExecutorTests.cs
  tests/Aspire.Hosting.Tests/DistributedApplicationBuilderTests.cs
  tests/Aspire.Hosting.Tests/Eventing/DistributedApplicationBuilderEventingTests.cs
  tests/Aspire.Hosting.Tests/Utils/TestDistributedApplicationBuilder.cs
Labels: area-app-model

#5296 Improve support for non-primitive OTEL values
  src/Aspire.Dashboard/Otlp/Model/OtlpHelpers.cs
  tests/Aspire.Dashboard.Tests/TelemetryRepositoryTests/OtlpHelpersTests.cs
Labels: area-dashboard, area-telemetry

#5294 [tests] Add tests for more Playground apps
  playground/TestShop/TestShop.AppHost/Program.cs
  tests/Aspire.Playground.Tests/AppHostTests.cs
  tests/Aspire.Playground.Tests/Aspire.Playground.Tests.csproj
  tests/Aspire.Playground.Tests/Infrastructure/DistributedApplicationTestFactory.cs
Labels: area-app-model, testing ☑️

#5301 [ci] Cleanup of `DisablePlaywright` setting
  tests/helix/send-to-helix-inner.proj
Labels: area-engineering-systems, testing ☑️

#5306 [tests] Add waitForTexts for Milvus playground app test
  tests/Aspire.Playground.Tests/AppHostTests.cs
Labels: area-app-model, testing ☑️

#5316 [tests] Add AzureStorageEndToEnd playground app to tests
  playground/AzureStorageEndToEnd/AzureStorageEndToEnd.ApiService/Program.cs
  tests/Aspire.Playground.Tests/AppHostTests.cs
  tests/Aspire.Playground.Tests/Aspire.Playground.Tests.csproj
Labels: area-components

#5315 [tests] DockerUtils.AttemptDeleteDockerVolume - allow throwing on failures
  tests/Aspire.Hosting.Elasticsearch.Tests/ElasticsearchFunctionalTests.cs
  tests/Aspire.Hosting.Kafka.Tests/KafkaFunctionalTests.cs
  tests/Aspire.Hosting.Milvus.Tests/MilvusFunctionalTests.cs
  tests/Aspire.Hosting.MongoDB.Tests/MongoDbFunctionalTests.cs
  tests/Aspire.Hosting.MySql.Tests/MySqlFunctionalTests.cs
  tests/Aspire.Hosting.Nats.Tests/NatsFunctionalTests.cs
  tests/Aspire.Hosting.PostgreSQL.Tests/PostgresFunctionalTests.cs
  tests/Aspire.Hosting.Qdrant.Tests/QdrantFunctionalTests.cs
  tests/Aspire.Hosting.RabbitMQ.Tests/RabbitMQFunctionalTests.cs
  tests/Aspire.Hosting.Redis.Tests/RedisFunctionalTests.cs
  tests/Aspire.Hosting.SqlServer.Tests/SqlServerFunctionalTests.cs
  tests/Aspire.Hosting.Tests/Utils/DockerUtils.cs
  tests/Aspire.Hosting.Valkey.Tests/ValkeyFunctionalTests.cs
Labels: area-app-model, testing ☑️

#5266 Replace data grid column headers with custom template
  src/Aspire.Dashboard/Components/Controls/Chart/ChartFilters.razor
  src/Aspire.Dashboard/Components/Controls/Chart/MetricTable.razor
  src/Aspire.Dashboard/Components/Controls/Grid/AspireFluentDataGridHeaderCell.razor
  src/Aspire.Dashboard/Components/Controls/Grid/AspireFluentDataGridHeaderCell.razor.cs
  src/Aspire.Dashboard/Components/Controls/Grid/AspirePropertyColumn.cs
  src/Aspire.Dashboard/Components/Controls/Grid/AspireTemplateColumn.cs
  src/Aspire.Dashboard/Components/Controls/PropertyGrid.razor
  src/Aspire.Dashboard/Components/Controls/ResourceDetails.razor
  src/Aspire.Dashboard/Components/Controls/SpanDetails.razor
  src/Aspire.Dashboard/Components/Controls/SpanDetails.razor.cs
  src/Aspire.Dashboard/Components/Dialogs/ExemplarsDialog.razor
  src/Aspire.Dashboard/Components/Pages/Metrics.razor
  src/Aspire.Dashboard/Components/Pages/Resources.razor
  src/Aspire.Dashboard/Components/Pages/StructuredLogs.razor
  src/Aspire.Dashboard/Components/Pages/TraceDetail.razor
  src/Aspire.Dashboard/Components/Pages/Traces.razor
  src/Aspire.Dashboard/Resources/ControlsStrings.Designer.cs
  src/Aspire.Dashboard/Resources/ControlsStrings.resx
  src/Aspire.Dashboard/Resources/xlf/ControlsStrings.cs.xlf
  src/Aspire.Dashboard/Resources/xlf/ControlsStrings.de.xlf
  src/Aspire.Dashboard/Resources/xlf/ControlsStrings.es.xlf
  src/Aspire.Dashboard/Resources/xlf/ControlsStrings.fr.xlf
  src/Aspire.Dashboard/Resources/xlf/ControlsStrings.it.xlf
  src/Aspire.Dashboard/Resources/xlf/ControlsStrings.ja.xlf
  src/Aspire.Dashboard/Resources/xlf/ControlsStrings.ko.xlf
  src/Aspire.Dashboard/Resources/xlf/ControlsStrings.pl.xlf
  src/Aspire.Dashboard/Resources/xlf/ControlsStrings.pt-BR.xlf
  src/Aspire.Dashboard/Resources/xlf/ControlsStrings.ru.xlf
  src/Aspire.Dashboard/Resources/xlf/ControlsStrings.tr.xlf
  src/Aspire.Dashboard/Resources/xlf/ControlsStrings.zh-Hans.xlf
  src/Aspire.Dashboard/Resources/xlf/ControlsStrings.zh-Hant.xlf
  tests/Aspire.Dashboard.Components.Tests/Pages/StructuredLogsTests.cs
  tests/Aspire.Dashboard.Components.Tests/Shared/MetricsSetupHelpers.cs
Labels: area-dashboard

#5302 Populate dashpages from configuration
  spelling.dic
  src/Aspire.Dashboard/Components/Controls/Chart/DashpageCharts.razor
  src/Aspire.Dashboard/Components/Pages/Metrics.razor
  src/Aspire.Dashboard/Components/Pages/Metrics.razor.cs
  src/Aspire.Dashboard/DashboardWebApplication.cs
  src/Aspire.Dashboard/Model/DashpageModels.cs
  src/Aspire.Dashboard/dashpages.json
  tests/Aspire.Dashboard.Components.Tests/Controls/PlotlyChartTests.cs
  tests/Aspire.Dashboard.Components.Tests/Shared/MetricsSetupHelpers.cs
  tests/Aspire.Dashboard.Components.Tests/Shared/TestDashpagePersistence.cs
  tests/Aspire.Dashboard.Tests/Model/DashpageJsonFilePersistenceTests.cs
Labels: area-dashboard, area-dashboard-dashpages

#5323 Allow env var with no name in dashboard
  src/Aspire.Dashboard/Model/ResourceViewModel.cs
  src/Aspire.Dashboard/ResourceService/Partials.cs
  tests/Aspire.Dashboard.Tests/Model/ResourceViewModelTests.cs
Labels: area-dashboard

#5282 Extract Aspire.Hosting.Dapr.Tests
  Aspire.sln
  tests/Aspire.Hosting.Dapr.Tests/Aspire.Hosting.Dapr.Tests.csproj
  tests/Aspire.Hosting.Dapr.Tests/DaprSchemaTests.cs
  tests/Aspire.Hosting.Dapr.Tests/DaprTests.cs
  tests/Aspire.Hosting.Tests/Aspire.Hosting.Tests.csproj
  tests/Aspire.Hosting.Tests/Schema/SchemaTests.cs
Labels: area-app-model, testing ☑️

#5320 Update default dashpages
  src/Aspire.Dashboard/dashpages.json
Labels: area-dashboard, area-dashboard-dashpages

#5321 [tests] Hosting.RabbitMQ: Adding waitFor, and xunit logging for client
  tests/Aspire.Hosting.RabbitMQ.Tests/RabbitMQFunctionalTests.cs
Labels: area-app-model, testing ☑️

#5318 [tests] Misc fixes for playground tests
  tests/Aspire.Playground.Tests/AppHostTests.cs
  tests/Aspire.Playground.Tests/Aspire.Playground.Tests.csproj
  tests/helix/send-to-helix-buildonhelixtests.targets
Labels: area-app-model, testing ☑️

#5327 Fix build break in Linux
  playground/BrowserTelemetry/BrowserTelemetry.Web/webpack.config.js
Labels: area-engineering-systems

#3833 Added implementation to support EventHubBufferedProducerClient
  src/Components/Aspire.Azure.Messaging.EventHubs/AspireEventHubsExtensions.cs
  src/Components/Aspire.Azure.Messaging.EventHubs/AzureMessagingEventHubsSettings.cs
  src/Components/Aspire.Azure.Messaging.EventHubs/EventHubBufferedProducerClientComponent.cs
  src/Components/Aspire.Azure.Messaging.EventHubs/PublicAPI.Unshipped.txt
  src/Components/Aspire.Azure.Messaging.EventHubs/README.md
  tests/Aspire.Azure.Messaging.EventHubs.Tests/AspireEventHubsExtensionsTests.cs
Labels: area-components, community-contribution

#5328 [tests] Add resource logging to EndToEnd tests
  src/Aspire.Hosting.Testing/ResourceLoggerForwarderService.cs
  tests/Aspire.EndToEnd.Tests/Aspire.EndToEnd.Tests.csproj
  tests/testproject/TestProject.AppHost/TestProgram.cs
  tests/testproject/TestProject.AppHost/TestProject.AppHost.csproj
Labels: area-app-model, testing ☑️

#5098 Add `WithPgWeb`
  playground/PostgresEndToEnd/PostgresEndToEnd.AppHost/Program.cs
  playground/PostgresEndToEnd/PostgresEndToEnd.AppHost/aspire-manifest.json
  spelling.dic
  src/Aspire.Hosting.PostgreSQL/PgWebContainerResource.cs
  src/Aspire.Hosting.PostgreSQL/PostgresBuilderExtensions.cs
  src/Aspire.Hosting.PostgreSQL/PostgresContainerImageTags.cs
  src/Aspire.Hosting.PostgreSQL/PublicAPI.Unshipped.txt
  tests/Aspire.Hosting.PostgreSQL.Tests/AddPostgresTests.cs
  tests/Aspire.Hosting.PostgreSQL.Tests/PostgresFunctionalTests.cs
Labels: area-components, community-contribution

#5351 Fix nuget8.config path in docs
  tests/Aspire.Workload.Tests/README.md
Labels: area-components

#5337 Filter dashpages to show only available ones
  src/Aspire.Dashboard/Components/Pages/Metrics.razor
  src/Aspire.Dashboard/Components/Pages/Metrics.razor.cs
  src/Shared/StringComparers.cs
  tests/Aspire.Dashboard.Components.Tests/Pages/MetricsViewModelTests.cs
Labels: area-dashboard-dashpages

#5352 [tests] Fix AddPostgresTests.WithPgwebProducesValidBookmarkFiles
  tests/Aspire.Hosting.PostgreSQL.Tests/AddPostgresTests.cs
Labels: area-app-model, testing ☑️

#5357 Fix console logs content changing order and the line number increasing
  src/Aspire.Hosting/ApplicationModel/ResourceLoggerService.cs
  src/Aspire.Hosting/Dashboard/DashboardService.cs
  src/Aspire.Hosting/Dcp/ApplicationExecutor.cs
  src/Aspire.Hosting/Dcp/ResourceLogSource.cs
  tests/Aspire.Hosting.Tests/Dcp/ApplicationExecutorTests.cs
  tests/Aspire.Hosting.Tests/Dcp/TestKubernetesService.cs
  tests/Aspire.Hosting.Tests/ResourceLoggerServiceTests.cs
  tests/Aspire.Hosting.Tests/Utils/AsyncTestHelpers.cs
Labels: area-app-model

#5361 Fix disabled meter column names
  src/Aspire.Dashboard/Components/Pages/Metrics.razor
  src/Aspire.Dashboard/Components/Pages/Metrics.razor.css
Labels: area-dashboard

#5358 Fix launching Azure Eventhubs emulator on linux
  src/Aspire.Hosting.Azure.EventHubs/AzureEventHubsExtensions.cs
Labels: area-app-model

#5365 [tests] Aspire.Playground.Tests: bump request timeout
  tests/Aspire.Playground.Tests/AppHostTests.cs
Labels: area-app-model, testing ☑️

#5350 Aspire.Hosting.Testing: Fix loading apphost assembly from a directory outside the entry assembly's location
  src/Aspire.Hosting.Testing/DistributedApplicationFactory.cs
  tests/Aspire.Hosting.Testing.Tests/Aspire.Hosting.Testing.Tests.csproj
  tests/Aspire.Hosting.Testing.Tests/TestingBuilderTests.cs
  tests/Aspire.Hosting.Tests/MSBuildTests.cs
  tests/Aspire.Hosting.Tests/Utils/MSBuildUtils.cs
  tests/testassets/ClassLibrary/Class1.cs
  tests/testassets/ClassLibrary/ClassLibrary.csproj
Labels: area-app-testing

#5363 Only run npm if required
  playground/BrowserTelemetry/BrowserTelemetry.Web/BrowserTelemetry.Web.csproj
  playground/BrowserTelemetry/BrowserTelemetry.Web/README.md
Labels: area-engineering-systems

#5366 ElasticSearchInstrumentationEndToEnd: Increase timeout for RemoteExecutor
  eng/test-configuration.json
  tests/Aspire.Elastic.Clients.Elasticsearch.Tests/AspireElasticClientExtensionsTest.cs
Labels: area-engineering-systems, testing ☑️

#5348 DistributedApplicationTestingBuilder.CreateAsync - Make an overload public
  src/Aspire.Hosting.Testing/DistributedApplicationTestingBuilder.cs
  src/Aspire.Hosting.Testing/PublicAPI.Unshipped.txt
  tests/Aspire.Hosting.Testing.Tests/PublicApiTests.cs
  tests/Aspire.Hosting.Testing.Tests/TestingBuilderTests.cs
Labels: area-app-testing

#5369 Change cert thumbprint rule to use SHA256 hash
  src/Aspire.Dashboard/DashboardWebApplication.cs
  tests/Aspire.Dashboard.Tests/Integration/OtlpGrpcServiceTests.cs
Labels: area-dashboard

#5119 Adding public API test coverage for Aspire.Hosting.Elasticsearch
  src/Aspire.Hosting.Elasticsearch/ElasticsearchBuilderExtensions.cs
  tests/Aspire.Hosting.Elasticsearch.Tests/ElasticsearchPublicApiTests.cs
Labels: area-components, community-contribution

#5370 [tests] Remove unused bits left by a previous commit
  tests/Aspire.Hosting.Testing.Tests/Aspire.Hosting.Testing.Tests.csproj
  tests/testassets/ClassLibrary/Class1.cs
  tests/testassets/ClassLibrary/ClassLibrary.csproj
Labels: area-app-model, testing ☑️

#5374 Bump default AzureOpenAIDeployment sku
  playground/OpenAIEndToEnd/OpenAIEndToEnd.AppHost/Program.cs
  src/Aspire.Hosting.Azure.CognitiveServices/AzureOpenAIDeployment.cs
  src/Aspire.Hosting.Azure.CognitiveServices/PublicAPI.Unshipped.txt
Labels: area-app-model

#5376 Add TFM guidance for Aspire Client Library Integrations
  src/Components/README.md
Labels: area-components

#5043 Setting a default TLS version for Azure SQL to 1.2
  src/Aspire.Hosting.Azure.Sql/AzureSqlExtensions.cs
  tests/Aspire.Hosting.Azure.Tests/AzureBicepResourceTests.cs
Labels: area-app-model, community-contribution

#5359 Introduce ResourceCreatingEvent
  src/Aspire.Hosting.Azure/Provisioning/Provisioners/AzureProvisioner.cs
  src/Aspire.Hosting/ApplicationModel/BeforeResourceStartedEvent.cs
  src/Aspire.Hosting/Dcp/ApplicationExecutor.cs
  src/Aspire.Hosting/PublicAPI.Unshipped.txt
  tests/Aspire.Hosting.Tests/Eventing/DistributedApplicationBuilderEventingTests.cs
Labels: area-app-model

#5381 Fix credscan warning in ElasticsearchPublicApiTests.cs
  tests/Aspire.Hosting.Elasticsearch.Tests/ElasticsearchPublicApiTests.cs
Labels: area-engineering-systems, testing ☑️

#4708 Remove DCP and Dashboard from the .NET Aspire SDK Workload
  docs/specs/future-of-workload.md
  eng/Build.props
  eng/Versions.props
  eng/dashboardpack/Aspire.Dashboard.Sdk.linux-arm64.csproj
  eng/dashboardpack/Aspire.Dashboard.Sdk.linux-x64.csproj
  eng/dashboardpack/Aspire.Dashboard.Sdk.osx-arm64.csproj
  eng/dashboardpack/Aspire.Dashboard.Sdk.osx-x64.csproj
  eng/dashboardpack/Aspire.Dashboard.Sdk.win-arm64.csproj
  eng/dashboardpack/Aspire.Dashboard.Sdk.win-x64.csproj
  eng/dashboardpack/Aspire.Dashboard.Sdk.win-x86.csproj
  eng/dashboardpack/Common.projitems
  eng/dashboardpack/Sdk.in.targets
  eng/dashboardpack/buildMultiTargeting/Aspire.Dashboard.Sdk.in.props
  eng/dashboardpack/buildMultiTargeting/Aspire.Dashboard.Sdk.in.targets
  eng/dashboardpack/buildTransitive/Aspire.Dashboard.Sdk.in.props
  eng/dashboardpack/buildTransitive/Aspire.Dashboard.Sdk.in.targets
  eng/dashboardpack/dashboardpack.csproj
  eng/dcppack/Aspire.Hosting.Orchestration.in.targets
  eng/dcppack/Aspire.Hosting.Orchestration.linux-arm64.csproj
  eng/dcppack/Aspire.Hosting.Orchestration.linux-x64.csproj
  eng/dcppack/Aspire.Hosting.Orchestration.osx-arm64.csproj
  eng/dcppack/Aspire.Hosting.Orchestration.osx-x64.csproj
  eng/dcppack/Aspire.Hosting.Orchestration.props
  eng/dcppack/Aspire.Hosting.Orchestration.win-arm64.csproj
  eng/dcppack/Aspire.Hosting.Orchestration.win-x64.csproj
  eng/dcppack/Aspire.Hosting.Orchestration.win-x86.csproj
  eng/dcppack/Common.projitems
  eng/dcppack/Sdk.in.targets
  eng/dcppack/Sdk.props
  eng/dcppack/buildMultiTargeting/Aspire.Hosting.Orchestration.in.targets
  eng/dcppack/buildTransitive/Aspire.Hosting.Orchestration.in.targets
  eng/workloads/workloads.csproj
  src/Aspire.Hosting.AppHost/Aspire.Hosting.AppHost.csproj
  src/Aspire.Hosting.AppHost/build/Aspire.Hosting.AppHost.targets
  src/Aspire.Hosting.Sdk/Aspire.Hosting.Sdk.csproj
  src/Aspire.Hosting.Sdk/SDK/Sdk.in.props
  src/Aspire.Hosting.Sdk/SDK/Sdk.props
  src/Aspire.Hosting.Sdk/SDK/Sdk.targets
  src/Microsoft.NET.Sdk.Aspire/WorkloadManifest.Aspire.targets
  src/Microsoft.NET.Sdk.Aspire/WorkloadManifest.in.json
  tests/Aspire.Hosting.Testing.Tests/Directory.Build.targets
  tests/Aspire.Hosting.Tests/MSBuildTests.cs
  tests/Aspire.Workload.Tests/TemplateTests.cs
  tests/Shared/Aspire.Workload.Testing.targets
  tests/Shared/RepoTesting/Aspire.RepoTesting.props
  tests/Shared/RepoTesting/Aspire.RepoTesting.targets
  tests/helix/send-to-helix-inner.proj
Labels: area-acquisition

#5388 Addressing follow-up feedback from the workload PR.
  docs/specs/future-of-workload.md
  src/Aspire.Hosting.AppHost/Aspire.Hosting.AppHost.csproj
  src/Aspire.Hosting.Sdk/SDK/Sdk.targets
  tests/Aspire.Hosting.Tests/MSBuildTests.cs
  tests/Shared/RepoTesting/Aspire.RepoTesting.props
Labels: area-components

#5387 Fix blob items clashing with each other during stable builds
  eng/Publishing.props
Labels: area-engineering-systems

#5392 Fix Secure Supply Chain Analysis warning - avoid using external registry for golang in playgrounds
  playground/withdockerfile/WithDockerfile.AppHost/qots/Dockerfile
Labels: area-engineering-systems

#5385 Fix regression not showing pointer cursor on trace detail
  src/Aspire.Dashboard/Components/Pages/TraceDetail.razor
  src/Aspire.Dashboard/Components/Pages/TraceDetail.razor.css
Labels: area-dashboard

#5340 Replace "component" with "integration"
  README.md
Labels: area-components

#5403 Update package tags for "integration" and "library" terms
  src/Aspire.Hosting.AWS/Aspire.Hosting.AWS.csproj
  src/Aspire.Hosting.Azure.AppConfiguration/Aspire.Hosting.Azure.AppConfiguration.csproj
  src/Aspire.Hosting.Azure.ApplicationInsights/Aspire.Hosting.Azure.ApplicationInsights.csproj
  src/Aspire.Hosting.Azure.CognitiveServices/Aspire.Hosting.Azure.CognitiveServices.csproj
  src/Aspire.Hosting.Azure.CosmosDB/Aspire.Hosting.Azure.CosmosDB.csproj
  src/Aspire.Hosting.Azure.EventHubs/Aspire.Hosting.Azure.EventHubs.csproj
  src/Aspire.Hosting.Azure.KeyVault/Aspire.Hosting.Azure.KeyVault.csproj
  src/Aspire.Hosting.Azure.OperationalInsights/Aspire.Hosting.Azure.OperationalInsights.csproj
  src/Aspire.Hosting.Azure.PostgreSQL/Aspire.Hosting.Azure.PostgreSQL.csproj
  src/Aspire.Hosting.Azure.Redis/Aspire.Hosting.Azure.Redis.csproj
  src/Aspire.Hosting.Azure.Search/Aspire.Hosting.Azure.Search.csproj
  src/Aspire.Hosting.Azure.ServiceBus/Aspire.Hosting.Azure.ServiceBus.csproj
  src/Aspire.Hosting.Azure.SignalR/Aspire.Hosting.Azure.SignalR.csproj
  src/Aspire.Hosting.Azure.Sql/Aspire.Hosting.Azure.Sql.csproj
  src/Aspire.Hosting.Azure.Storage/Aspire.Hosting.Azure.Storage.csproj
  src/Aspire.Hosting.Azure.WebPubSub/Aspire.Hosting.Azure.WebPubSub.csproj
  src/Aspire.Hosting.Dapr/Aspire.Hosting.Dapr.csproj
  src/Aspire.Hosting.Elasticsearch/Aspire.Hosting.Elasticsearch.csproj
  src/Aspire.Hosting.Garnet/Aspire.Hosting.Garnet.csproj
  src/Aspire.Hosting.Kafka/Aspire.Hosting.Kafka.csproj
  src/Aspire.Hosting.Keycloak/Aspire.Hosting.Keycloak.csproj
  src/Aspire.Hosting.Milvus/Aspire.Hosting.Milvus.csproj
  src/Aspire.Hosting.MongoDB/Aspire.Hosting.MongoDB.csproj
  src/Aspire.Hosting.MySql/Aspire.Hosting.MySql.csproj
  src/Aspire.Hosting.Nats/Aspire.Hosting.Nats.csproj
  src/Aspire.Hosting.NodeJs/Aspire.Hosting.NodeJs.csproj
  src/Aspire.Hosting.Oracle/Aspire.Hosting.Oracle.csproj
  src/Aspire.Hosting.Orleans/Aspire.Hosting.Orleans.csproj
  src/Aspire.Hosting.PostgreSQL/Aspire.Hosting.PostgreSQL.csproj
  src/Aspire.Hosting.Python/Aspire.Hosting.Python.csproj
  src/Aspire.Hosting.Qdrant/Aspire.Hosting.Qdrant.csproj
  src/Aspire.Hosting.RabbitMQ/Aspire.Hosting.RabbitMQ.csproj
  src/Aspire.Hosting.Redis/Aspire.Hosting.Redis.csproj
  src/Aspire.Hosting.Seq/Aspire.Hosting.Seq.csproj
  src/Aspire.Hosting.SqlServer/Aspire.Hosting.SqlServer.csproj
  src/Aspire.Hosting.Valkey/Aspire.Hosting.Valkey.csproj
  src/Components/Directory.Build.props
Labels: area-components

#5406 [templates] Update test package versions
  src/Aspire.ProjectTemplates/templates/aspire-mstest/Aspire.Tests.1.csproj
  src/Aspire.ProjectTemplates/templates/aspire-nunit/Aspire.Tests.1.csproj
Labels: area-templates, testing ☑️

#5411 Fix issue where replacement text is not getting evaluated when pack
  eng/dcppack/Common.projitems
Labels: area-engineering-systems

#5129 Adding public API test coverage for Aspire.Hosting.Nats
  src/Aspire.Hosting.Nats/NatsBuilderExtensions.cs
  src/Aspire.Hosting.Nats/NatsServerResource.cs
  tests/Aspire.Hosting.Nats.Tests/NatsPublicApiTests.cs
Labels: area-app-model, community-contribution, testing ☑️

#5405 Updating NuGet and Docker versions to latest
  Directory.Packages.props
  src/Aspire.Hosting.Elasticsearch/ElasticsearchContainerImageTags.cs
  src/Aspire.Hosting.Kafka/KafkaContainerImageTags.cs
  src/Aspire.Hosting.Keycloak/KeycloakContainerImageTags.cs
  src/Aspire.Hosting.Milvus/MilvusContainerImageTags.cs
  src/Aspire.Hosting.MySql/MySqlBuilderExtensions.cs
  src/Aspire.Hosting.MySql/MySqlContainerImageTags.cs
  src/Aspire.Hosting.Oracle/OracleContainerImageTags.cs
  src/Aspire.Hosting.PostgreSQL/PostgresContainerImageTags.cs
  src/Aspire.Hosting.Qdrant/QdrantContainerImageTags.cs
  src/Aspire.Hosting.Redis/RedisContainerImageTags.cs
  src/Aspire.Hosting.Seq/SeqContainerImageTags.cs
  src/Aspire.Hosting.Valkey/ValkeyContainerImageTags.cs
Labels: area-components, feature

#5110 Adding public API test coverage for Aspire.Hosting.Python
  src/Aspire.Hosting.Python/PythonProjectResource.cs
  src/Aspire.Hosting.Python/PythonProjectResourceBuilderExtensions.cs
  tests/Aspire.Hosting.Python.Tests/PythonPublicApiTests.cs
Labels: area-app-model, community-contribution, testing ☑️

#5428 Test that StringComparers and StringComparisons are kept in sync
  src/Shared/StringComparers.cs
  tests/Aspire.Hosting.Tests/Utils/StringComparersTests.cs
Labels: area-dashboard, area-app-model, testing ☑️

#5433 GridColumnManager improvements
  src/Aspire.Dashboard/Components/ResourcesGridColumns/GridColumnManager.cs
Labels: area-dashboard

#5425 Fix dashboard log parsing in host
  src/Aspire.Hosting/Aspire.Hosting.csproj
  src/Aspire.Hosting/Dashboard/DashboardLifecycleHook.cs
  src/Shared/ConsoleLogs/TimestampParser.cs
  tests/Aspire.Hosting.Tests/Dashboard/DashboardLifecycleHookTests.cs
Labels: area-app-model

#5400 Branding changes for 9.0
  eng/Versions.props
Labels: area-codeflow

#4912 close #2636: added json schemas for Aspire.Hosting.AppHost and Aspire.Hosting.Azure
  src/Aspire.Hosting.AppHost/Aspire.Hosting.AppHost.csproj
  src/Aspire.Hosting.AppHost/AspireAppHostConfiguration.json
  src/Aspire.Hosting.AppHost/build/Aspire.Hosting.AppHost.targets
  src/Aspire.Hosting.Azure/Aspire.Hosting.Azure.csproj
  src/Aspire.Hosting.Azure/AspireAzureConfigurationSchema.json
  src/Aspire.Hosting.Azure/buildTransitive/Aspire.Hosting.Azure.targets
Labels: area-app-model, community-contribution

#5434 Store non-sensitive UI state without protection
  src/Aspire.Dashboard/Components/Controls/SummaryDetailsView.razor.cs
  src/Aspire.Dashboard/Components/Pages/ConsoleLogs.razor.cs
  src/Aspire.Dashboard/Components/Pages/Metrics.razor.cs
  src/Aspire.Dashboard/Components/Pages/StructuredLogs.razor.cs
  src/Aspire.Dashboard/Components/Pages/Traces.razor.cs
  src/Aspire.Dashboard/Model/BrowserStorage/ILocalStorage.cs
  src/Aspire.Dashboard/Model/BrowserStorage/LocalBrowserStorage.cs
  src/Aspire.Dashboard/Model/BrowserStorage/SessionBrowserStorage.cs
  src/Aspire.Dashboard/Utils/IBrowserStorageExtensions.cs
  tests/Aspire.Dashboard.Components.Tests/Shared/TestLocalStorage.cs
  tests/Aspire.Dashboard.Tests/LocalBrowserStorageTests.cs
Labels: area-dashboard

#5429 Give theme cookie an expiration
  src/Aspire.Dashboard/wwwroot/js/app-theme.js
Labels: area-dashboard

#5398 Logging ordering fixes and feedback
  playground/Stress/Stress.ApiService/ConsoleStresser.cs
  playground/Stress/Stress.ApiService/Program.cs
  src/Aspire.Dashboard/Aspire.Dashboard.csproj
  src/Aspire.Dashboard/Components/Controls/LogViewer.razor
  src/Aspire.Dashboard/Components/Controls/LogViewer.razor.cs
  src/Aspire.Dashboard/ConsoleLogs/LogEntries.cs
  src/Aspire.Dashboard/ConsoleLogs/LogEntry.cs
  src/Aspire.Dashboard/ConsoleLogs/LogParser.cs
  src/Aspire.Dashboard/ConsoleLogs/TimestampParser.cs
  src/Aspire.Dashboard/ConsoleLogs/UrlParser.cs
  src/Aspire.Hosting/ApplicationModel/ResourceLoggerService.cs
  src/Aspire.Hosting/Aspire.Hosting.csproj
  src/Aspire.Hosting/Dcp/ApplicationExecutor.cs
  src/Shared/ConsoleLogs/LogEntries.cs
  src/Shared/ConsoleLogs/LogEntry.cs
  src/Shared/ConsoleLogs/TimestampParser.cs
  tests/Aspire.Dashboard.Tests/ConsoleLogsTests/LogEntriesTests.cs
  tests/Aspire.Dashboard.Tests/ConsoleLogsTests/TimestampParserTests.cs
  tests/Aspire.Hosting.Testing.Tests/Aspire.Hosting.Testing.Tests.csproj
  tests/Aspire.Hosting.Testing.Tests/ResourceLoggerForwarderServiceTests.cs
  tests/Aspire.Hosting.Tests/Aspire.Hosting.Tests.csproj
  tests/Aspire.Hosting.Tests/Dashboard/DashboardLifecycleHookTests.cs
  tests/Aspire.Hosting.Tests/Dcp/ApplicationExecutorTests.cs
  tests/Aspire.Hosting.Tests/ResourceLoggerServiceTests.cs
  tests/Shared/ConsoleLogging/ConsoleLoggingTestHelpers.cs
Labels: area-dashboard, area-app-model

#5455 Simplify timestamp display in console logs
  src/Aspire.Dashboard/Components/Controls/LogViewer.razor
  src/Aspire.Dashboard/Components/Controls/LogViewer.razor.cs
  src/Aspire.Dashboard/Components/Pages/ConsoleLogs.razor.cs
  src/Aspire.Hosting/Dashboard/ConsoleLogsConfigurationExtensions.cs
  src/Shared/KnownFormats.cs
  tests/Aspire.Hosting.Testing.Tests/ResourceLoggerForwarderServiceTests.cs
  tests/Aspire.Hosting.Tests/Dcp/ApplicationExecutorTests.cs
  tests/Aspire.Hosting.Tests/ProjectResourceTests.cs
  tests/Aspire.Hosting.Tests/ResourceLoggerServiceTests.cs
Labels: area-dashboard

#5443 Reuse properties in VersionPrefix
  eng/Versions.props
Labels: area-codeflow

#5395 [tests] Add more playground apps
  playground/kafka/Consumer/ConsumerWorker.cs
  playground/withdockerfile/WithDockerfile.AppHost/Program.cs
  tests/Aspire.Hosting.Tests/Utils/LoggerNotificationExtensions.cs
  tests/Aspire.Playground.Tests/Aspire.Playground.Tests.csproj
  tests/Aspire.Playground.Tests/ProjectSpecificTests.cs
  tests/helix/send-to-helix-buildonhelixtests.targets
Labels: area-app-model, testing ☑️

#5449 Mark Aspire.Azure.Messaging.EventHubs as stable
  src/Components/Aspire.Azure.Messaging.EventHubs/Aspire.Azure.Messaging.EventHubs.csproj
Labels: area-components

#5424 [release/8.2] Enable signing and use stable packages
  eng/Versions.props
  eng/pipelines/azure-pipelines.yml
  eng/pipelines/common-variables.yml
  tests/Aspire.EndToEnd.Tests/Aspire.EndToEnd.Tests.csproj
  tests/Shared/RepoTesting/Directory.Packages.Helix.props
Labels: area-engineering-systems, Servicing-approved

#5476 Update MongoDB to 2.28
  Directory.Packages.props
  playground/mongo/Mongo.ApiService/Mongo.ApiService.csproj
  src/Components/Aspire.MongoDB.Driver/Aspire.MongoDB.Driver.csproj
  tests/Aspire.Hosting.MongoDB.Tests/Aspire.Hosting.MongoDB.Tests.csproj
  tests/Aspire.MongoDB.Driver.Tests/Aspire.MongoDB.Driver.Tests.csproj
Labels: area-components

#5465 Persist dismissing the OTLP unsecured message bar
  src/Aspire.Dashboard/Components/Controls/SummaryDetailsView.razor.cs
  src/Aspire.Dashboard/Components/Controls/UserProfile.razor
  src/Aspire.Dashboard/Components/Layout/MainLayout.razor.cs
  src/Aspire.Dashboard/Components/Pages/ConsoleLogs.razor.cs
  src/Aspire.Dashboard/Components/Pages/Metrics.razor.cs
  src/Aspire.Dashboard/Components/Pages/StructuredLogs.razor.cs
  src/Aspire.Dashboard/Components/Pages/Traces.razor.cs
  src/Aspire.Dashboard/Utils/BrowserStorageKeys.cs
  tests/Aspire.Dashboard.Components.Tests/Layout/MainLayoutTests.cs
  tests/Aspire.Dashboard.Components.Tests/Shared/TestDashboardClient.cs
  tests/Aspire.Dashboard.Components.Tests/Shared/TestLocalStorage.cs
Labels: area-dashboard

#5481 Support multiple applicationUrl endpoints for the same scheme
  src/Aspire.Hosting/ProjectResourceBuilderExtensions.cs
  tests/Aspire.Hosting.Tests/ProjectResourceTests.cs
Labels: area-app-model, community-contribution

#5394 WaitFor/WaitForCompletion implementation.
  playground/TestShop/CatalogDb/Program.cs
  playground/TestShop/TestShop.AppHost/Program.cs
  src/Aspire.Dashboard/Components/ResourcesGridColumns/StateColumnDisplay.razor
  src/Aspire.Dashboard/Extensions/ResourceViewModelExtensions.cs
  src/Aspire.Dashboard/Model/KnownResourceState.cs
  src/Aspire.Hosting/ApplicationModel/CustomResourceSnapshot.cs
  src/Aspire.Hosting/ApplicationModel/ResourceNotificationService.cs
  src/Aspire.Hosting/PublicAPI.Unshipped.txt
  src/Aspire.Hosting/ResourceBuilderExtensions.cs
  tests/Aspire.Hosting.Tests/WaitForTests.cs
  tests/Aspire.Playground.Tests/ProjectSpecificTests.cs
Labels: area-app-model

#5354 Persistent container support
  src/Aspire.Hosting/ApplicationModel/ContainerLifetimeAnnotation.cs
  src/Aspire.Hosting/ApplicationModel/ResourceExtensions.cs
  src/Aspire.Hosting/ContainerResourceBuilderExtensions.cs
  src/Aspire.Hosting/Dcp/ApplicationExecutor.cs
  src/Aspire.Hosting/PublicAPI.Unshipped.txt
Labels: area-app-model

#5464 [tests] Increase efcore timeout for cosmos in CosmosEndToEnd
  playground/CosmosEndToEnd/CosmosEndToEnd.ApiService/Program.cs
Labels: area-app-model, testing ☑️

#5491 Support reference expressions and endpoint references in WithParameter
  src/Aspire.Hosting.Azure/AzureBicepResourceExtensions.cs
  src/Aspire.Hosting.Azure/PublicAPI.Unshipped.txt
  tests/Aspire.Hosting.Azure.Tests/AzureBicepProvisionerTests.cs
Labels: area-app-model

#5500 WaitFor PR feedback
  src/Aspire.Hosting/ApplicationModel/CustomResourceSnapshot.cs
  src/Aspire.Hosting/ApplicationModel/ResourceNotificationService.cs
  src/Aspire.Hosting/PublicAPI.Unshipped.txt
Labels: area-meta
