Repository dotnet/aspire, pull requests merged in 2025-08, with the labels that each got.

#10790 External Services with URL Parameter fails to generate manifests
  playground/ExternalServices/ExternalServices.AppHost/aspire-manifest.json
  src/Aspire.Hosting/ResourceBuilderExtensions.cs
  tests/Aspire.Hosting.Tests/ExternalServiceTests.cs
  tests/Aspire.Hosting.Tests/Snapshots/ExternalServiceTests.ExternalServiceWithParameterPublishManifest.verified.json
Labels: area-app-model

#10795 Unquarantine UseOrFindAppHostProjectFilePromptsWhenMultipleFilesFound test.
  tests/Aspire.Cli.Tests/Projects/ProjectLocatorTests.cs
Labels: needs-area-label, area-cli

#10773 Replace `BicepFormatString` with real `FormattableString`
  Directory.Packages.props
  src/Aspire.Hosting.Azure.AppContainers/Aspire.Hosting.Azure.AppContainers.csproj
  src/Aspire.Hosting.Azure.AppContainers/ContainerAppContext.cs
  src/Aspire.Hosting.Azure.AppService/Aspire.Hosting.Azure.AppService.csproj
  src/Aspire.Hosting.Azure.AppService/AzureAppServiceWebsiteContext.cs
  src/Aspire.Hosting.Azure/Aspire.Hosting.Azure.csproj
  src/Aspire.Hosting.Azure/AzurePublishingContext.cs
  src/Shared/BicepFunction2.cs
Labels: area-integrations, community-contribution

#10741 [CI] Build Cli native archives on GH runs
  .github/workflows/tests.yml
Labels: area-cli

#10792 Set up Azure deployer and provisioning context prompting
  src/Aspire.Hosting.Azure/AzureDeployingContext.cs
  src/Aspire.Hosting.Azure/AzureEnvironmentResource.cs
  src/Aspire.Hosting.Azure/Provisioning/Internal/DefaultProvisioningContextProvider.cs
  src/Aspire.Hosting/Publishing/PublishingActivityReporter.cs
  tests/Aspire.Hosting.Azure.Tests/AzureDeployerTests.cs
  tests/Aspire.Hosting.Azure.Tests/DefaultProvisioningContextProviderTests.cs
  tests/Aspire.Hosting.Azure.Tests/ProvisioningTestHelpers.cs
  tests/Aspire.Hosting.Tests/Publishing/PublishingActivityReporterTests.cs
  tests/Aspire.Hosting.Tests/Utils/TestDistributedApplicationBuilder.cs
Labels: area-integrations

#10822 Fixed properties override when publishing an update in external service
  src/Aspire.Hosting/ExternalServiceBuilderExtensions.cs
Labels: needs-area-label, community-contribution

#10842 Fix GH Models lifetime
  src/Aspire.Hosting.GitHub.Models/GitHubModelResource.cs
  tests/Aspire.Hosting.GitHub.Models.Tests/Aspire.Hosting.GitHub.Models.Tests.csproj
  tests/Aspire.Hosting.GitHub.Models.Tests/GitHubModelsFunctionalTests.cs
Labels: area-app-model, breaking-change

#10848 Fix navigating to resources with a selected resource
  src/Aspire.Dashboard/Components/Pages/Resources.razor
  src/Aspire.Dashboard/Components/Pages/Resources.razor.cs
Labels: area-dashboard

#10870 Fix competing resource generation on shared file
  src/Aspire.Hosting.Azure.Functions/Aspire.Hosting.Azure.Functions.csproj
Labels: area-app-model

#10864 Adding Resource to `CommandLineArgsCallbackContext`
  src/Aspire.Hosting.Azure.AppContainers/ContainerAppContext.cs
  src/Aspire.Hosting.Azure.AppService/AzureAppServiceWebsiteContext.cs
  src/Aspire.Hosting.Azure/AzureResourcePreparer.cs
  src/Aspire.Hosting.Docker/DockerComposeEnvironmentContext.cs
  src/Aspire.Hosting.Kubernetes/KubernetesResource.cs
  src/Aspire.Hosting/ApplicationModel/CommandLineArgsCallbackAnnotation.cs
  src/Aspire.Hosting/ApplicationModel/ResourceExtensions.cs
  tests/Aspire.Hosting.Containers.Tests/ContainerResourceTests.cs
  tests/Aspire.Hosting.Tests/ExecutableResourceTests.cs
  tests/Aspire.Hosting.Tests/ProjectResourceTests.cs
Labels: area-app-model

#10730 Bump Package Baseline validation to 9.4.0
  src/Aspire.Hosting.Azure/CompatibilitySuppressions.xml
  src/Aspire.Hosting/CompatibilitySuppressions.xml
  src/Directory.Build.props
Labels: needs-area-label

#10862 Remove page logging
  src/Aspire.Dashboard/Components/Pages/StructuredLogs.razor.cs
Labels: area-dashboard

#10878 Making arg non-nullable on CommandLineArgsCallbackContext
  src/Aspire.Hosting/ApplicationModel/CommandLineArgsCallbackAnnotation.cs
Labels: area-app-model

#10884 Do not match `pipe` as port separator
  src/Aspire.Dashboard/Model/ConnectionStringParser.cs
Labels: needs-area-label, community-contribution

#10891 Bump package versions to 9.4.1 in project files
  eng/Versions.props
  tests/Shared/RepoTesting/Aspire.RepoTesting.targets
  tests/Shared/RepoTesting/Directory.Packages.Helix.props
Labels: area-integrations

#10905 Add localhive.sh script for building NuGet packages and managing Aspire CLI hives
  localhive.sh
Labels: needs-area-label

#10854 upgrade extension npm packages
  extension/yarn.lock
Labels: needs-area-label

#10906 Add LaunchProfile property to project details pane
  src/Aspire.Dashboard/Model/KnownPropertyLookup.cs
  src/Aspire.Dashboard/Resources/Resources.Designer.cs
  src/Aspire.Dashboard/Resources/Resources.resx
  src/Aspire.Dashboard/Resources/xlf/Resources.cs.xlf
  src/Aspire.Dashboard/Resources/xlf/Resources.de.xlf
  src/Aspire.Dashboard/Resources/xlf/Resources.es.xlf
  src/Aspire.Dashboard/Resources/xlf/Resources.fr.xlf
  src/Aspire.Dashboard/Resources/xlf/Resources.it.xlf
  src/Aspire.Dashboard/Resources/xlf/Resources.ja.xlf
  src/Aspire.Dashboard/Resources/xlf/Resources.ko.xlf
  src/Aspire.Dashboard/Resources/xlf/Resources.pl.xlf
  src/Aspire.Dashboard/Resources/xlf/Resources.pt-BR.xlf
  src/Aspire.Dashboard/Resources/xlf/Resources.ru.xlf
  src/Aspire.Dashboard/Resources/xlf/Resources.tr.xlf
  src/Aspire.Dashboard/Resources/xlf/Resources.zh-Hans.xlf
  src/Aspire.Dashboard/Resources/xlf/Resources.zh-Hant.xlf
  src/Aspire.Hosting/Dcp/ResourceSnapshotBuilder.cs
  src/Shared/Model/KnownProperties.cs
Labels: area-dashboard

#10865 Update appmodel.md
  docs/specs/appmodel.md
Labels: area-app-model

#10898 Add IResourceWithEndpoints interface to Azure resource classes
  src/Aspire.Hosting.Azure.AIFoundry/AzureAIFoundryResource.cs
  src/Aspire.Hosting.Azure.KeyVault/AzureKeyVaultResource.cs
  src/Aspire.Hosting.Azure.PostgreSQL/AzurePostgresFlexibleServerResource.cs
  src/Aspire.Hosting.Azure.Redis/AzureRedisCacheResource.cs
Labels: area-integrations

#10938 Fix CognitiveService integration compatibility with Aspire.Azure.AI.Inference
  src/Components/Aspire.Azure.AI.Inference/README.md
Labels: area-integrations

#10869 Improve resources action menu
  src/Aspire.Dashboard/Components/Controls/AspireMenu.razor
  src/Aspire.Dashboard/Model/MenuButtonItem.cs
  src/Aspire.Dashboard/Model/ResourceMenuItems.cs
  src/Aspire.Dashboard/Model/ResourceViewModel.cs
  src/Aspire.Dashboard/Resources/Resources.Designer.cs
  src/Aspire.Dashboard/Resources/Resources.resx
  src/Aspire.Dashboard/Resources/xlf/Resources.cs.xlf
  src/Aspire.Dashboard/Resources/xlf/Resources.de.xlf
  src/Aspire.Dashboard/Resources/xlf/Resources.es.xlf
  src/Aspire.Dashboard/Resources/xlf/Resources.fr.xlf
  src/Aspire.Dashboard/Resources/xlf/Resources.it.xlf
  src/Aspire.Dashboard/Resources/xlf/Resources.ja.xlf
  src/Aspire.Dashboard/Resources/xlf/Resources.ko.xlf
  src/Aspire.Dashboard/Resources/xlf/Resources.pl.xlf
  src/Aspire.Dashboard/Resources/xlf/Resources.pt-BR.xlf
  src/Aspire.Dashboard/Resources/xlf/Resources.ru.xlf
  src/Aspire.Dashboard/Resources/xlf/Resources.tr.xlf
  src/Aspire.Dashboard/Resources/xlf/Resources.zh-Hans.xlf
  src/Aspire.Dashboard/Resources/xlf/Resources.zh-Hant.xlf
Labels: area-dashboard

#10950 Update copilot-instructions.md
  .github/copilot-instructions.md
Labels: area-integrations

#10945 Make grid value component more reusable
  src/Aspire.Dashboard/Components/Controls/PropertyValues/IconValue.razor
  src/Aspire.Dashboard/Components/Controls/PropertyValues/IconValue.razor.cs
  src/Aspire.Dashboard/Components/Controls/SpanDetails.razor.cs
Labels: area-dashboard

#10845 Hook up Azure Deployer to BicepProvisioner
  Aspire.slnx
  playground/deployers/Deployers.AppHost/AppHost.cs
  playground/deployers/Deployers.AppHost/Deployers.AppHost.csproj
  playground/deployers/Deployers.AppHost/Properties/launchSettings.json
  playground/deployers/Deployers.AppHost/appsettings.Development.json
  playground/deployers/Deployers.AppHost/appsettings.json
  src/Aspire.Hosting.Azure/AzureBicepResource.cs
  src/Aspire.Hosting.Azure/AzureDeployingContext.cs
  src/Aspire.Hosting.Azure/AzureEnvironmentResource.cs
  src/Aspire.Hosting.Azure/AzurePublishingContext.cs
  src/Aspire.Hosting.Azure/Provisioning/AzureProvisionerExtensions.cs
  src/Aspire.Hosting.Azure/Provisioning/Internal/DefaultArmDeploymentCollection.cs
  src/Aspire.Hosting.Azure/Provisioning/Internal/DefaultProvisioningContextProvider.cs
  src/Aspire.Hosting.Azure/Provisioning/Internal/DefaultResourceGroupResource.cs
  src/Aspire.Hosting.Azure/Provisioning/Internal/DefaultSubscriptionResource.cs
  src/Aspire.Hosting.Azure/Provisioning/Internal/IProvisioningServices.cs
  src/Aspire.Hosting.Azure/Provisioning/Provisioners/AzureProvisioner.cs
  src/Aspire.Hosting.Azure/Provisioning/Provisioners/BicepProvisioner.cs
  src/Aspire.Hosting.Azure/Provisioning/Provisioners/IBicepProvisioner.cs
  src/Aspire.Hosting.Azure/Provisioning/ProvisioningContext.cs
  tests/Aspire.Hosting.Azure.Tests/AzureDeployerTests.cs
  tests/Aspire.Hosting.Azure.Tests/DefaultProvisioningContextProviderTests.cs
  tests/Aspire.Hosting.Azure.Tests/ProvisioningTestHelpers.cs
  tests/Aspire.Hosting.Azure.Tests/Snapshots/AzureEnvironmentResourceTests.AzurePublishingContext_IgnoresAzureBicepResourcesWithIgnoreAnnotation.verified.bicep
Labels: azure, area-deployment

#10956 Fix version checking with mixed state
  src/Aspire.Hosting/DistributedApplicationBuilder.cs
  src/Aspire.Hosting/VersionChecking/IPackageVersionProvider.cs
  src/Aspire.Hosting/VersionChecking/PackageVersionProvider.cs
  src/Aspire.Hosting/VersionChecking/VersionCheckService.cs
  src/Shared/PackageUpdateHelpers.cs
  tests/Aspire.Hosting.Tests/VersionChecking/VersionCheckServiceTests.cs
Labels: area-app-model

#10928 Update Azure.AI.OpenAI
  Directory.Packages.props
  eng/Version.Details.xml
  eng/Versions.props
Labels: area-integrations

#10978 Quarantine: BrowserToken_LoginPage_Success_RedirectToResources
  tests/Aspire.Dashboard.Tests/Integration/Playwright/BrowserTokenAuthenticationTests.cs
Labels: area-dashboard

#10984 Contribution guidelines: use local copy of dotnet CLI
  docs/contributing.md
Labels: needs-area-label

#10954 serve blazor.web.js from wwwroot instead of setting up new endpoint to serve it
  Directory.Packages.props
  eng/Versions.props
  src/Aspire.Dashboard/Aspire.Dashboard.csproj
  src/Aspire.Dashboard/Components/App.razor
  src/Aspire.Dashboard/DashboardEndpointsBuilder.cs
  src/Aspire.Dashboard/DashboardWebApplication.cs
  src/Aspire.Dashboard/Embedded/blazor.web.js
  src/Aspire.Dashboard/wwwroot/framework/blazor.web.js
Labels: area-dashboard

#10971 Unsubscribe once with multiple dispose calls
  src/Aspire.Dashboard/Otlp/Storage/Subscription.cs
  src/Aspire.Dashboard/Utils/CallbackThrottler.cs
  tests/Aspire.Dashboard.Tests/TelemetryRepositoryTests/TelemetryRepositoryTests.cs
Labels: area-dashboard

#10972 Bump azurite to latest release for azure storage emulator
  src/Aspire.Hosting.Azure.Storage/StorageEmulatorContainerImageTags.cs
Labels: needs-area-label, community-contribution

#10990 [release/9.4] serve blazor.web.js from wwwroot
  Directory.Packages.props
  eng/Versions.props
  src/Aspire.Dashboard/Aspire.Dashboard.csproj
  src/Aspire.Dashboard/Components/App.razor
  src/Aspire.Dashboard/DashboardEndpointsBuilder.cs
  src/Aspire.Dashboard/DashboardWebApplication.cs
  src/Aspire.Dashboard/Embedded/blazor.web.js
  src/Aspire.Dashboard/wwwroot/framework/blazor.web.js
Labels: area-dashboard

#11003 fix for wrong OpenAIClientOptions used with keyed OpenAIClient(s)
  src/Components/Aspire.OpenAI/AspireOpenAIExtensions.cs
  tests/Aspire.OpenAI.Tests/AspireOpenAIExtensionsTests.cs
Labels: area-integrations, community-contribution

#10986 Generate classes methods for model catalog in Azure AI Foundry integration
  src/Aspire.Hosting.Azure.AIFoundry/AIFoundryModel.Generated.cs
  src/Aspire.Hosting.Azure.AIFoundry/AIFoundryModel.cs
  src/Aspire.Hosting.Azure.AIFoundry/Aspire.Hosting.Azure.AIFoundry.csproj
  src/Aspire.Hosting.Azure.AIFoundry/AzureAIFoundryExtensions.cs
  src/Aspire.Hosting.Azure.AIFoundry/tools/Directory.Build.props
  src/Aspire.Hosting.Azure.AIFoundry/tools/Directory.Build.targets
  src/Aspire.Hosting.Azure.AIFoundry/tools/GenModel.cs
Labels: area-integrations

#10796 Add emulator support for azure app configuration
  Aspire.slnx
  Directory.Packages.props
  playground/AzureAppConfiguration/AzureAppConfiguration.AppHost/.aace/appconfig/kv.ndjson
  playground/AzureAppConfiguration/AzureAppConfiguration.AppHost/AppHost.cs
  playground/AzureAppConfiguration/AzureAppConfiguration.AppHost/AzureAppConfiguration.AppHost.csproj
  playground/AzureAppConfiguration/AzureAppConfiguration.AppHost/Properties/launchSettings.json
  playground/AzureAppConfiguration/AzureAppConfiguration.AppHost/appsettings.Development.json
  playground/AzureAppConfiguration/AzureAppConfiguration.AppHost/appsettings.json
  playground/AzureAppConfiguration/AzureAppConfiguration.Web/AzureAppConfiguration.Web.csproj
  playground/AzureAppConfiguration/AzureAppConfiguration.Web/AzureAppConfiguration.Web.http
  playground/AzureAppConfiguration/AzureAppConfiguration.Web/Program.cs
  playground/AzureAppConfiguration/AzureAppConfiguration.Web/Properties/launchSettings.json
  playground/AzureAppConfiguration/AzureAppConfiguration.Web/appsettings.Development.json
  playground/AzureAppConfiguration/AzureAppConfiguration.Web/appsettings.json
  src/Aspire.Hosting.Azure.AppConfiguration/AppConfigurationEmulatorContainerImageTags.cs
  src/Aspire.Hosting.Azure.AppConfiguration/AzureAppConfigurationEmulatorConnectionString.cs
  src/Aspire.Hosting.Azure.AppConfiguration/AzureAppConfigurationEmulatorOptions.cs
  src/Aspire.Hosting.Azure.AppConfiguration/AzureAppConfigurationEmulatorResource.cs
  src/Aspire.Hosting.Azure.AppConfiguration/AzureAppConfigurationExtensions.cs
  src/Aspire.Hosting.Azure.AppConfiguration/AzureAppConfigurationResource.cs
  src/Components/Aspire.Microsoft.Extensions.Configuration.AzureAppConfiguration/Aspire.Microsoft.Extensions.Configuration.AzureAppConfiguration.csproj
  src/Components/Aspire.Microsoft.Extensions.Configuration.AzureAppConfiguration/AspireAppConfigurationExtensions.cs
  src/Components/Aspire.Microsoft.Extensions.Configuration.AzureAppConfiguration/AzureAppConfigurationSettings.cs
  src/Components/Aspire.Microsoft.Extensions.Configuration.AzureAppConfiguration/ConfigurationSchema.json
  tests/Aspire.Microsoft.Extensions.Configuration.AzureAppConfiguration.Tests/AspireAppConfigurationExtensionsTest.cs
Labels: area-integrations, community-contribution

#10388 Updated Dashboard to accept/map forwarded headers
  src/Aspire.Dashboard/DashboardWebApplication.cs
  src/Shared/DashboardConfigNames.cs
  src/Shared/KnownConfigNames.cs
  tests/Aspire.Dashboard.Tests/Integration/StartupTests.cs
Labels: area-dashboard, community-contribution

#10934 Fix Azure AI Foundry resource name
  playground/AzureAIFoundryEndToEnd/AzureAIFoundryEndToEnd.AppHost/aspire-manifest.json
  playground/AzureAIFoundryEndToEnd/AzureAIFoundryEndToEnd.AppHost/foundry.module.bicep
  src/Aspire.Hosting.Azure.AIFoundry/AzureAIFoundryDeploymentResource.cs
  src/Aspire.Hosting.Azure.AIFoundry/AzureAIFoundryResource.cs
  tests/Aspire.Hosting.Azure.Tests/AzureAIFoundryExtensionsTests.cs
  tests/Aspire.Hosting.Azure.Tests/Snapshots/AzureAIFoundryExtensionsTests.AddAzureAIFoundry_GeneratesValidBicep#00.verified.bicep
Labels: area-integrations

#11058 [CI] Bump timeout for Hosting tests on linux to 25m
  .github/workflows/tests.yml
Labels: area-engineering-systems, testing ☑️

#11063 Revert deployment connection string changes
  playground/AzureAIFoundryEndToEnd/AzureAIFoundryEndToEnd.AppHost/aspire-manifest.json
  src/Aspire.Hosting.Azure.AIFoundry/AzureAIFoundryDeploymentResource.cs
  src/Aspire.Hosting.Azure.AIFoundry/AzureAIFoundryResource.cs
  tests/Aspire.Hosting.Azure.Tests/AzureAIFoundryExtensionsTests.cs
Labels: area-integrations

#11082 Details padding consistency
  src/Aspire.Dashboard/Components/Controls/SummaryDetailsView.razor.css
  src/Aspire.Dashboard/wwwroot/css/app.css
Labels: area-dashboard

#11078 Improve displaying durations
  src/Aspire.Dashboard/Components/Controls/SpanDetails.razor
  src/Aspire.Dashboard/Otlp/Model/DurationFormatter.cs
  tests/Aspire.Dashboard.Tests/DurationFormatterTests.cs
Labels: area-dashboard

#11087 Tweak displaying (All) console logs content
  src/Aspire.Dashboard/Components/Controls/LogViewer.razor
  src/Aspire.Dashboard/Components/Controls/LogViewer.razor.cs
  src/Aspire.Dashboard/Components/Controls/LogViewer.razor.css
Labels: area-dashboard

#11097 Update CODEOWNERS to include @captainsafia
  .github/CODEOWNERS
Labels: area-codeflow

#10470 Build ServiceDiscovery library and tests against netstandard2.0
  Directory.Packages.props
  eng/Version.Details.xml
  eng/Versions.props
  src/Microsoft.Extensions.ServiceDiscovery.Abstractions/Microsoft.Extensions.ServiceDiscovery.Abstractions.csproj
  src/Microsoft.Extensions.ServiceDiscovery/Microsoft.Extensions.ServiceDiscovery.csproj
  src/Microsoft.Extensions.ServiceDiscovery/ServiceDiscoveryHttpClientBuilderExtensions.cs
  src/Shared/FxPolyfills/ArgumentException.cs
  src/Shared/FxPolyfills/ArgumentNullException.cs
  src/Shared/FxPolyfills/CallerArgumentExpressionAttribute.cs
  src/Shared/FxPolyfills/ConcurrentDictionary.cs
  src/Shared/FxPolyfills/ExceptionDispatchInfo.cs
  src/Shared/FxPolyfills/FxPolyfills.targets
  src/Shared/FxPolyfills/IPEndPoint.cs
  src/Shared/FxPolyfills/Interlocked.cs
  src/Shared/FxPolyfills/IsExternalInit.cs
  src/Shared/FxPolyfills/KeyValuePair.cs
  src/Shared/FxPolyfills/ObjectDisposedException.cs
  src/Shared/FxPolyfills/OperatingSystem.cs
  src/Shared/FxPolyfills/String.cs
  src/Shared/FxPolyfills/Task.TimeProvider.cs
  src/Shared/FxPolyfills/Task.cs
  tests/Aspire.TestUtilities/Aspire.TestUtilities.csproj
  tests/Microsoft.Extensions.ServiceDiscovery.Tests/Microsoft.Extensions.ServiceDiscovery.Tests.csproj
  tests/Microsoft.Extensions.ServiceDiscovery.Tests/ServiceEndpointResolverTests.cs
  tests/Shared/TemplatesTesting/Aspire.Shared.TemplatesTesting.targets
Labels: area-service-discovery

#11101 Add strongly typed github models classes to make them more discoverable
  .github/workflows/update-ai-foundry-models copy.yml
  .github/workflows/update-github-models.yml
  playground/GitHubModelsEndToEnd/GitHubModelsEndToEnd.AppHost/Program.cs
  src/Aspire.Hosting.GitHub.Models/Aspire.Hosting.GitHub.Models.csproj
  src/Aspire.Hosting.GitHub.Models/GitHubModel.Generated.cs
  src/Aspire.Hosting.GitHub.Models/GitHubModelsExtensions.cs
  src/Aspire.Hosting.GitHub.Models/GithubModel.cs
  src/Aspire.Hosting.GitHub.Models/tools/Directory.Build.props
  src/Aspire.Hosting.GitHub.Models/tools/Directory.Build.targets
  src/Aspire.Hosting.GitHub.Models/tools/GenModel.cs
Labels: area-app-model

#11117 Verify Functions deployment via aspire deploy
  playground/AzureFunctionsEndToEnd/AzureFunctionsEndToEnd.ApiService/Program.cs
  playground/AzureFunctionsEndToEnd/AzureFunctionsEndToEnd.Functions/MyAzureBlobTrigger.cs
  playground/deployers/Deployers.AppHost/AppHost.cs
  playground/deployers/Deployers.AppHost/Deployers.AppHost.csproj
  tests/Aspire.Hosting.Azure.Tests/AzureDeployerTests.cs
Labels: area-integrations

#11147 [CI] Fix signing with Arcade
  .github/workflows/ci.yml
  eng/Signing.props
  eng/pipelines/templates/build_sign_native.yml
Labels: area-engineering-systems

#11164 Make copying project templates incremental
  src/Aspire.ProjectTemplates/Aspire.ProjectTemplates.csproj
Labels: area-templates

#11179 Add suppressions for test credentials in CredScan
  .config/CredScanSuppressions.json
Labels: area-integrations

#11186 Fix localhive pack syntax
  localhive.ps1
Labels: needs-area-label
