Repository dotnet/aspire, pull requests merged in 2025-03, with the labels that each got.

#7681 Update to FluentUI 4.11.5
  Directory.Packages.props
  tests/Aspire.Dashboard.Components.Tests/Pages/ConsoleLogsTests.cs
  tests/Aspire.Dashboard.Components.Tests/Pages/StructuredLogsTests.cs
  tests/Aspire.Dashboard.Components.Tests/Pages/TraceDetailsTests.cs
  tests/Aspire.Dashboard.Components.Tests/Shared/MetricsSetupHelpers.cs
  tests/Aspire.Dashboard.Components.Tests/Shared/ResourceSetupHelpers.cs
  tests/Aspire.Dashboard.Components.Tests/Shared/StructuredLogsSetupHelpers.cs
Labels: area-dashboard

#7844 Improve flaky test logging
  src/Aspire.Hosting/Dcp/DcpExecutor.cs
  tests/Aspire.Hosting.Tests/DistributedApplicationTests.cs
Labels: area-app-model

#7841 Fix components test and remove added padding/margin on tabs
  src/Aspire.Dashboard/Components/Controls/Chart/ChartContainer.razor
  src/Aspire.Dashboard/Components/Pages/Resources.razor
  tests/Aspire.Dashboard.Components.Tests/Pages/ConsoleLogsTests.cs
Labels: area-dashboard

#7861 Make AppHost shutdown if orphaned by aspire CLI.
  src/Aspire.Cli/AppHostRunner.cs
  src/Aspire.Cli/Properties/launchSettings.json
  src/Aspire.Hosting/Aspire.Hosting.csproj
  src/Aspire.Hosting/Cli/CliOrphanDetector.cs
  src/Aspire.Hosting/DistributedApplicationBuilder.cs
  tests/Aspire.Cli.Tests/Aspire.Cli.Tests.csproj
  tests/Aspire.Cli.Tests/CliSmokeTests.cs
  tests/Aspire.Cli.Tests/Helpers/StubProcess.cs
  tests/Aspire.Cli.Tests/Hosting/CliOrphanDetectorTests.cs
Labels: area-cli

#7830 Use Kafbat/kafkaui
  src/Aspire.Hosting.Kafka/KafkaContainerImageTags.cs
Labels: community-contribution

#6032 Add tests for Seq
  .github/workflows/tests.yml
  Aspire.sln
  src/Aspire.Hosting.Seq/SeqBuilderExtensions.cs
  tests/Aspire.Hosting.Seq.Tests/AddSeqTests.cs
  tests/Aspire.Hosting.Seq.Tests/Aspire.Hosting.Seq.Tests.csproj
  tests/Aspire.Hosting.Seq.Tests/SeqFunctionalTests.cs
  tests/Aspire.Hosting.Seq.Tests/SeqPublicApiTests.cs
Labels: community-contribution

#7874 `aspire pack [project] --target [publisher] --output-path [manifest filename]`
  src/Aspire.Cli/AppHostRunner.cs
  src/Aspire.Cli/Aspire.Cli.csproj
  src/Aspire.Cli/Program.cs
  src/Aspire.Cli/Properties/launchSettings.json
  src/Aspire.Hosting/Cli/CliOrphanDetector.cs
Labels: area-cli

#7618 Add Password for Garnet
  playground/Redis/Redis.AppHost/aspire-manifest.json
  src/Aspire.Hosting.Garnet/GarnetBuilderExtensions.cs
  src/Aspire.Hosting.Garnet/GarnetResource.cs
  tests/Aspire.Hosting.Garnet.Tests/AddGarnetTests.cs
Labels: area-integrations, community-contribution, security 🔐

#7893 [issues/7885] Fix test ProjectA
  tests/Aspire.Hosting.Azure.Tests/PublicApiTests/AppContainersPublicApiTests.cs
Labels: community-contribution

#7895 Add --project option with automatic apphost detection
  src/Aspire.Cli/Aspire.Cli.csproj
  src/Aspire.Cli/Program.cs
  src/Aspire.Cli/Properties/launchSettings.json
Labels: area-cli

#7887 Add password for Valkey
  playground/Redis/Redis.AppHost/aspire-manifest.json
  src/Aspire.Hosting.Valkey/ValkeyBuilderExtensions.cs
  src/Aspire.Hosting.Valkey/ValkeyResource.cs
  tests/Aspire.Hosting.Valkey.Tests/AddValkeyTests.cs
Labels: community-contribution

#7899 `aspire new` bootstrap
  src/Aspire.Cli/AppHostRunner.cs
  src/Aspire.Cli/DotNetCliRunner.cs
  src/Aspire.Cli/ExitCodeConstants.cs
  src/Aspire.Cli/Program.cs
Labels: area-cli

#7906 Add is_inactive to Url, return Urls for non-running resources
  src/Aspire.Dashboard/Model/ResourceEndpointHelpers.cs
  src/Aspire.Dashboard/Model/ResourceViewModel.cs
  src/Aspire.Dashboard/ResourceService/Partials.cs
  src/Aspire.Hosting/ApplicationModel/CustomResourceSnapshot.cs
  src/Aspire.Hosting/Dashboard/proto/Partials.cs
  src/Aspire.Hosting/Dashboard/proto/resource_service.proto
  src/Aspire.Hosting/Dcp/DcpExecutor.cs
  src/Aspire.Hosting/Dcp/DcpResourceState.cs
  src/Aspire.Hosting/Dcp/ResourceSnapshotBuilder.cs
  tests/Aspire.Dashboard.Tests/Model/ResourceEndpointHelpersTests.cs
  tests/Aspire.Dashboard.Tests/ResourceOutgoingPeerResolverTests.cs
Labels: area-app-model

#7916 Publish snapshot using DCP data before resource started in DCP
  src/Aspire.Hosting/Dcp/DcpExecutor.cs
  tests/Aspire.Hosting.Tests/DistributedApplicationTests.cs
Labels: area-app-model

#7928 Resource graph UI fixes
  src/Aspire.Dashboard/Components/Pages/Resources.razor.cs
  src/Aspire.Dashboard/Components/Pages/Resources.razor.css
Labels: area-dashboard

#7919 Bootstrap more publishers
  Aspire.sln
  playground/publishers/Publishers.ApiService/Program.cs
  playground/publishers/Publishers.ApiService/Properties/launchSettings.json
  playground/publishers/Publishers.ApiService/Publishers.ApiService.csproj
  playground/publishers/Publishers.ApiService/Publishers.ApiService.http
  playground/publishers/Publishers.ApiService/appsettings.Development.json
  playground/publishers/Publishers.ApiService/appsettings.json
  playground/publishers/Publishers.AppHost/Program.cs
  playground/publishers/Publishers.AppHost/Properties/launchSettings.json
  playground/publishers/Publishers.AppHost/Publishers.AppHost.csproj
  playground/publishers/Publishers.AppHost/appsettings.Development.json
  playground/publishers/Publishers.AppHost/appsettings.json
  playground/publishers/Publishers.AppHost/aspire-manifest.json
  playground/publishers/Publishers.AppHost/pg.module.bicep
  playground/publishers/Publishers.Common/Entry.cs
  playground/publishers/Publishers.Common/MyDbContext.cs
  playground/publishers/Publishers.Common/Publishers.Common.csproj
  playground/publishers/Publishers.DbSetup/Program.cs
  playground/publishers/Publishers.DbSetup/Properties/launchSettings.json
  playground/publishers/Publishers.DbSetup/Publishers.DbSetup.csproj
  playground/publishers/Publishers.Frontend/Components/App.razor
  playground/publishers/Publishers.Frontend/Components/Layout/MainLayout.razor
  playground/publishers/Publishers.Frontend/Components/Layout/MainLayout.razor.css
  playground/publishers/Publishers.Frontend/Components/Pages/Error.razor
  playground/publishers/Publishers.Frontend/Components/Pages/Home.razor
  playground/publishers/Publishers.Frontend/Components/Routes.razor
  playground/publishers/Publishers.Frontend/Components/_Imports.razor
  playground/publishers/Publishers.Frontend/Program.cs
  playground/publishers/Publishers.Frontend/Properties/launchSettings.json
  playground/publishers/Publishers.Frontend/Publishers.Frontend.csproj
  playground/publishers/Publishers.Frontend/appsettings.Development.json
  playground/publishers/Publishers.Frontend/appsettings.json
  playground/publishers/Publishers.Frontend/wwwroot/app.css
  src/Aspire.Cli/Program.cs
  src/Aspire.Hosting.Azure/AzureContainerAppPublisher.cs
  src/Aspire.Hosting.Docker/Aspire.Hosting.Docker.csproj
  src/Aspire.Hosting.Docker/DockerComposePublisher.cs
  src/Aspire.Hosting.Docker/README.md
  src/Aspire.Hosting.Kubernetes/Aspire.Hosting.Kubernetes.csproj
  src/Aspire.Hosting.Kubernetes/KubernetesPublisher.cs
  src/Aspire.Hosting.Kubernetes/README.md
  src/Aspire.Hosting/DistributedApplicationBuilder.cs
  src/Aspire.Hosting/DistributedApplicationExecutionContext.cs
  src/Aspire.Hosting/DistributedApplicationExecutionContextOptions.cs
  src/Aspire.Hosting/DistributedApplicationRunner.cs
  src/Aspire.Hosting/PublisherDistributedApplicationBuilderExtensions.cs
Labels: area-app-model, area-cli

#7947 Publisher options pattern
  playground/publishers/Publishers.AppHost/Program.cs
  playground/publishers/Publishers.AppHost/Properties/launchSettings.json
  src/Aspire.Hosting.Azure/AzureContainerAppPublisher.cs
  src/Aspire.Hosting.Azure/AzureContainerAppsPublisherExtensions.cs
  src/Aspire.Hosting.Azure/AzureContainerAppsPublisherOptions.cs
  src/Aspire.Hosting.Docker/DockerComposePublisher.cs
  src/Aspire.Hosting.Docker/DockerComposePublisherExtensions.cs
  src/Aspire.Hosting.Docker/DockerComposePublisherOptions.cs
  src/Aspire.Hosting.Kubernetes/KubernetesPublisher.cs
  src/Aspire.Hosting.Kubernetes/KubernetesPublisherExtensions.cs
  src/Aspire.Hosting.Kubernetes/KubernetesPublisherOptions.cs
  src/Aspire.Hosting/DistributedApplicationBuilder.cs
  src/Aspire.Hosting/DistributedApplicationExecutionContext.cs
  src/Aspire.Hosting/PublisherDistributedApplicationBuilderExtensions.cs
Labels: area-app-model, area-deployment, area-cli

#7967 Hoist StopApplication out of ManifestPublisher.
  src/Aspire.Hosting/DistributedApplicationRunner.cs
  src/Aspire.Hosting/Publishing/ManifestPublisher.cs
  tests/Aspire.Hosting.Tests/Helpers/JsonDocumentManifestPublisher.cs
Labels: area-app-model

#7968 Fix triple slash docs in MongoDBBuilderExtensions
  src/Aspire.Hosting.MongoDB/MongoDBBuilderExtensions.cs
Labels: needs-area-label, community-contribution

#7980 Don't trigger codeql pipeline for preview/rc branches
  eng/pipelines/azure-pipelines-codeql.yml
Labels: area-engineering-systems

#7983 Add policy to close & re-open github-action PRs
  .github/policies/eventResponderTask.GithubActionPROpened.yml
Labels: area-engineering-systems

#6636 API for role assignments
  playground/AspireEventHub/EventHubs.AppHost/ehstorage.module.bicep
  playground/AzureContainerApps/AzureContainerApps.AppHost/Program.cs
  playground/AzureContainerApps/AzureContainerApps.AppHost/api-roles.module.bicep
  playground/AzureContainerApps/AzureContainerApps.AppHost/api.module.bicep
  playground/AzureContainerApps/AzureContainerApps.AppHost/aspire-manifest.json
  playground/AzureContainerApps/AzureContainerApps.AppHost/cache.module.bicep
  playground/AzureContainerApps/AzureContainerApps.AppHost/pythonapp.module.bicep
  playground/AzureContainerApps/AzureContainerApps.AppHost/storage.module.bicep
  playground/AzureFunctionsEndToEnd/AzureFunctionsEndToEnd.AppHost/funcstorage67c6c.module.bicep
  playground/AzureFunctionsEndToEnd/AzureFunctionsEndToEnd.AppHost/storage.module.bicep
  playground/AzureStorageEndToEnd/AzureStorageEndToEnd.AppHost/storage.module.bicep
  playground/bicep/BicepSample.AppHost/storage.module.bicep
  playground/cdk/CdkSample.AppHost/storage.module.bicep
  playground/orleans/Orleans.AppHost/storage.module.bicep
  src/Aspire.Hosting.Azure.AppContainers/AzureContainerAppExtensions.cs
  src/Aspire.Hosting.Azure.AppContainers/AzureContainerAppsInfrastructure.cs
  src/Aspire.Hosting.Azure.Storage/AzureStorageExtensions.cs
  src/Aspire.Hosting.Azure.Storage/AzureStorageResource.cs
  src/Aspire.Hosting.Azure/AppliedRoleAssignmentsAnnotation.cs
  src/Aspire.Hosting.Azure/AzureProvisioningOptions.cs
  src/Aspire.Hosting.Azure/AzureProvisioningResource.cs
  src/Aspire.Hosting.Azure/AzureProvisioningResourceExtensions.cs
  src/Aspire.Hosting.Azure/AzureResourcePreparer.cs
  src/Aspire.Hosting.Azure/DefaultRoleAssignmentsAnnotation.cs
  src/Aspire.Hosting.Azure/Provisioning/AzureProvisionerExtensions.cs
  src/Aspire.Hosting.Azure/Provisioning/Provisioners/AzureProvisioner.cs
  src/Aspire.Hosting.Azure/RoleAssignmentAnnotation.cs
  src/Aspire.Hosting.Azure/RoleDefinition.cs
  src/Aspire.Hosting/ApplicationModel/DistributedApplicationModel.cs
  src/Aspire.Hosting/ApplicationModel/ResourceCollection.cs
  tests/Aspire.Hosting.Azure.Tests/AzureBicepResourceTests.cs
  tests/Aspire.Hosting.Azure.Tests/AzureContainerAppsTests.cs
  tests/Aspire.Hosting.Azure.Tests/AzureEventHubsExtensionsTests.cs
  tests/Aspire.Hosting.Azure.Tests/AzureManifestUtils.cs
  tests/Aspire.Hosting.Azure.Tests/AzurePostgresExtensionsTests.cs
  tests/Aspire.Hosting.Azure.Tests/AzureProvisioningResourceExtensionsTests.cs
  tests/Aspire.Hosting.Azure.Tests/AzureRedisExtensionsTests.cs
  tests/Aspire.Hosting.Azure.Tests/AzureResourcePreparerTests.cs
  tests/Aspire.Hosting.Azure.Tests/AzureServiceBusExtensionsTests.cs
  tests/Aspire.Hosting.Azure.Tests/AzureSignalRExtensionsTests.cs
  tests/Aspire.Hosting.Azure.Tests/AzureSqlExtensionsTests.cs
  tests/Aspire.Hosting.Azure.Tests/AzureWebPubSubExtensionsTests.cs
  tests/Aspire.Hosting.Azure.Tests/ExistingAzureResourceTests.cs
  tests/Aspire.Hosting.Tests/Utils/ManifestUtils.cs
Labels: area-app-model

#7960 Resources view: Updated icon and tooltip for View options
  src/Aspire.Dashboard/Components/Pages/ConsoleLogs.razor
  src/Aspire.Dashboard/Components/Pages/Resources.razor
  src/Aspire.Dashboard/Resources/Resources.Designer.cs
  src/Aspire.Dashboard/Resources/Resources.resx
  src/Aspire.Dashboard/Resources/xlf/Resources.cs.xlf
  src/Aspire.Dashboard/Resources/xlf/Resources.de.xlf
  src/Aspire.Dashboard/Resources/xlf/Resources.es.xlf
  src/Aspire.Dashboard/Resources/xlf/Resources.fr.xlf
  src/Aspire.Dashboard/Resources/xlf/Resources.it.xlf
  src/Aspire.Dashboard/Resources/xlf/Resources.ja.xlf
  src/Aspire.Dashboard/Resources/xlf/Resources.ko.xlf
  src/Aspire.Dashboard/Resources/xlf/Resources.pl.xlf
  src/Aspire.Dashboard/Resources/xlf/Resources.pt-BR.xlf
  src/Aspire.Dashboard/Resources/xlf/Resources.ru.xlf
  src/Aspire.Dashboard/Resources/xlf/Resources.tr.xlf
  src/Aspire.Dashboard/Resources/xlf/Resources.zh-Hans.xlf
  src/Aspire.Dashboard/Resources/xlf/Resources.zh-Hant.xlf
Labels: area-dashboard

#7991 Backchannel between CLI and AppHost
  .editorconfig
  Directory.Packages.props
  playground/waitfor/WaitForSandbox.AppHost/appsettings.json
  src/Aspire.Cli/Aspire.Cli.csproj
  src/Aspire.Cli/CliRpcTarget.cs
  src/Aspire.Cli/DotNetCliRunner.cs
  src/Aspire.Cli/Program.cs
  src/Aspire.Hosting/Aspire.Hosting.csproj
  src/Aspire.Hosting/Cli/AppHostRpcTarget.cs
  src/Aspire.Hosting/Cli/CliBackchannel.cs
  src/Aspire.Hosting/DistributedApplicationBuilder.cs
  tests/Aspire.Cli.Tests/Aspire.Cli.Tests.csproj
  tests/Aspire.Cli.Tests/Hosting/CliBackchannelTests.cs
Labels: area-cli

#7999 Revert "Backchannel between CLI and AppHost (#7991)"
  .editorconfig
  Directory.Packages.props
  playground/waitfor/WaitForSandbox.AppHost/appsettings.json
  src/Aspire.Cli/Aspire.Cli.csproj
  src/Aspire.Cli/CliRpcTarget.cs
  src/Aspire.Cli/DotNetCliRunner.cs
  src/Aspire.Cli/Program.cs
  src/Aspire.Hosting/Aspire.Hosting.csproj
  src/Aspire.Hosting/Cli/AppHostRpcTarget.cs
  src/Aspire.Hosting/Cli/CliBackchannel.cs
  src/Aspire.Hosting/DistributedApplicationBuilder.cs
  tests/Aspire.Cli.Tests/Aspire.Cli.Tests.csproj
  tests/Aspire.Cli.Tests/Hosting/CliBackchannelTests.cs
Labels: needs-area-label

#7962 Add WithHttpCommand
  playground/Stress/Stress.AppHost/ResourceBuilderExtensions.cs
  playground/TestShop/CatalogDb/CatalogDbInitializer.cs
  playground/TestShop/CatalogDb/Program.cs
  playground/TestShop/CatalogDb/ResetDbExtensions.cs
  playground/TestShop/TestShop.AppHost/Program.cs
  src/Aspire.Hosting/ApplicationModel/HttpCommandContext.cs
  src/Aspire.Hosting/ApplicationModel/ResourceCommandAnnotation.cs
  src/Aspire.Hosting/ResourceBuilderExtensions.cs
  src/Shared/StringComparers.cs
  tests/Aspire.Hosting.Tests/WithHttpCommandTests.cs
  tests/testproject/TestProject.ServiceA/Program.cs
Labels: area-app-model

#8003 Enhance the Storage role assignments docs
  src/Aspire.Hosting.Azure.Storage/AzureStorageExtensions.cs
Labels: area-integrations

#7940 Adding spectre.console to package deps and using it in Aspire.CLI
  Directory.Packages.props
  src/Aspire.Cli/Aspire.Cli.csproj
  src/Aspire.Cli/Program.cs
  src/Aspire.Cli/Properties/launchSettings.json
Labels: area-cli

#8016 Increase timeout on flakey test
  src/Aspire.Hosting/ApplicationModel/ResourceNotificationService.cs
  tests/Aspire.Hosting.Tests/WithHttpCommandTests.cs
Labels: area-app-model

#7963 Docker Compose publishing
  .gitignore
  playground/publishers/Publishers.AppHost/Program.cs
  src/Aspire.Hosting.Docker/Aspire.Hosting.Docker.csproj
  src/Aspire.Hosting.Docker/DockerComposePublisher.cs
  src/Aspire.Hosting.Docker/DockerComposePublisherExtensions.cs
  src/Aspire.Hosting.Docker/DockerComposePublisherLoggerExtensions.cs
  src/Aspire.Hosting.Docker/DockerComposePublisherOptions.cs
  src/Aspire.Hosting.Docker/DockerComposePublishingContext.cs
  src/Aspire.Hosting.Docker/Resources/ComposeFile.cs
  src/Aspire.Hosting.Docker/Resources/ComposeNodes/Config.cs
  src/Aspire.Hosting.Docker/Resources/ComposeNodes/NamedComposeMember.cs
  src/Aspire.Hosting.Docker/Resources/ComposeNodes/Network.cs
  src/Aspire.Hosting.Docker/Resources/ComposeNodes/Secret.cs
  src/Aspire.Hosting.Docker/Resources/ComposeNodes/Service.cs
  src/Aspire.Hosting.Docker/Resources/ServiceNodes/Build.cs
  src/Aspire.Hosting.Docker/Resources/ServiceNodes/ConfigReference.cs
  src/Aspire.Hosting.Docker/Resources/ServiceNodes/Healthcheck.cs
  src/Aspire.Hosting.Docker/Resources/ServiceNodes/Ipam.cs
  src/Aspire.Hosting.Docker/Resources/ServiceNodes/Logging.cs
  src/Aspire.Hosting.Docker/Resources/ServiceNodes/SecretReference.cs
  src/Aspire.Hosting.Docker/Resources/ServiceNodes/Swarm/Deploy.cs
  src/Aspire.Hosting.Docker/Resources/ServiceNodes/Swarm/LabelSpecs.cs
  src/Aspire.Hosting.Docker/Resources/ServiceNodes/Swarm/Placement.cs
  src/Aspire.Hosting.Docker/Resources/ServiceNodes/Swarm/ResourceSpec.cs
  src/Aspire.Hosting.Docker/Resources/ServiceNodes/Swarm/Resources.cs
  src/Aspire.Hosting.Docker/Resources/ServiceNodes/Swarm/RestartPolicy.cs
  src/Aspire.Hosting.Docker/Resources/ServiceNodes/Swarm/UpdateConfig.cs
  src/Aspire.Hosting.Docker/Resources/ServiceNodes/Ulimit.cs
  src/Aspire.Hosting.Docker/Resources/ServiceNodes/Volume.cs
  src/Aspire.Hosting/ApplicationModel/ResourceExtensions.cs
  src/Aspire.Hosting/Aspire.Hosting.csproj
  src/Aspire.Hosting/Publishing/PublishingOptions.cs
  src/Aspire.Hosting/Utils/ContainerReferenceParser.cs
  src/Shared/PortAllocator.cs
  src/Shared/Yaml/ForceQuotedStringsEventEmitter.cs
  src/Shared/Yaml/QuotationEventEmitter.cs
  src/Shared/Yaml/StringSequencesFlowStyle.cs
  src/Shared/Yaml/YamlIEnumerableSkipEmptyObjectGraphVisitor.cs
Labels: community-contribution, area-deployment

#8026 Fix flaky ResourceName_SubscribeOnLoadAndChange_SubscribeConsoleLogsOnce
  tests/Aspire.Dashboard.Components.Tests/Pages/ConsoleLogsTests.cs
Labels: area-dashboard

#8017 Create SQL Server container folders on Windows
  src/Aspire.Hosting.SqlServer/SqlServerBuilderExtensions.cs
Labels: needs-area-label

#8024 Start params flow - fixes for ports, and generated / appsettings
  playground/publishers/Publishers.AppHost/Program.cs
  src/Aspire.Hosting.Docker/DockerComposePublishingContext.cs
Labels: needs-area-label, community-contribution

#8023 Update to M.E.AI 9.3.0-preview.1.25161.3
  eng/Versions.props
  playground/OpenAIEndToEnd/OpenAIEndToEnd.WebStory/Components/Pages/UseIChatClient.razor
  tests/Aspire.Azure.AI.OpenAI.Tests/AspireAzureOpenAIClientBuilderChatClientExtensionsTests.cs
  tests/Aspire.OpenAI.Tests/AspireOpenAIClientBuilderChatClientExtensionsTests.cs
Labels: area-integrations

#8010 Use test acr in DistributedApplicationTests
  tests/Aspire.Hosting.Tests/DistributedApplicationTests.cs
Labels: area-app-model

#8031 Fix redis image and version name in dist app test
  tests/Aspire.Hosting.Tests/DistributedApplicationTests.cs
Labels: area-app-model

#8030 Make secrets in docker compose placeholders
  playground/publishers/Publishers.AppHost/Program.cs
  playground/publishers/Publishers.AppHost/docker-compose.yaml
  src/Aspire.Hosting.Docker/DockerComposePublishingContext.cs
Labels: needs-area-label

#8041 Update timeouts for WithHttpCommand tests
  tests/Aspire.Hosting.Tests/WithHttpCommandTests.cs
Labels: needs-area-label

#8019 Add Role Assignment support for Azure Service Bus
  src/Aspire.Hosting.Azure.AppContainers/AzureContainerAppsInfrastructure.cs
  src/Aspire.Hosting.Azure.ServiceBus/Aspire.Hosting.Azure.ServiceBus.csproj
  src/Aspire.Hosting.Azure.ServiceBus/AzureServiceBusExtensions.cs
  src/Aspire.Hosting.Azure.ServiceBus/AzureServiceBusResource.cs
  src/Aspire.Hosting.Azure.Storage/AzureStorageExtensions.cs
  src/Aspire.Hosting.Azure.Storage/AzureStorageResource.cs
  src/Aspire.Hosting.Azure/AzureProvisioningResource.cs
  tests/Aspire.Hosting.Azure.Tests/AzureBicepResourceTests.cs
  tests/Aspire.Hosting.Azure.Tests/AzureResourceOptionsTests.cs
  tests/Aspire.Hosting.Azure.Tests/AzureServiceBusExtensionsTests.cs
  tests/Aspire.Hosting.Azure.Tests/ExistingAzureResourceTests.cs
  tests/Aspire.Hosting.Azure.Tests/RoleAssignmentTests.cs
Labels: area-integrations

#8042 Parametrize parameters as env replacements
  playground/publishers/Publishers.AppHost/Program.cs
  playground/publishers/Publishers.AppHost/docker-compose.yaml
  src/Aspire.Hosting.Docker/DockerComposePublishingContext.cs
Labels: area-integrations

#8043 Use custom queue/topic names in SB emulator heath-checks
  src/Aspire.Hosting.Azure.ServiceBus/AzureServiceBusQueueResource.cs
  tests/Aspire.Hosting.Azure.Tests/AzureEventHubsExtensionsTests.cs
  tests/Aspire.Hosting.Azure.Tests/AzureServiceBusExtensionsTests.cs
Labels: area-app-model

#8015 [CI] Simplify gathering test projects to run for non-templates on PRs
  .github/actions/enumerate-tests/action.yml
  .github/workflows/run-tests.yml
  .github/workflows/template-tests.yml
  .github/workflows/tests.yml
  tests/Aspire.Playground.Tests/AppHostTests.cs
  tests/Aspire.Playground.Tests/Aspire.Playground.Tests.csproj
  tests/Aspire.Playground.Tests/ProjectSpecificTests.cs
Labels: area-engineering-systems

#8047 Port arcade publishing fix
  eng/common/templates-official/job/job.yml
  eng/common/templates-official/steps/publish-build-artifacts.yml
  eng/common/templates/job/job.yml
  eng/common/templates/steps/publish-build-artifacts.yml
Labels: area-codeflow

#8018 Reapply "Backchannel between CLI and AppHost (#7991)" (#7999)
  .editorconfig
  Directory.Packages.props
  playground/waitfor/WaitForSandbox.AppHost/appsettings.json
  src/Aspire.Cli/Aspire.Cli.csproj
  src/Aspire.Cli/CliRpcTarget.cs
  src/Aspire.Cli/DotNetCliRunner.cs
  src/Aspire.Cli/Program.cs
  src/Aspire.Hosting/Aspire.Hosting.csproj
  src/Aspire.Hosting/Cli/AppHostRpcTarget.cs
  src/Aspire.Hosting/Cli/CliBackchannel.cs
  src/Aspire.Hosting/DistributedApplicationBuilder.cs
  tests/Aspire.Cli.Tests/Aspire.Cli.Tests.csproj
  tests/Aspire.Cli.Tests/Hosting/CliBackchannelTests.cs
Labels: area-cli

#8048 Generate env file with defaults and descriptions
  playground/publishers/Publishers.AppHost/Program.cs
  playground/publishers/Publishers.AppHost/docker-compose.yaml
  src/Aspire.Hosting.Docker/DockerComposePublishingContext.cs
Labels: area-integrations

#8040 Refactor SignalR sample
  playground/signalr/SignalRServerlessWeb/BackgroundWorker.cs
  playground/signalr/SignalRServerlessWeb/Program.cs
Labels: needs-area-label, community-contribution

#8049 Added a test for docker compose file generation
  Aspire.sln
  src/Aspire.Hosting.Docker/Aspire.Hosting.Docker.csproj
  src/Aspire.Hosting.Docker/DockerComposePublishingContext.cs
  tests/Aspire.Hosting.Docker.Tests/Aspire.Hosting.Docker.Tests.csproj
  tests/Aspire.Hosting.Docker.Tests/DockerComposePublisherTests.cs
Labels: area-integrations

#7924 xunitv3
  src/Aspire.ProjectTemplates/templates/aspire-starter/.template.config/dotnetcli.host.json
  src/Aspire.ProjectTemplates/templates/aspire-starter/.template.config/ide.host.json
  src/Aspire.ProjectTemplates/templates/aspire-starter/.template.config/localize/templatestrings.cs.json
  src/Aspire.ProjectTemplates/templates/aspire-starter/.template.config/localize/templatestrings.de.json
  src/Aspire.ProjectTemplates/templates/aspire-starter/.template.config/localize/templatestrings.en.json
  src/Aspire.ProjectTemplates/templates/aspire-starter/.template.config/localize/templatestrings.es.json
  src/Aspire.ProjectTemplates/templates/aspire-starter/.template.config/localize/templatestrings.fr.json
  src/Aspire.ProjectTemplates/templates/aspire-starter/.template.config/localize/templatestrings.it.json
  src/Aspire.ProjectTemplates/templates/aspire-starter/.template.config/localize/templatestrings.ja.json
  src/Aspire.ProjectTemplates/templates/aspire-starter/.template.config/localize/templatestrings.ko.json
  src/Aspire.ProjectTemplates/templates/aspire-starter/.template.config/localize/templatestrings.pl.json
  src/Aspire.ProjectTemplates/templates/aspire-starter/.template.config/localize/templatestrings.pt-BR.json
  src/Aspire.ProjectTemplates/templates/aspire-starter/.template.config/localize/templatestrings.ru.json
  src/Aspire.ProjectTemplates/templates/aspire-starter/.template.config/localize/templatestrings.tr.json
  src/Aspire.ProjectTemplates/templates/aspire-starter/.template.config/localize/templatestrings.zh-Hans.json
  src/Aspire.ProjectTemplates/templates/aspire-starter/.template.config/localize/templatestrings.zh-Hant.json
  src/Aspire.ProjectTemplates/templates/aspire-starter/.template.config/template.json
  src/Aspire.ProjectTemplates/templates/aspire-starter/8.2/Aspire-StarterApplication.1.Tests/Aspire-StarterApplication.1.Tests.csproj
  src/Aspire.ProjectTemplates/templates/aspire-starter/8.2/Aspire-StarterApplication.1.Tests/WebTests.cs
  src/Aspire.ProjectTemplates/templates/aspire-starter/8.2/Aspire-StarterApplication.1.sln
  src/Aspire.ProjectTemplates/templates/aspire-starter/9.1/Aspire-StarterApplication.1.Tests/Aspire-StarterApplication.1.Tests.csproj
  src/Aspire.ProjectTemplates/templates/aspire-starter/9.1/Aspire-StarterApplication.1.Tests/WebTests.cs
  src/Aspire.ProjectTemplates/templates/aspire-starter/9.1/Aspire-StarterApplication.1.sln
  src/Aspire.ProjectTemplates/templates/aspire-starter/9.2/Aspire-StarterApplication.1.Tests/Aspire-StarterApplication.1.Tests.csproj
  src/Aspire.ProjectTemplates/templates/aspire-starter/9.2/Aspire-StarterApplication.1.Tests/WebTests.cs
  src/Aspire.ProjectTemplates/templates/aspire-starter/9.2/Aspire-StarterApplication.1.sln
  src/Aspire.ProjectTemplates/templates/aspire-xunit/.template.config/dotnetcli.host.json
  src/Aspire.ProjectTemplates/templates/aspire-xunit/.template.config/ide.host.json
  src/Aspire.ProjectTemplates/templates/aspire-xunit/.template.config/localize/templatestrings.cs.json
  src/Aspire.ProjectTemplates/templates/aspire-xunit/.template.config/localize/templatestrings.de.json
  src/Aspire.ProjectTemplates/templates/aspire-xunit/.template.config/localize/templatestrings.en.json
  src/Aspire.ProjectTemplates/templates/aspire-xunit/.template.config/localize/templatestrings.es.json
  src/Aspire.ProjectTemplates/templates/aspire-xunit/.template.config/localize/templatestrings.fr.json
  src/Aspire.ProjectTemplates/templates/aspire-xunit/.template.config/localize/templatestrings.it.json
  src/Aspire.ProjectTemplates/templates/aspire-xunit/.template.config/localize/templatestrings.ja.json
  src/Aspire.ProjectTemplates/templates/aspire-xunit/.template.config/localize/templatestrings.ko.json
  src/Aspire.ProjectTemplates/templates/aspire-xunit/.template.config/localize/templatestrings.pl.json
  src/Aspire.ProjectTemplates/templates/aspire-xunit/.template.config/localize/templatestrings.pt-BR.json
  src/Aspire.ProjectTemplates/templates/aspire-xunit/.template.config/localize/templatestrings.ru.json
  src/Aspire.ProjectTemplates/templates/aspire-xunit/.template.config/localize/templatestrings.tr.json
  src/Aspire.ProjectTemplates/templates/aspire-xunit/.template.config/localize/templatestrings.zh-Hans.json
  src/Aspire.ProjectTemplates/templates/aspire-xunit/.template.config/localize/templatestrings.zh-Hant.json
  src/Aspire.ProjectTemplates/templates/aspire-xunit/.template.config/template.json
  src/Aspire.ProjectTemplates/templates/aspire-xunit/9.2/Aspire.Tests.1.csproj
Labels: area-templates

#8014 Fix named configuration handling in DbContext-based clients
  src/Aspire.Hosting.Azure.CosmosDB/AzureCosmosDBResource.cs
  src/Components/Aspire.Microsoft.EntityFrameworkCore.Cosmos/AspireAzureEFCoreCosmosExtensions.cs
  src/Components/Aspire.Microsoft.EntityFrameworkCore.SqlServer/AspireSqlServerEFCoreSqlClientExtensions.cs
  src/Components/Aspire.Npgsql.EntityFrameworkCore.PostgreSQL/AspireEFPostgreSqlExtensions.cs
  src/Components/Aspire.Oracle.EntityFrameworkCore/AspireOracleEFCoreExtensions.cs
  src/Components/Aspire.Pomelo.EntityFrameworkCore.MySql/AspireEFMySqlExtensions.cs
  src/Components/Common/EntityFrameworkUtils.cs
  tests/Aspire.Hosting.Azure.Tests/AzureCosmosDBExtensionsTests.cs
  tests/Aspire.Microsoft.EntityFrameworkCore.Cosmos.Tests/AspireAzureEfCoreCosmosDBExtensionsTests.cs
  tests/Aspire.Microsoft.EntityFrameworkCore.SqlServer.Tests/AspireSqlServerEFCoreSqlClientExtensionsTests.cs
  tests/Aspire.Npgsql.EntityFrameworkCore.PostgreSQL.Tests/AspireEFPostgreSqlExtensionsTests.cs
  tests/Aspire.Oracle.EntityFrameworkCore.Tests/AspireOracleEFCoreDatabaseExtensionsTests.cs
  tests/Aspire.Pomelo.EntityFrameworkCore.MySql.Tests/AspireEFMySqlExtensionsTests.cs
Labels: area-integrations

#8057 5x test timeout
  tests/Aspire.Dashboard.Components.Tests/Pages/ResourcesTests.cs
Labels: area-dashboard

#8059 [CI] Use LogFilePrefix instead of LogFileName
  .github/workflows/run-tests.yml
  .github/workflows/template-tests.yml
Labels: area-engineering-systems

#8067 Introduce --operation switch and inspect mode
  src/Aspire.Hosting/DistributedApplicationBuilder.cs
  src/Aspire.Hosting/DistributedApplicationExecutionContext.cs
  src/Aspire.Hosting/DistributedApplicationOperation.cs
  src/Aspire.Hosting/DistributedApplicationRunner.cs
  tests/Aspire.Cli.Tests/Hosting/CliBackchannelTests.cs
  tests/Aspire.Hosting.Tests/OperationModesTests.cs
  tests/Aspire.Hosting.Tests/WithHttpCommandTests.cs
Labels: area-app-model, NO-MERGE, area-cli

#8022 Create database for Sql Server resource
  playground/SqlServerEndToEnd/SqlServerEndToEnd.ApiService/Program.cs
  playground/SqlServerEndToEnd/SqlServerEndToEnd.DbSetup/Program.cs
  src/Aspire.Hosting.SqlServer/Aspire.Hosting.SqlServer.csproj
  src/Aspire.Hosting.SqlServer/SqlServerBuilderExtensions.cs
  src/Aspire.Hosting.SqlServer/SqlServerDatabaseResource.cs
  src/Aspire.Hosting.SqlServer/SqlServerServerResource.cs
  src/Aspire.Hosting/ApplicationModel/CreationScriptAnnotation.cs
  tests/Aspire.Hosting.SqlServer.Tests/AddSqlServerTests.cs
  tests/Aspire.Hosting.SqlServer.Tests/Aspire.Hosting.SqlServer.Tests.csproj
  tests/Aspire.Hosting.SqlServer.Tests/SqlServerFunctionalTests.cs
  tests/Aspire.Hosting.SqlServer.Tests/SqlServerGoStatementTests.cs
Labels: area-app-model

#8086 Add Sql Server tests and improve logging
  src/Aspire.Hosting.SqlServer/SqlServerBuilderExtensions.cs
  tests/Aspire.Hosting.SqlServer.Tests/SqlServerFunctionalTests.cs
Labels: needs-area-label

#8091 Dispose data readers between retries
  tests/Aspire.Hosting.SqlServer.Tests/SqlServerFunctionalTests.cs
Labels: needs-area-label

#8053 Add Role Assignment support to the non-database Azure resources
  playground/AspireEventHub/EventHubs.AppHost/aspire-manifest.json
  playground/AspireEventHub/EventHubs.AppHost/eventhubns.module.bicep
  playground/AzureFunctionsEndToEnd/AzureFunctionsEndToEnd.AppHost/eventhubs.module.bicep
  playground/AzureFunctionsEndToEnd/AzureFunctionsEndToEnd.AppHost/messaging.module.bicep
  playground/AzureSearchEndToEnd/AzureSearch.AppHost/search.module.bicep
  playground/AzureServiceBus/ServiceBus.AppHost/aspire-manifest.json
  playground/AzureServiceBus/ServiceBus.AppHost/sbemulator.module.bicep
  playground/OpenAIEndToEnd/OpenAIEndToEnd.AppHost/openai.module.bicep
  playground/bicep/BicepSample.AppHost/appConfig.module.bicep
  playground/bicep/BicepSample.AppHost/kv3.module.bicep
  playground/bicep/BicepSample.AppHost/sb.module.bicep
  playground/bicep/BicepSample.AppHost/signalr.module.bicep
  playground/bicep/BicepSample.AppHost/wps.module.bicep
  playground/cdk/CdkSample.AppHost/appConfig.module.bicep
  playground/cdk/CdkSample.AppHost/mykv.module.bicep
  playground/cdk/CdkSample.AppHost/search.module.bicep
  playground/cdk/CdkSample.AppHost/servicebus.module.bicep
  playground/cdk/CdkSample.AppHost/signalr.module.bicep
  playground/signalr/SignalR.AppHost/signalrDefault.module.bicep
  playground/signalr/SignalR.AppHost/signalrServerless.module.bicep
  playground/webpubsub/WebPubSub.AppHost/wps1.module.bicep
  src/Aspire.Hosting.Azure.AppConfiguration/Aspire.Hosting.Azure.AppConfiguration.csproj
  src/Aspire.Hosting.Azure.AppConfiguration/AzureAppConfigurationExtensions.cs
  src/Aspire.Hosting.Azure.AppConfiguration/AzureAppConfigurationResource.cs
  src/Aspire.Hosting.Azure.CognitiveServices/Aspire.Hosting.Azure.CognitiveServices.csproj
  src/Aspire.Hosting.Azure.CognitiveServices/AzureOpenAIExtensions.cs
  src/Aspire.Hosting.Azure.CognitiveServices/AzureOpenAIResource.cs
  src/Aspire.Hosting.Azure.EventHubs/Aspire.Hosting.Azure.EventHubs.csproj
  src/Aspire.Hosting.Azure.EventHubs/AzureEventHubsExtensions.cs
  src/Aspire.Hosting.Azure.EventHubs/AzureEventHubsResource.cs
  src/Aspire.Hosting.Azure.KeyVault/Aspire.Hosting.Azure.KeyVault.csproj
  src/Aspire.Hosting.Azure.KeyVault/AzureKeyVaultResource.cs
  src/Aspire.Hosting.Azure.KeyVault/AzureKeyVaultResourceExtensions.cs
  src/Aspire.Hosting.Azure.Search/Aspire.Hosting.Azure.Search.csproj
  src/Aspire.Hosting.Azure.Search/AzureSearchExtensions.cs
  src/Aspire.Hosting.Azure.Search/AzureSearchResource.cs
  src/Aspire.Hosting.Azure.ServiceBus/Aspire.Hosting.Azure.ServiceBus.csproj
  src/Aspire.Hosting.Azure.ServiceBus/AzureServiceBusExtensions.cs
  src/Aspire.Hosting.Azure.ServiceBus/AzureServiceBusResource.cs
  src/Aspire.Hosting.Azure.SignalR/Aspire.Hosting.Azure.SignalR.csproj
  src/Aspire.Hosting.Azure.SignalR/AzureSignalRExtensions.cs
  src/Aspire.Hosting.Azure.SignalR/AzureSignalRResource.cs
  src/Aspire.Hosting.Azure.Storage/Aspire.Hosting.Azure.Storage.csproj
  src/Aspire.Hosting.Azure.Storage/AzureStorageExtensions.cs
  src/Aspire.Hosting.Azure.Storage/AzureStorageResource.cs
  src/Aspire.Hosting.Azure.WebPubSub/Aspire.Hosting.Azure.WebPubSub.csproj
  src/Aspire.Hosting.Azure.WebPubSub/AzureWebPubSubExtensions.cs
  src/Aspire.Hosting.Azure.WebPubSub/AzureWebPubSubResource.cs
  src/Shared/AzureRoleAssignmentUtils.cs
  tests/Aspire.Hosting.Azure.Tests/AzureBicepResourceTests.cs
  tests/Aspire.Hosting.Azure.Tests/AzureEventHubsExtensionsTests.cs
  tests/Aspire.Hosting.Azure.Tests/AzureSignalRExtensionsTests.cs
  tests/Aspire.Hosting.Azure.Tests/AzureWebPubSubExtensionsTests.cs
  tests/Aspire.Hosting.Azure.Tests/ExistingAzureResourceTests.cs
  tests/Aspire.Hosting.Azure.Tests/RoleAssignmentTests.cs
Labels: area-integrations

#8071 Change hubName and negotiate endpoint to match convention
  playground/signalr/SignalRServerlessWeb/Pages/Index.cshtml
  playground/signalr/SignalRServerlessWeb/Program.cs
Labels: area-codeflow, community-contribution

#7944 Adding workflow to update dependencies weekly
  .github/dependabot.yml
  .github/workflows/update-dependencies.yml
  Directory.Packages.props
Labels: area-engineering-systems

#8093 Remove unused registry to fix the build
  .github/dependabot.yml
  .github/workflows/update-dependencies.yml
Labels: area-engineering-systems

#8095 increase timeout from 1 to 10 sec for bUnit waits
  tests/Aspire.Dashboard.Components.Tests/Controls/ApplicationNameTests.cs
  tests/Aspire.Dashboard.Components.Tests/Controls/PlotlyChartTests.cs
  tests/Aspire.Dashboard.Components.Tests/Controls/ResourceDetailsTests.cs
  tests/Aspire.Dashboard.Components.Tests/Controls/StructuredLogDetailsTests.cs
  tests/Aspire.Dashboard.Components.Tests/Controls/TextVisualizerDialogTests.cs
  tests/Aspire.Dashboard.Components.Tests/GridColumnManagerTests.cs
  tests/Aspire.Dashboard.Components.Tests/Layout/MainLayoutTests.cs
  tests/Aspire.Dashboard.Components.Tests/Pages/ConsoleLogsTests.cs
  tests/Aspire.Dashboard.Components.Tests/Pages/LoginTests.cs
  tests/Aspire.Dashboard.Components.Tests/Pages/MetricsTests.cs
  tests/Aspire.Dashboard.Components.Tests/Pages/ResourcesTests.cs
  tests/Aspire.Dashboard.Components.Tests/Pages/StructuredLogsTests.cs
  tests/Aspire.Dashboard.Components.Tests/Pages/TraceDetailsTests.cs
  tests/Aspire.Dashboard.Components.Tests/Shared/DashboardPageTestContext.cs
  tests/Aspire.Dashboard.Components.Tests/Shared/TestConstants.cs
Labels: area-dashboard

#8050 Introduce the azure publisher
  playground/publishers/Publishers.AppHost/Program.cs
  playground/publishers/Publishers.AppHost/Publishers.AppHost.csproj
  playground/publishers/Publishers.AppHost/infra/api/api.bicep
  playground/publishers/Publishers.AppHost/infra/azpg/azpg.bicep
  playground/publishers/Publishers.AppHost/infra/dbsetup/dbsetup.bicep
  playground/publishers/Publishers.AppHost/infra/frontend/frontend.bicep
  playground/publishers/Publishers.AppHost/infra/main.bicep
  playground/publishers/Publishers.AppHost/infra/pg/pg.bicep
  playground/publishers/Publishers.AppHost/infra/sqlserver/sqlserver.bicep
  src/Aspire.Hosting.Azure/Aspire.Hosting.Azure.csproj
  src/Aspire.Hosting.Azure/AzureContainerAppPublisher.cs
  src/Aspire.Hosting.Azure/AzurePublisher.cs
  src/Aspire.Hosting.Azure/AzurePublisherExtensions.cs
  src/Aspire.Hosting.Azure/AzurePublisherOptions.cs
  src/Aspire.Hosting/PublisherDistributedApplicationBuilderExtensions.cs
  src/Shared/BicepFunction2.cs
  tests/Aspire.Hosting.Azure.Tests/AzurePublisherTests.cs
Labels: area-app-model

#7602 Add UTC timestamp display option
  src/Aspire.Dashboard/Components/Controls/LogViewer.razor.cs
  src/Aspire.Dashboard/Components/Pages/ConsoleLogs.razor
  src/Aspire.Dashboard/Components/Pages/ConsoleLogs.razor.cs
  src/Aspire.Dashboard/Resources/ConsoleLogs.Designer.cs
  src/Aspire.Dashboard/Resources/ConsoleLogs.resx
  src/Aspire.Dashboard/Resources/xlf/ConsoleLogs.cs.xlf
  src/Aspire.Dashboard/Resources/xlf/ConsoleLogs.de.xlf
  src/Aspire.Dashboard/Resources/xlf/ConsoleLogs.es.xlf
  src/Aspire.Dashboard/Resources/xlf/ConsoleLogs.fr.xlf
  src/Aspire.Dashboard/Resources/xlf/ConsoleLogs.it.xlf
  src/Aspire.Dashboard/Resources/xlf/ConsoleLogs.ja.xlf
  src/Aspire.Dashboard/Resources/xlf/ConsoleLogs.ko.xlf
  src/Aspire.Dashboard/Resources/xlf/ConsoleLogs.pl.xlf
  src/Aspire.Dashboard/Resources/xlf/ConsoleLogs.pt-BR.xlf
  src/Aspire.Dashboard/Resources/xlf/ConsoleLogs.ru.xlf
  src/Aspire.Dashboard/Resources/xlf/ConsoleLogs.tr.xlf
  src/Aspire.Dashboard/Resources/xlf/ConsoleLogs.zh-Hans.xlf
  src/Aspire.Dashboard/Resources/xlf/ConsoleLogs.zh-Hant.xlf
  src/Shared/KnownFormats.cs
Labels: area-dashboard

#8106 Add a dashboard configuration option to disable resource graph view
  src/Aspire.Dashboard/Components/Pages/Resources.razor
  src/Aspire.Dashboard/Components/Pages/Resources.razor.cs
  src/Aspire.Dashboard/Components/Pages/Resources.razor.css
  src/Aspire.Dashboard/Configuration/DashboardOptions.cs
  src/Shared/DashboardConfigNames.cs
  tests/Aspire.Dashboard.Tests/Integration/StartupTests.cs
Labels: area-dashboard

#8025 `aspire add` command
  src/Aspire.Cli/DotNetCliRunner.cs
  src/Aspire.Cli/ExitCodeConstants.cs
  src/Aspire.Cli/NuGetPackageCache.cs
  src/Aspire.Cli/Program.cs
Labels: area-cli

#8114 Disable flakey Cli test
  tests/Aspire.Cli.Tests/Hosting/CliBackchannelTests.cs
Labels: area-integrations

#8112 Reenable EventHub emulator tests
  tests/Aspire.Hosting.Azure.Tests/AzureEventHubsExtensionsTests.cs
Labels: area-integrations

#8130 Fix resource graph disappearing when switching to mobile view
  src/Aspire.Dashboard/Components/Controls/SummaryDetailsView.razor
  src/Aspire.Dashboard/wwwroot/js/app-resourcegraph.js
Labels: area-dashboard

#8131 Improve ensure resource deleted logic in restart
  src/Aspire.Hosting/Dcp/DcpExecutor.cs
Labels: area-app-model

#8117 Add localized values for column resize strings
  src/Aspire.Dashboard/Resources/ControlsStrings.Designer.cs
  src/Aspire.Dashboard/Resources/ControlsStrings.resx
  src/Aspire.Dashboard/Resources/xlf/ControlsStrings.cs.xlf
  src/Aspire.Dashboard/Resources/xlf/ControlsStrings.de.xlf
  src/Aspire.Dashboard/Resources/xlf/ControlsStrings.es.xlf
  src/Aspire.Dashboard/Resources/xlf/ControlsStrings.fr.xlf
  src/Aspire.Dashboard/Resources/xlf/ControlsStrings.it.xlf
  src/Aspire.Dashboard/Resources/xlf/ControlsStrings.ja.xlf
  src/Aspire.Dashboard/Resources/xlf/ControlsStrings.ko.xlf
  src/Aspire.Dashboard/Resources/xlf/ControlsStrings.pl.xlf
  src/Aspire.Dashboard/Resources/xlf/ControlsStrings.pt-BR.xlf
  src/Aspire.Dashboard/Resources/xlf/ControlsStrings.ru.xlf
  src/Aspire.Dashboard/Resources/xlf/ControlsStrings.tr.xlf
  src/Aspire.Dashboard/Resources/xlf/ControlsStrings.zh-Hans.xlf
  src/Aspire.Dashboard/Resources/xlf/ControlsStrings.zh-Hant.xlf
  src/Aspire.Dashboard/Utils/DashboardUIHelpers.cs
Labels: area-dashboard

#8126 Dependency flow from dotnet repos
  Directory.Packages.props
  eng/Version.Details.xml
  eng/Versions.props
Labels: area-codeflow

#7970 Move remaining ACA infrastructure generation to Aspire.Hosting.Azure.AppContainers
  Directory.Packages.props
  playground/AzureContainerApps/AzureContainerApps.AppHost/Program.cs
  playground/AzureContainerApps/AzureContainerApps.AppHost/account.module.bicep
  playground/AzureContainerApps/AzureContainerApps.AppHost/api.module.bicep
  playground/AzureContainerApps/AzureContainerApps.AppHost/aspire-manifest.json
  playground/AzureContainerApps/AzureContainerApps.AppHost/cache.module.bicep
  playground/AzureContainerApps/AzureContainerApps.AppHost/infra.module.bicep
  playground/AzureContainerApps/AzureContainerApps.AppHost/pythonapp.module.bicep
  playground/publishers/Publishers.AppHost/Program.cs
  playground/publishers/Publishers.AppHost/infra/api/api.bicep
  playground/publishers/Publishers.AppHost/infra/dbsetup/dbsetup.bicep
  playground/publishers/Publishers.AppHost/infra/env/env.bicep
  playground/publishers/Publishers.AppHost/infra/frontend/frontend.bicep
  playground/publishers/Publishers.AppHost/infra/main.bicep
  playground/publishers/Publishers.AppHost/infra/pg/pg.bicep
  playground/publishers/Publishers.AppHost/infra/sqlserver/sqlserver.bicep
  src/Aspire.Hosting.Azure.AppContainers/Aspire.Hosting.Azure.AppContainers.csproj
  src/Aspire.Hosting.Azure.AppContainers/AzdAzureContainerAppEnvironment.cs
  src/Aspire.Hosting.Azure.AppContainers/AzureContainerAppEnvironmentResource.cs
  src/Aspire.Hosting.Azure.AppContainers/AzureContainerAppExtensions.cs
  src/Aspire.Hosting.Azure.AppContainers/AzureContainerAppsInfrastructure.cs
  src/Aspire.Hosting.Azure.AppContainers/ContainerAppEnvironmentDotnetComponentResource.cs
  src/Aspire.Hosting.Azure.AppContainers/ContainerAppExtensions.cs
  src/Aspire.Hosting.Azure.AppContainers/IAzureContainerAppEnvironment.cs
  src/Aspire.Hosting.Azure/AzureBicepResource.cs
  src/Aspire.Hosting.Azure/AzurePublisher.cs
  src/Shared/BicepFunction2.cs
  tests/Aspire.Hosting.Azure.Tests/AzureContainerAppsTests.cs
  tests/Aspire.Hosting.Azure.Tests/AzurePublisherTests.cs
Labels: area-integrations

#8124 Updating NuGet package dependencies
  Directory.Packages.props
  src/Components/Aspire.RabbitMQ.Client.v7/Aspire.RabbitMQ.Client.v7.csproj
  tests/Aspire.MongoDB.Driver.Tests/ConformanceTests.cs
Labels: area-integrations

#8083 [CI] Add EndToEnd tests for PR validation
  .github/workflows/run-tests.yml
  .github/workflows/template-tests.yml
  .github/workflows/tests.yml
  tests/Shared/GetTestProjects.proj
Labels: area-engineering-systems

#7600 Allow filtering trace details with search
  src/Aspire.Dashboard/Components/Pages/TraceDetail.razor
  src/Aspire.Dashboard/Components/Pages/TraceDetail.razor.cs
  src/Aspire.Dashboard/Model/Otlp/SpanWaterfallViewModel.cs
  src/Aspire.Dashboard/Otlp/Model/OtlpSpan.cs
  tests/Aspire.Dashboard.Tests/Model/SpanWaterfallViewModelTests.cs
  tests/Shared/Telemetry/TelemetryTestHelpers.cs
Labels: area-dashboard

#8144 Moving property IsAspireHost to the SDK
  src/Aspire.AppHost.Sdk/SDK/Sdk.in.props
  src/Aspire.ProjectTemplates/templates/aspire-apphost/9.2/Aspire.AppHost1.csproj
  src/Aspire.ProjectTemplates/templates/aspire-empty/9.2/AspireApplication.1.AppHost/AspireApplication.1.AppHost.csproj
  src/Aspire.ProjectTemplates/templates/aspire-starter/9.2/Aspire-StarterApplication.1.AppHost/Aspire-StarterApplication.1.AppHost.csproj
Labels: area-templates

#8157 Move CODEOWNERS to correct location
  .github/CODEOWNERS
  CODEOWNERS
Labels: area-engineering-systems

#8081 [CI] Playwright on Linux for PR validation
  .github/workflows/run-tests.yml
  .github/workflows/tests.yml
  eng/pipelines/templates/BuildAndTest.yml
  tests/Aspire.Dashboard.Tests/Integration/Playwright/BrowserTokenAuthenticationTests.cs
  tests/Aspire.Workload.Tests/BuildAndRunTemplateTests.cs
  tests/Aspire.Workload.Tests/EmptyTemplateRunTests.cs
  tests/Aspire.Workload.Tests/PerTestFrameworkTemplatesTests.cs
  tests/Aspire.Workload.Tests/StarterTemplateRunTestsBase.cs
  tests/Aspire.Workload.Tests/WorkloadTestsBase.cs
  tests/Shared/Playwright/PlaywrightProvider.cs
  tests/Shared/Playwright/RequiresPlaywrightAttribute.cs
  tests/Shared/Playwright/RequiresPlaywrightDiscoverer.cs
  tests/Shared/WorkloadTesting/BuildEnvironment.cs
  tests/Shared/WorkloadTesting/TestExtensions.cs
  tests/helix/send-to-helix-inner.proj
Labels: area-engineering-systems

#8136 Making `aspire run` pretty
  Directory.Packages.props
  src/Aspire.Cli/AppHostRunner.cs
  src/Aspire.Cli/CliRpcTarget.cs
  src/Aspire.Cli/ConsoleAppModel.cs
  src/Aspire.Cli/DotNetCliRunner.cs
  src/Aspire.Cli/NuGetPackageCache.cs
  src/Aspire.Cli/Program.cs
  src/Aspire.Hosting/Cli/CliBackchannel.cs
  src/Aspire.Hosting/Dashboard/DashboardLifecycleHook.cs
  src/Aspire.Hosting/Devcontainers/Codespaces/CodespacesUrlRewriter.cs
  src/Aspire.Hosting/DistributedApplication.cs
  src/Aspire.Hosting/DistributedApplicationBuilder.cs
  src/Shared/LoggingHelpers.cs
  tests/Aspire.Hosting.Tests/Dashboard/DashboardLifecycleHookTests.cs
Labels: area-app-model, area-cli

#8161 Save OTLP API key in user secrets
  src/Aspire.Hosting/ApplicationModel/UserSecretsParameterDefault.cs
  src/Aspire.Hosting/DistributedApplicationBuilder.cs
  src/Shared/SecretsStore.cs
  tests/Aspire.Hosting.Tests/SecretsStoreTests.cs
Labels: area-app-model

#8163 Fixed issues with the azure container apps environment logic
  src/Aspire.Hosting.Azure.AppContainers/AzdAzureContainerAppEnvironment.cs
  src/Aspire.Hosting.Azure.AppContainers/AzureContainerAppExtensions.cs
  src/Aspire.Hosting.Azure.AppContainers/AzureContainerAppsInfrastructure.cs
  tests/Aspire.Hosting.Azure.Tests/AzureContainerAppsTests.cs
Labels: area-integrations

#8164 Improve `aspire build` CLI experience
  src/Aspire.Cli/ExitCodeConstants.cs
  src/Aspire.Cli/Program.cs
Labels: area-engineering-systems

#8166 Make --wait-for-debugger workin release builds of aspire CLI.
  src/Aspire.Cli/Program.cs
Labels: needs-area-label

#8154 Specify EntityPath in EH client health checks
  src/Components/Aspire.Azure.Messaging.EventHubs/EventHubsComponent.cs
  tests/Aspire.Hosting.Azure.Tests/AzureEventHubsExtensionsTests.cs
Labels: area-integrations

#8169 Fix resource graph duplication
  src/Aspire.Dashboard/Components/Pages/Resources.razor.cs
  tests/Aspire.Dashboard.Components.Tests/Pages/ResourcesTests.cs
Labels: area-dashboard

#8162 Fix trace order when buffer is full under certain situations
  src/Aspire.Dashboard/Otlp/Model/OtlpTrace.cs
  src/Aspire.Dashboard/Otlp/Storage/TelemetryRepository.cs
  src/Shared/CircularBuffer.cs
  tests/Aspire.Dashboard.Tests/CircularBufferTests.cs
Labels: area-dashboard

#8102 pin GHA
  .github/actions/enumerate-template-tests/action.yml
  .github/actions/enumerate-tests/action.yml
  .github/dependabot.yml
  .github/workflows/backport.yml
  .github/workflows/generate-api-diffs.yml
  .github/workflows/locker.yml
  .github/workflows/markdownlint.yml
  .github/workflows/run-tests.yml
  .github/workflows/template-tests.yml
  .github/workflows/tests.yml
  .github/workflows/update-dependencies.yml
Labels: area-engineering-systems

#8151 Test to ensure SB emulator supports queues and custom config
  src/Aspire.Hosting.Azure.ServiceBus/AzureServiceBusExtensions.cs
  tests/Aspire.Hosting.Azure.Tests/AzureServiceBusExtensionsTests.cs
Labels: needs-area-label

#8160 [tests] Fix some failing tests
  tests/Aspire.Components.Common.Tests/PlatformDetection.cs
  tests/Aspire.Components.Common.Tests/RequiresPlaywrightAttribute.cs
  tests/Aspire.Components.Common.Tests/RequiresPlaywrightDiscoverer.cs
  tests/Aspire.Dashboard.Tests/Aspire.Dashboard.Tests.csproj
  tests/Aspire.Hosting.PostgreSQL.Tests/PostgresFunctionalTests.cs
Labels: area-engineering-systems, needs-area-label

#8182 Remove role assignments on implicit storage account
  src/Aspire.Hosting.Azure.Functions/AzureFunctionsProjectResourceExtensions.cs
  tests/Aspire.Hosting.Azure.Tests/AzureFunctionsTests.cs
Labels: area-app-model

#8121 Add support for creating files and folders in a container via `docker/podman cp`
  src/Aspire.Hosting.PostgreSQL/PostgresBuilderExtensions.cs
  src/Aspire.Hosting/ApplicationModel/ContainerCreateFilesCallbackAnnotation.cs
  src/Aspire.Hosting/ContainerResourceBuilderExtensions.cs
  src/Aspire.Hosting/Dcp/DcpExecutor.cs
  src/Aspire.Hosting/Dcp/Model/Container.cs
  tests/Aspire.Hosting.PostgreSQL.Tests/AddPostgresTests.cs
  tests/Aspire.Hosting.Tests/DistributedApplicationTests.cs
Labels: area-app-model

#8156 Fix event attributes not displaying
  playground/Stress/Stress.ApiService/TraceCreator.cs
  playground/Stress/Stress.AppHost/Program.cs
  src/Aspire.Dashboard/Components/Controls/GridValue.razor.css
  src/Aspire.Dashboard/Components/Controls/PropertyGrid.razor
  src/Aspire.Dashboard/Components/Controls/PropertyGrid.razor.cs
  src/Aspire.Dashboard/Components/Controls/PropertyGrid.razor.css
  src/Aspire.Dashboard/Components/Controls/SpanDetails.razor
Labels: area-dashboard

#8189 Misc improvements to add package and overall experience
  src/Aspire.Cli/DotNetCliRunner.cs
  src/Aspire.Cli/NuGetPackageCache.cs
  src/Aspire.Cli/Program.cs
  src/Aspire.Cli/README.md
  tests/Aspire.Hosting.Tests/WithHttpCommandTests.cs
  tests/Aspire.Workload.Tests/StarterTemplateRunTestsBase.cs
Labels: area-cli

#8120 Add secret warning alert to text visualizer the first time you open it with a secret
  src/Aspire.Dashboard/Components/Controls/ExceptionDetails.razor
  src/Aspire.Dashboard/Components/Controls/GridValue.razor.cs
  src/Aspire.Dashboard/Components/Controls/StructuredLogActions.razor.cs
  src/Aspire.Dashboard/Components/Dialogs/TextVisualizerDialog.razor
  src/Aspire.Dashboard/Components/Dialogs/TextVisualizerDialog.razor.cs
  src/Aspire.Dashboard/Components/Dialogs/TextVisualizerDialog.razor.css
  src/Aspire.Dashboard/Components/ResourcesGridColumns/SourceColumnDisplay.razor
  src/Aspire.Dashboard/Model/TextVisualizerDialogViewModel.cs
  src/Aspire.Dashboard/Resources/Dialogs.Designer.cs
  src/Aspire.Dashboard/Resources/Dialogs.resx
  src/Aspire.Dashboard/Resources/xlf/Dialogs.cs.xlf
  src/Aspire.Dashboard/Resources/xlf/Dialogs.de.xlf
  src/Aspire.Dashboard/Resources/xlf/Dialogs.es.xlf
  src/Aspire.Dashboard/Resources/xlf/Dialogs.fr.xlf
  src/Aspire.Dashboard/Resources/xlf/Dialogs.it.xlf
  src/Aspire.Dashboard/Resources/xlf/Dialogs.ja.xlf
  src/Aspire.Dashboard/Resources/xlf/Dialogs.ko.xlf
  src/Aspire.Dashboard/Resources/xlf/Dialogs.pl.xlf
  src/Aspire.Dashboard/Resources/xlf/Dialogs.pt-BR.xlf
  src/Aspire.Dashboard/Resources/xlf/Dialogs.ru.xlf
  src/Aspire.Dashboard/Resources/xlf/Dialogs.tr.xlf
  src/Aspire.Dashboard/Resources/xlf/Dialogs.zh-Hans.xlf
  src/Aspire.Dashboard/Resources/xlf/Dialogs.zh-Hant.xlf
  src/Aspire.Dashboard/Utils/BrowserStorageKeys.cs
  tests/Aspire.Dashboard.Components.Tests/Controls/TextVisualizerDialogTests.cs
Labels: area-dashboard

#8123 Move filters into a menu, add a remove all filters button
  src/Aspire.Dashboard/Components/Controls/AspireMenuButton.razor
  src/Aspire.Dashboard/Components/Controls/AspireMenuButton.razor.cs
  src/Aspire.Dashboard/Components/Pages/StructuredLogs.razor
  src/Aspire.Dashboard/Components/Pages/StructuredLogs.razor.cs
  src/Aspire.Dashboard/Components/Pages/Traces.razor
  src/Aspire.Dashboard/Components/Pages/Traces.razor.cs
  src/Aspire.Dashboard/Model/MenuButtonItem.cs
  src/Aspire.Dashboard/wwwroot/css/app.css
  tests/Aspire.Dashboard.Components.Tests/Pages/StructuredLogsTests.cs
  tests/Shared/AsyncTestHelpers.cs
Labels: area-dashboard

#8201 Implement pull based model resource states in `aspire` CLI.
  src/Aspire.Cli/Backchannel/AppHostBackchannel.cs
  src/Aspire.Cli/Backchannel/CliRpcTarget.cs
  src/Aspire.Cli/CliRpcTarget.cs
  src/Aspire.Cli/ConsoleAppModel.cs
  src/Aspire.Cli/DotNetCliRunner.cs
  src/Aspire.Cli/Program.cs
  src/Aspire.Hosting/Backchannel/AppHostRpcTarget.cs
  src/Aspire.Hosting/Backchannel/BackchannelService.cs
  src/Aspire.Hosting/Cli/AppHostRpcTarget.cs
  src/Aspire.Hosting/Cli/CliBackchannel.cs
  src/Aspire.Hosting/Dashboard/DashboardLifecycleHook.cs
  src/Aspire.Hosting/DistributedApplicationBuilder.cs
  tests/Aspire.Cli.Tests/Hosting/CliBackchannelTests.cs
  tests/Aspire.Hosting.Tests/Dashboard/DashboardLifecycleHookTests.cs
Labels: area-app-model, area-cli

#8153 Clarify purpose of GH test workflows
  .github/workflows/run-tests.yml
  .github/workflows/tests-integration.yml
  .github/workflows/tests-templates.yml
  tests/Aspire.EndToEnd.Tests/README.md
  tests/Aspire.Templates.Tests/README.md
Labels: area-engineering-systems

#8140 Support CosmosDB and Redis role assignments on app specific managed identity
  playground/AzureContainerApps/AzureContainerApps.AppHost/account.module.bicep
  playground/AzureContainerApps/AzureContainerApps.AppHost/api-identity.module.bicep
  playground/AzureContainerApps/AzureContainerApps.AppHost/api-roles-storage.module.bicep
  playground/AzureContainerApps/AzureContainerApps.AppHost/api.module.bicep
  playground/AzureContainerApps/AzureContainerApps.AppHost/aspire-manifest.json
  playground/AzureFunctionsEndToEnd/AzureFunctionsEndToEnd.AppHost/aspire-manifest.json
  playground/AzureFunctionsEndToEnd/AzureFunctionsEndToEnd.AppHost/cosmosdb.module.bicep
  playground/CosmosEndToEnd/CosmosEndToEnd.AppHost/CosmosEndToEnd.AppHost.csproj
  playground/CosmosEndToEnd/CosmosEndToEnd.AppHost/aspire-manifest.json
  playground/CosmosEndToEnd/CosmosEndToEnd.AppHost/cosmos.module.bicep
  playground/Redis/Redis.ApiService/Redis.ApiService.csproj
  playground/Redis/Redis.AppHost/Redis.AppHost.csproj
  playground/Redis/Redis.AppHost/aspire-manifest.json
  playground/bicep/BicepSample.AppHost/aspire-manifest.json
  playground/bicep/BicepSample.AppHost/cosmos.module.bicep
  playground/bicep/BicepSample.AppHost/redis.module.bicep
  playground/cdk/CdkSample.AppHost/aspire-manifest.json
  playground/cdk/CdkSample.AppHost/cache.module.bicep
  playground/cdk/CdkSample.AppHost/cosmos.module.bicep
  src/Aspire.Hosting.Azure.AppContainers/AzureContainerAppsInfrastructure.cs
  src/Aspire.Hosting.Azure.CosmosDB/AzureCosmosDBExtensions.cs
  src/Aspire.Hosting.Azure.CosmosDB/AzureCosmosDBResource.cs
  src/Aspire.Hosting.Azure.Redis/AzureRedisCacheResource.cs
  src/Aspire.Hosting.Azure.Redis/AzureRedisExtensions.cs
  src/Aspire.Hosting.Azure.ServiceBus/Aspire.Hosting.Azure.ServiceBus.csproj
  src/Aspire.Hosting.Azure/AddRoleAssignmentsContext.cs
  src/Aspire.Hosting.Azure/AzureProvisioningResource.cs
  src/Aspire.Hosting.Azure/AzureResourcePreparer.cs
  tests/Aspire.Hosting.Azure.Tests/AzureBicepResourceTests.cs
  tests/Aspire.Hosting.Azure.Tests/AzureContainerAppsTests.cs
  tests/Aspire.Hosting.Azure.Tests/AzureCosmosDBExtensionsTests.cs
  tests/Aspire.Hosting.Azure.Tests/AzureFunctionsTests.cs
  tests/Aspire.Hosting.Azure.Tests/AzurePublisherTests.cs
  tests/Aspire.Hosting.Azure.Tests/AzureRedisExtensionsTests.cs
  tests/Aspire.Hosting.Azure.Tests/ExistingAzureResourceTests.cs
  tests/Aspire.Hosting.Azure.Tests/RoleAssignmentTests.cs
Labels: area-integrations

#8211 Fix tests after bad merge
  tests/Aspire.Hosting.Azure.Tests/AzureFunctionsTests.cs
Labels: area-integrations

#8132 Add test coverage for named config handling for Azure OpenAI
  tests/Aspire.Azure.AI.OpenAI.Tests/AspireAzureAIOpenAIExtensionsTests.cs
Labels: area-integrations

#8216 Remove verb from annotation name
  src/Aspire.Hosting/ApplicationModel/ContainerFileSystemCallbackAnnotation.cs
  src/Aspire.Hosting/ContainerResourceBuilderExtensions.cs
  src/Aspire.Hosting/Dcp/DcpExecutor.cs
  tests/Aspire.Hosting.PostgreSQL.Tests/AddPostgresTests.cs
Labels: area-app-model

#8197 [tests] Reduce the number of template tests run on PR validation
  tests/Aspire.Components.Common.Tests/PlatformDetection.cs
  tests/Aspire.Hosting.Tests/WithHttpCommandTests.cs
  tests/Aspire.Templates.Tests/BuildAndRunStarterTemplateBuiltInTest.cs
  tests/Aspire.Templates.Tests/BuildAndRunTemplateTests.cs
  tests/Aspire.Templates.Tests/PerTestFrameworkTemplatesTests.cs
  tests/Aspire.Templates.Tests/StarterTemplateProjectNamesTests.cs
  tests/Aspire.Templates.Tests/StarterTemplateRunTestsBase.cs
  tests/Aspire.Templates.Tests/WorkloadTestsBase.cs
  tests/helix/send-to-helix-templatestests.targets
Labels: area-integrations

#8212 Follow up on database role assignments
  src/Aspire.Hosting.Azure.AppContainers/AddRoleAssignmentContext.cs
  src/Aspire.Hosting.Azure.AppContainers/AzureContainerAppsInfrastructure.cs
  src/Aspire.Hosting.Azure.CosmosDB/AzureCosmosDBResource.cs
  src/Aspire.Hosting.Azure.Redis/AzureRedisCacheResource.cs
  src/Aspire.Hosting.Azure/AddRoleAssignmentsContext.cs
  src/Aspire.Hosting.Azure/AzureProvisioningResource.cs
  src/Aspire.Hosting.Azure/IAddRoleAssignmentsContext.cs
Labels: area-app-model

#8196 Add Issue template for filing blocking-clean-ci issues
  .github/ISSUE_TEMPLATE/40_blocking_clean_ci.yml
Labels: area-engineering-systems

#8217 [CI] Run source-index stage1 only for the main branch
  eng/pipelines/azure-pipelines.yml
Labels: area-engineering-systems

#8195 Use Arcade SDK IsTestUtilityProject property
  tests/Aspire.Components.Common.Tests/Aspire.Components.Common.Tests.csproj
  tests/Directory.Build.targets
  tests/Shared/RepoTesting/Aspire.RepoTesting.targets
Labels: area-engineering-systems

#8068 Support CosmosDB child resources in client integration
  playground/CosmosEndToEnd/CosmosEndToEnd.ApiService/Program.cs
  playground/CosmosEndToEnd/CosmosEndToEnd.AppHost/Program.cs
  src/Aspire.Hosting.Azure.CosmosDB/AzureCosmosDBContainerResource.cs
  src/Aspire.Hosting.Azure.CosmosDB/AzureCosmosDBDatabaseResource.cs
  src/Aspire.Hosting.Azure.CosmosDB/AzureCosmosDBResource.cs
  src/Components/Aspire.Microsoft.Azure.Cosmos/AspireMicrosoftAzureCosmosExtensions.cs
  src/Components/Aspire.Microsoft.Azure.Cosmos/ConfigurationSchema.json
  src/Components/Aspire.Microsoft.Azure.Cosmos/MicrosoftAzureCosmosSettings.cs
  src/Components/Aspire.Microsoft.EntityFrameworkCore.Cosmos/AspireAzureEFCoreCosmosExtensions.cs
  src/Components/Aspire.Microsoft.EntityFrameworkCore.Cosmos/ConfigurationSchema.json
  src/Components/Aspire.Microsoft.EntityFrameworkCore.Cosmos/EntityFrameworkCoreCosmosSettings.cs
  src/Shared/Cosmos/CosmosUtils.cs
  tests/Aspire.Hosting.Azure.Tests/AzureCosmosDBExtensionsTests.cs
  tests/Aspire.Hosting.Azure.Tests/ResourceWithAzureFunctionsConfigTests.cs
  tests/Aspire.Microsoft.Azure.Cosmos.Tests/AspireMicrosoftAzureCosmosExtensionsTests.cs
  tests/Aspire.Microsoft.EntityFrameworkCore.Cosmos.Tests/AspireAzureEfCoreCosmosDBExtensionsTests.cs
Labels: area-integrations

#8165 Add buttons to resource graph to zoom and reset position
  src/Aspire.Dashboard/Components/Pages/Resources.razor
  src/Aspire.Dashboard/Components/Pages/Resources.razor.css
  src/Aspire.Dashboard/Resources/Resources.Designer.cs
  src/Aspire.Dashboard/Resources/Resources.resx
  src/Aspire.Dashboard/Resources/xlf/Resources.cs.xlf
  src/Aspire.Dashboard/Resources/xlf/Resources.de.xlf
  src/Aspire.Dashboard/Resources/xlf/Resources.es.xlf
  src/Aspire.Dashboard/Resources/xlf/Resources.fr.xlf
  src/Aspire.Dashboard/Resources/xlf/Resources.it.xlf
  src/Aspire.Dashboard/Resources/xlf/Resources.ja.xlf
  src/Aspire.Dashboard/Resources/xlf/Resources.ko.xlf
  src/Aspire.Dashboard/Resources/xlf/Resources.pl.xlf
  src/Aspire.Dashboard/Resources/xlf/Resources.pt-BR.xlf
  src/Aspire.Dashboard/Resources/xlf/Resources.ru.xlf
  src/Aspire.Dashboard/Resources/xlf/Resources.tr.xlf
  src/Aspire.Dashboard/Resources/xlf/Resources.zh-Hans.xlf
  src/Aspire.Dashboard/Resources/xlf/Resources.zh-Hant.xlf
  src/Aspire.Dashboard/wwwroot/js/app-resourcegraph.js
Labels: area-dashboard

#8220 [cli] null check on project file logic
  src/Aspire.Cli/ExitCodeConstants.cs
  src/Aspire.Cli/Program.cs
Labels: area-cli

#8228 Add an animation to reset button
  src/Aspire.Dashboard/wwwroot/js/app-resourcegraph.js
Labels: area-dashboard

#8219 Remove ConfigureAwait from the Cli
  .editorconfig
  src/Aspire.Cli/Backchannel/AppHostBackchannel.cs
  src/Aspire.Cli/DotNetCliRunner.cs
  src/Aspire.Cli/NuGetPackageCache.cs
  src/Aspire.Cli/Program.cs
Labels: area-cli

#8221 Skip Aspire.Cli project in API diffs
  .github/workflows/generate-api-diffs.yml
Labels: area-engineering-systems

#8222 Add new 3rd party dependencies to Signing.props to fix official build
  eng/Signing.props
Labels: area-engineering-systems

#8148 tests for resourceready
  tests/Aspire.Hosting.Tests/Health/ResourceHealthCheckServiceTests.cs
Labels: area-app-model

#8202 [CI] Combine Templates, and Integrations test workflows
  .github/actions/enumerate-template-tests/action.yml
  .github/actions/enumerate-tests/action.yml
  .github/workflows/run-tests.yml
  .github/workflows/tests-integration.yml
  .github/workflows/tests.yml
  tests/Aspire.EndToEnd.Tests/Aspire.EndToEnd.Tests.csproj
  tests/Aspire.Playground.Tests/Aspire.Playground.Tests.csproj
  tests/Aspire.Templates.Tests/TemplateTestsBase.cs
Labels: area-engineering-systems

#8226 Support Azure SqlServer role assignments on app specific managed identity
  playground/SqlServerEndToEnd/SqlServerEndToEnd.AppHost/aspire-manifest.json
  playground/SqlServerEndToEnd/SqlServerEndToEnd.AppHost/sql1.module.bicep
  src/Aspire.Hosting.Azure.Sql/AzureSqlExtensions.cs
  src/Aspire.Hosting.Azure.Sql/AzureSqlServerResource.cs
  tests/Aspire.Hosting.Azure.Tests/AzureBicepResourceTests.cs
  tests/Aspire.Hosting.Azure.Tests/AzureResourceOptionsTests.cs
  tests/Aspire.Hosting.Azure.Tests/AzureSqlExtensionsTests.cs
  tests/Aspire.Hosting.Azure.Tests/ExistingAzureResourceTests.cs
  tests/Aspire.Hosting.Azure.Tests/RoleAssignmentTests.cs
Labels: area-integrations

#8210 Update tsaoptions.json
  .config/tsaoptions.json
Labels: area-integrations

#8238 Retry both deletion and verification when restarting a resource
  src/Aspire.Hosting/Dcp/DcpExecutor.cs
Labels: area-app-model, area-orchestrator

#8240 Mark AzurePublisherOptions as Experimental
  src/Aspire.Hosting.Azure/AzurePublisher.cs
  src/Aspire.Hosting.Azure/AzurePublisherOptions.cs
  tests/Aspire.Hosting.Azure.Tests/AzurePublisherTests.cs
Labels: area-integrations

#8239 Refactor Role Assignment Design
  src/Aspire.Hosting.Azure.AppContainers/AddRoleAssignmentContext.cs
  src/Aspire.Hosting.Azure.AppContainers/AzureContainerAppsInfrastructure.cs
  src/Aspire.Hosting.Azure/AppIdentityAnnotation.cs
  src/Aspire.Hosting.Azure/AppIdentityResource.cs
  src/Aspire.Hosting.Azure/AzureResourcePreparer.cs
  src/Aspire.Hosting.Azure/IAppIdentityResource.cs
Labels: area-app-model

#8224 Implement publisher advertisement and CLI integration
  playground/publishers/Publishers.AppHost/Properties/launchSettings.json
  playground/publishers/Publishers.AppHost/docker-compose.yaml
  src/Aspire.Cli/Backchannel/AppHostBackchannel.cs
  src/Aspire.Cli/DotNetCliRunner.cs
  src/Aspire.Cli/Program.cs
  src/Aspire.Hosting/Backchannel/AppHostRpcTarget.cs
  src/Aspire.Hosting/Backchannel/BackchannelConnectedEvent.cs
  src/Aspire.Hosting/Backchannel/BackchannelReadyEvent.cs
  src/Aspire.Hosting/Backchannel/BackchannelService.cs
  src/Aspire.Hosting/DistributedApplication.cs
  src/Aspire.Hosting/PublisherDistributedApplicationBuilderExtensions.cs
  src/Aspire.Hosting/Publishing/PublisherAdvertisementEvent.cs
  tests/Aspire.Hosting.Tests/Backchannel/AppHostBackchannelTests.cs
  tests/Aspire.Hosting.Tests/OperationModesTests.cs
  tests/Aspire.Hosting.Tests/Utils/UnixSocketHelper.cs
Labels: area-app-model, area-cli

#8243 Fix Korean close tooltip text
  src/Aspire.Dashboard/wwwroot/css/app.css
Labels: area-dashboard

#8248 Add minimal dotnet watch support to CLI
  src/Aspire.Cli/DotNetCliRunner.cs
  src/Aspire.Cli/Program.cs
Labels: area-app-model, area-cli

#8247 Rename publisher methods for clarity and add overloads for defaults
  playground/publishers/Publishers.AppHost/Program.cs
  src/Aspire.Hosting.Azure/AzurePublisherExtensions.cs
  src/Aspire.Hosting.Docker/DockerComposePublisherExtensions.cs
  src/Aspire.Hosting.Kubernetes/KubernetesPublisherExtensions.cs
Labels: needs-area-label

#8249 Automatically determine default template version from CLI version
  src/Aspire.Cli/Program.cs
  src/Aspire.Cli/Utils/VersionHelper.cs
Labels: area-cli

#8236 Address feedback on CosmosDB child client integration
  src/Aspire.Hosting.Azure.CosmosDB/AzureCosmosDBContainerResource.cs
  src/Aspire.Hosting.Azure.CosmosDB/AzureCosmosDBDatabaseResource.cs
  src/Aspire.Hosting.Azure.CosmosDB/AzureCosmosDBResource.cs
  src/Components/Aspire.Microsoft.Azure.Cosmos/AspireMicrosoftAzureCosmosExtensions.cs
  tests/Aspire.Microsoft.Azure.Cosmos.Tests/AspireMicrosoftAzureCosmosExtensionsTests.cs
Labels: area-integrations

#8252 Fix Codespaces URL display on local machine
  src/Aspire.Cli/Program.cs
  src/Aspire.Hosting/Backchannel/AppHostRpcTarget.cs
Labels: needs-area-label, area-cli

#8259 [Docs] Small typos in CreateBuilder method signature documentation
  src/Aspire.Hosting/DistributedApplication.cs
Labels: needs-area-label, community-contribution

#8251 Added overload of AddConnectionString using the builder pattern to make it more approachable
  src/Aspire.Hosting/ApplicationModel/ReferenceExpression.cs
  src/Aspire.Hosting/ConnectionStringBuilderExtensions.cs
  tests/Aspire.Hosting.Tests/WithReferenceTests.cs
Labels: area-app-model

#8271 docs(Aspire.Azure.Messaging.EventHubs): Update AspireEventHubsExtensions
  src/Components/Aspire.Azure.Messaging.EventHubs/AspireEventHubsExtensions.cs
Labels: area-integrations, community-contribution

#8272 Only add .msi in Signing.props when missing
  eng/Signing.props
Labels: area-engineering-systems

#8273 Templates: Use latest OTel packages when targeting net9.0
  Directory.Packages.props
  eng/Versions.props
  src/Aspire.ProjectTemplates/Aspire.ProjectTemplates.csproj
  src/Aspire.ProjectTemplates/templates/aspire-empty/9.2/AspireApplication.1.ServiceDefaults/AspireApplication.1.ServiceDefaults.csproj
  src/Aspire.ProjectTemplates/templates/aspire-servicedefaults/9.2/Aspire.ServiceDefaults1.csproj
  src/Aspire.ProjectTemplates/templates/aspire-starter/9.2/Aspire-StarterApplication.1.ServiceDefaults/Aspire-StarterApplication.1.ServiceDefaults.csproj
Labels: area-templates

#8275 Ensure WithHttpCommand adds HttpClientFactory
  src/Aspire.Hosting/ResourceBuilderExtensions.cs
  tests/Aspire.Hosting.Tests/WithHttpCommandTests.cs
Labels: area-app-model

#8265 Clean up build scripts
  .config/dotnet-tools.json
  eng/build.ps1
  eng/build.sh
Labels: area-engineering-systems

#8276 Introduce CommandOptions & HttpCommandOptions
  playground/Stress/Stress.AppHost/Program.cs
  playground/TestShop/TestShop.AppHost/Program.cs
  src/Aspire.Hosting/ApplicationModel/CommandOptions.cs
  src/Aspire.Hosting/ApplicationModel/HttpCommandContext.cs
  src/Aspire.Hosting/ApplicationModel/HttpCommandOptions.cs
  src/Aspire.Hosting/ResourceBuilderExtensions.cs
  tests/Aspire.Hosting.Tests/Dashboard/DashboardServiceTests.cs
  tests/Aspire.Hosting.Tests/WithHttpCommandTests.cs
Labels: area-app-model

#8235 Support deep-link for Azure WebPubSub Hubs in clients
  playground/webpubsub/WebPubSub.AppHost/Program.cs
  playground/webpubsub/WebPubSub.AppHost/aspire-manifest.json
  playground/webpubsub/WebPubSub.AppHost/wps1.module.bicep
  playground/webpubsub/WebPubSubWeb/Program.cs
  src/Aspire.Hosting.Azure.WebPubSub/AzureWebPubSubExtensions.cs
  src/Aspire.Hosting.Azure.WebPubSub/AzureWebPubSubHubResource.cs
  src/Components/Aspire.Azure.Messaging.WebPubSub/AspireWebPubSubExtensions.cs
  src/Components/Aspire.Azure.Messaging.WebPubSub/AzureMessagingWebPubSubSettings.cs
  tests/Aspire.Azure.Messaging.WebPubSub.Tests/AspireWebPubSubExtensionsTests.cs
  tests/Aspire.Hosting.Azure.Tests/AzureWebPubSubExtensionsTests.cs
  tests/Aspire.Hosting.Azure.Tests/PublicApiTests/WebPubSubPublicApiTests.cs
Labels: area-integrations

#8296 [CI] Bump number of retries for downloading dotnet-install.sh
  tests/Shared/InstallSdk.targets
Labels: area-engineering-systems

#8227 [tests] PR validation speed ups
  .github/actions/enumerate-template-tests/action.yml
  .github/actions/enumerate-tests/action.yml
  .github/workflows/run-tests.yml
  .github/workflows/tests.yml
  eng/Build.props
  tests/Aspire.EndToEnd.Tests/IntegrationServicesFixture.cs
  tests/Aspire.Hosting.Tests/Health/ResourceHealthCheckServiceTests.cs
  tests/Shared/GetTestProjects.proj
Labels: area-integrations

#8266 Add Cosmos database builder pattern for child containers
  playground/CosmosEndToEnd/CosmosEndToEnd.ApiService/Program.cs
  playground/CosmosEndToEnd/CosmosEndToEnd.AppHost/Program.cs
  src/Components/Aspire.Microsoft.Azure.Cosmos/AspireMicrosoftAzureCosmosExtensions.cs
  src/Components/Aspire.Microsoft.Azure.Cosmos/CosmosDatabaseBuilder.cs
  tests/Aspire.Microsoft.Azure.Cosmos.Tests/AspireMicrosoftAzureCosmosExtensionsTests.cs
Labels: area-integrations

#8290 Fix Azure Functions Role Assignments to Host Storage
  playground/AzureFunctionsEndToEnd/AzureFunctionsEndToEnd.AppHost/aspire-manifest.json
  src/Aspire.Hosting.Azure.Functions/Aspire.Hosting.Azure.Functions.csproj
  src/Aspire.Hosting.Azure.Functions/AzureFunctionsProjectResourceExtensions.cs
  tests/Aspire.Hosting.Azure.Tests/AzureFunctionsTests.cs
Labels: area-integrations

#8302 Clean up build scripts
  .config/dotnet-tools.json
  eng/build.ps1
  eng/build.sh
Labels: area-engineering-systems

#8303 Fix DockerComposePublisher port rendering
  src/Aspire.Hosting.Docker/DockerComposePublishingContext.cs
  tests/Aspire.Hosting.Docker.Tests/DockerComposePublisherTests.cs
Labels: area-deployment

#7021 Grafana: improved aspnetcore.json
  src/Grafana/dashboards/aspnetcore-endpoint.json
  src/Grafana/dashboards/aspnetcore.json
Labels: needs-area-label, community-contribution

#8264 Bootstrapping container builds for `aspire build` / `aspire publish`.
  playground/publishers/Publishers.AppHost/docker-compose.yaml
  src/Aspire.Cli/Backchannel/AppHostBackchannel.cs
  src/Aspire.Cli/Program.cs
  src/Aspire.Hosting.Docker/DockerComposePublisher.cs
  src/Aspire.Hosting.Docker/DockerComposePublishingContext.cs
  src/Aspire.Hosting/Backchannel/AppHostRpcTarget.cs
  src/Aspire.Hosting/Backchannel/BackchannelService.cs
  src/Aspire.Hosting/DistributedApplicationBuilder.cs
  src/Aspire.Hosting/DistributedApplicationRunner.cs
  src/Aspire.Hosting/Publishing/DockerContainerRuntime.cs
  src/Aspire.Hosting/Publishing/IContainerRuntime.cs
  src/Aspire.Hosting/Publishing/PodmanContainerRuntime.cs
  src/Aspire.Hosting/Publishing/PublishingActivityProgressReporter.cs
  src/Aspire.Hosting/Publishing/ResourceContainerImageBuilder.cs
  tests/Aspire.Hosting.Containers.Tests/WithDockerfileTests.cs
  tests/Aspire.Hosting.Docker.Tests/DockerComposePublisherTests.cs
  tests/Aspire.Hosting.Tests/Health/ResourceHealthCheckServiceTests.cs
  tests/Aspire.Hosting.Tests/Helpers/NoopPublisher.cs
  tests/Aspire.Hosting.Tests/Publishing/ResourceContainerImageBuilderTests.cs
  tests/Aspire.Hosting.Tests/Utils/DockerfileUtils.cs
Labels: area-deployment, area-cli

#8316 Move extra URLs to stress, customize frontend endpoints
  playground/Stress/Stress.AppHost/Program.cs
  playground/TestShop/TestShop.AppHost/Program.cs
Labels: area-dashboard

#8298 Add resource to environment callback context
  playground/AzureContainerApps/AzureContainerApps.AppHost/Program.cs
  playground/AzureContainerApps/AzureContainerApps.AppHost/api.module.bicep
  playground/AzureContainerApps/AzureContainerApps.AppHost/aspire-manifest.json
  src/Aspire.Hosting.Azure.AppContainers/AzureContainerAppsInfrastructure.cs
  src/Aspire.Hosting.Azure/AzureResourcePreparer.cs
  src/Aspire.Hosting.Docker/DockerComposePublishingContext.cs
  src/Aspire.Hosting.Kubernetes/KubernetesResourceContext.cs
  src/Aspire.Hosting/ApplicationModel/EnvironmentCallbackContext.cs
  src/Aspire.Hosting/ApplicationModel/ResourceExtensions.cs
  tests/Aspire.Hosting.Tests/ExpressionResolverTests.cs
  tests/Aspire.Hosting.Tests/ResourceExtensionsTests.cs
  tests/Aspire.Hosting.Tests/WithEnvironmentTests.cs
Labels: area-app-model

#8282 Fix Cosmos child resource connection strings with access key auth
  playground/AzureContainerApps/AzureContainerApps.AppHost/account.module.bicep
  playground/AzureContainerApps/AzureContainerApps.AppHost/aspire-manifest.json
  playground/AzureFunctionsEndToEnd/AzureFunctionsEndToEnd.AppHost/aspire-manifest.json
  playground/AzureServiceBus/ServiceBus.AppHost/aspire-manifest.json
  playground/CosmosEndToEnd/CosmosEndToEnd.AppHost/aspire-manifest.json
  playground/CosmosEndToEnd/CosmosEndToEnd.AppHost/cosmos.module.bicep
  playground/TestShop/TestShop.AppHost/aspire-manifest.json
  playground/bicep/BicepSample.AppHost/aspire-manifest.json
  playground/cdk/CdkSample.AppHost/aspire-manifest.json
  src/Aspire.Hosting.Azure.CosmosDB/AzureCosmosDBContainerResource.cs
  src/Aspire.Hosting.Azure.CosmosDB/AzureCosmosDBDatabaseResource.cs
  src/Aspire.Hosting.Azure.CosmosDB/AzureCosmosDBExtensions.cs
  src/Aspire.Hosting.Azure.CosmosDB/AzureCosmosDBResource.cs
  tests/Aspire.Hosting.Azure.Tests/AzureBicepResourceTests.cs
  tests/Aspire.Hosting.Azure.Tests/AzureCosmosDBExtensionsTests.cs
  tests/Aspire.Hosting.Azure.Tests/ExistingAzureResourceTests.cs
Labels: area-integrations

#8323 Obsolete EventHubs Emulator WithDataBindMount and WithDataVolume
  src/Aspire.Hosting.Azure.EventHubs/AzureEventHubsExtensions.cs
  tests/Aspire.Hosting.Azure.Tests/AzureEventHubsExtensionsTests.cs
  tests/Aspire.Hosting.Azure.Tests/PublicApiTests/EventHubsPublicApiTests.cs
Labels: area-integrations

#8324 [CI] Don't use short url for dotnet-install script
  tests/Aspire.Hosting.Tests/Health/ResourceHealthCheckServiceTests.cs
  tests/Shared/InstallSdk.targets
Labels: area-engineering-systems

#8307 Show endpoints in `aspire run` table as the localhost addresses
  src/Aspire.Hosting/Backchannel/AppHostRpcTarget.cs
Labels: area-cli

#8329 [tests] Run Hosting.Docker.Tests on the pipeline
  tests/Aspire.Hosting.Docker.Tests/Aspire.Hosting.Docker.Tests.csproj
Labels: area-engineering-systems, testing ☑️
