Repository dotnet/aspire, pull requests merged in 2025-05, with the labels that each got.

#9028 Fix error when metrics have no scope
  playground/Stress/Stress.TelemetryService/TelemetryStresser.cs
  src/Aspire.Dashboard/Components/Controls/SpanDetails.razor.cs
  src/Aspire.Dashboard/Components/Controls/StructuredLogDetails.razor.cs
  src/Aspire.Dashboard/Components/Controls/TreeMetricSelector.razor
  src/Aspire.Dashboard/Components/Pages/Metrics.razor
  src/Aspire.Dashboard/Components/Pages/Metrics.razor.cs
  src/Aspire.Dashboard/Components/Pages/StructuredLogs.razor
  src/Aspire.Dashboard/Otlp/Model/OtlpApplication.cs
  src/Aspire.Dashboard/Otlp/Model/OtlpHelpers.cs
  src/Aspire.Dashboard/Otlp/Model/OtlpInstrument.cs
  src/Aspire.Dashboard/Otlp/Model/OtlpLogEntry.cs
  src/Aspire.Dashboard/Otlp/Model/OtlpMeter.cs
  src/Aspire.Dashboard/Otlp/Model/OtlpScope.cs
  src/Aspire.Dashboard/Otlp/Model/OtlpSpan.cs
  src/Aspire.Dashboard/Otlp/Storage/TelemetryRepository.cs
  tests/Aspire.Dashboard.Components.Tests/Controls/PlotlyChartTests.cs
  tests/Aspire.Dashboard.Components.Tests/Controls/StructuredLogDetailsTests.cs
  tests/Aspire.Dashboard.Components.Tests/Pages/MetricsTests.cs
  tests/Aspire.Dashboard.Tests/Model/DefaultInstrumentUnitResolverTests.cs
  tests/Aspire.Dashboard.Tests/Model/SpanWaterfallViewModelTests.cs
  tests/Aspire.Dashboard.Tests/Model/TraceHelpersTests.cs
  tests/Aspire.Dashboard.Tests/TelemetryRepositoryTests/LogTests.cs
  tests/Aspire.Dashboard.Tests/TelemetryRepositoryTests/MetricsTests.cs
  tests/Aspire.Dashboard.Tests/TelemetryRepositoryTests/OtlpSpanTests.cs
  tests/Aspire.Dashboard.Tests/TelemetryRepositoryTests/TraceTests.cs
  tests/Shared/Telemetry/TelemetryTestHelpers.cs
Labels: area-dashboard

#9031 Improve PauseResumeButton_TogglePauseResume_LogsPausedAndResumed logging
  src/Aspire.Dashboard/Components/Controls/LogViewer.razor
  src/Shared/ConsoleLogs/LogPauseViewModel.cs
  tests/Aspire.Dashboard.Components.Tests/Pages/ConsoleLogsTests.cs
Labels: area-dashboard

#8108 Clarify DCP Not Found Error
  src/Aspire.Hosting/Dcp/DcpHost.cs
Labels: area-app-model, community-contribution

#9059 Add hosting integration for Azure Container Registry
  Aspire.sln
  playground/AzureContainerApps/AzureContainerApps.AppHost/api-roles-account-kv.module.bicep
  src/Aspire.Hosting.Azure.AppContainers/Aspire.Hosting.Azure.AppContainers.csproj
  src/Aspire.Hosting.Azure.AppContainers/AzureContainerAppExtensions.cs
  src/Aspire.Hosting.Azure.AppContainers/AzureContainerAppsInfrastructure.cs
  src/Aspire.Hosting.Azure.ContainerRegistry/Aspire.Hosting.Azure.ContainerRegistry.csproj
  src/Aspire.Hosting.Azure.ContainerRegistry/AzureContainerRegistryExtensions.cs
  src/Aspire.Hosting.Azure.ContainerRegistry/AzureContainerRegistryResource.cs
  src/Aspire.Hosting.Azure.ContainerRegistry/ContainerRegistryReferenceAnnotation.cs
  src/Aspire.Hosting.Azure/AzurePublishingContext.cs
  src/Aspire.Hosting.Docker/DockerComposeInfrastructure.cs
  src/Aspire.Hosting.Kubernetes/KubernetesInfrastructure.cs
  src/Aspire.Hosting/ApplicationModel/ContainerResource.cs
  src/Aspire.Hosting/ApplicationModel/DeploymentTargetAnnotation.cs
  src/Aspire.Hosting/ApplicationModel/ExecutableResource.cs
  src/Aspire.Hosting/ApplicationModel/ProjectResource.cs
  src/Aspire.Hosting/DistributedApplication.cs
  src/Aspire.Hosting/ResourceBuilderExtensions.cs
  tests/Aspire.Hosting.Azure.Tests/Aspire.Hosting.Azure.Tests.csproj
  tests/Aspire.Hosting.Azure.Tests/AzureContainerAppsTests.cs
  tests/Aspire.Hosting.Azure.Tests/AzureContainerRegistryTests.cs
  tests/Aspire.Hosting.Azure.Tests/ContainerRegistryTests.cs
  tests/Aspire.Hosting.Azure.Tests/ExistingAzureResourceTests.cs
  tests/Aspire.Hosting.Docker.Tests/DockerComposeTests.cs
  tests/Shared/RepoTesting/Directory.Packages.Helix.props
Labels: area-integrations

#9058 regularize and increase some timeouts
  tests/Aspire.Playground.Tests/Aspire.Playground.Tests.csproj
  tests/Aspire.Playground.Tests/ProjectSpecificTests.cs
Labels: area-integrations

#9062 Update `Microsoft.Extensions.AI` to 9.4.3-preview.1.25230.7
  eng/Versions.props
  tests/Aspire.Azure.AI.OpenAI.Tests/AspireAzureOpenAIClientBuilderEmbeddingGeneratorExtensionsTests.cs
  tests/Aspire.OpenAI.Tests/AspireOpenAIClientBuilderEmbeddingGeneratorExtensionsTests.cs
Labels: area-integrations

#9054 Put examples docs in remark to be visible in Visual Studio (XML doc comments)
  playground/AspireEventHub/EventHubsConsumer/Processor.cs
  src/Aspire.Hosting.Azure.AppConfiguration/AzureAppConfigurationExtensions.cs
  src/Aspire.Hosting.Azure.AppContainers/AzureContainerAppContainerExtensions.cs
  src/Aspire.Hosting.Azure.AppContainers/AzureContainerAppExecutableExtensions.cs
  src/Aspire.Hosting.Azure.AppContainers/AzureContainerAppProjectExtensions.cs
  src/Aspire.Hosting.Azure.AppContainers/ContainerAppExtensions.cs
  src/Aspire.Hosting.Azure.CognitiveServices/AzureOpenAIExtensions.cs
  src/Aspire.Hosting.Azure.CosmosDB/AzureCosmosDBExtensions.cs
  src/Aspire.Hosting.Azure.KeyVault/AzureKeyVaultResourceExtensions.cs
  src/Aspire.Hosting.Azure.PostgreSQL/AzurePostgresExtensions.cs
  src/Aspire.Hosting.Azure.Redis/AzureRedisExtensions.cs
  src/Aspire.Hosting.Azure.Search/AzureSearchExtensions.cs
  src/Aspire.Hosting.Azure.ServiceBus/AzureServiceBusExtensions.cs
  src/Aspire.Hosting.Azure.SignalR/AzureSignalRExtensions.cs
  src/Aspire.Hosting.Azure.Sql/AzureSqlExtensions.cs
  src/Aspire.Hosting.Azure.Storage/AzureStorageExtensions.cs
  src/Aspire.Hosting.Azure.WebPubSub/AzureWebPubSubExtensions.cs
  src/Aspire.Hosting.Docker/DockerComposeServiceExtensions.cs
  src/Aspire.Hosting.Kubernetes/KubernetesServiceExtensions.cs
  src/Aspire.Hosting.Python/PythonProjectResourceBuilderExtensions.cs
  src/Aspire.Hosting.Valkey/ValkeyBuilderExtensions.cs
  src/Aspire.Hosting/ApplicationModel/AfterEndpointsAllocatedEvent.cs
  src/Aspire.Hosting/ApplicationModel/ResourceExtensions.cs
  src/Aspire.Hosting/ConnectionStringBuilderExtensions.cs
  src/Aspire.Hosting/ContainerResourceBuilderExtensions.cs
  src/Aspire.Hosting/DistributedApplication.cs
  src/Aspire.Hosting/DistributedApplicationBuilderExtensions.cs
  src/Aspire.Hosting/IDistributedApplicationBuilder.cs
  src/Aspire.Hosting/ProjectResourceBuilderExtensions.cs
  src/Aspire.Hosting/ResourceBuilderExtensions.cs
  tests/Aspire.TestUtilities/QuarantinedTestAttribute.cs
Labels: area-integrations, community-contribution

#8907 Update templates descriptions to be more beginner-friendly
  src/Aspire.ProjectTemplates/templates/aspire-apphost/.template.config/localize/templatestrings.en.json
  src/Aspire.ProjectTemplates/templates/aspire-apphost/.template.config/template.json
  src/Aspire.ProjectTemplates/templates/aspire-empty/.template.config/localize/templatestrings.en.json
  src/Aspire.ProjectTemplates/templates/aspire-empty/.template.config/template.json
  src/Aspire.ProjectTemplates/templates/aspire-mstest/.template.config/localize/templatestrings.en.json
  src/Aspire.ProjectTemplates/templates/aspire-mstest/.template.config/template.json
  src/Aspire.ProjectTemplates/templates/aspire-nunit/.template.config/localize/templatestrings.en.json
  src/Aspire.ProjectTemplates/templates/aspire-nunit/.template.config/template.json
  src/Aspire.ProjectTemplates/templates/aspire-servicedefaults/.template.config/localize/templatestrings.en.json
  src/Aspire.ProjectTemplates/templates/aspire-servicedefaults/.template.config/template.json
  src/Aspire.ProjectTemplates/templates/aspire-starter/.template.config/localize/templatestrings.en.json
  src/Aspire.ProjectTemplates/templates/aspire-starter/.template.config/template.json
  src/Aspire.ProjectTemplates/templates/aspire-xunit/.template.config/localize/templatestrings.en.json
  src/Aspire.ProjectTemplates/templates/aspire-xunit/.template.config/template.json
Labels: area-templates, community-contribution

#9066 Remove Elasticsearch-related implementations
  Aspire.sln
  playground/Elasticsearch/Elasticsearch.ApiService/Elasticsearch.ApiService.csproj
  playground/Elasticsearch/Elasticsearch.ApiService/Models/Person.cs
  playground/Elasticsearch/Elasticsearch.ApiService/Program.cs
  playground/Elasticsearch/Elasticsearch.ApiService/Properties/launchSettings.json
  playground/Elasticsearch/Elasticsearch.ApiService/appsettings.Development.json
  playground/Elasticsearch/Elasticsearch.ApiService/appsettings.json
  playground/Elasticsearch/Elasticsearch.AppHost/Elasticsearch.AppHost.csproj
  playground/Elasticsearch/Elasticsearch.AppHost/Program.cs
  playground/Elasticsearch/Elasticsearch.AppHost/Properties/launchSettings.json
  playground/Elasticsearch/Elasticsearch.AppHost/appsettings.Development.json
  playground/Elasticsearch/Elasticsearch.AppHost/appsettings.json
  playground/Elasticsearch/Elasticsearch.AppHost/aspire-manifest.json
  src/Aspire.Hosting.Elasticsearch/Aspire.Hosting.Elasticsearch.csproj
  src/Aspire.Hosting.Elasticsearch/ElasticsearchBuilderExtensions.cs
  src/Aspire.Hosting.Elasticsearch/ElasticsearchContainerImageTags.cs
  src/Aspire.Hosting.Elasticsearch/ElasticsearchResource.cs
  src/Aspire.Hosting.Elasticsearch/api/Aspire.Hosting.Elasticsearch.cs
  src/Components/Aspire.Elastic.Clients.Elasticsearch/Aspire.Elastic.Clients.Elasticsearch.csproj
  src/Components/Aspire.Elastic.Clients.Elasticsearch/AspireElasticClientsElasticsearchExtensions.cs
  src/Components/Aspire.Elastic.Clients.Elasticsearch/AssemblyInfo.cs
  src/Components/Aspire.Elastic.Clients.Elasticsearch/ConfigurationSchema.json
  src/Components/Aspire.Elastic.Clients.Elasticsearch/ElasticClientsElasticsearchSettings.cs
  src/Components/Aspire.Elastic.Clients.Elasticsearch/ElasticsearchHealthCheck.cs
  src/Components/Aspire.Elastic.Clients.Elasticsearch/README.md
  src/Components/Aspire.Elastic.Clients.Elasticsearch/api/Aspire.Elastic.Clients.Elasticsearch.cs
  tests/Aspire.Elastic.Clients.Elasticsearch.Tests/Aspire.Elastic.Clients.Elasticsearch.Tests.csproj
  tests/Aspire.Elastic.Clients.Elasticsearch.Tests/AspireElasticClientExtensionsTest.cs
  tests/Aspire.Elastic.Clients.Elasticsearch.Tests/ConfigurationTests.cs
  tests/Aspire.Elastic.Clients.Elasticsearch.Tests/ConformanceTests.cs
  tests/Aspire.Elastic.Clients.Elasticsearch.Tests/ElasticClientsElasticsearchPublicApiTests.cs
  tests/Aspire.Elastic.Clients.Elasticsearch.Tests/ElasticsearchContainerFixture.cs
  tests/Aspire.Hosting.Elasticsearch.Tests/AddElasticsearchTests.cs
  tests/Aspire.Hosting.Elasticsearch.Tests/Aspire.Hosting.Elasticsearch.Tests.csproj
  tests/Aspire.Hosting.Elasticsearch.Tests/ElasticsearchFunctionalTests.cs
  tests/Aspire.Hosting.Elasticsearch.Tests/ElasticsearchPublicApiTests.cs
Labels: area-integrations

#9044 Wait for dashboard to be healthy before returning URL via RPC (revert-revert)
  src/Aspire.Hosting/Aspire.Hosting.csproj
  src/Aspire.Hosting/Backchannel/AppHostRpcTarget.cs
  src/Aspire.Hosting/Dashboard/DashboardLifecycleHook.cs
  src/Aspire.Hosting/DistributedApplicationBuilder.cs
  src/Aspire.Hosting/Health/ResourceHealthCheckService.cs
  src/Shared/KnownHealthCheckNames.cs
Labels: area-app-model, area-cli

#9081 Make ComponentTelemetryContext resilent to multiple disposes
  src/Aspire.Dashboard/Components/Pages/ComponentTelemetryContext.cs
Labels: area-dashboard

#9069 Add hidden to protocol, support in dashboard
  playground/Stress/Stress.AppHost/Program.cs
  src/Aspire.Dashboard/Components/Pages/ConsoleLogs.razor.cs
  src/Aspire.Dashboard/Components/Pages/Resources.razor.cs
  src/Aspire.Dashboard/Extensions/ResourceViewModelExtensions.cs
  src/Aspire.Dashboard/Model/ResourceGraph/ResourceGraphMapper.cs
  src/Aspire.Dashboard/Model/ResourceViewModel.cs
  src/Aspire.Dashboard/ResourceService/Partials.cs
  src/Aspire.Hosting/ApplicationModel/CustomResourceSnapshot.cs
  src/Aspire.Hosting/ConnectionStringBuilderExtensions.cs
  src/Aspire.Hosting/Dashboard/DashboardLifecycleHook.cs
  src/Aspire.Hosting/Dashboard/DashboardServiceData.cs
  src/Aspire.Hosting/Dashboard/ResourceSnapshot.cs
  src/Aspire.Hosting/Dashboard/proto/Partials.cs
  src/Aspire.Hosting/Dashboard/proto/resource_service.proto
  src/Aspire.Hosting/Dcp/ResourceSnapshotBuilder.cs
  src/Aspire.Hosting/ParameterResourceBuilderExtensions.cs
  tests/Aspire.Dashboard.Components.Tests/Pages/ResourcesTests.cs
  tests/Aspire.Hosting.Tests/Dashboard/ResourcePublisherTests.cs
  tests/Aspire.Playground.Tests/Infrastructure/DistributedApplicationExtensions.cs
  tests/Shared/DashboardModel/ModelTestHelpers.cs
Labels: area-dashboard

#9080 Drive output path from project name based on template
  src/Aspire.Cli/Commands/NewCommand.cs
  tests/Aspire.Cli.Tests/Commands/NewCommandTests.cs
Labels: area-cli

#9075 Refactor Azure Container Apps processing
  playground/AzureContainerApps/AzureContainerApps.AppHost/api.module.bicep
  playground/AzureContainerApps/AzureContainerApps.AppHost/aspire-manifest.json
  playground/AzureContainerApps/AzureContainerApps.AppHost/cache.module.bicep
  src/Aspire.Hosting.Azure.AppContainers/AzureContainerAppsInfrastructure.cs
  src/Aspire.Hosting.Azure.AppContainers/ContainerAppContext.cs
  src/Aspire.Hosting.Azure.AppContainers/ContainerAppEnvironmentContext.cs
  src/Aspire.Hosting.Azure/AzureProvisioningResourceExtensions.cs
  tests/Aspire.Hosting.Azure.Tests/AzureContainerAppsTests.cs
  tests/Aspire.Hosting.Azure.Tests/AzurePublisherTests.cs
Labels: area-integrations

#9091 Fix publishing of ConnectionStringAvailableEvent
  src/Aspire.Hosting/Orchestrator/ApplicationOrchestrator.cs
  tests/Aspire.Hosting.Tests/Orchestrator/ApplicationOrchestratorTests.cs
Labels: needs-area-label, community-contribution

#9074 Upgrade Issue-Labeler to v2.0.0
  .github/workflows/labeler-build-predictor.yml
  .github/workflows/labeler-cache-retention.yml
  .github/workflows/labeler-predict-issues.yml
  .github/workflows/labeler-predict-pulls.yml
  .github/workflows/labeler-promote.yml
  .github/workflows/labeler-train.yml
Labels: area-engineering-systems

#9090 Added initial support for app service as a compute environment
  Aspire.sln
  Directory.Packages.props
  playground/AzureAppService/.aspire/settings.json
  playground/AzureAppService/AzureAppService.ApiService/AzureAppService.ApiService.csproj
  playground/AzureAppService/AzureAppService.ApiService/Program.cs
  playground/AzureAppService/AzureAppService.ApiService/Properties/launchSettings.json
  playground/AzureAppService/AzureAppService.ApiService/appsettings.Development.json
  playground/AzureAppService/AzureAppService.ApiService/appsettings.json
  playground/AzureAppService/AzureAppService.AppHost/AzureAppService.AppHost.csproj
  playground/AzureAppService/AzureAppService.AppHost/Program.cs
  playground/AzureAppService/AzureAppService.AppHost/Properties/launchSettings.json
  playground/AzureAppService/AzureAppService.AppHost/account.module.bicep
  playground/AzureAppService/AzureAppService.AppHost/api-identity.module.bicep
  playground/AzureAppService/AzureAppService.AppHost/api-roles-account.module.bicep
  playground/AzureAppService/AzureAppService.AppHost/api-roles-storage.module.bicep
  playground/AzureAppService/AzureAppService.AppHost/api.module.bicep
  playground/AzureAppService/AzureAppService.AppHost/appsettings.Development.json
  playground/AzureAppService/AzureAppService.AppHost/appsettings.json
  playground/AzureAppService/AzureAppService.AppHost/aspire-manifest.json
  playground/AzureAppService/AzureAppService.AppHost/infra.module.bicep
  playground/AzureAppService/AzureAppService.AppHost/storage.module.bicep
  src/Aspire.Hosting.Azure.AppContainers/ContainerAppContext.cs
  src/Aspire.Hosting.Azure.AppContainers/IContainerRegistry.cs
  src/Aspire.Hosting.Azure.AppService/Aspire.Hosting.Azure.AppService.csproj
  src/Aspire.Hosting.Azure.AppService/AzureAppServiceComputeResourceExtensions.cs
  src/Aspire.Hosting.Azure.AppService/AzureAppServiceEnvironmentContext.cs
  src/Aspire.Hosting.Azure.AppService/AzureAppServiceEnvironmentExtensions.cs
  src/Aspire.Hosting.Azure.AppService/AzureAppServiceEnvironmentResource.cs
  src/Aspire.Hosting.Azure.AppService/AzureAppServiceInfrastructure.cs
  src/Aspire.Hosting.Azure.AppService/AzureAppServiceWebsiteContext.cs
  src/Aspire.Hosting.Azure.AppService/AzureAppServiceWebsiteCustomizationAnnotation.cs
  src/Aspire.Hosting.Azure/AzureProvisioningResourceExtensions.cs
  tests/Aspire.Hosting.Azure.Tests/Aspire.Hosting.Azure.Tests.csproj
  tests/Aspire.Hosting.Azure.Tests/AzureAppServiceTests.cs
  tests/Aspire.Hosting.Azure.Tests/AzureContainerAppsTests.cs
  tests/Aspire.Hosting.Azure.Tests/AzureKeyVaultTests.cs
Labels: area-integrations, azure

#9052 Follow-up telemetry updates
  src/Aspire.Dashboard/Components/Controls/ResourceDetails.razor.cs
  src/Aspire.Dashboard/Components/Pages/ComponentTelemetryContext.cs
  src/Aspire.Dashboard/Components/Pages/Metrics.razor.cs
  src/Aspire.Dashboard/Components/Pages/Resources.razor.cs
  src/Aspire.Dashboard/Components/Pages/StructuredLogs.razor.cs
  src/Aspire.Dashboard/Components/Pages/TraceDetail.razor.cs
  src/Aspire.Dashboard/Components/Pages/Traces.razor.cs
  src/Aspire.Dashboard/Model/DashboardCommandExecutor.cs
  src/Aspire.Dashboard/README.md
  src/Aspire.Dashboard/Telemetry/DashboardTelemetryService.cs
  src/Aspire.Dashboard/Telemetry/TelemetryPropertyKeys.cs
  src/Aspire.Dashboard/Telemetry/TelemetryPropertyValues.cs
  src/Shared/Model/KnownResourceCommands.cs
  src/Shared/Model/KnownResourceTypes.cs
Labels: area-dashboard

#9068 Fix localized built-in command display names and descriptions
  src/Aspire.Dashboard/Components/Controls/ResourceActions.razor
  src/Aspire.Dashboard/Components/Controls/ResourceActions.razor.cs
  src/Aspire.Dashboard/Components/Pages/ConsoleLogs.razor
  src/Aspire.Dashboard/Components/Pages/ConsoleLogs.razor.cs
  src/Aspire.Dashboard/Components/Pages/Resources.razor
  src/Aspire.Dashboard/Components/Pages/Resources.razor.cs
  src/Aspire.Dashboard/Model/DashboardCommandExecutor.cs
  src/Aspire.Dashboard/Model/ResourceMenuItems.cs
  src/Aspire.Dashboard/Model/ResourceViewModel.cs
  src/Aspire.Dashboard/ResourceService/Partials.cs
  tests/Aspire.Dashboard.Tests/Model/ResourceMenuItemsTests.cs
Labels: area-dashboard

#9088 Add an option to set DCP log file name suffix based on test name
  src/Aspire.Hosting/Dcp/DcpHost.cs
  src/Aspire.Hosting/Dcp/DcpOptions.cs
  tests/testproject/TestProject.AppHost/TestProgram.cs
Labels: area-app-model

#9099 Use normal WaitForResourceHealthyAsync in AppHostRpcTarget.
  src/Aspire.Hosting/Backchannel/AppHostRpcTarget.cs
  src/Aspire.Hosting/Dashboard/DashboardLifecycleHook.cs
  src/Aspire.Hosting/DistributedApplicationBuilder.cs
  src/Aspire.Hosting/Health/ResourceHealthCheckService.cs
  src/Aspire.Hosting/ResourceBuilderExtensions.cs
  src/Aspire.Hosting/Utils/LoggingUtils.cs
  tests/Aspire.Hosting.Tests/Dashboard/DashboardResourceTests.cs
Labels: area-cli

#9102 Wait for debugger when app host runs.
  src/Aspire.Cli/Commands/PublishCommand.cs
  src/Aspire.Cli/Commands/RootCommand.cs
  src/Aspire.Cli/Commands/RunCommand.cs
Labels: area-cli

#9108 Add support for strongly-typed ContainerPort/ContainerImage
  playground/AzureContainerApps/AzureContainerApps.AppHost/api.module.bicep
  src/Aspire.Hosting.Azure.AppContainers/ContainerAppContext.cs
  src/Aspire.Hosting.Azure.AppService/AzureAppServiceInfrastructure.cs
  src/Aspire.Hosting.Azure.AppService/AzureAppServiceWebsiteContext.cs
  src/Aspire.Hosting/ApplicationModel/ContainerImageReference.cs
  src/Aspire.Hosting/ApplicationModel/ContainerPortReference.cs
  tests/Aspire.Hosting.Azure.Tests/AzureContainerAppsTests.cs
Labels: area-deployment

#9113 Split out collectors and handle process crash before backchannel connection.
  src/Aspire.Cli/Backchannel/FailedToConnectBackchannelConnection.cs
  src/Aspire.Cli/Commands/PublishCommand.cs
  src/Aspire.Cli/Commands/RunCommand.cs
  src/Aspire.Cli/DotNetCliRunner.cs
Labels: area-cli

#9096 Implement new "default" publisher
  playground/publishers/Publishers.AppHost/.aspire/settings.json
  playground/publishers/Publishers.AppHost/Program.cs
  playground/publishers/Publishers.AppHost/appsettings.json
  src/Aspire.Hosting.Docker/DockerComposeEnvironmentExtensions.cs
  src/Aspire.Hosting.Docker/DockerComposeEnvironmentResource.cs
  src/Aspire.Hosting.Docker/DockerComposePublishingContext.cs
  src/Aspire.Hosting.Kubernetes/KubernetesEnvironmentExtensions.cs
  src/Aspire.Hosting.Kubernetes/KubernetesEnvironmentResource.cs
  src/Aspire.Hosting.Kubernetes/KubernetesPublishingContext.cs
  src/Aspire.Hosting/ApplicationModel/PublishingCallbackAnnotation.cs
  src/Aspire.Hosting/ApplicationModel/ResourceExtensions.cs
  src/Aspire.Hosting/DistributedApplicationBuilder.cs
  src/Aspire.Hosting/PublisherDistributedApplicationBuilderExtensions.cs
  src/Aspire.Hosting/Publishing/Publisher.cs
  src/Aspire.Hosting/Publishing/PublishingContext.cs
  src/Aspire.Hosting/ResourceBuilderExtensions.cs
  tests/Aspire.Hosting.Docker.Tests/DockerComposeTests.cs
  tests/Aspire.Hosting.Kubernetes.Tests/KubernetesEnvironmentResourceTests.cs
  tests/Aspire.Hosting.Tests/Backchannel/AppHostBackchannelTests.cs
  tests/Aspire.Hosting.Tests/PublishingTests.cs
  tests/Aspire.Hosting.Tests/ResourceExtensionsTests.cs
  tests/Aspire.Hosting.Tests/Utils/TestDistributedApplicationBuilder.cs
Labels: area-app-model

#9115 [tests] Unquarantine some tests
  tests/Aspire.Hosting.MongoDB.Tests/MongoDbFunctionalTests.cs
  tests/Aspire.Hosting.Tests/DistributedApplicationTests.cs
Labels: needs-area-label

#9119 Delete k8s and compose publishers
  src/Aspire.Hosting.Docker/DockerComposeEnvironmentResource.cs
  src/Aspire.Hosting.Docker/DockerComposePublisher.cs
  src/Aspire.Hosting.Docker/DockerComposePublisherExtensions.cs
  src/Aspire.Hosting.Docker/DockerComposePublisherOptions.cs
  src/Aspire.Hosting.Docker/DockerComposePublishingContext.cs
  src/Aspire.Hosting.Kubernetes/KubernetesEnvironmentResource.cs
  src/Aspire.Hosting.Kubernetes/KubernetesPublisher.cs
  src/Aspire.Hosting.Kubernetes/KubernetesPublisherExtensions.cs
  src/Aspire.Hosting.Kubernetes/KubernetesPublisherOptions.cs
  src/Aspire.Hosting.Kubernetes/KubernetesPublishingContext.cs
  src/Aspire.Hosting/ApplicationModel/ResourceExtensions.cs
  tests/Aspire.Hosting.Azure.Tests/Aspire.Hosting.Azure.Tests.csproj
  tests/Aspire.Hosting.Docker.Tests/Aspire.Hosting.Docker.Tests.csproj
  tests/Aspire.Hosting.Docker.Tests/DockerComposePublisherTests.cs
  tests/Aspire.Hosting.Docker.Tests/DockerComposeTests.cs
  tests/Aspire.Hosting.Docker.Tests/EnvVarEscaperTests.cs
  tests/Aspire.Hosting.Docker.Tests/Snapshots/DockerComposePublisherTests.DockerComposeAppliesServiceCustomizations.verified.yaml
  tests/Aspire.Hosting.Docker.Tests/Snapshots/DockerComposePublisherTests.DockerComposeCorrectlyEmitsPortMappings.verified.yaml
  tests/Aspire.Hosting.Docker.Tests/Snapshots/DockerComposePublisherTests.PublishAsync_GeneratesValidDockerComposeFile.verified.env
  tests/Aspire.Hosting.Docker.Tests/Snapshots/DockerComposePublisherTests.PublishAsync_GeneratesValidDockerComposeFile.verified.yaml
  tests/Aspire.Hosting.Kubernetes.Tests/Aspire.Hosting.Kubernetes.Tests.csproj
  tests/Aspire.Hosting.Kubernetes.Tests/ExpectedValues.cs
  tests/Aspire.Hosting.Kubernetes.Tests/KubernetesEnvironmentResourceTests.cs
  tests/Aspire.Hosting.Kubernetes.Tests/KubernetesPublisherFixture.cs
  tests/Aspire.Hosting.Kubernetes.Tests/KubernetesPublisherTests.PublishAppliesServiceCustomizations.verified.yaml
  tests/Aspire.Hosting.Kubernetes.Tests/KubernetesPublisherTests.cs
  tests/Aspire.Hosting.Kubernetes.Tests/Snapshots/KubernetesEnvironmentResourceTests.PublishingDockerComposeEnviromentPublishesFile#00.verified.yaml
  tests/Aspire.Hosting.Kubernetes.Tests/Snapshots/KubernetesEnvironmentResourceTests.PublishingDockerComposeEnviromentPublishesFile#01.verified.yaml
  tests/Aspire.Hosting.Kubernetes.Tests/Snapshots/KubernetesEnvironmentResourceTests.PublishingDockerComposeEnviromentPublishesFile#02.verified.yaml
  tests/Aspire.Hosting.Kubernetes.Tests/Snapshots/KubernetesPublisherTests.PublishAsync_GeneratesValidHelmChart#00.verified.yaml
  tests/Aspire.Hosting.Kubernetes.Tests/Snapshots/KubernetesPublisherTests.PublishAsync_GeneratesValidHelmChart#01.verified.yaml
  tests/Aspire.Hosting.Kubernetes.Tests/Snapshots/KubernetesPublisherTests.PublishAsync_GeneratesValidHelmChart#02.verified.yaml
  tests/Aspire.Hosting.Kubernetes.Tests/Snapshots/KubernetesPublisherTests.PublishAsync_GeneratesValidHelmChart#03.verified.yaml
  tests/Aspire.Hosting.Kubernetes.Tests/Snapshots/KubernetesPublisherTests.PublishAsync_GeneratesValidHelmChart#04.verified.yaml
  tests/Aspire.Hosting.Kubernetes.Tests/Snapshots/KubernetesPublisherTests.PublishAsync_GeneratesValidHelmChart#05.verified.yaml
  tests/Aspire.Hosting.Kubernetes.Tests/Snapshots/KubernetesPublisherTests.PublishAsync_GeneratesValidHelmChart#06.verified.yaml
  tests/Aspire.Hosting.Kubernetes.Tests/Snapshots/KubernetesPublisherTests.PublishAsync_GeneratesValidHelmChart#07.verified.yaml
  tests/Shared/TestModuleInitializer.cs
  tests/Shared/VerifyExtensions.cs
  tests/helix/send-to-helix-inner.proj
Labels: area-deployment

#8408 Add CertificateClient and KeyClient support to Aspire.Azure.Security.KeyVault
  Directory.Packages.props
  src/Components/Aspire.Azure.Security.KeyVault/AbstractAzureKeyVaultComponent.cs
  src/Components/Aspire.Azure.Security.KeyVault/Aspire.Azure.Security.KeyVault.csproj
  src/Components/Aspire.Azure.Security.KeyVault/AspireKeyVaultExtensions.cs
  src/Components/Aspire.Azure.Security.KeyVault/AzureKeyVaultCertificatesComponent.cs
  src/Components/Aspire.Azure.Security.KeyVault/AzureKeyVaultKeysComponent.cs
  src/Components/Aspire.Azure.Security.KeyVault/AzureKeyVaultSecretsComponent.cs
  src/Components/Aspire.Azure.Security.KeyVault/README.md
  tests/Aspire.Azure.Security.KeyVault.Tests/AspireKeyVaultExtensionsTests.cs
  tests/Aspire.Azure.Security.KeyVault.Tests/CertificateClientConformanceTests.cs
  tests/Aspire.Azure.Security.KeyVault.Tests/ConformanceConstants.cs
  tests/Aspire.Azure.Security.KeyVault.Tests/KeyClientConformanceTests.cs
  tests/Aspire.Azure.Security.KeyVault.Tests/SecretClientConformanceTests.cs
Labels: area-integrations, community-contribution

#9082 Update OTEL in templates
  eng/Versions.props
Labels: area-templates

#9129 Update Baseline package validation to 9.2.0
  src/Aspire.Hosting.Azure/CompatibilitySuppressions.xml
  src/Directory.Build.props
Labels: area-codeflow

#9123 Make URLs available on snapshot of unstarted and waiting resources
  src/Aspire.Hosting/Dcp/DcpExecutor.cs
  src/Aspire.Hosting/Orchestrator/ApplicationOrchestrator.cs
  tests/Aspire.Hosting.Tests/DistributedApplicationTests.cs
Labels: area-app-model

#9130 Add support for creating and using user-assigned identities
  src/Aspire.Hosting.Azure/AppIdentityResource.cs
  src/Aspire.Hosting.Azure/AzureResourcePreparer.cs
  src/Aspire.Hosting.Azure/AzureUserAssignedIdentityExtensions.cs
  src/Aspire.Hosting.Azure/AzureUserAssignedIdentityResource.cs
  tests/Aspire.Hosting.Azure.Tests/AzureUserAssignedIdentityTests.cs
  tests/Aspire.Hosting.Azure.Tests/Snapshots/AzureUserAssignedIdentityTests.AddAzureUserAssignedIdentity_GeneratesExpectedResourcesAndBicep.verified.bicep
  tests/Aspire.Hosting.Azure.Tests/Snapshots/AzureUserAssignedIdentityTests.AddAzureUserAssignedIdentity_PublishAsExisting_Works.verified.bicep
  tests/Aspire.Hosting.Azure.Tests/Snapshots/AzureUserAssignedIdentityTests.AddAzureUserAssignedIdentity_WithRoleAssignments_Works#00.verified.bicep
  tests/Aspire.Hosting.Azure.Tests/Snapshots/AzureUserAssignedIdentityTests.AddAzureUserAssignedIdentity_WithRoleAssignments_Works#01.verified.bicep
  tests/Aspire.Hosting.Azure.Tests/Snapshots/AzureUserAssignedIdentityTests.AddAzureUserAssignedIdentity_WithRoleAssignments_Works#02.verified.bicep
Labels: area-integrations

#9008 AzureStorage auto create blob containers
  .github/copilot-instructions.md
  Aspire.sln
  Directory.Build.props
  playground/AzureFunctionsEndToEnd/AzureFunctionsEndToEnd.AppHost/Program.cs
  playground/AzureFunctionsEndToEnd/AzureFunctionsEndToEnd.Functions/MyAzureBlobTrigger.cs
  playground/AzureFunctionsEndToEnd/AzureFunctionsEndToEnd.Functions/MyHttpTrigger.cs
  playground/AzureFunctionsEndToEnd/AzureFunctionsEndToEnd.Functions/Program.cs
  playground/AzureStorageEndToEnd/AzureStorageEndToEnd.ApiService/Program.cs
  playground/AzureStorageEndToEnd/AzureStorageEndToEnd.AppHost/Program.cs
  src/Aspire.Hosting.Azure.Storage/AzureBlobStorageContainerResource.cs
  src/Aspire.Hosting.Azure.Storage/AzureBlobStorageResource.cs
  src/Aspire.Hosting.Azure.Storage/AzureStorageEmulatorConnectionString.cs
  src/Aspire.Hosting.Azure.Storage/AzureStorageExtensions.cs
  src/Aspire.Hosting.Azure.Storage/AzureStorageResource.cs
  src/Components/Aspire.Azure.Storage.Blobs/AspireBlobStorageExtensions.BlobStorageComponent.cs
  src/Components/Aspire.Azure.Storage.Blobs/AspireBlobStorageExtensions.BlobStorageContainerComponent.AzureBlobStorageContainerHealthCheck.cs
  src/Components/Aspire.Azure.Storage.Blobs/AspireBlobStorageExtensions.BlobStorageContainerComponent.cs
  src/Components/Aspire.Azure.Storage.Blobs/AspireBlobStorageExtensions.cs
  src/Components/Aspire.Azure.Storage.Blobs/AssemblyInfo.cs
  src/Components/Aspire.Azure.Storage.Blobs/AzureBlobStorageContainerSettings.cs
  src/Components/Aspire.Azure.Storage.Blobs/AzureStorageBlobsSettings.cs
  src/Components/Aspire.Microsoft.Azure.Cosmos/AspireMicrosoftAzureCosmosExtensions.cs
  tests/Aspire.Azure.Storage.Blobs.Tests/AzureBlobStorageContainerSettingsTests.cs
  tests/Aspire.Azure.Storage.Blobs.Tests/ConformanceTests.cs
  tests/Aspire.Hosting.Azure.Tests/AzureStorageEmulatorFunctionalTests.cs
  tests/Aspire.Hosting.Azure.Tests/AzureStorageExtensionsTests.cs
  tests/Aspire.Hosting.Azure.Tests/Snapshots/AzureStorageExtensionsTests.ResourceNamesBicepValid.verified.bicep
  tests/Aspire.Playground.Tests/ProjectSpecificTests.cs
Labels: area-integrations

#9114 Disable launch profiles for publish mode and inspect mode runs.
  src/Aspire.Cli/Commands/PublishCommand.cs
  src/Aspire.Cli/DotNetCliRunner.cs
  tests/Aspire.Cli.Tests/Commands/PublishCommandTests.cs
  tests/Aspire.Cli.Tests/DotNet/DotNetCliRunnerTests.cs
Labels: area-cli

#9133 Make WithHttpHealthCheck work like WithHttpCommand
  playground/TestShop/TestShop.AppHost/Program.cs
  src/Aspire.Hosting/ResourceBuilderExtensions.cs
  src/Aspire.ProjectTemplates/templates/aspire-starter/9.3/Aspire-StarterApplication.1.AppHost/AppHost.cs
  tests/Aspire.Hosting.Tests/HealthCheckTests.cs
  tests/Aspire.Hosting.Tests/WithHttpCommandTests.cs
Labels: area-app-model

#9131 Address feedback on Azure Container Registry
  src/Aspire.Hosting.Azure.AppContainers/AzureContainerAppsInfrastructure.cs
  src/Aspire.Hosting.Azure.ContainerRegistry/Aspire.Hosting.Azure.ContainerRegistry.csproj
  src/Aspire.Hosting.Azure.ContainerRegistry/AzureContainerRegistryResource.cs
  src/Aspire.Hosting/ApplicationModel/ContainerRegistryReferenceAnnotation.cs
Labels: area-integrations

#9134 Update AzureUserAssignedIdentityTests.cs
  tests/Aspire.Hosting.Azure.Tests/AzureUserAssignedIdentityTests.cs
Labels: area-integrations

#9140 Quarantine `VerifyAzureStorageEmulator_blobcontainer_auto_created`
  tests/Aspire.Hosting.Azure.Tests/AzureStorageEmulatorFunctionalTests.cs
Labels: area-integrations

#9138 Reinstate warnings
  Directory.Build.props
  src/Components/Aspire.Azure.Storage.Blobs/AzureBlobStorageContainerSettings.cs
  tests/Aspire.Azure.Storage.Blobs.Tests/AzureBlobStorageContainerSettingsTests.cs
Labels: area-integrations

#9136 Improve header button style
  src/Aspire.Dashboard/Components/Layout/MainLayout.razor
  src/Aspire.Dashboard/Components/Layout/MainLayout.razor.css
Labels: area-dashboard

#9150 Add a CTRL-C message to row below table.
  src/Aspire.Cli/Commands/RunCommand.cs
Labels: area-cli

#9148 Add AzureEnvironmentResource for publishing Azure resources
  src/Aspire.Hosting.Azure/AzureEnvironmentResource.cs
  src/Aspire.Hosting.Azure/AzureEnvironmentResourceExtensions.cs
  src/Aspire.Hosting.Azure/AzurePublisher.cs
  src/Aspire.Hosting.Azure/AzurePublisherExtensions.cs
  src/Aspire.Hosting.Azure/AzurePublishingContext.cs
  src/Aspire.Hosting.Azure/CompatibilitySuppressions.xml
  src/Aspire.Hosting.Azure/Provisioning/AzureProvisionerExtensions.cs
  src/Aspire.Hosting/ParameterResourceBuilderExtensions.cs
  tests/Aspire.Hosting.Azure.Tests/AzureEnvironmentResourceExtensionsTests.cs
  tests/Aspire.Hosting.Azure.Tests/AzureEnvironmentResourceTests.cs
  tests/Aspire.Hosting.Azure.Tests/AzurePublisherTests.cs
  tests/Aspire.Hosting.Azure.Tests/AzureUserAssignedIdentityTests.cs
  tests/Aspire.Hosting.Azure.Tests/Snapshots/AzureEnvironmentResourceTests.AzurePublishingContext_CapturesParametersAndOutputsCorrectly_WithSnapshot#00.verified.bicep
  tests/Aspire.Hosting.Azure.Tests/Snapshots/AzureEnvironmentResourceTests.AzurePublishingContext_CapturesParametersAndOutputsCorrectly_WithSnapshot#01.verified.bicep
  tests/Aspire.Hosting.Azure.Tests/Snapshots/AzureEnvironmentResourceTests.PublishAsync_GeneratesMainBicep_WithSnapshots.verified.bicep
  tests/Aspire.Hosting.Azure.Tests/Snapshots/AzureEnvironmentResourceTests.WhenUsedWithAzureContainerAppsEnvironment_GeneratesProperBicep#00.verified.bicep
  tests/Aspire.Hosting.Azure.Tests/Snapshots/AzureEnvironmentResourceTests.WhenUsedWithAzureContainerAppsEnvironment_GeneratesProperBicep#01.verified.bicep
  tests/Aspire.Hosting.Azure.Tests/Snapshots/AzureEnvironmentResourceTests.WhenUsedWithAzureContainerAppsEnvironment_RespectsStronglyTypedProperties.verified.bicep
Labels: area-integrations

#9154 Fix access denied error when searching Application Data for apphost project.
  src/Aspire.Cli/Projects/ProjectLocator.cs
Labels: area-cli

#9092 Use IsHidden instead of KnownResourceStates.Hidden
  src/Aspire.Hosting/ApplicationModel/ResourceNotificationService.cs
  src/Aspire.Hosting/ConnectionStringBuilderExtensions.cs
  src/Aspire.Hosting/Dcp/ResourceSnapshotBuilder.cs
  src/Aspire.Hosting/ParameterResourceBuilderExtensions.cs
  tests/Aspire.Hosting.Tests/AddParameterTests.cs
  tests/Aspire.Hosting.Tests/Dashboard/DashboardResourceTests.cs
  tests/Aspire.Playground.Tests/Infrastructure/DistributedApplicationExtensions.cs
Labels: area-app-model

#9170 Revert "Use IsHidden instead of KnownResourceStates.Hidden"
  src/Aspire.Hosting/ApplicationModel/ResourceNotificationService.cs
  src/Aspire.Hosting/ConnectionStringBuilderExtensions.cs
  src/Aspire.Hosting/Dcp/ResourceSnapshotBuilder.cs
  src/Aspire.Hosting/ParameterResourceBuilderExtensions.cs
  tests/Aspire.Hosting.Tests/AddParameterTests.cs
  tests/Aspire.Hosting.Tests/Dashboard/DashboardResourceTests.cs
  tests/Aspire.Playground.Tests/Infrastructure/DistributedApplicationExtensions.cs
Labels: area-app-model

#9077 Fix tests
  .github/workflows/tests-runner.yml
  eng/TestRunsheetBuilder/TestRunsheetBuilder.targets
  tests/Aspire.Playground.Tests/Aspire.Playground.Tests.csproj
Labels: area-engineering-systems

#9174 Address follow-ups on AzureEnvironmentResource
  src/Aspire.Hosting.Azure/AzureEnvironmentResource.cs
  src/Aspire.Hosting.Azure/AzureEnvironmentResourceExtensions.cs
  src/Aspire.Hosting.Azure/AzurePublishingContext.cs
  tests/Aspire.Hosting.Azure.Tests/Snapshots/AzureEnvironmentResourceTests.AzurePublishingContext_CapturesParametersAndOutputsCorrectly_WithSnapshot#00.verified.bicep
  tests/Aspire.Hosting.Azure.Tests/Snapshots/AzureEnvironmentResourceTests.PublishAsync_GeneratesMainBicep_WithSnapshots.verified.bicep
  tests/Aspire.Hosting.Azure.Tests/Snapshots/AzureEnvironmentResourceTests.WhenUsedWithAzureContainerAppsEnvironment_GeneratesProperBicep#00.verified.bicep
  tests/Aspire.Hosting.Azure.Tests/Snapshots/AzureEnvironmentResourceTests.WhenUsedWithAzureContainerAppsEnvironment_RespectsStronglyTypedProperties.verified.bicep
Labels: area-integrations

#9161 Don't clobber env files
  src/Aspire.Hosting.Docker/DockerComposePublishingContext.cs
  src/Aspire.Hosting.Docker/EnvFile.cs
  tests/Aspire.Hosting.Docker.Tests/DockerComposePublisherTests.cs
  tests/Aspire.Hosting.Docker.Tests/Snapshots/DockerComposePublisherTests.DockerComposeAppendsNewKeysToEnvFileOnPublish#00.verified.env
  tests/Aspire.Hosting.Docker.Tests/Snapshots/DockerComposePublisherTests.DockerComposeAppendsNewKeysToEnvFileOnPublish#01.verified.env
  tests/Aspire.Hosting.Docker.Tests/Snapshots/DockerComposePublisherTests.DockerComposeDoesNotOverwriteEnvFileOnPublish#00.verified.env
  tests/Aspire.Hosting.Docker.Tests/Snapshots/DockerComposePublisherTests.DockerComposeDoesNotOverwriteEnvFileOnPublish#01.verified.env
Labels: area-integrations

#9181 Mark AzureEnvironmentResource type as experimental
  src/Aspire.Hosting.Azure/AzureEnvironmentResource.cs
  tests/Aspire.Hosting.Azure.Tests/AzureUserAssignedIdentityTests.cs
Labels: area-integrations

#9183 Mark AzurePublishingContext.WriteModelAsync as public
  src/Aspire.Hosting.Azure/AzurePublishingContext.cs
Labels: needs-area-label

#9182 Add tooltip to usage telemetry link
  src/Aspire.Dashboard/Components/Dialogs/SettingsDialog.razor
  src/Aspire.Dashboard/Resources/Dialogs.Designer.cs
  src/Aspire.Dashboard/Resources/Dialogs.resx
  src/Aspire.Dashboard/Resources/xlf/Dialogs.cs.xlf
  src/Aspire.Dashboard/Resources/xlf/Dialogs.de.xlf
  src/Aspire.Dashboard/Resources/xlf/Dialogs.es.xlf
  src/Aspire.Dashboard/Resources/xlf/Dialogs.fr.xlf
  src/Aspire.Dashboard/Resources/xlf/Dialogs.it.xlf
  src/Aspire.Dashboard/Resources/xlf/Dialogs.ja.xlf
  src/Aspire.Dashboard/Resources/xlf/Dialogs.ko.xlf
  src/Aspire.Dashboard/Resources/xlf/Dialogs.pl.xlf
  src/Aspire.Dashboard/Resources/xlf/Dialogs.pt-BR.xlf
  src/Aspire.Dashboard/Resources/xlf/Dialogs.ru.xlf
  src/Aspire.Dashboard/Resources/xlf/Dialogs.tr.xlf
  src/Aspire.Dashboard/Resources/xlf/Dialogs.zh-Hans.xlf
  src/Aspire.Dashboard/Resources/xlf/Dialogs.zh-Hant.xlf
Labels: area-dashboard

#9172 Quarantine ProjectSpecificTests.WithDockerfileTest
  tests/Aspire.Playground.Tests/ProjectSpecificTests.cs
Labels: area-integrations

#9147 Introduce InitializeResourceEvent & fix parent/child & URLs for custom resources
  playground/CustomResources/CustomResources.AppHost/Program.cs
  playground/CustomResources/CustomResources.AppHost/TalkingClockResource.cs
  src/Aspire.Hosting.Azure/Aspire.Hosting.Azure.csproj
  src/Aspire.Hosting.Azure/AzureResourcePreparer.cs
  src/Aspire.Hosting.Azure/Provisioning/Provisioners/AzureProvisioner.cs
  src/Aspire.Hosting/ApplicationModel/InitializeResourceEvent.cs
  src/Aspire.Hosting/ApplicationModel/ResourceEndpointsAllocatedEvent.cs
  src/Aspire.Hosting/Dcp/DcpExecutor.cs
  src/Aspire.Hosting/Orchestrator/ApplicationOrchestrator.cs
  tests/Aspire.Hosting.Azure.Tests/Aspire.Hosting.Azure.Tests.csproj
  tests/Aspire.Hosting.Azure.Tests/AzureManifestUtils.cs
  tests/Aspire.Hosting.Tests/Orchestrator/ApplicationOrchestratorTests.cs
Labels: area-app-model

#9157 Validate project name and fix pathing for project templates.
  src/Aspire.Cli/Commands/NewCommand.cs
Labels: area-cli

#9192 Update README for Docker and Kubernetes usage examples
  src/Aspire.Hosting.Docker/README.md
  src/Aspire.Hosting.Kubernetes/README.md
Labels: needs-area-label

#9191 Add health endpoint to dashboard and call from app host
  src/Aspire.Dashboard/DashboardEndpointsBuilder.cs
  src/Aspire.Dashboard/DashboardWebApplication.cs
  src/Aspire.Dashboard/Utils/DashboardUrls.cs
  src/Aspire.Hosting/Dashboard/DashboardLifecycleHook.cs
  src/Aspire.Hosting/DistributedApplicationBuilder.cs
  src/Shared/KnownHealthCheckNames.cs
  tests/Aspire.Dashboard.Tests/Integration/HealthTests.cs
Labels: area-dashboard, area-app-model

#9149 Fixes to life cycle commands state
  src/Aspire.Hosting/ApplicationModel/CommandsConfigurationExtensions.cs
  tests/Aspire.Hosting.Tests/ResourceCommandAnnotationTests.cs
Labels: area-app-model

#9187 Add method to emitting env placeholders
  src/Aspire.Hosting.Docker/DockerComposeEnvironmentContext.cs
  src/Aspire.Hosting.Docker/DockerComposeEnvironmentResource.cs
  src/Aspire.Hosting.Docker/DockerComposePublishingContext.cs
  src/Aspire.Hosting.Docker/DockerComposeServiceExtensions.cs
  src/Aspire.Hosting.Docker/DockerComposeServiceResource.cs
  src/Aspire.Hosting.Docker/DockerComposeServiceResourceExtensions.cs
  tests/Aspire.Hosting.Docker.Tests/DockerComposePublisherTests.cs
  tests/Aspire.Hosting.Docker.Tests/Snapshots/DockerComposePublisherTests.DockerComposeAppliesServiceCustomizations.verified.env
  tests/Aspire.Hosting.Docker.Tests/Snapshots/DockerComposePublisherTests.DockerComposeAppliesServiceCustomizations.verified.yaml
Labels: area-integrations

#9200 Explicitly set Docker as test runtime to avoid issues with docker info
  .github/workflows/run-tests.yml
  eng/pipelines/templates/BuildAndTest.yml
  tests/helix/send-to-helix-inner.proj
Labels: needs-area-label

#9204 Update obsolete message
  src/Aspire.Hosting/ApplicationModel/CustomResourceSnapshot.cs
Labels: needs-area-label

#9179 Update diagnostic URLs
  src/Aspire.AppHost.Sdk/SDK/Sdk.in.targets
  src/Aspire.Hosting.Analyzers/AppHostAnalyzer.Diagnostics.cs
  src/Aspire.Hosting.AppHost/build/Aspire.Hosting.AppHost.in.targets
  src/Aspire.Hosting.Azure.AppContainers/ContainerAppExtensions.cs
  src/Aspire.Hosting.Azure.CosmosDB/AzureCosmosDBExtensions.cs
  src/Aspire.Hosting.Azure/AzureEnvironmentResourceExtensions.cs
  src/Aspire.Hosting.Azure/AzurePublisherOptions.cs
  src/Aspire.Hosting.Azure/AzurePublishingContext.cs
  src/Aspire.Hosting.Azure/IAzureContainerRegistry.cs
  src/Aspire.Hosting.Python/AssemblyInfo.cs
  src/Aspire.Hosting/ApplicationModel/ComputeEnvironmentAnnotation.cs
  src/Aspire.Hosting/ApplicationModel/DeploymentTargetAnnotation.cs
  src/Aspire.Hosting/ApplicationModel/IComputeEnvironmentResource.cs
  src/Aspire.Hosting/ApplicationModel/IComputeResource.cs
  src/Aspire.Hosting/ApplicationModel/IContainerRegistry.cs
  src/Aspire.Hosting/ApplicationModel/ProxySupportAnnotation.cs
  src/Aspire.Hosting/ContainerResourceBuilderExtensions.cs
  src/Aspire.Hosting/PublisherDistributedApplicationBuilderExtensions.cs
  src/Aspire.Hosting/Publishing/NullPublishingActivityProgressReporter.cs
  src/Aspire.Hosting/Publishing/PublishingActivityProgressReporter.cs
  src/Aspire.Hosting/Publishing/ResourceContainerImageBuilder.cs
  src/Aspire.Hosting/ResourceBuilderExtensions.cs
  tests/Aspire.Hosting.Azure.Tests/PublicApiTests/AppContainersPublicApiTests.cs
  tests/Aspire.Hosting.Azure.Tests/PublicApiTests/CosmosDBPublicApiTests.cs
Labels: area-app-model

#9206 Fix template aspire version selection
  src/Aspire.ProjectTemplates/templates/aspire-apphost/.template.config/template.json
  src/Aspire.ProjectTemplates/templates/aspire-empty/.template.config/template.json
  src/Aspire.ProjectTemplates/templates/aspire-mstest/.template.config/template.json
  src/Aspire.ProjectTemplates/templates/aspire-nunit/.template.config/template.json
  src/Aspire.ProjectTemplates/templates/aspire-servicedefaults/.template.config/template.json
  src/Aspire.ProjectTemplates/templates/aspire-starter/.template.config/template.json
  src/Aspire.ProjectTemplates/templates/aspire-xunit/.template.config/template.json
Labels: area-templates

#9178 [CI] Github actions rolling builds
  .github/workflows/tests.yml
Labels: area-engineering-systems

#9175 [CI] Add PR validation on macOS
  .github/actions/enumerate-tests/action.yml
  .github/workflows/run-tests.yml
  .github/workflows/tests-outerloop.yml
  .github/workflows/tests.yml
  eng/QuarantinedTestRunsheetBuilder/QuarantinedTestRunsheetBuilder.targets
  eng/TestRunsheetBuilder/TestRunsheetBuilder.targets
  eng/Testing.props
  eng/Testing.targets
  tests/Aspire.Dashboard.Tests/FormatHelpersTests.cs
  tests/Aspire.Dashboard.Tests/Integration/Playwright/AppBarTests.cs
  tests/Aspire.EndToEnd.Tests/Aspire.EndToEnd.Tests.csproj
  tests/Aspire.Playground.Tests/Aspire.Playground.Tests.csproj
  tests/Aspire.Templates.Tests/BuildAndRunTemplateTests.cs
  tests/Aspire.TestUtilities/PlatformDetection.cs
  tests/Aspire.TestUtilities/RequiresDockerAttribute.cs
  tests/Aspire.TestUtilities/RequiresSSLCertificateAttribute.cs
  tests/Directory.Build.targets
Labels: area-engineering-systems

#9199 Revert "update descriptions (#8907)"
  src/Aspire.ProjectTemplates/templates/aspire-apphost/.template.config/localize/templatestrings.en.json
  src/Aspire.ProjectTemplates/templates/aspire-apphost/.template.config/template.json
  src/Aspire.ProjectTemplates/templates/aspire-empty/.template.config/localize/templatestrings.en.json
  src/Aspire.ProjectTemplates/templates/aspire-empty/.template.config/template.json
  src/Aspire.ProjectTemplates/templates/aspire-mstest/.template.config/localize/templatestrings.en.json
  src/Aspire.ProjectTemplates/templates/aspire-mstest/.template.config/template.json
  src/Aspire.ProjectTemplates/templates/aspire-nunit/.template.config/localize/templatestrings.en.json
  src/Aspire.ProjectTemplates/templates/aspire-nunit/.template.config/template.json
  src/Aspire.ProjectTemplates/templates/aspire-servicedefaults/.template.config/localize/templatestrings.en.json
  src/Aspire.ProjectTemplates/templates/aspire-servicedefaults/.template.config/template.json
  src/Aspire.ProjectTemplates/templates/aspire-starter/.template.config/localize/templatestrings.en.json
  src/Aspire.ProjectTemplates/templates/aspire-starter/.template.config/template.json
  src/Aspire.ProjectTemplates/templates/aspire-xunit/.template.config/localize/templatestrings.en.json
  src/Aspire.ProjectTemplates/templates/aspire-xunit/.template.config/template.json
Labels: area-templates

#9208 Revert "[CI] Add PR validation on macOS (#9175)"
  .github/actions/enumerate-tests/action.yml
  .github/workflows/run-tests.yml
  .github/workflows/tests-outerloop.yml
  .github/workflows/tests.yml
  eng/QuarantinedTestRunsheetBuilder/QuarantinedTestRunsheetBuilder.targets
  eng/TestRunsheetBuilder/TestRunsheetBuilder.targets
  eng/Testing.props
  eng/Testing.targets
  tests/Aspire.Dashboard.Tests/FormatHelpersTests.cs
  tests/Aspire.Dashboard.Tests/Integration/Playwright/AppBarTests.cs
  tests/Aspire.EndToEnd.Tests/Aspire.EndToEnd.Tests.csproj
  tests/Aspire.Playground.Tests/Aspire.Playground.Tests.csproj
  tests/Aspire.Templates.Tests/BuildAndRunTemplateTests.cs
  tests/Aspire.TestUtilities/PlatformDetection.cs
  tests/Aspire.TestUtilities/RequiresDockerAttribute.cs
  tests/Aspire.TestUtilities/RequiresSSLCertificateAttribute.cs
  tests/Directory.Build.targets
Labels: area-engineering-systems

#9209 Add documentation to clarify use of executables in working directory.
  src/Aspire.Hosting/ApplicationModel/ExecutableResource.cs
  src/Aspire.Hosting/ExecutableResourceBuilderExtensions.cs
Labels: area-app-model, community-contribution

#9195 Rename AddAppServiceEnvironment to AddAzureAppServiceEnvironment
  playground/AzureAppService/AzureAppService.AppHost/Program.cs
  src/Aspire.Hosting.Azure.AppService/AzureAppServiceEnvironmentExtensions.cs
  tests/Aspire.Hosting.Azure.Tests/AzureAppServiceTests.cs
Labels: area-integrations

#8887 Make it easier to choose Azure SQL SKU
  src/Aspire.Hosting.Azure.Sql/AzureSqlDatabaseResource.cs
  src/Aspire.Hosting.Azure.Sql/AzureSqlExtensions.cs
  src/Aspire.Hosting.Azure.Sql/AzureSqlServerResource.cs
  src/Aspire.Hosting.Azure.Sql/README.md
  tests/Aspire.Hosting.Azure.Tests/AzureContainerAppsTests.cs
  tests/Aspire.Hosting.Azure.Tests/AzureResourceOptionsTests.cs
  tests/Aspire.Hosting.Azure.Tests/AzureSqlExtensionsTests.cs
Labels: area-integrations, community-contribution

#9215 Delete src/Aspire.Hosting.Azure/AzurePublisherOptions.cs
  src/Aspire.Hosting.Azure/AzurePublisherOptions.cs
  src/Aspire.Hosting.Azure/CompatibilitySuppressions.xml
Labels: area-integrations

#9219 Fix race causing `ResourceNotificationService.GetAllAsync` to fail
  src/Aspire.Hosting/ApplicationModel/ResourceLoggerService.cs
  tests/Aspire.Hosting.Tests/ResourceLoggerServiceTests.cs
Labels: area-dashboard

#9207 Add pause warning to metrics
  src/Aspire.Dashboard/Components/Controls/Chart/ChartContainer.razor
  src/Aspire.Dashboard/Components/Controls/Chart/ChartContainer.razor.cs
  src/Aspire.Dashboard/Components/Controls/PauseWarning.razor
  src/Aspire.Dashboard/Components/Controls/TotalItemsFooter.razor
  src/Aspire.Dashboard/Components/Pages/Metrics.razor
  src/Aspire.Dashboard/Components/Pages/Metrics.razor.cs
  src/Aspire.Dashboard/Components/Pages/Metrics.razor.css
  src/Aspire.Dashboard/Components/Pages/Traces.razor.cs
  src/Aspire.Dashboard/Resources/ControlsStrings.Designer.cs
  src/Aspire.Dashboard/Resources/ControlsStrings.resx
  src/Aspire.Dashboard/Resources/Metrics.Designer.cs
  src/Aspire.Dashboard/Resources/Metrics.resx
  src/Aspire.Dashboard/Resources/xlf/ControlsStrings.cs.xlf
  src/Aspire.Dashboard/Resources/xlf/ControlsStrings.de.xlf
  src/Aspire.Dashboard/Resources/xlf/ControlsStrings.es.xlf
  src/Aspire.Dashboard/Resources/xlf/ControlsStrings.fr.xlf
  src/Aspire.Dashboard/Resources/xlf/ControlsStrings.it.xlf
  src/Aspire.Dashboard/Resources/xlf/ControlsStrings.ja.xlf
  src/Aspire.Dashboard/Resources/xlf/ControlsStrings.ko.xlf
  src/Aspire.Dashboard/Resources/xlf/ControlsStrings.pl.xlf
  src/Aspire.Dashboard/Resources/xlf/ControlsStrings.pt-BR.xlf
  src/Aspire.Dashboard/Resources/xlf/ControlsStrings.ru.xlf
  src/Aspire.Dashboard/Resources/xlf/ControlsStrings.tr.xlf
  src/Aspire.Dashboard/Resources/xlf/ControlsStrings.zh-Hans.xlf
  src/Aspire.Dashboard/Resources/xlf/ControlsStrings.zh-Hant.xlf
  src/Aspire.Dashboard/Resources/xlf/Metrics.cs.xlf
  src/Aspire.Dashboard/Resources/xlf/Metrics.de.xlf
  src/Aspire.Dashboard/Resources/xlf/Metrics.es.xlf
  src/Aspire.Dashboard/Resources/xlf/Metrics.fr.xlf
  src/Aspire.Dashboard/Resources/xlf/Metrics.it.xlf
  src/Aspire.Dashboard/Resources/xlf/Metrics.ja.xlf
  src/Aspire.Dashboard/Resources/xlf/Metrics.ko.xlf
  src/Aspire.Dashboard/Resources/xlf/Metrics.pl.xlf
  src/Aspire.Dashboard/Resources/xlf/Metrics.pt-BR.xlf
  src/Aspire.Dashboard/Resources/xlf/Metrics.ru.xlf
  src/Aspire.Dashboard/Resources/xlf/Metrics.tr.xlf
  src/Aspire.Dashboard/Resources/xlf/Metrics.zh-Hans.xlf
  src/Aspire.Dashboard/Resources/xlf/Metrics.zh-Hant.xlf
Labels: area-dashboard

#9218 Reset SqlServer playground apps to new free default sku
  playground/SqlServerEndToEnd/SqlServerEndToEnd.AppHost/Program.cs
  playground/SqlServerEndToEnd/SqlServerEndToEnd.AppHost/sql1-roles.module.bicep
  playground/SqlServerEndToEnd/SqlServerEndToEnd.AppHost/sql1.module.bicep
  playground/SqlServerEndToEnd/SqlServerEndToEnd.AppHost/sql2-roles.module.bicep
  playground/SqlServerEndToEnd/SqlServerEndToEnd.AppHost/sql2.module.bicep
  playground/SqlServerScript/AppHost1/Program.cs
  playground/SqlServerScript/AppHost1/mysqlserver.module.bicep
Labels: area-integrations

#9217 Fix relationships for azure projects
  src/Aspire.Hosting.Azure.Functions/AzureFunctionsProjectResourceExtensions.cs
  tests/Aspire.Hosting.Azure.Tests/AzureFunctionsTests.cs
Labels: area-integrations

#9213 [tests] Quarantine some tests
  tests/Aspire.Dashboard.Components.Tests/Pages/ConsoleLogsTests.cs
  tests/Aspire.Dashboard.Tests/Integration/Playwright/AppBarTests.cs
  tests/Aspire.Hosting.Tests/DistributedApplicationTests.cs
Labels: area-dashboard

#9224 Fixed endpoint mapping in compose resources
  src/Aspire.Hosting.Docker/DockerComposeEnvironmentContext.cs
  src/Aspire.Hosting.Docker/DockerComposeEnvironmentResource.cs
  src/Aspire.Hosting.Docker/DockerComposePublishingContext.cs
  src/Aspire.Hosting.Docker/DockerComposeServiceResource.cs
  src/Aspire.Hosting.Docker/DockerComposeServiceResourceExtensions.cs
  src/Aspire.Hosting.Docker/ResourceComparer.cs
  tests/Aspire.Hosting.Docker.Tests/DockerComposePublisherTests.cs
  tests/Aspire.Hosting.Docker.Tests/Snapshots/DockerComposePublisherTests.DockerComposeMapsPortsProperly.verified.txt
Labels: area-deployment

#9225 Handle bait and switch resources in ACA
  src/Aspire.Hosting.Azure.AppContainers/ContainerAppEnvironmentContext.cs
  src/Aspire.Hosting.Azure.AppContainers/ResourceComparer.cs
  tests/Aspire.Hosting.Azure.Tests/AzureAppServiceTests.cs
  tests/Aspire.Hosting.Azure.Tests/AzureContainerAppsTests.cs
  tests/Aspire.Hosting.Azure.Tests/Snapshots/AzureContainerAppsTests.AzureContainerAppsMapsPortsForBaitAndSwitchResources.verified.bicep
  tests/Aspire.Hosting.Azure.Tests/Snapshots/AzureContainerAppsTests.AzureContainerAppsMapsPortsForBaitAndSwitchResources.verified.json
Labels: area-deployment

#9216 Document package validation handling
  docs/contributing.md
Labels: area-integrations

#9227 fix: Dashboard URL Token without dot.
  src/Shared/LoggingHelpers.cs
  tests/Aspire.Dashboard.Tests/Integration/FrontendBrowserTokenAuthTests.cs
Labels: needs-area-label, community-contribution

#9212 [CI] Don't cancel in-progress runs for rolling builds
  .github/workflows/tests.yml
Labels: area-engineering-systems

#8180 Added XML docs to the AddServiceDefaults and other extensions methods.
  playground/Playground.ServiceDefaults/Extensions.cs
  playground/TestShop/TestShop.ServiceDefaults/Extensions.cs
  playground/seq/Seq.ServiceDefaults/Extensions.cs
  src/Aspire.ProjectTemplates/templates/aspire-empty/9.2/AspireApplication.1.ServiceDefaults/Extensions.cs
  src/Aspire.ProjectTemplates/templates/aspire-empty/9.3/AspireApplication.1.ServiceDefaults/Extensions.cs
  src/Aspire.ProjectTemplates/templates/aspire-servicedefaults/9.2/Extensions.cs
  src/Aspire.ProjectTemplates/templates/aspire-servicedefaults/9.3/Extensions.cs
  src/Aspire.ProjectTemplates/templates/aspire-starter/9.2/Aspire-StarterApplication.1.ServiceDefaults/Extensions.cs
  src/Aspire.ProjectTemplates/templates/aspire-starter/9.3/Aspire-StarterApplication.1.ServiceDefaults/Extensions.cs
  tests/TestingAppHost1/TestingAppHost1.ServiceDefaults/Extensions.cs
Labels: documentation, area-templates, needs-author-action, community-contribution

#9234 Don't duplicate adding secrets to the infrastructure
  src/Aspire.Hosting.Azure.AppContainers/ContainerAppContext.cs
  tests/Aspire.Hosting.Azure.Tests/AzureContainerAppsTests.cs
  tests/Aspire.Hosting.Azure.Tests/Snapshots/AzureContainerAppsTests.AzureContainerAppsBicepGenerationIsIdempotent.verified.bicep
  tests/Aspire.Hosting.Azure.Tests/Snapshots/AzureContainerAppsTests.AzureContainerAppsBicepGenerationIsIdempotent.verified.json
Labels: azure, area-deployment

#9237 Revert "Added XML docs to the AddServiceDefaults and other extensions methods."
  playground/Playground.ServiceDefaults/Extensions.cs
  playground/TestShop/TestShop.ServiceDefaults/Extensions.cs
  playground/seq/Seq.ServiceDefaults/Extensions.cs
  src/Aspire.ProjectTemplates/templates/aspire-empty/9.2/AspireApplication.1.ServiceDefaults/Extensions.cs
  src/Aspire.ProjectTemplates/templates/aspire-empty/9.3/AspireApplication.1.ServiceDefaults/Extensions.cs
  src/Aspire.ProjectTemplates/templates/aspire-servicedefaults/9.2/Extensions.cs
  src/Aspire.ProjectTemplates/templates/aspire-servicedefaults/9.3/Extensions.cs
  src/Aspire.ProjectTemplates/templates/aspire-starter/9.2/Aspire-StarterApplication.1.ServiceDefaults/Extensions.cs
  src/Aspire.ProjectTemplates/templates/aspire-starter/9.3/Aspire-StarterApplication.1.ServiceDefaults/Extensions.cs
  tests/TestingAppHost1/TestingAppHost1.ServiceDefaults/Extensions.cs
Labels: area-templates

#9239 Improve GHA presentation
  .github/workflows/tests-outerloop.yml
  .github/workflows/tests-runner.yml
  eng/QuarantinedTestRunsheetBuilder/QuarantinedTestRunsheetBuilder.targets
  eng/TestRunsheetBuilder/TestRunsheetBuilder.targets
Labels: area-engineering-systems

#9232 Fix XML docs for WithArgs methods to clarify support for all IResourceWithArgs resources
  src/Aspire.Hosting/ResourceBuilderExtensions.cs
Labels: needs-area-label, community-contribution

#9238 Stream logs from docker build on publish.
  playground/withdockerfile/WithDockerfile.AppHost/Program.cs
  playground/withdockerfile/WithDockerfile.AppHost/Properties/launchSettings.json
  playground/withdockerfile/WithDockerfile.AppHost/WithDockerfile.AppHost.csproj
  src/Aspire.Cli/Commands/PublishCommand.cs
  src/Aspire.Cli/Commands/RunCommand.cs
  src/Aspire.Cli/DotNetCliRunner.cs
  src/Aspire.Hosting/Publishing/DockerContainerRuntime.cs
  src/Aspire.Hosting/Publishing/IContainerRuntime.cs
  src/Aspire.Hosting/Publishing/PodmanContainerRuntime.cs
  src/Aspire.Hosting/Publishing/ResourceContainerImageBuilder.cs
Labels: area-cli

#9223 [CI] Generate simple test summary
  .github/workflows/run-tests.yml
  .github/workflows/tests.yml
  Aspire.sln
  tools/GenerateTestSummary/GenerateTestSummary.csproj
  tools/GenerateTestSummary/Program.cs
  tools/GenerateTestSummary/TestSummaryGenerator.cs
  tools/GenerateTestSummary/TrxReader.cs
Labels: area-engineering-systems

#9247 Tweak GHA report generator
  tools/GenerateTestSummary/Program.cs
  tools/GenerateTestSummary/TestSummaryGenerator.cs
Labels: needs-area-label

#9249 Remove Task.Delay from kafka tests
  tests/Aspire.Hosting.Kafka.Tests/KafkaFunctionalTests.cs
Labels: needs-area-label, community-contribution

#9240 Fix confusing error message when test project doesn't reference an AppHost project
  src/Aspire.Hosting.Testing/DistributedApplicationTestingBuilder.cs
Labels: needs-area-label

#9245 [CI] Add OS name for tests in tests summary
  tools/GenerateTestSummary/TestSummaryGenerator.cs
Labels: area-integrations

#9253 Remove culture code from Microsoft documentation urls
  src/Aspire.Hosting.Azure.AppContainers/ContainerAppContext.cs
  src/Aspire.Hosting.Azure.AppService/AzureAppServiceWebsiteContext.cs
  src/Aspire.Hosting.Azure.CosmosDB/AzureCosmosDBExtensions.cs
  src/Aspire.Hosting.Azure.Sql/SqlServerScriptProvisioningResource.cs
  src/Components/Aspire.Azure.Messaging.EventHubs/README.md
  src/Components/Aspire.Microsoft.EntityFrameworkCore.Cosmos/README.md
  src/Microsoft.Extensions.ServiceDiscovery/README.md
  src/Shared/CommandLineArgsParser.cs
Labels: area-integrations

#9244 [tests] Disable failing test ProjectSpecificTests.AzureFunctionsTest
  .github/workflows/run-tests.yml
  eng/Testing.props
  tests/Aspire.Components.Common.Tests/Aspire.Components.Common.Tests.csproj
  tests/Aspire.Playground.Tests/ProjectSpecificTests.cs
Labels: area-integrations

#9255 Update `Microsoft.Extensions.AI` to 9.4.4-preview.1.25259.16
  eng/Versions.props
Labels: area-codeflow

#9262 [CI] Fix `main` build for AzDo
  tests/Shared/RepoTesting/Directory.Packages.Helix.props
  tests/helix/send-to-helix-buildonhelixtests.targets
Labels: area-engineering-systems

#8945 Azure App Configuration client integration
  Aspire.sln
  Directory.Packages.props
  src/Components/Aspire.Microsoft.Extensions.Configuration.AzureAppConfiguration/Aspire.Microsoft.Extensions.Configuration.AzureAppConfiguration.csproj
  src/Components/Aspire.Microsoft.Extensions.Configuration.AzureAppConfiguration/AspireAppConfigurationExtensions.cs
  src/Components/Aspire.Microsoft.Extensions.Configuration.AzureAppConfiguration/AssemblyInfo.cs
  src/Components/Aspire.Microsoft.Extensions.Configuration.AzureAppConfiguration/AzureAppConfigurationSettings.cs
  src/Components/Aspire.Microsoft.Extensions.Configuration.AzureAppConfiguration/ConfigurationSchema.json
  src/Components/Aspire.Microsoft.Extensions.Configuration.AzureAppConfiguration/README.md
  src/Components/Aspire_Components_Progress.md
  src/Components/Telemetry.md
  tests/Aspire.Components.Common.Tests/ConformanceTests.cs
  tests/Aspire.Microsoft.Extensions.Configuration.AzureAppConfiguration.Tests/AppConfiguratinPublicApiTests.cs
  tests/Aspire.Microsoft.Extensions.Configuration.AzureAppConfiguration.Tests/Aspire.Microsoft.Extensions.Configuration.AzureAppConfiguration.Tests.csproj
  tests/Aspire.Microsoft.Extensions.Configuration.AzureAppConfiguration.Tests/AspireAppConfigurationExtensionsTest.cs
  tests/Aspire.Microsoft.Extensions.Configuration.AzureAppConfiguration.Tests/ConfigurationTests.cs
  tests/Aspire.Microsoft.Extensions.Configuration.AzureAppConfiguration.Tests/ConformanceTests.cs
Labels: area-integrations, community-contribution

#9103 Integration for `Azure.AI.Inference`
  Aspire.sln
  Directory.Packages.props
  src/Components/Aspire.Azure.AI.Inference/Aspire.Azure.AI.Inference.csproj
  src/Components/Aspire.Azure.AI.Inference/AspireAzureAIInferenceExtensions.cs
  src/Components/Aspire.Azure.AI.Inference/AspireChatCompletionsClientBuilder.cs
  src/Components/Aspire.Azure.AI.Inference/AssemblyInfo.cs
  src/Components/Aspire.Azure.AI.Inference/ChatCompletionsClientSettings.cs
  src/Components/Aspire.Azure.AI.Inference/ConfigurationSchema.json
  src/Components/Aspire.Azure.AI.Inference/README.md
  src/Components/Aspire_Components_Progress.md
  src/Components/Telemetry.md
  tests/Aspire.Azure.AI.Inference.Tests/Aspire.Azure.AI.Inference.Tests.csproj
  tests/Aspire.Azure.AI.Inference.Tests/AspireAzureAIInferenceExtensionTests.cs
  tests/Aspire.Azure.AI.Inference.Tests/AspireAzureAIInferencePublicApiTests.cs
  tests/Aspire.Azure.AI.Inference.Tests/ConformanceTests.cs
Labels: area-integrations, community-contribution

#9263 [CI] Test summary reporter improvements
  .github/workflows/run-tests.yml
  tools/GenerateTestSummary/Program.cs
  tools/GenerateTestSummary/TestSummaryGenerator.cs
Labels: area-integrations

#9270 API review: Add Services property to ResourceEndpointsAllocatedEvent
  Aspire.sln
  src/Aspire.Hosting/ApplicationModel/ResourceEndpointsAllocatedEvent.cs
  src/Aspire.Hosting/Orchestrator/ApplicationOrchestrator.cs
Labels: area-app-model

#9264 Fix visibility updates during resource upserts
  src/Aspire.Dashboard/Components/Pages/Resources.razor.cs
  tests/Aspire.Dashboard.Components.Tests/Pages/ResourcesTests.cs
Labels: area-dashboard, Servicing-approved

#9278 Accept null value in Redis WithPassword to ensure password dosen't set in redis-server
  src/Aspire.Hosting.Redis/RedisBuilderExtensions.cs
  src/Aspire.Hosting.Redis/RedisResource.cs
  tests/Aspire.Hosting.Redis.Tests/AddRedisTests.cs
  tests/Aspire.Hosting.Redis.Tests/RedisFunctionalTests.cs
Labels: area-integrations, community-contribution

#9282 API review: `WithHostPort` should accept null for port param
  src/Aspire.Hosting.Redis/RedisBuilderExtensions.cs
  src/Aspire.Hosting.SqlServer/SqlServerBuilderExtensions.cs
Labels: area-integrations, community-contribution

#9285 [release/9.3] Respond to API Review feedback
  src/Aspire.Hosting.Azure.AppContainers/AzureContainerAppExtensions.cs
  src/Aspire.Hosting.Azure.AppService/AzureAppServiceEnvironmentExtensions.cs
  src/Aspire.Hosting.Azure.AppService/AzureAppServiceEnvironmentResource.cs
  src/Aspire.Hosting.Azure.ContainerRegistry/AzureContainerRegistryExtensions.cs
  src/Aspire.Hosting.Azure.ContainerRegistry/AzureContainerRegistryResource.cs
  src/Aspire.Hosting.Azure.Storage/AzureBlobStorageContainerResource.cs
  src/Aspire.Hosting.Azure/AzureEnvironmentResourceExtensions.cs
  src/Aspire.Hosting.Azure/AzurePublishingContext.cs
  src/Aspire.Hosting.Docker/DockerComposeEnvironmentResource.cs
  src/Aspire.Hosting.Kubernetes/KubernetesEnvironmentResource.cs
  src/Aspire.Hosting/ApplicationModel/ContainerRegistryReferenceAnnotation.cs
  src/Aspire.Hosting/ApplicationModel/PublishingCallbackAnnotation.cs
  src/Aspire.Hosting/CompatibilitySuppressions.xml
  src/Aspire.Hosting/PublisherDistributedApplicationBuilderExtensions.cs
  src/Aspire.Hosting/Publishing/Publisher.cs
  src/Aspire.Hosting/Publishing/PublishingContext.cs
  src/Aspire.Hosting/ResourceBuilderExtensions.cs
  tests/Aspire.Hosting.Azure.Tests/AzureAppServiceTests.cs
  tests/Aspire.Hosting.Azure.Tests/AzureContainerAppsTests.cs
  tests/Aspire.Hosting.Azure.Tests/AzureContainerRegistryTests.cs
  tests/Aspire.Hosting.Azure.Tests/AzureUserAssignedIdentityTests.cs
  tests/Aspire.Hosting.Tests/DistributedApplicationRunnerTests.cs
  tests/Aspire.Hosting.Tests/PublishingTests.cs
Labels: area-app-model, Servicing-approved

#9289 Enable stable branding for release 9.3
  eng/Versions.props
  src/Aspire.Hosting.Azure.AppContainers/Aspire.Hosting.Azure.AppContainers.csproj
  src/Aspire.Hosting.Azure.AppService/Aspire.Hosting.Azure.AppService.csproj
  tests/Shared/RepoTesting/Aspire.RepoTesting.targets
  tests/Shared/RepoTesting/Directory.Packages.Helix.props
Labels: needs-area-label

#9296 Test that ensures legacy dashboard token env var is honored
  tests/Aspire.Hosting.Tests/DistributedApplicationTests.cs
Labels: area-app-model

#9295 Refactor solution file from .sln to .slnx format and update related d…
  .devcontainer/devcontainer.json
  .gitattributes
  .github/workflows/update-dependencies.yml
  .vscode/settings.json
  Aspire.sln
  Aspire.slnx
  docs/contributing.md
  docs/using-latest-daily.md
  eng/build.ps1
  eng/common/build.ps1
  src/Aspire.ProjectTemplates/templates/aspire-empty/.template.config/template.json
  startvs.cmd
Labels: area-engineering-systems

#9301 Minor dashboard improvements and clean up
  src/Aspire.Dashboard/Components/Dialogs/SettingsDialog.razor.cs
  src/Aspire.Dashboard/Components/ResourcesGridColumns/LogMessageColumnDisplay.razor.cs
  src/Aspire.Dashboard/DashboardEndpointsBuilder.cs
  src/Aspire.Dashboard/Extensions/ResourceViewModelExtensions.cs
  src/Aspire.Dashboard/Model/DebugSessionHelpers.cs
  src/Aspire.Dashboard/Model/ResourceStateViewModel.cs
  src/Aspire.Dashboard/Model/ResourceViewModel.cs
  src/Aspire.Dashboard/Otlp/Model/OtlpHelpers.cs
  src/Aspire.Dashboard/Otlp/Model/OtlpLogEntry.cs
  src/Aspire.Dashboard/Otlp/Storage/Subscription.cs
  src/Aspire.Dashboard/Otlp/Storage/TelemetryRepository.cs
  src/Aspire.Dashboard/Resources/Columns.Designer.cs
  src/Aspire.Dashboard/Resources/Columns.resx
  src/Aspire.Dashboard/Resources/xlf/Columns.cs.xlf
  src/Aspire.Dashboard/Resources/xlf/Columns.de.xlf
  src/Aspire.Dashboard/Resources/xlf/Columns.es.xlf
  src/Aspire.Dashboard/Resources/xlf/Columns.fr.xlf
  src/Aspire.Dashboard/Resources/xlf/Columns.it.xlf
  src/Aspire.Dashboard/Resources/xlf/Columns.ja.xlf
  src/Aspire.Dashboard/Resources/xlf/Columns.ko.xlf
  src/Aspire.Dashboard/Resources/xlf/Columns.pl.xlf
  src/Aspire.Dashboard/Resources/xlf/Columns.pt-BR.xlf
  src/Aspire.Dashboard/Resources/xlf/Columns.ru.xlf
  src/Aspire.Dashboard/Resources/xlf/Columns.tr.xlf
  src/Aspire.Dashboard/Resources/xlf/Columns.zh-Hans.xlf
  src/Aspire.Dashboard/Resources/xlf/Columns.zh-Hant.xlf
  src/Aspire.Dashboard/Utils/CallbackThrottler.cs
  src/Aspire.Dashboard/Utils/GlobalizationHelpers.cs
  tests/Aspire.Dashboard.Tests/GlobalizationHelpersTests.cs
Labels: area-dashboard

#9303 Minor improvements to resource changed log
  src/Aspire.Hosting/ApplicationModel/ResourceNotificationService.cs
Labels: area-app-model

#9304 Fix Blazor error logging to telemetry
  src/Aspire.Dashboard/Components/Controls/TelemetryErrorBoundary.cs
  src/Aspire.Dashboard/Components/Routes.razor
  src/Aspire.Dashboard/DashboardWebApplication.cs
  src/Aspire.Dashboard/Telemetry/TelemetryLoggerProvider.cs
  tests/Aspire.Dashboard.Tests/Integration/StartupTests.cs
  tests/Aspire.Dashboard.Tests/Telemetry/TelemetryLoggerProviderTests.cs
Labels: area-dashboard

#9306 Don't throw from component telemetry context dispose if not initialized
  src/Aspire.Dashboard/Components/Pages/ComponentTelemetryContext.cs
  tests/Aspire.Dashboard.Tests/Telemetry/ComponentTelemetryContextTests.cs
Labels: area-dashboard

#9316 Ignore case on FormatDateTime_WithMilliseconds_NewZealandCulture
  tests/Aspire.Dashboard.Tests/FormatHelpersTests.cs
Labels: area-dashboard

#9280 Changing default SKU for App Service Plan to P0V3
  playground/AzureAppService/AzureAppService.AppHost/api.module.bicep
  playground/AzureAppService/AzureAppService.AppHost/infra.module.bicep
  src/Aspire.Hosting.Azure.AppService/AzureAppServiceEnvironmentExtensions.cs
  src/Aspire.Hosting.Azure.AppService/AzureAppServiceWebsiteContext.cs
  tests/Aspire.Hosting.Azure.Tests/Snapshots/AzureAppServiceTests.AddContainerAppEnvironmentAddsDeploymentTargetWithContainerAppToProjectResources.verified.bicep
  tests/Aspire.Hosting.Azure.Tests/Snapshots/AzureAppServiceTests.AddContainerAppEnvironmentAddsEnvironmentResource.verified.bicep
  tests/Aspire.Hosting.Azure.Tests/Snapshots/AzureAppServiceTests.EndpointReferencesAreResolvedAcrossProjects.verified.bicep
  tests/Aspire.Hosting.Azure.Tests/Snapshots/AzureAppServiceTests.KeyvaultReferenceHandling.verified.bicep
Labels: area-integrations, community-contribution

#9317 Increase retry time in AppBar_Change_Theme_ReloadPage
  tests/Aspire.Dashboard.Tests/Integration/Playwright/AppBarTests.cs
  tests/Shared/AsyncTestHelpers.cs
Labels: area-integrations

#9261 Update xUnit.v3 to support MTP tests
  .vscode/settings.json
  eng/Versions.props
Labels: area-engineering-systems

#9336 Revert "Update xUnit.v3 to support MTP tests (#9261)"
  .vscode/settings.json
  eng/Versions.props
Labels: area-codeflow

#9339 Remove the workaround to explicitly set the container runtime for tests now that the orchestrator is updated
  .github/workflows/run-tests.yml
  eng/pipelines/templates/BuildAndTest.yml
  tests/helix/send-to-helix-inner.proj
Labels: area-engineering-systems

#9337 Revert "Revert "Update xUnit.v3 to support MTP tests (#9261)" (#9336)"
  .vscode/settings.json
  eng/Versions.props
Labels: area-engineering-systems, testing ☑️

#9335 TestsReportGenerator: Always show the error message, and truncate only the stdout
  tests/Aspire.Hosting.Tests/DistributedApplicationTests.cs
  tests/Aspire.Hosting.Yarp.Tests/YarpFunctionalTests.cs
  tools/GenerateTestSummary/TestSummaryGenerator.cs
Labels: area-integrations

#9338 [CI] Fix azdo builds for `main`
  eng/pipelines/templates/BuildAndTest.yml
  tests/Aspire.Dashboard.Tests/Integration/Playwright/BrowserTokenAuthenticationTests.cs
Labels: area-engineering-systems

#9348 Bumping MEAI to stable 9.5.0 versions
  Directory.Packages.props
  NuGet.config
  eng/Versions.props
Labels: area-codeflow

#9342 Fix typo in doccomment in `ContainerResourceBuilderExtensions.cs`
  src/Aspire.Hosting/ContainerResourceBuilderExtensions.cs
Labels: needs-area-label, community-contribution

#9159 Update health check to ensure blob containers created at right time
  src/Aspire.Hosting.Azure.CosmosDB/AzureCosmosDBExtensions.cs
  src/Aspire.Hosting.Azure.Storage/AzureStorageExtensions.cs
  src/Components/Aspire.Azure.Storage.Blobs/AspireBlobStorageExtensions.BlobStorageContainerComponent.AzureBlobStorageContainerHealthCheck.cs
  src/Components/Aspire.Azure.Storage.Blobs/AspireBlobStorageExtensions.BlobStorageContainerComponent.cs
  tests/Aspire.Hosting.Azure.Tests/AzureBicepResourceTests.cs
  tests/Aspire.Hosting.Azure.Tests/AzureStorageEmulatorFunctionalTests.cs
Labels: area-integrations

#9364 Re-apply quarantined test for validation
  tests/Aspire.Hosting.Azure.Tests/AzureStorageEmulatorFunctionalTests.cs
Labels: area-integrations

#9365 Update telemetry doc for AzureAppConfiguration
  src/Components/Aspire.Microsoft.Extensions.Configuration.AzureAppConfiguration/AspireAppConfigurationExtensions.cs
  src/Components/Telemetry.md
Labels: area-integrations

#9361 Enable MTP tests via MSBuild property
  tests/Shared/RepoTesting/Aspire.RepoTesting.props
Labels: needs-area-label

#9369 catch json error
  src/Aspire.Cli/DotNetCliRunner.cs
Labels: area-cli

#9370 Refactor a common TempDirectory test class
  tests/Aspire.Hosting.Docker.Tests/DockerComposePublisherTests.cs
  tests/Aspire.Hosting.Kubernetes.Tests/KubernetesPublisherTests.cs
  tests/Aspire.Hosting.MySql.Tests/AddMySqlTests.cs
  tests/Aspire.Hosting.MySql.Tests/MySqlFunctionalTests.cs
  tests/Aspire.Hosting.PostgreSQL.Tests/AddPostgresTests.cs
  tests/Aspire.Hosting.PostgreSQL.Tests/PostgresFunctionalTests.cs
  tests/Aspire.Hosting.Tests/Aspire.Hosting.Tests.csproj
  tests/Aspire.Hosting.Tests/MSBuildTests.cs
  tests/Aspire.Hosting.Tests/PublishAsDockerfileTests.cs
  tests/Shared/TempDirectory.cs
Labels: area-integrations

#9371 Centralize Verify convention
  tests/Aspire.Hosting.Azure.Tests/AzureAppServiceTests.cs
  tests/Aspire.Hosting.Azure.Tests/AzureBicepResourceTests.cs
  tests/Aspire.Hosting.Azure.Tests/AzureContainerAppsTests.cs
  tests/Aspire.Hosting.Azure.Tests/AzureContainerRegistryTests.cs
  tests/Aspire.Hosting.Azure.Tests/AzureCosmosDBExtensionsTests.cs
  tests/Aspire.Hosting.Azure.Tests/AzureEnvironmentResourceTests.cs
  tests/Aspire.Hosting.Azure.Tests/AzureEventHubsExtensionsTests.cs
  tests/Aspire.Hosting.Azure.Tests/AzureFunctionsTests.cs
  tests/Aspire.Hosting.Azure.Tests/AzureKeyVaultTests.cs
  tests/Aspire.Hosting.Azure.Tests/AzurePostgresExtensionsTests.cs
  tests/Aspire.Hosting.Azure.Tests/AzureProvisioningResourceExtensionsTests.cs
  tests/Aspire.Hosting.Azure.Tests/AzureRedisExtensionsTests.cs
  tests/Aspire.Hosting.Azure.Tests/AzureResourceOptionsTests.cs
  tests/Aspire.Hosting.Azure.Tests/AzureResourcePreparerTests.cs
  tests/Aspire.Hosting.Azure.Tests/AzureServiceBusExtensionsTests.cs
  tests/Aspire.Hosting.Azure.Tests/AzureSignalRExtensionsTests.cs
  tests/Aspire.Hosting.Azure.Tests/AzureSqlExtensionsTests.cs
  tests/Aspire.Hosting.Azure.Tests/AzureStorageExtensionsTests.cs
  tests/Aspire.Hosting.Azure.Tests/AzureUserAssignedIdentityTests.cs
  tests/Aspire.Hosting.Azure.Tests/AzureWebPubSubExtensionsTests.cs
  tests/Aspire.Hosting.Azure.Tests/ExistingAzureResourceTests.cs
  tests/Aspire.Hosting.Azure.Tests/RoleAssignmentTests.cs
  tests/Aspire.Hosting.Docker.Tests/DockerComposePublisherTests.cs
  tests/Aspire.Hosting.Kubernetes.Tests/KubernetesEnvironmentResourceTests.cs
  tests/Aspire.Hosting.Kubernetes.Tests/KubernetesPublisherTests.cs
  tests/Shared/TestModuleInitializer.cs
  tests/Shared/VerifyExtensions.cs
Labels: area-integrations

#9356 Update Aspire to stable Microsoft.Extensions.AI.Abstractions
  Directory.Packages.props
  eng/Versions.props
Labels: area-integrations

#9360 Update RunCommand.cs
  src/Aspire.Cli/Commands/RunCommand.cs
Labels: area-cli

#8908 Add support for copying existing files via WithContainerFiles API
  src/Aspire.Hosting.Azure.EventHubs/AzureEventHubsEmulatorResource.cs
  src/Aspire.Hosting.Azure.EventHubs/AzureEventHubsExtensions.cs
  src/Aspire.Hosting.Azure.EventHubs/ConfigFileAnnotation.cs
  src/Aspire.Hosting.Azure.ServiceBus/AzureServiceBusEmulatorResource.cs
  src/Aspire.Hosting.Azure.ServiceBus/AzureServiceBusExtensions.cs
  src/Aspire.Hosting.Azure.ServiceBus/ConfigFileAnnotation.cs
  src/Aspire.Hosting.Docker/DockerComposePublisherLoggerExtensions.cs
  src/Aspire.Hosting.Docker/DockerComposePublishingContext.cs
  src/Aspire.Hosting.Docker/Resources/ComposeFile.cs
  src/Aspire.Hosting.Docker/Resources/ComposeNodes/Config.cs
  src/Aspire.Hosting.Docker/Resources/ComposeNodes/Service.cs
  src/Aspire.Hosting.Docker/Resources/ServiceNodes/ConfigReference.cs
  src/Aspire.Hosting.Docker/UnixFileModeTypeConverter.cs
  src/Aspire.Hosting.Keycloak/KeycloakResourceBuilderExtensions.cs
  src/Aspire.Hosting.Milvus/MilvusBuilderExtensions.cs
  src/Aspire.Hosting.MongoDB/MongoDBBuilderExtensions.cs
  src/Aspire.Hosting.MySql/MySqlBuilderExtensions.cs
  src/Aspire.Hosting.Oracle/OracleDatabaseBuilderExtensions.cs
  src/Aspire.Hosting.PostgreSQL/PostgresBuilderExtensions.cs
  src/Aspire.Hosting/ApplicationModel/ContainerFileSystemCallbackAnnotation.cs
  src/Aspire.Hosting/Dcp/Model/Container.cs
  tests/Aspire.Hosting.Azure.Tests/AzureEventHubsExtensionsTests.cs
  tests/Aspire.Hosting.Azure.Tests/AzureServiceBusExtensionsTests.cs
  tests/Aspire.Hosting.Docker.Tests/Aspire.Hosting.Docker.Tests.csproj
  tests/Aspire.Hosting.Docker.Tests/DockerComposePublisherTests.cs
  tests/Aspire.Hosting.Docker.Tests/Snapshots/DockerComposePublisherTests.PublishAsync_GeneratesValidDockerComposeFile.verified.yaml
  tests/Aspire.Hosting.Docker.Tests/hello.sh
  tests/Aspire.Hosting.Keycloak.Tests/KeycloakPublicApiTests.cs
  tests/Aspire.Hosting.Milvus.Tests/MilvusPublicApiTests.cs
  tests/Aspire.Hosting.MongoDB.Tests/MongoDBPublicApiTests.cs
  tests/Aspire.Hosting.MongoDB.Tests/MongoDbFunctionalTests.cs
  tests/Aspire.Hosting.MySql.Tests/MySqlFunctionalTests.cs
  tests/Aspire.Hosting.MySql.Tests/MySqlPublicApiTests.cs
  tests/Aspire.Hosting.Oracle.Tests/OracleFunctionalTests.cs
  tests/Aspire.Hosting.Oracle.Tests/OraclePublicApiTests.cs
  tests/Aspire.Hosting.PostgreSQL.Tests/PostgrePublicApiTests.cs
  tests/Aspire.Hosting.PostgreSQL.Tests/PostgresFunctionalTests.cs
  tests/Aspire.Hosting.Tests/DistributedApplicationTests.cs
Labels: area-app-model, NO-MERGE

#9384 Do not fail on partial trust warning.
  src/Aspire.Cli/Certificates/CertificateService.cs
  tests/Aspire.Cli.Tests/Certificates/CertificateServiceTests.cs
Labels: area-cli

#9389 markdown lint
  .github/workflows/markdownlint.yml
  README.md
  src/Aspire.Dashboard/README.md
  src/Components/Aspire_Components_Progress.md
Labels: area-integrations

#9394 Merge branch release/9.3 into main
  src/Aspire.Hosting.Azure.AppContainers/Aspire.Hosting.Azure.AppContainers.csproj
  src/Aspire.Hosting.Azure.AppContainers/AzureContainerAppExtensions.cs
  src/Aspire.Hosting.Azure.AppService/Aspire.Hosting.Azure.AppService.csproj
  src/Aspire.Hosting.Azure.AppService/AzureAppServiceEnvironmentExtensions.cs
  src/Aspire.Hosting.Azure.AppService/AzureAppServiceEnvironmentResource.cs
  src/Aspire.Hosting.Azure.ContainerRegistry/AzureContainerRegistryExtensions.cs
  src/Aspire.Hosting.Azure.ContainerRegistry/AzureContainerRegistryResource.cs
  src/Aspire.Hosting.Azure.Storage/AzureBlobStorageContainerResource.cs
  src/Aspire.Hosting.Azure/AzureEnvironmentResourceExtensions.cs
  src/Aspire.Hosting.Azure/AzurePublishingContext.cs
  src/Aspire.Hosting.Docker/DockerComposeEnvironmentResource.cs
  src/Aspire.Hosting.Kubernetes/KubernetesEnvironmentResource.cs
  src/Aspire.Hosting/ApplicationModel/ContainerRegistryReferenceAnnotation.cs
  src/Aspire.Hosting/ApplicationModel/PublishingCallbackAnnotation.cs
  src/Aspire.Hosting/CompatibilitySuppressions.xml
  src/Aspire.Hosting/PublisherDistributedApplicationBuilderExtensions.cs
  src/Aspire.Hosting/Publishing/Publisher.cs
  src/Aspire.Hosting/Publishing/PublishingContext.cs
  src/Aspire.Hosting/ResourceBuilderExtensions.cs
  tests/Aspire.Hosting.Azure.Tests/AzureAppServiceTests.cs
  tests/Aspire.Hosting.Azure.Tests/AzureContainerAppsTests.cs
  tests/Aspire.Hosting.Azure.Tests/AzureContainerRegistryTests.cs
  tests/Aspire.Hosting.Azure.Tests/AzureUserAssignedIdentityTests.cs
  tests/Aspire.Hosting.Tests/DistributedApplicationRunnerTests.cs
  tests/Aspire.Hosting.Tests/PublishingTests.cs
Labels: needs-area-label

#9391 Fix failure in MongoDbFunctionalTests.VerifyWithInitFiles
  tests/Aspire.Hosting.MongoDB.Tests/MongoDbFunctionalTests.cs
Labels: needs-area-label

#9401 Ensure all grid columns have tooltips
  src/Aspire.Dashboard/Components/Controls/Grid/AspirePropertyColumn.cs
  src/Aspire.Dashboard/Components/Controls/Grid/AspireTemplateColumn.cs
Labels: area-dashboard

#9402 Remove test from quarantine
  tests/Aspire.Hosting.MongoDB.Tests/MongoDbFunctionalTests.cs
Labels: area-integrations

#9409 copilot setup steps
  .github/copilot-instructions.md
  .github/workflows/copilot-setup-steps.yml
Labels: area-engineering-systems

#9408 docs update
  docs/api-review-process.md
  docs/area-owners.md
  docs/contributing.md
  docs/getting-perf-traces.md
  docs/machine-requirements.md
  docs/using-latest-daily.md
Labels: area-engineering-systems

#9414 [CI] Fix copilot setup steps
  .github/workflows/copilot-setup-steps.yml
Labels: area-engineering-systems

#9314 Prevent text overflow in resource action URLs
  playground/Stress/Stress.AppHost/Program.cs
  src/Aspire.Dashboard/Components/Controls/AspireMenu.razor.cs
  src/Aspire.Dashboard/wwwroot/css/app.css
Labels: area-dashboard

#9404 Support setting existing app identity on compute resources
  src/Aspire.Hosting.Azure/AzureResourcePreparer.cs
  src/Aspire.Hosting.Azure/AzureUserAssignedIdentityExtensions.cs
  tests/Aspire.Hosting.Azure.Tests/AzureUserAssignedIdentityTests.cs
  tests/Aspire.Hosting.Azure.Tests/Snapshots/AzureUserAssignedIdentityTests.WithAzureUserAssignedIdentity_WithRoleAssignments_AzureAppService_Works#00.verified.bicep
  tests/Aspire.Hosting.Azure.Tests/Snapshots/AzureUserAssignedIdentityTests.WithAzureUserAssignedIdentity_WithRoleAssignments_AzureAppService_Works#01.verified.bicep
  tests/Aspire.Hosting.Azure.Tests/Snapshots/AzureUserAssignedIdentityTests.WithAzureUserAssignedIdentity_WithRoleAssignments_AzureAppService_Works#02.verified.bicep
  tests/Aspire.Hosting.Azure.Tests/Snapshots/AzureUserAssignedIdentityTests.WithAzureUserAssignedIdentity_WithRoleAssignments_MultipleProjects_Works#00.verified.bicep
  tests/Aspire.Hosting.Azure.Tests/Snapshots/AzureUserAssignedIdentityTests.WithAzureUserAssignedIdentity_WithRoleAssignments_MultipleProjects_Works#01.verified.bicep
  tests/Aspire.Hosting.Azure.Tests/Snapshots/AzureUserAssignedIdentityTests.WithAzureUserAssignedIdentity_WithRoleAssignments_MultipleProjects_Works#02.verified.bicep
  tests/Aspire.Hosting.Azure.Tests/Snapshots/AzureUserAssignedIdentityTests.WithAzureUserAssignedIdentity_WithRoleAssignments_MultipleProjects_Works#03.verified.bicep
  tests/Aspire.Hosting.Azure.Tests/Snapshots/AzureUserAssignedIdentityTests.WithAzureUserAssignedIdentity_WithRoleAssignments_MultipleProjects_Works#04.verified.bicep
  tests/Aspire.Hosting.Azure.Tests/Snapshots/AzureUserAssignedIdentityTests.WithAzureUserAssignedIdentity_WithRoleAssignments_Works#00.verified.bicep
  tests/Aspire.Hosting.Azure.Tests/Snapshots/AzureUserAssignedIdentityTests.WithAzureUserAssignedIdentity_WithRoleAssignments_Works#01.verified.bicep
  tests/Aspire.Hosting.Azure.Tests/Snapshots/AzureUserAssignedIdentityTests.WithAzureUserAssignedIdentity_WithRoleAssignments_Works#02.verified.bicep
  tests/Aspire.Hosting.Azure.Tests/Snapshots/AzureUserAssignedIdentityTests.WithAzureUserAssignedIdentity_Works.verified.bicep
Labels: area-integrations

#9417 Update FluentUI to 4.11.9
  Directory.Packages.props
  src/Aspire.Dashboard/Components/Controls/FixedFluentCombobox.razor
  src/Aspire.Dashboard/Components/Controls/FixedFluentCombobox.razor.cs
  src/Aspire.Dashboard/Components/Dialogs/FilterDialog.razor
  src/Aspire.Dashboard/Model/IconResolver.cs
  tests/Aspire.Dashboard.Components.Tests/Pages/ConsoleLogsTests.cs
Labels: area-dashboard

#9432 Add a counter to Stress app
  playground/Stress/Stress.TelemetryService/CounterMetrics.cs
  playground/Stress/Stress.TelemetryService/Program.cs
Labels: area-dashboard

#9415 Fix error in json in README.md
  src/Microsoft.Extensions.ServiceDiscovery/README.md
Labels: area-service-discovery, community-contribution

#9416 Add Tests badge for rolling builds on github workflows
  README.md
Labels: area-engineering-systems

#9443 Trace detail improvements
  src/Aspire.Dashboard/Components/Pages/TraceDetail.razor
  src/Aspire.Dashboard/Components/Pages/TraceDetail.razor.cs
  src/Aspire.Dashboard/Components/Pages/TraceDetail.razor.css
  tests/Aspire.Dashboard.Components.Tests/Pages/TraceDetailsTests.cs
Labels: area-dashboard

#9435 More logging in flaky pause console logs test
  src/Aspire.Dashboard/Components/Pages/ConsoleLogs.razor.cs
  tests/Aspire.Dashboard.Components.Tests/Pages/ConsoleLogsTests.cs
Labels: area-dashboard

#9405 Remove ACA Environment Contributor role assignment
  src/Aspire.Hosting.Azure.AppContainers/AzureContainerAppExtensions.cs
  tests/Aspire.Hosting.Azure.Tests/Snapshots/AzureContainerAppsTests.AddContainerAppEnvironmentAddsEnvironmentResource_useAzdNaming=False.verified.bicep
  tests/Aspire.Hosting.Azure.Tests/Snapshots/AzureContainerAppsTests.AddContainerAppEnvironmentAddsEnvironmentResource_useAzdNaming=True.verified.bicep
  tests/Aspire.Hosting.Azure.Tests/Snapshots/AzureContainerAppsTests.ContainerAppEnvironmentWithCustomRegistry#00.verified.bicep
  tests/Aspire.Hosting.Azure.Tests/Snapshots/AzureEnvironmentResourceTests.WhenUsedWithAzureContainerAppsEnvironment_GeneratesProperBicep#01.verified.bicep
Labels: area-integrations

#9479 Use ProcessSpec for invoking dotnet publish
  src/Aspire.Cli/Commands/PublishCommand.cs
  src/Aspire.Hosting/Publishing/ResourceContainerImageBuilder.cs
Labels: area-cli
