Repository dotnet/aspire, pull requests merged in 2025-09, with the labels that each got.

#10378 Use mssql instead of azure-sql-edge for ServiceBus Emulator
  src/Aspire.Hosting.Azure.ServiceBus/AzureServiceBusExtensions.cs
  src/Aspire.Hosting.Azure.ServiceBus/ServiceBusEmulatorContainerImageTags.cs
  tests/Aspire.Hosting.Azure.Tests/AzureServiceBusExtensionsTests.cs
Labels: area-integrations, azure, community-contribution, azure-servicebus

#11114 Add net462 target to ServiceDiscovery
  src/Microsoft.Extensions.ServiceDiscovery.Abstractions/Microsoft.Extensions.ServiceDiscovery.Abstractions.csproj
  src/Microsoft.Extensions.ServiceDiscovery/Microsoft.Extensions.ServiceDiscovery.csproj
Labels: area-service-discovery

#10662 Caitie/update test templates
  src/Aspire.ProjectTemplates/templates/aspire-mstest/9.4/IntegrationTest1.cs
  src/Aspire.ProjectTemplates/templates/aspire-mstest/9.5/IntegrationTest1.cs
  src/Aspire.ProjectTemplates/templates/aspire-nunit/9.4/IntegrationTest1.cs
  src/Aspire.ProjectTemplates/templates/aspire-nunit/9.5/IntegrationTest1.cs
  src/Aspire.ProjectTemplates/templates/aspire-xunit/9.4/IntegrationTest1.cs
  src/Aspire.ProjectTemplates/templates/aspire-xunit/9.5/IntegrationTest1.cs
  tests/Aspire.Templates.Tests/NewUpAndBuildSupportProjectTemplatesTests.cs
Labels: area-templates, community-contribution

#11175 Split up publish and deploy and unify graphs
  src/Aspire.Cli/Commands/DeployCommand.cs
  src/Aspire.Cli/Commands/PublishCommand.cs
  src/Aspire.Cli/Commands/PublishCommandBase.cs
  src/Aspire.Cli/Resources/DeployCommandStrings.resx
  src/Aspire.Cli/Resources/xlf/DeployCommandStrings.cs.xlf
  src/Aspire.Cli/Resources/xlf/DeployCommandStrings.de.xlf
  src/Aspire.Cli/Resources/xlf/DeployCommandStrings.es.xlf
  src/Aspire.Cli/Resources/xlf/DeployCommandStrings.fr.xlf
  src/Aspire.Cli/Resources/xlf/DeployCommandStrings.it.xlf
  src/Aspire.Cli/Resources/xlf/DeployCommandStrings.ja.xlf
  src/Aspire.Cli/Resources/xlf/DeployCommandStrings.ko.xlf
  src/Aspire.Cli/Resources/xlf/DeployCommandStrings.pl.xlf
  src/Aspire.Cli/Resources/xlf/DeployCommandStrings.pt-BR.xlf
  src/Aspire.Cli/Resources/xlf/DeployCommandStrings.ru.xlf
  src/Aspire.Cli/Resources/xlf/DeployCommandStrings.tr.xlf
  src/Aspire.Cli/Resources/xlf/DeployCommandStrings.zh-Hans.xlf
  src/Aspire.Cli/Resources/xlf/DeployCommandStrings.zh-Hant.xlf
  src/Aspire.Hosting.Azure/AzureDeployingContext.cs
  src/Aspire.Hosting.Azure/Provisioning/ResourceDeploymentGraph.cs
  src/Aspire.Hosting/Publishing/DeployingContext.cs
  src/Aspire.Hosting/Publishing/Publisher.cs
  tests/Aspire.Cli.Tests/Commands/DeployCommandTests.cs
  tests/Aspire.Hosting.Azure.Tests/AzureDeployerTests.cs
  tests/Aspire.Hosting.Tests/PublishingTests.cs
Labels: area-deployment

#11192 [CI] Add a QuarantineTool for tests
  .github/copilot-instructions.md
  .github/instructions/quarantine.instructions.md
  Aspire.slnx
  Directory.Packages.props
  tests/Directory.Build.targets
  tests/QuarantineTools.Tests/QuarantineScriptTests.cs
  tests/QuarantineTools.Tests/QuarantineTools.Tests.csproj
  tools/QuarantineTools/Directory.Build.props
  tools/QuarantineTools/Directory.Build.targets
  tools/QuarantineTools/Directory.Packages.props
  tools/QuarantineTools/Quarantine.cs
  tools/QuarantineTools/QuarantineTools.csproj
  tools/QuarantineTools/README.md
Labels: area-integrations, area-engineering-systems

#10935 Add initial version of Aspire.Hosting.Azure.Kusto
  Aspire.slnx
  Directory.Packages.props
  playground/AzureKusto/AzureKusto.AppHost/AzureKusto.AppHost.csproj
  playground/AzureKusto/AzureKusto.AppHost/Program.cs
  playground/AzureKusto/AzureKusto.AppHost/Properties/launchSettings.json
  playground/AzureKusto/AzureKusto.AppHost/appsettings.Development.json
  playground/AzureKusto/AzureKusto.AppHost/appsettings.json
  playground/AzureKusto/AzureKusto.Worker/AzureKusto.Worker.csproj
  playground/AzureKusto/AzureKusto.Worker/IngestionWorker.cs
  playground/AzureKusto/AzureKusto.Worker/Program.cs
  playground/AzureKusto/AzureKusto.Worker/Properties/launchSettings.json
  playground/AzureKusto/AzureKusto.Worker/QueryWorker.cs
  playground/AzureKusto/AzureKusto.Worker/WorkerOptions.cs
  playground/AzureKusto/AzureKusto.Worker/appsettings.Development.json
  playground/AzureKusto/AzureKusto.Worker/appsettings.json
  spelling.dic
  src/Aspire.Hosting.Azure.Kusto/Aspire.Hosting.Azure.Kusto.csproj
  src/Aspire.Hosting.Azure.Kusto/AzureKustoBuilderExtensions.cs
  src/Aspire.Hosting.Azure.Kusto/AzureKustoClusterResource.cs
  src/Aspire.Hosting.Azure.Kusto/AzureKustoCreateDatabaseScriptAnnotation.cs
  src/Aspire.Hosting.Azure.Kusto/AzureKustoDatabaseResource.cs
  src/Aspire.Hosting.Azure.Kusto/AzureKustoEmulatorContainerDefaults.cs
  src/Aspire.Hosting.Azure.Kusto/AzureKustoEmulatorContainerImageTags.cs
  src/Aspire.Hosting.Azure.Kusto/AzureKustoEmulatorResource.cs
  src/Aspire.Hosting.Azure.Kusto/AzureKustoHealthCheck.cs
  src/Aspire.Hosting.Azure.Kusto/AzureKustoHealthCheckBuilderExtensions.cs
  src/Aspire.Hosting.Azure.Kusto/README.md
  tests/Aspire.Hosting.Azure.Kusto.Tests/AddAzureKustoTests.cs
  tests/Aspire.Hosting.Azure.Kusto.Tests/Aspire.Hosting.Azure.Kusto.Tests.csproj
  tests/Aspire.Hosting.Azure.Kusto.Tests/KustoFunctionalTests.cs
  tests/Aspire.Hosting.Azure.Kusto.Tests/KustoPublicApiTests.cs
  tests/Aspire.Hosting.Azure.Kusto.Tests/Snapshots/KustoFunctionalTests.KustoEmulator_WithDatabase_CanReadIngestedData.verified.txt
Labels: area-integrations, community-contribution

#11233 Standardizes log message parameter names for consistency
  src/Aspire.Hosting/ApplicationModel/ResourceNotificationService.cs
Labels: needs-area-label, community-contribution

#11241 Add publishing step/task for fetch sub IDs and regions
  src/Aspire.Hosting.Azure/Provisioning/Internal/PublishModeProvisioningContextProvider.cs
  src/Aspire.Hosting/Publishing/NullPublishingActivityReporter.cs
  tests/Aspire.Hosting.Azure.Tests/ProvisioningContextProviderTests.cs
Labels: area-app-model

#11247 Remove ingestion endpoint from Kusto emulator
  src/Aspire.Hosting.Azure.Kusto/AzureKustoBuilderExtensions.cs
  src/Aspire.Hosting.Azure.Kusto/AzureKustoEmulatorContainerDefaults.cs
  tests/Aspire.Hosting.Azure.Kusto.Tests/AddAzureKustoTests.cs
Labels: area-integrations, community-contribution

#11246 Mark Aspire.Hosting.Azure.Kusto as a preview package
  src/Aspire.Hosting.Azure.Kusto/Aspire.Hosting.Azure.Kusto.csproj
Labels: area-integrations, community-contribution

#11249 Mark Kusto db as FailedToStart if creation fails
  playground/AzureKusto/AzureKusto.AppHost/Program.cs
  src/Aspire.Hosting.Azure.Kusto/AzureKustoBuilderExtensions.cs
  tests/Aspire.Hosting.Azure.Kusto.Tests/Aspire.Hosting.Azure.Kusto.Tests.csproj
  tests/Aspire.Hosting.Azure.Kusto.Tests/KustoFunctionalTests.cs
Labels: area-integrations, community-contribution

#11237 Use MEAI for AI telemetry
  src/Components/Aspire.Azure.AI.Inference/AspireAzureAIInferenceExtensions.cs
  src/Components/Aspire.Azure.AI.Inference/AspireChatCompletionsClientBuilder.cs
  src/Components/Aspire.Azure.AI.Inference/ChatCompletionsClientSettings.cs
  src/Components/Aspire.Azure.AI.Inference/ConfigurationSchema.json
  src/Components/Aspire.Azure.AI.OpenAI/AspireAzureOpenAIClientBuilder.cs
  src/Components/Aspire.Azure.AI.OpenAI/AspireAzureOpenAIExtensions.cs
  src/Components/Aspire.Azure.AI.OpenAI/AzureOpenAISettings.cs
  src/Components/Aspire.Azure.AI.OpenAI/ConfigurationSchema.json
  src/Components/Aspire.OpenAI/AspireOpenAIClientBuilder.cs
  src/Components/Aspire.OpenAI/AspireOpenAIClientBuilderChatClientExtensions.cs
  src/Components/Aspire.OpenAI/AspireOpenAIClientBuilderEmbeddingGeneratorExtensions.cs
  src/Components/Aspire.OpenAI/AspireOpenAIExtensions.cs
  src/Components/Aspire.OpenAI/ConfigurationSchema.json
  src/Components/Aspire.OpenAI/OpenAISettings.cs
  tests/Aspire.Azure.AI.Inference.Tests/ConformanceTests.cs
  tests/Aspire.Azure.AI.OpenAI.Tests/AIOpenAIPublicApiTests.cs
  tests/Aspire.Azure.AI.OpenAI.Tests/AzureOpenAISettingsTests.cs
  tests/Aspire.Azure.AI.OpenAI.Tests/ConformanceTests.cs
  tests/Aspire.OpenAI.Tests/ConformanceTests.cs
  tests/Aspire.OpenAI.Tests/OpenAIPublicApiTests.cs
  tests/Aspire.OpenAI.Tests/OpenAISettingsTests.cs
Labels: area-integrations

#11135 Move executable command / working directory to be annotation based
  src/Aspire.Hosting/ApplicationModel/ExecutableAnnotation.cs
  src/Aspire.Hosting/ApplicationModel/ExecutableResource.cs
  src/Aspire.Hosting/ExecutableResourceBuilderExtensions.cs
  tests/Aspire.Hosting.Tests/ExecutableResourceBuilderExtensionTests.cs
Labels: area-app-model, community-contribution

#11287 Only capitalize start of title
  src/Aspire.Hosting/Resources/InteractionStrings.Designer.cs
  src/Aspire.Hosting/Resources/InteractionStrings.resx
  src/Aspire.Hosting/Resources/xlf/InteractionStrings.cs.xlf
  src/Aspire.Hosting/Resources/xlf/InteractionStrings.de.xlf
  src/Aspire.Hosting/Resources/xlf/InteractionStrings.es.xlf
  src/Aspire.Hosting/Resources/xlf/InteractionStrings.fr.xlf
  src/Aspire.Hosting/Resources/xlf/InteractionStrings.it.xlf
  src/Aspire.Hosting/Resources/xlf/InteractionStrings.ja.xlf
  src/Aspire.Hosting/Resources/xlf/InteractionStrings.ko.xlf
  src/Aspire.Hosting/Resources/xlf/InteractionStrings.pl.xlf
  src/Aspire.Hosting/Resources/xlf/InteractionStrings.pt-BR.xlf
  src/Aspire.Hosting/Resources/xlf/InteractionStrings.ru.xlf
  src/Aspire.Hosting/Resources/xlf/InteractionStrings.tr.xlf
  src/Aspire.Hosting/Resources/xlf/InteractionStrings.zh-Hans.xlf
  src/Aspire.Hosting/Resources/xlf/InteractionStrings.zh-Hant.xlf
Labels: area-app-model

#11248 Parallelize more deployment steps
  src/Aspire.Hosting.Azure/AzureDeployingContext.cs
Labels: area-app-model

#11286 Improve GenAI and interactions Markdown rendering
  src/Aspire.Dashboard/Components/App.razor
  src/Aspire.Dashboard/Components/Controls/MarkdownRenderer.razor
  src/Aspire.Dashboard/Components/Controls/MarkdownRenderer.razor.cs
  src/Aspire.Dashboard/Components/Controls/MarkdownRenderer.razor.js
  src/Aspire.Dashboard/Components/Dialogs/GenAIVisualizerDialog.razor
  src/Aspire.Dashboard/Components/Dialogs/GenAIVisualizerDialog.razor.cs
  src/Aspire.Dashboard/Components/Dialogs/GenAIVisualizerDialog.razor.css
  src/Aspire.Dashboard/Components/Dialogs/InteractionsInputDialog.razor
  src/Aspire.Dashboard/Components/Dialogs/InteractionsInputDialog.razor.cs
  src/Aspire.Dashboard/Components/Dialogs/InteractionsInputDialog.razor.css
  src/Aspire.Dashboard/Components/Interactions/InteractionsProvider.cs
  src/Aspire.Dashboard/Model/GenAI/GenAIMarkdownHelper.cs
  src/Aspire.Dashboard/Model/Interaction/InputViewModel.cs
  src/Aspire.Dashboard/Model/Interaction/InteractionMarkdownHelper.cs
  src/Aspire.Dashboard/Model/Interaction/InteractionsInputsDialogViewModel.cs
  src/Aspire.Dashboard/Model/Markdown/AspireCodeBlockExtension.cs
  src/Aspire.Dashboard/Model/Markdown/HighlightedCodeBlockRenderer.cs
  src/Aspire.Dashboard/Model/Markdown/MarkdownHelpers.cs
  src/Aspire.Dashboard/Model/Markdown/MarkdownOptions.cs
  src/Aspire.Dashboard/Model/Markdown/MarkdownProcessor.cs
  src/Aspire.Dashboard/Utils/InteractionMarkdownHelper.cs
  src/Aspire.Dashboard/wwwroot/css/markdown.css
  src/Aspire.Dashboard/wwwroot/js/app.js
  tests/Aspire.Dashboard.Components.Tests/Interactions/InteractionsProviderTests.cs
Labels: area-dashboard

#11304 Set OTEL_INSTRUMENTATION_GENAI_CAPTURE_MESSAGE_CONTENT to true in local development
  src/Aspire.Hosting/OtlpConfigurationExtensions.cs
  tests/Aspire.Hosting.Tests/ProjectResourceTests.cs
Labels: area-app-model

#11302 Support for container app job
  src/Aspire.Hosting.Azure.AppContainers/AzureContainerAppJobCustomizationAnnotation.cs
  src/Aspire.Hosting.Azure.AppContainers/BaseContainerAppContext.cs
  src/Aspire.Hosting.Azure.AppContainers/ContainerAppContext.cs
  src/Aspire.Hosting.Azure.AppContainers/ContainerAppEnvironmentContext.cs
  src/Aspire.Hosting.Azure.AppContainers/ContainerAppExtensions.cs
  src/Aspire.Hosting.Azure.AppContainers/ContainerAppJobContext.cs
  tests/Aspire.Hosting.Azure.Tests/AzureContainerAppsTests.cs
  tests/Aspire.Hosting.Azure.Tests/Snapshots/AzureContainerAppsTests.PublishAsContainerAppJobInfluencesContainerAppDefinition.verified.bicep
  tests/Aspire.Hosting.Azure.Tests/Snapshots/AzureContainerAppsTests.PublishAsContainerAppJob_WorksForProjectResource.verified.bicep
Labels: area-integrations, azure

#11216 Automatically apply WithUrl with relative URL to all URLs
  src/Aspire.Hosting/Orchestrator/ApplicationOrchestrator.cs
  src/Aspire.Hosting/ResourceBuilderExtensions.cs
  tests/Aspire.Hosting.Tests/WithUrlsTests.cs
Labels: area-app-model

#11387 Update whats-new-95.md
  tools/ReleaseNotes/data/whats-new-95.md
Labels: area-codeflow, community-contribution

#11395 Add tooltip to selects with long content
  src/Aspire.Dashboard/Components/Controls/ResourceSelectOptionTemplate.razor
  src/Aspire.Dashboard/Components/Dialogs/FilterDialog.razor
  src/Aspire.Dashboard/Components/Dialogs/InteractionsInputDialog.razor
Labels: area-dashboard

#11409 Fail if PublishAsAzureContainerAppJob is called without AddAzureContainerAppEnvironment
  src/Aspire.Hosting.Azure.AppContainers/AzureContainerAppsInfrastructure.cs
  tests/Aspire.Hosting.Azure.Tests/AzureContainerAppsTests.cs
Labels: area-integrations

#11283 Properly compare tokens using timingSafeEqual in extension and remove token parameter from extension rpc target
  extension/package.json
  extension/src/dcp/AspireDcpServer.ts
  extension/src/extension.ts
  extension/src/server/AspireRpcServer.ts
  extension/src/server/rpcClient.ts
  extension/src/utils/security.ts
  src/Aspire.Cli/Backchannel/ExtensionRpcTarget.cs
Labels: needs-area-label

#11324 Add cloud type filter to tracing pages
  src/Aspire.Dashboard/Model/SpanType.cs
  src/Aspire.Dashboard/Resources/ControlsStrings.Designer.cs
  src/Aspire.Dashboard/Resources/ControlsStrings.resx
  src/Aspire.Dashboard/Resources/xlf/ControlsStrings.cs.xlf
  src/Aspire.Dashboard/Resources/xlf/ControlsStrings.de.xlf
  src/Aspire.Dashboard/Resources/xlf/ControlsStrings.es.xlf
  src/Aspire.Dashboard/Resources/xlf/ControlsStrings.fr.xlf
  src/Aspire.Dashboard/Resources/xlf/ControlsStrings.it.xlf
  src/Aspire.Dashboard/Resources/xlf/ControlsStrings.ja.xlf
  src/Aspire.Dashboard/Resources/xlf/ControlsStrings.ko.xlf
  src/Aspire.Dashboard/Resources/xlf/ControlsStrings.pl.xlf
  src/Aspire.Dashboard/Resources/xlf/ControlsStrings.pt-BR.xlf
  src/Aspire.Dashboard/Resources/xlf/ControlsStrings.ru.xlf
  src/Aspire.Dashboard/Resources/xlf/ControlsStrings.tr.xlf
  src/Aspire.Dashboard/Resources/xlf/ControlsStrings.zh-Hans.xlf
  src/Aspire.Dashboard/Resources/xlf/ControlsStrings.zh-Hant.xlf
  tests/Aspire.Dashboard.Tests/Model/SpanWaterfallViewModelTests.cs
Labels: area-dashboard

#11361 Add span details action menu with GenAI link
  src/Aspire.Dashboard/Components/Controls/SpanDetails.razor
  src/Aspire.Dashboard/Components/Controls/SpanDetails.razor.cs
  src/Aspire.Dashboard/Components/Dialogs/GenAIVisualizerDialog.razor
  src/Aspire.Dashboard/Components/Pages/TraceDetail.razor
  src/Aspire.Dashboard/Components/Pages/TraceDetail.razor.cs
Labels: area-dashboard

#11402 GenAI visualizer improvements and bug fixes
  playground/Stress/Stress.ApiService/Program.cs
  playground/Stress/Stress.AppHost/Program.cs
  src/Aspire.Dashboard/Components/Controls/TextVisualizer.razor
  src/Aspire.Dashboard/Components/Controls/TextVisualizer.razor.cs
  src/Aspire.Dashboard/Components/Controls/TreeGenAISelector.razor
  src/Aspire.Dashboard/Components/Controls/TreeGenAISelector.razor.cs
  src/Aspire.Dashboard/Components/Dialogs/GenAIVisualizerDialog.razor
  src/Aspire.Dashboard/Components/Dialogs/GenAIVisualizerDialog.razor.cs
  src/Aspire.Dashboard/Components/Dialogs/GenAIVisualizerDialog.razor.css
  src/Aspire.Dashboard/Model/GenAI/GenAIItemPartViewModel.cs
  src/Aspire.Dashboard/Model/GenAI/GenAIMessages.cs
  src/Aspire.Dashboard/Model/GenAI/GenAIVisualizerDialogViewModel.cs
  tests/Aspire.Dashboard.Tests/Model/GenAIVisualizerDialogViewModelTests.cs
Labels: area-dashboard

#11416 Improve display of replica instances in resource selector
  src/Aspire.Dashboard/Components/Controls/ResourceSelectOptionTemplate.razor
Labels: area-dashboard

#10231 Add extension-compatible aspire config command implementation
  extension/src/server/interactionService.ts
  extension/src/test/rpc/interactionServiceTests.test.ts
  src/Aspire.Cli/Backchannel/ExtensionBackchannel.cs
  src/Aspire.Cli/Commands/BaseConfigSubCommand.cs
  src/Aspire.Cli/Commands/ConfigCommand.cs
  src/Aspire.Cli/Commands/NewCommand.cs
  src/Aspire.Cli/Configuration/ConfigurationService.cs
  src/Aspire.Cli/Configuration/IConfigurationService.cs
  src/Aspire.Cli/Interaction/ExtensionInteractionService.cs
  src/Aspire.Cli/Resources/ConfigCommandStrings.Designer.cs
  src/Aspire.Cli/Resources/ConfigCommandStrings.resx
  src/Aspire.Cli/Resources/xlf/ConfigCommandStrings.cs.xlf
  src/Aspire.Cli/Resources/xlf/ConfigCommandStrings.de.xlf
  src/Aspire.Cli/Resources/xlf/ConfigCommandStrings.es.xlf
  src/Aspire.Cli/Resources/xlf/ConfigCommandStrings.fr.xlf
  src/Aspire.Cli/Resources/xlf/ConfigCommandStrings.it.xlf
  src/Aspire.Cli/Resources/xlf/ConfigCommandStrings.ja.xlf
  src/Aspire.Cli/Resources/xlf/ConfigCommandStrings.ko.xlf
  src/Aspire.Cli/Resources/xlf/ConfigCommandStrings.pl.xlf
  src/Aspire.Cli/Resources/xlf/ConfigCommandStrings.pt-BR.xlf
  src/Aspire.Cli/Resources/xlf/ConfigCommandStrings.ru.xlf
  src/Aspire.Cli/Resources/xlf/ConfigCommandStrings.tr.xlf
  src/Aspire.Cli/Resources/xlf/ConfigCommandStrings.zh-Hans.xlf
  src/Aspire.Cli/Resources/xlf/ConfigCommandStrings.zh-Hant.xlf
  src/Aspire.Hosting/Resources/CommandStrings.Designer.cs
  src/Aspire.Hosting/Resources/InteractionStrings.Designer.cs
  src/Aspire.Hosting/Resources/LaunchProfileStrings.Designer.cs
  src/Aspire.Hosting/Resources/MessageStrings.Designer.cs
  tests/Aspire.Cli.Tests/Commands/ConfigCommandTests.cs
  tests/Aspire.Cli.Tests/Projects/ProjectLocatorTests.cs
  tests/Aspire.Cli.Tests/TestServices/TestExtensionBackchannel.cs
  tests/Aspire.Cli.Tests/TestServices/TestExtensionInteractionService.cs
Labels: area-cli

#11419 Update to latest runtime, aspnetcore, and extensions
  Directory.Packages.props
  eng/Version.Details.xml
  eng/Versions.props
Labels: area-codeflow

#11439 Ensure devtunnels CLI is at least minimum required version
  src/Aspire.Hosting.DevTunnels/DevTunnelCli.cs
  src/Aspire.Hosting.DevTunnels/DevTunnelCliClient.cs
  src/Aspire.Hosting.DevTunnels/DevTunnelCliInstallationManager.cs
  src/Aspire.Hosting.DevTunnels/IDevTunnelClient.cs
  src/Aspire.Hosting.DevTunnels/RequiredCommandValidator.cs
  tests/Aspire.Hosting.DevTunnels.Tests/DevTunnelCliInstallationManagerTests.cs
Labels: area-integrations

#11446 Fix text visualizer dialog max height
  playground/Stress/Stress.AppHost/Program.cs
  src/Aspire.Dashboard/Components/Dialogs/TextVisualizerDialog.razor.css
Labels: area-dashboard

#11352 Fix up passing Dockerfile build arguments and secrets
  playground/deployers/Deployers.AppHost/AppHost.cs
  playground/deployers/Deployers.Dockerfile/Dockerfile
  playground/deployers/Deployers.Dockerfile/app.py
  src/Aspire.Hosting/Publishing/DockerContainerRuntime.cs
  src/Aspire.Hosting/Publishing/IContainerRuntime.cs
  src/Aspire.Hosting/Publishing/PodmanContainerRuntime.cs
  src/Aspire.Hosting/Publishing/ResourceContainerImageBuilder.cs
  tests/Aspire.Hosting.Tests/Publishing/ResourceContainerImageBuilderTests.cs
Labels: area-deployment

#11464 More updates! (to whats new)
  tools/ReleaseNotes/data/whats-new-95.md
Labels: needs-area-label

#11457 Refactor Program.cs to use app.UseStaticFiles() and update WebFrontEnd.csproj to target DefaultTargetFramework
  Aspire.slnx
  playground/DevTunnels/DevTunnels.ApiService/DevTunnels.ApiService.csproj
  playground/DevTunnels/DevTunnels.ApiService/Program.cs
  playground/DevTunnels/DevTunnels.ApiService/Properties/launchSettings.json
  playground/DevTunnels/DevTunnels.ApiService/appsettings.Development.json
  playground/DevTunnels/DevTunnels.ApiService/appsettings.json
  playground/DevTunnels/DevTunnels.AppHost/AppHost.cs
  playground/DevTunnels/DevTunnels.AppHost/DevTunnels.AppHost.csproj
  playground/DevTunnels/DevTunnels.WebFrontEnd/Components/App.razor
  playground/DevTunnels/DevTunnels.WebFrontEnd/Components/Layout/MainLayout.razor
  playground/DevTunnels/DevTunnels.WebFrontEnd/Components/Layout/MainLayout.razor.css
  playground/DevTunnels/DevTunnels.WebFrontEnd/Components/Layout/NavMenu.razor
  playground/DevTunnels/DevTunnels.WebFrontEnd/Components/Layout/NavMenu.razor.css
  playground/DevTunnels/DevTunnels.WebFrontEnd/Components/Pages/Counter.razor
  playground/DevTunnels/DevTunnels.WebFrontEnd/Components/Pages/Error.razor
  playground/DevTunnels/DevTunnels.WebFrontEnd/Components/Pages/Home.razor
  playground/DevTunnels/DevTunnels.WebFrontEnd/Components/Routes.razor
  playground/DevTunnels/DevTunnels.WebFrontEnd/Components/_Imports.razor
  playground/DevTunnels/DevTunnels.WebFrontEnd/DevTunnels.WebFrontEnd.csproj
  playground/DevTunnels/DevTunnels.WebFrontEnd/Program.cs
  playground/DevTunnels/DevTunnels.WebFrontEnd/Properties/launchSettings.json
  playground/DevTunnels/DevTunnels.WebFrontEnd/appsettings.Development.json
  playground/DevTunnels/DevTunnels.WebFrontEnd/appsettings.json
  playground/DevTunnels/DevTunnels.WebFrontEnd/wwwroot/app.css
  playground/DevTunnels/DevTunnels.WebFrontEnd/wwwroot/favicon.png
Labels: area-integrations

#11486 [release/9.4] Bump KubernetesClient version to 17.0.14
  Directory.Packages.props
Labels: area-codeflow

#11495 Fix restore issue by fixing xunit version
  eng/Versions.props
Labels: area-codeflow

#11471 Refactor dashboard accent colors
  src/Aspire.Dashboard/Components/Controls/GenAIItemTitle.razor
  src/Aspire.Dashboard/Components/Controls/LogViewer.razor
  src/Aspire.Dashboard/Components/Controls/PropertyValues/ResourceNameValue.razor
  src/Aspire.Dashboard/Components/Controls/SpanDetails.razor
  src/Aspire.Dashboard/Components/Dialogs/ExemplarsDialog.razor
  src/Aspire.Dashboard/Components/Pages/StructuredLogs.razor
  src/Aspire.Dashboard/Components/Pages/TraceDetail.razor
  src/Aspire.Dashboard/Components/Pages/Traces.razor
  src/Aspire.Dashboard/Components/ResourcesGridColumns/ResourceNameDisplay.razor
  src/Aspire.Dashboard/Model/ResourceGraph/ResourceGraphMapper.cs
  src/Aspire.Dashboard/Otlp/Model/ColorGenerator.cs
  src/Aspire.Dashboard/wwwroot/css/app.css
Labels: area-dashboard

#11497 [release/9.5] Support prompting for generated values during deploy
  src/Aspire.Hosting.Azure/AzureDeployingContext.cs
  src/Aspire.Hosting/Orchestrator/ParameterProcessor.cs
  tests/Aspire.Hosting.Azure.Tests/AzureDeployerTests.cs
  tests/Aspire.Hosting.Tests/Orchestrator/ApplicationOrchestratorTests.cs
  tests/Aspire.Hosting.Tests/Orchestrator/ParameterProcessorTests.cs
Labels: Servicing-approved, area-deployment

#11520 9.5 API Review Feedback Round 1
  src/Aspire.Hosting.Azure.AIFoundry/AzureAIFoundryResource.cs
  src/Aspire.Hosting.Azure.AppConfiguration/AzureAppConfigurationResource.cs
  src/Aspire.Hosting.Azure.AppContainers/AzureContainerAppEnvironmentResource.cs
  src/Aspire.Hosting.Azure.AppContainers/ContainerAppExtensions.cs
  src/Aspire.Hosting.Azure.AppService/AzureAppServiceEnvironmentResource.cs
  src/Aspire.Hosting.Azure.CognitiveServices/AzureOpenAIResource.cs
  src/Aspire.Hosting.Azure.ContainerRegistry/AzureContainerRegistryResource.cs
  src/Aspire.Hosting.Azure.CosmosDB/AzureCosmosDBResource.cs
  src/Aspire.Hosting.Azure.EventHubs/AzureEventHubsResource.cs
  src/Aspire.Hosting.Azure.KeyVault/AzureKeyVaultResource.cs
  src/Aspire.Hosting.Azure.Kusto/AzureKustoBuilderExtensions.cs
  src/Aspire.Hosting.Azure.Kusto/AzureKustoClusterResource.cs
  src/Aspire.Hosting.Azure.Kusto/AzureKustoEmulatorResource.cs
  src/Aspire.Hosting.Azure.OperationalInsights/AzureLogAnalyticsWorkspaceResource.cs
  src/Aspire.Hosting.Azure.PostgreSQL/AzurePostgresFlexibleServerResource.cs
  src/Aspire.Hosting.Azure.Redis/AzureRedisCacheResource.cs
  src/Aspire.Hosting.Azure.Redis/AzureRedisEnterpriseResource.cs
  src/Aspire.Hosting.Azure.Search/AzureSearchResource.cs
  src/Aspire.Hosting.Azure.ServiceBus/AzureServiceBusResource.cs
  src/Aspire.Hosting.Azure.SignalR/AzureSignalRResource.cs
  src/Aspire.Hosting.Azure.Sql/AzureSqlServerResource.cs
  src/Aspire.Hosting.Azure.Storage/AzureStorageResource.cs
  src/Aspire.Hosting.Azure.WebPubSub/AzureWebPubSubResource.cs
  src/Aspire.Hosting.Azure/AzureDeployingContext.cs
  src/Aspire.Hosting.Azure/AzureProvisioningResource.cs
  src/Aspire.Hosting.Azure/AzureProvisioningResourceExtensions.cs
  src/Aspire.Hosting.Azure/AzureUserAssignedIdentityResource.cs
  src/Aspire.Hosting.DevTunnels/DevTunnelResource.cs
  src/Aspire.Hosting/ApplicationModel/ContainerImageReference.cs
  src/Aspire.Hosting/ApplicationModel/DeploymentImageTagAnnotation.cs
  src/Aspire.Hosting/ApplicationModel/ResourceExtensions.cs
  src/Aspire.Hosting/IInteractionService.cs
  tests/Aspire.Hosting.Azure.Kusto.Tests/AddAzureKustoTests.cs
  tests/Aspire.Hosting.Azure.Kusto.Tests/KustoPublicApiTests.cs
  tests/Aspire.Hosting.Azure.Tests/AzureContainerAppsTests.cs
  tests/Aspire.Hosting.Azure.Tests/Snapshots/AzureContainerAppsTests.PublishAsAzureContainerAppJobWithCronExpressionConfiguresScheduleTrigger.verified.bicep
  tests/Aspire.Hosting.Azure.Tests/Snapshots/AzureContainerAppsTests.PublishAsAzureContainerAppJobWithCronExpressionConfiguresScheduleTrigger.verified.json
  tests/Aspire.Hosting.Azure.Tests/Snapshots/AzureContainerAppsTests.PublishAsScheduledAzureContainerAppJobConfiguresScheduleTrigger.verified.bicep
  tests/Aspire.Hosting.Tests/ResourceExtensionsTests.cs
Labels: needs-area-label

#11525 Ensure devtunnel URLs are updated when started
  src/Aspire.Hosting.DevTunnels/DevTunnelResourceBuilderExtensions.cs
Labels: needs-area-label

#11532 Fix 9.5 option in templates & update 9.4 option to 9.4.1
  src/Aspire.ProjectTemplates/README.md
  src/Aspire.ProjectTemplates/templates/aspire-apphost/.template.config/template.json
  src/Aspire.ProjectTemplates/templates/aspire-apphost/9.4/Aspire.AppHost1.csproj
  src/Aspire.ProjectTemplates/templates/aspire-empty/.template.config/localize/templatestrings.cs.json
  src/Aspire.ProjectTemplates/templates/aspire-empty/.template.config/localize/templatestrings.de.json
  src/Aspire.ProjectTemplates/templates/aspire-empty/.template.config/localize/templatestrings.en.json
  src/Aspire.ProjectTemplates/templates/aspire-empty/.template.config/localize/templatestrings.es.json
  src/Aspire.ProjectTemplates/templates/aspire-empty/.template.config/localize/templatestrings.fr.json
  src/Aspire.ProjectTemplates/templates/aspire-empty/.template.config/localize/templatestrings.it.json
  src/Aspire.ProjectTemplates/templates/aspire-empty/.template.config/localize/templatestrings.ja.json
  src/Aspire.ProjectTemplates/templates/aspire-empty/.template.config/localize/templatestrings.ko.json
  src/Aspire.ProjectTemplates/templates/aspire-empty/.template.config/localize/templatestrings.pl.json
  src/Aspire.ProjectTemplates/templates/aspire-empty/.template.config/localize/templatestrings.pt-BR.json
  src/Aspire.ProjectTemplates/templates/aspire-empty/.template.config/localize/templatestrings.ru.json
  src/Aspire.ProjectTemplates/templates/aspire-empty/.template.config/localize/templatestrings.tr.json
  src/Aspire.ProjectTemplates/templates/aspire-empty/.template.config/localize/templatestrings.zh-Hans.json
  src/Aspire.ProjectTemplates/templates/aspire-empty/.template.config/localize/templatestrings.zh-Hant.json
  src/Aspire.ProjectTemplates/templates/aspire-empty/.template.config/template.json
  src/Aspire.ProjectTemplates/templates/aspire-empty/9.4/AspireApplication.1.AppHost/AspireApplication.1.AppHost.csproj
  src/Aspire.ProjectTemplates/templates/aspire-empty/9.4/AspireApplication.1.ServiceDefaults/AspireApplication.1.ServiceDefaults.csproj
  src/Aspire.ProjectTemplates/templates/aspire-mstest/.template.config/template.json
  src/Aspire.ProjectTemplates/templates/aspire-mstest/9.4/Aspire.Tests.1.csproj
  src/Aspire.ProjectTemplates/templates/aspire-nunit/.template.config/template.json
  src/Aspire.ProjectTemplates/templates/aspire-nunit/9.4/Aspire.Tests.1.csproj
  src/Aspire.ProjectTemplates/templates/aspire-servicedefaults/.template.config/template.json
  src/Aspire.ProjectTemplates/templates/aspire-servicedefaults/9.4/Aspire.ServiceDefaults1.csproj
  src/Aspire.ProjectTemplates/templates/aspire-starter/.template.config/template.json
  src/Aspire.ProjectTemplates/templates/aspire-starter/9.4/Aspire-StarterApplication.1.AppHost/Aspire-StarterApplication.1.AppHost.csproj
  src/Aspire.ProjectTemplates/templates/aspire-starter/9.4/Aspire-StarterApplication.1.ServiceDefaults/Aspire-StarterApplication.1.ServiceDefaults.csproj
  src/Aspire.ProjectTemplates/templates/aspire-starter/9.4/Aspire-StarterApplication.1.Tests/Aspire-StarterApplication.1.Tests.csproj
  src/Aspire.ProjectTemplates/templates/aspire-starter/9.4/Aspire-StarterApplication.1.Web/Aspire-StarterApplication.1.Web.csproj
  src/Aspire.ProjectTemplates/templates/aspire-xunit/.template.config/template.json
  src/Aspire.ProjectTemplates/templates/aspire-xunit/9.4/Aspire.Tests.1.csproj
Labels: area-templates, Servicing-approved

#11530 Fix remove logs error
  src/Aspire.Dashboard/Components/Pages/ConsoleLogs.razor.cs
  src/Aspire.Dashboard/Model/ConsoleLogsFilters.cs
  tests/Aspire.Dashboard.Tests/Model/ConsoleLogsFiltersTests.cs
Labels: area-dashboard

#11523 Update extension strings and readme
  extension/README.md
  extension/package.nls.cs.json
  extension/package.nls.de.json
  extension/package.nls.es.json
  extension/package.nls.fr.json
  extension/package.nls.it.json
  extension/package.nls.ja.json
  extension/package.nls.json
  extension/package.nls.ko.json
  extension/package.nls.pl.json
  extension/package.nls.pt-br.json
  extension/package.nls.ru.json
  extension/package.nls.tr.json
  extension/package.nls.zh-cn.json
  extension/package.nls.zh-tw.json
  extension/src/loc/strings.ts
Labels: needs-area-label

#11548 Display multiple log lines in tooltip
  src/Aspire.Dashboard/Components/Pages/TraceDetail.razor
  src/Aspire.Dashboard/Components/Pages/TraceDetail.razor.css
Labels: area-dashboard

#11549 Prefer older nowrap CSS rule
  src/Aspire.Dashboard/Components/Pages/TraceDetail.razor.css
Labels: area-dashboard

#11611 Add a size check for the max size of the aspire CLI executable.
  eng/clipack/Common.projitems
Labels: area-engineering-systems

#11665 Merge in changes from 'release/9.5' branch
  src/Aspire.Cli/Aspire.Cli.csproj
  src/Aspire.Hosting.Azure.AppContainers/BaseContainerAppContext.cs
  src/Aspire.Hosting.Azure.AppService/AzureAppServiceWebsiteContext.cs
  src/Aspire.Hosting.Azure/AzureDeployingContext.cs
  src/Aspire.Hosting.Azure/AzureEnvironmentResource.cs
  src/Aspire.Hosting.Docker/DockerComposeEnvironmentContext.cs
  src/Aspire.Hosting.Docker/DockerComposeInfrastructure.cs
  src/Aspire.Hosting.Docker/DockerComposeServiceExtensions.cs
  src/Aspire.Hosting.Docker/DockerComposeServiceResource.cs
  src/Aspire.Hosting/ApplicationModel/ContainerImageReference.cs
  src/Aspire.Hosting/ApplicationModel/DeploymentImageTagAnnotation.cs
  tests/Aspire.Hosting.Tests/ResourceExtensionsTests.cs
Labels: needs-area-label

#11678 Enable building of extensions in the internal build pipeline using property directly instead of switch
  eng/pipelines/templates/BuildAndTest.yml
Labels: area-engineering-systems

#11680 Suppress Docker security warnings for playground applications
  playground/AspireWithJavaScript/AspireJavaScript.Angular/Dockerfile
  playground/AspireWithJavaScript/AspireJavaScript.React/Dockerfile
  playground/AspireWithJavaScript/AspireJavaScript.Vite/Dockerfile
  playground/AspireWithJavaScript/AspireJavaScript.Vue/Dockerfile
  playground/AspireWithNode/NodeFrontend/Dockerfile
  playground/AspireWithPython/InstrumentedPythonProject/Dockerfile
Labels: area-integrations

#11695 Rename AppHost.cs to Program.cs in AspireWithNode.AspNetCoreApi sample
  playground/AspireWithNode/AspireWithNode.AspNetCoreApi/Program.cs
Labels: needs-area-label, community-contribution

#11733 Don't require gen_ai.system attribute on span events
  src/Aspire.Dashboard/Model/GenAI/GenAIVisualizerDialogViewModel.cs
  tests/Aspire.Dashboard.Tests/Model/GenAIVisualizerDialogViewModelTests.cs
Labels: area-dashboard

#11738 Truncate span name with ellipsis
  src/Aspire.Dashboard/Components/Pages/TraceDetail.razor.css
Labels: area-dashboard

#11266 Obsolete the `IDistributedApplicationLifecycleHook` interface and extension methods and add a new eventing based replacement
  playground/CustomResources/CustomResources.AppHost/TestResource.cs
  playground/HealthChecks/HealthChecksSandbox.AppHost/Program.cs
  playground/Stress/Stress.AppHost/TestResource.cs
  src/Aspire.Hosting.Azure.AppContainers/AzureContainerAppExtensions.cs
  src/Aspire.Hosting.Azure.AppContainers/AzureContainerAppsInfrastructure.cs
  src/Aspire.Hosting.Azure.AppService/AzureAppServiceEnvironmentExtensions.cs
  src/Aspire.Hosting.Azure.AppService/AzureAppServiceInfrastructure.cs
  src/Aspire.Hosting.Azure/AzureResourcePreparer.cs
  src/Aspire.Hosting.Azure/Provisioning/AzureProvisionerExtensions.cs
  src/Aspire.Hosting.Azure/Provisioning/Provisioners/AzureProvisioner.cs
  src/Aspire.Hosting.Docker/DockerComposeEnvironmentExtensions.cs
  src/Aspire.Hosting.Docker/DockerComposeInfrastructure.cs
  src/Aspire.Hosting.Kubernetes/KubernetesEnvironmentExtensions.cs
  src/Aspire.Hosting.Kubernetes/KubernetesInfrastructure.cs
  src/Aspire.Hosting/Dashboard/DashboardEventHandlers.cs
  src/Aspire.Hosting/Devcontainers/DevcontainerPortForwardingLifecycleHook.cs
  src/Aspire.Hosting/DistributedApplication.cs
  src/Aspire.Hosting/DistributedApplicationBuilder.cs
  src/Aspire.Hosting/Lifecycle/EventingSubscriberServiceCollectionExtensions.cs
  src/Aspire.Hosting/Lifecycle/IDistributedApplicationEventingSubscriber.cs
  src/Aspire.Hosting/Lifecycle/IDistributedApplicationLifecycleHook.cs
  src/Aspire.Hosting/Lifecycle/LifecycleHookServiceCollectionExtensions.cs
  src/Aspire.Hosting/Orchestrator/ApplicationOrchestrator.cs
  tests/Aspire.Hosting.Azure.Tests/AzureBicepResourceTests.cs
  tests/Aspire.Hosting.Azure.Tests/AzureFunctionsTests.cs
  tests/Aspire.Hosting.Azure.Tests/AzureManifestUtils.cs
  tests/Aspire.Hosting.Tests/Dashboard/DashboardLifecycleHookTests.cs
  tests/Aspire.Hosting.Tests/Dashboard/DashboardResourceTests.cs
  tests/Aspire.Hosting.Tests/DistributedApplicationBuilderTests.cs
  tests/Aspire.Hosting.Tests/DistributedApplicationTests.cs
  tests/Aspire.Hosting.Tests/Helpers/CallbackLifecycleHook.cs
  tests/Aspire.Hosting.Tests/Helpers/DummyLifecycleHook.cs
  tests/Aspire.Playground.Tests/Infrastructure/DistributedApplicationTestFactory.cs
  tests/Shared/TemplatesTesting/AspireProject.cs
  tests/Shared/TemplatesTesting/data/EndPointWriterHook_cs
  tests/testproject/TestProject.AppHost/TestProgram.cs
Labels: area-app-model, breaking-change
