Repository dotnet/aspire, pull requests merged in 2025-04, with the labels that each got.

#8431 Update visualizer secret warning and fixed regression
  src/Aspire.Dashboard/Components/Controls/TotalItemsFooter.razor
  src/Aspire.Dashboard/Components/Dialogs/TextVisualizerDialog.razor
  src/Aspire.Dashboard/Components/Dialogs/TextVisualizerDialog.razor.cs
  tests/Aspire.Dashboard.Components.Tests/Controls/TextVisualizerDialogTests.cs
Labels: area-dashboard

#8450 Temporary workaround to fix filter dialog combobox
  src/Aspire.Dashboard/Components/Controls/FixedFluentCombobox.razor
  src/Aspire.Dashboard/Components/Controls/FixedFluentCombobox.razor.cs
  src/Aspire.Dashboard/Components/Dialogs/FilterDialog.razor
Labels: area-dashboard

#8455 Add tooltips to resource telemetry menu items
  src/Aspire.Dashboard/Components/Controls/ResourceActions.razor.cs
Labels: area-dashboard

#8452 Detect apphost and check version.
  Directory.Packages.props
  src/Aspire.Cli/Aspire.Cli.csproj
  src/Aspire.Cli/DotNetCliRunner.cs
  src/Aspire.Cli/Program.cs
Labels: area-cli

#8458 Translate WaitAnnotations to docker compose depends_on
  src/Aspire.Hosting.Docker/DockerComposePublishingContext.cs
  src/Aspire.Hosting.Docker/Resources/ComposeNodes/Service.cs
  src/Aspire.Hosting.Docker/Resources/ComposeNodes/ServiceDependency.cs
  tests/Aspire.Hosting.Docker.Tests/DockerComposePublisherTests.cs
Labels: needs-area-label

#8460 Omnibus fixes for `aspire add`
  src/Aspire.Cli/DotNetCliRunner.cs
  src/Aspire.Cli/Program.cs
Labels: area-cli

#8465 Update Docker Compose service conditions to use 'service_started' instead of healthy
  src/Aspire.Hosting.Docker/DockerComposePublishingContext.cs
  tests/Aspire.Hosting.Docker.Tests/DockerComposePublisherTests.cs
Labels: area-integrations

#8463 Disable otel when env not present.
  src/Aspire.Cli/Program.cs
  tests/Aspire.Hosting.Python.Tests/AddPythonAppTests.cs
  tests/Aspire.Hosting.Tests/MSBuildTests.cs
  tests/Aspire.Hosting.Tests/OperationModesTests.cs
Labels: area-cli

#8451 azd up doesn't show the Aspire dashboard URL with AddAzureContainerAppEnvironment
  playground/AzureContainerApps/AzureContainerApps.AppHost/api.module.bicep
  playground/AzureContainerApps/AzureContainerApps.AppHost/aspire-manifest.json
  playground/AzureContainerApps/AzureContainerApps.AppHost/cache.module.bicep
  playground/AzureContainerApps/AzureContainerApps.AppHost/pythonapp.module.bicep
  src/Aspire.Hosting.Azure.AppContainers/AzureContainerAppsInfrastructure.cs
  tests/Aspire.Hosting.Azure.Tests/AzureContainerAppsTests.cs
  tests/Aspire.Hosting.Azure.Tests/AzurePublisherTests.cs
Labels: area-integrations

#8462 Big refactor of run command into separate class.
  src/Aspire.Cli/Commands/BaseCommand.cs
  src/Aspire.Cli/Commands/RunCommand.cs
  src/Aspire.Cli/Program.cs
  src/Aspire.Cli/Utils/AppHostHelper.cs
  src/Aspire.Cli/Utils/CertificatesHelper.cs
  src/Aspire.Cli/Utils/ProjectFileHelper.cs
Labels: area-cli

#8346 Template tests: Add retries to handle browser failures
  tests/Aspire.Templates.Tests/StarterTemplateRunTestsBase.cs
  tests/Aspire.Templates.Tests/StarterTemplateWithRedisCacheTests.cs
  tests/Aspire.Templates.Tests/StarterTemplateWithRedisCacheTests_PreviousTFM.cs
  tests/Aspire.Templates.Tests/TemplateTestsBase.cs
  tests/Shared/Playwright/WrapperForIPage.cs
  tests/Shared/TemplatesTesting/Aspire.Shared.TemplatesTesting.targets
  tests/Shared/TemplatesTesting/AspireProject.cs
  tests/Shared/TemplatesTesting/TestExtensions.cs
Labels: area-integrations

#8469 Update to latest Microsoft.Extensions.AI version
  Directory.Packages.props
  eng/Versions.props
  src/Components/Aspire.Azure.AI.OpenAI/ConfigurationSchema.json
  src/Components/Aspire.OpenAI/AspireOpenAIClientBuilderChatClientExtensions.cs
  src/Components/Aspire.OpenAI/AspireOpenAIClientBuilderEmbeddingGeneratorExtensions.cs
  src/Components/Aspire.OpenAI/MEAIPackageOverrides.targets
  tests/Aspire.Azure.AI.OpenAI.Tests/AspireAzureOpenAIClientBuilderChatClientExtensionsTests.cs
  tests/Aspire.Azure.AI.OpenAI.Tests/AspireAzureOpenAIClientBuilderEmbeddingGeneratorExtensionsTests.cs
  tests/Aspire.OpenAI.Tests/AspireOpenAIClientBuilderChatClientExtensionsTests.cs
  tests/Aspire.OpenAI.Tests/AspireOpenAIClientBuilderEmbeddingGeneratorExtensionsTests.cs
Labels: area-integrations

#8474 change 1-2 mins to longtimeout
  tests/Aspire.Hosting.RabbitMQ.Tests/RabbitMQFunctionalTests.cs
  tests/Aspire.Hosting.Valkey.Tests/Aspire.Hosting.Valkey.Tests.csproj
  tests/Aspire.Hosting.Valkey.Tests/ValkeyFunctionalTests.cs
  tests/Shared/AsyncTestHelpers.cs
Labels: area-integrations

#8448 Add cancellationtoken to test templates
  src/Aspire.ProjectTemplates/templates/aspire-mstest/9.2/IntegrationTest1.cs
  src/Aspire.ProjectTemplates/templates/aspire-nunit/9.2/IntegrationTest1.cs
  src/Aspire.ProjectTemplates/templates/aspire-starter/9.2/Aspire-StarterApplication.1.Tests/WebTests.cs
  src/Aspire.ProjectTemplates/templates/aspire-xunit/9.2/IntegrationTest1.cs
  tests/Aspire.Templates.Tests/NewUpAndBuildSupportProjectTemplatesTests.cs
Labels: area-templates

#8475 [tests] Simplify some dashboard parts of template tests
  tests/Aspire.Templates.Tests/StarterTemplateRunTestsBase.cs
  tests/Aspire.Templates.Tests/TemplateTestsBase.cs
Labels: area-templates

#8471 Refactor new command into its own class
  src/Aspire.Cli/Commands/NewCommand.cs
  src/Aspire.Cli/Commands/RunCommand.cs
  src/Aspire.Cli/Program.cs
  tests/Aspire.Hosting.Python.Tests/AddPythonAppTests.cs
Labels: area-cli

#8407 Review feedback for Azure.EFCore.Npgsql integration
  playground/PostgresEndToEnd/PostgresEndToEnd.ApiService/PostgresEndToEnd.ApiService.csproj
  playground/TestShop/CatalogDb/CatalogDb.csproj
  playground/TestShop/CatalogModel/CatalogModel.csproj
  playground/TestShop/CatalogService/CatalogService.csproj
  playground/bicep/BicepSample.ApiService/BicepSample.ApiService.csproj
  playground/cdk/CdkSample.ApiService/CdkSample.ApiService.csproj
  playground/publishers/Publishers.ApiService/Publishers.ApiService.csproj
  playground/publishers/Publishers.DbSetup/Publishers.DbSetup.csproj
  playground/waitfor/WaitForSandbox.ApiService/WaitForSandbox.ApiService.csproj
  playground/waitfor/WaitForSandbox.DbSetup/WaitForSandbox.DbSetup.csproj
  src/Components/Aspire.Azure.Npgsql.EntityFrameworkCore.PostgreSQL/AspireAzureEFPostgreSqlExtensions.cs
  src/Components/Aspire.Azure.Npgsql/AspireAzureNpgsqlExtensions.cs
  src/Components/Aspire.Npgsql.EntityFrameworkCore.PostgreSQL/Aspire.Npgsql.EntityFrameworkCore.PostgreSQL.csproj
  src/Components/Common/EntityFrameworkUtils.cs
  src/Components/Common/ManagedIdentityTokenCredentialHelpers.cs
  tests/Aspire.Azure.Npgsql.EntityFrameworkCore.PostgreSQL.Tests/Aspire.Azure.Npgsql.EntityFrameworkCore.PostgreSQL.Tests.csproj
  tests/Aspire.Azure.Npgsql.EntityFrameworkCore.PostgreSQL.Tests/AspireAzureEFPostgreSqlExtensionsTests.cs
  tests/Aspire.Azure.Npgsql.EntityFrameworkCore.PostgreSQL.Tests/ConformanceTests.cs
  tests/Aspire.Azure.Npgsql.EntityFrameworkCore.PostgreSQL.Tests/ConformanceTests_TypeSpecificConfig.cs
  tests/Aspire.Azure.Npgsql.EntityFrameworkCore.PostgreSQL.Tests/CustomExecutionStrategy.cs
  tests/Aspire.Azure.Npgsql.EntityFrameworkCore.PostgreSQL.Tests/CustomRetryExecutionStrategy.cs
  tests/Aspire.Azure.Npgsql.EntityFrameworkCore.PostgreSQL.Tests/EnrichNpgsqlTests.cs
  tests/Aspire.Azure.Npgsql.EntityFrameworkCore.PostgreSQL.Tests/FakeTokenCredential.cs
  tests/Aspire.Azure.Npgsql.EntityFrameworkCore.PostgreSQL.Tests/TestDbContext.cs
  tests/Aspire.Azure.Npgsql.EntityFrameworkCore.PostgreSQL.Tests/TokenCredentialTests.cs
  tests/Aspire.Azure.Npgsql.EntityFrameworkCore.PostgreSQL.Tests/WorkaroundToReadProtectedField.cs
  tests/Aspire.Azure.Npgsql.Tests/AspireAzurePostgreSqlNpgsqlExtensionsTests.cs
  tests/Aspire.Npgsql.EntityFrameworkCore.PostgreSQL.Tests/Aspire.Npgsql.EntityFrameworkCore.PostgreSQL.Tests.csproj
  tests/Aspire.Npgsql.EntityFrameworkCore.PostgreSQL.Tests/AspireEFPostgreSqlExtensionsTests.cs
  tests/Aspire.Npgsql.EntityFrameworkCore.PostgreSQL.Tests/WorkaroundToReadProtectedField.cs
Labels: area-integrations

#8484 Ensure legacy browser token env var name is honored
  src/Aspire.Hosting/DistributedApplicationBuilder.cs
Labels: needs-area-label

#8490 When publishing via `aspire publish` the AppHost lifetime should be controlled by CLI.
  src/Aspire.Cli/Program.cs
  src/Aspire.Hosting/Backchannel/AppHostRpcTarget.cs
  src/Aspire.Hosting/Backchannel/BackchannelService.cs
  src/Aspire.Hosting/DistributedApplicationRunner.cs
  tests/Aspire.Hosting.Tests/OperationModesTests.cs
Labels: needs-area-label, area-cli

#8485 Fix role assignments for existing resources
  src/Aspire.Hosting.Azure/Provisioning/Provisioners/BicepProvisioner.cs
Labels: area-app-model

#8493 Fix console logs error when unselecting resource
  src/Aspire.Dashboard/Components/Pages/ConsoleLogs.razor
Labels: area-dashboard

#8199 Run only quarantined tests in outer loop
  .github/workflows/tests-outerloop.yml
  .github/workflows/tests.yml
  eng/Testing.props
  eng/Testing.targets
  eng/build.ps1
  global.json
  tests/Aspire.Azure.Npgsql.Tests/PostgreSQLContainerFixture.cs
  tests/Aspire.Cli.Tests/Hosting/CliOrphanDetectorTests.cs
  tests/Aspire.Components.Common.Tests/ComponentTestConstants.cs
  tests/Aspire.Confluent.Kafka.Tests/KafkaContainerFixture.cs
  tests/Aspire.Dashboard.Tests/Integration/Playwright/AppBarTests.cs
  tests/Aspire.Dashboard.Tests/Integration/Playwright/BrowserTokenAuthenticationTests.cs
  tests/Aspire.Elastic.Clients.Elasticsearch.Tests/ElasticsearchContainerFixture.cs
  tests/Aspire.Hosting.Azure.Tests/AzureCosmosDBEmulatorFunctionalTests.cs
  tests/Aspire.Hosting.Elasticsearch.Tests/ElasticsearchFunctionalTests.cs
  tests/Aspire.Hosting.MongoDB.Tests/MongoDbFunctionalTests.cs
  tests/Aspire.Hosting.NodeJs.Tests/NodeFunctionalTests.cs
  tests/Aspire.Hosting.Oracle.Tests/OracleFunctionalTests.cs
  tests/Aspire.Hosting.Redis.Tests/RedisFunctionalTests.cs
  tests/Aspire.Hosting.Testing.Tests/TestingBuilderTests.cs
  tests/Aspire.Hosting.Testing.Tests/TestingFactoryTests.cs
  tests/Aspire.Hosting.Tests/Aspire.Hosting.Tests.csproj
  tests/Aspire.Hosting.Tests/Codespaces/CodespacesUrlRewriterTests.cs
  tests/Aspire.Hosting.Tests/DistributedApplicationTests.cs
  tests/Aspire.Hosting.Tests/Health/ResourceHealthCheckServiceTests.cs
  tests/Aspire.Hosting.Tests/ManifestGenerationTests.cs
  tests/Aspire.Hosting.Tests/SlimTestProgramTests.cs
  tests/Aspire.Hosting.Tests/Utils/TestDistributedApplicationBuilder.cs
  tests/Aspire.Hosting.Tests/WithHttpCommandTests.cs
  tests/Aspire.Milvus.Client.Tests/MilvusContainerFixture.cs
  tests/Aspire.MongoDB.Driver.Tests/MongoDbContainerFixture.cs
  tests/Aspire.MySqlConnector.Tests/MySqlContainerFixture.cs
  tests/Aspire.NATS.Net.Tests/NatsContainerFixture.cs
  tests/Aspire.Npgsql.Tests/PostgreSQLContainerFixture.cs
  tests/Aspire.Oracle.EntityFrameworkCore.Tests/OracleContainerFixture.cs
  tests/Aspire.Playground.Tests/AppHostTests.cs
  tests/Aspire.Playground.Tests/Aspire.Playground.Tests.csproj
  tests/Aspire.Playground.Tests/ProjectSpecificTests.cs
  tests/Aspire.Playground.Tests/QuarantinedTestAttribute.cs
  tests/Aspire.Qdrant.Client.Tests/QdrantContainerFixture.cs
  tests/Aspire.RabbitMQ.Client.Tests/AspireRabbitMQLoggingTests.cs
  tests/Aspire.RabbitMQ.Client.Tests/RabbitMQContainerFixture.cs
  tests/Aspire.StackExchange.Redis.Tests/RedisContainerFixture.cs
  tests/Aspire.Templates.Tests/StarterTemplateWithRedisCacheTests.cs
  tests/Aspire.Templates.Tests/StarterTemplateWithRedisCacheTests_PreviousTFM.cs
  tests/Aspire.TestUtilities/QuarantinedTestAttribute.cs
  tests/Aspire.TestUtilities/QuarantinedTestTraitDiscoverer.cs
  tests/Directory.Build.props
  tests/Directory.Build.targets
  tests/Shared/SolutionTests.proj
  tests/helix/send-to-helix-basictests.targets
  tests/helix/send-to-helix-buildonhelixtests.targets
  tests/helix/send-to-helix-endtoendtests.targets
  tests/helix/send-to-helix-templatestests.targets
Labels: area-engineering-systems

#8495 Fix GHA test project selector
  tests/Shared/SolutionTests.proj
Labels: area-engineering-systems, testing ☑️

#8491 Publish, Add, and Root commands to separate classes.
  src/Aspire.Cli/Commands/AddCommand.cs
  src/Aspire.Cli/Commands/PublishCommand.cs
  src/Aspire.Cli/Commands/RootCommand.cs
  src/Aspire.Cli/Program.cs
Labels: area-cli

#8497 Never render secrets into values.yaml
  src/Aspire.Hosting.Kubernetes/KubernetesResourceContext.cs
  tests/Aspire.Hosting.Kubernetes.Tests/ExpectedValues.cs
  tests/Aspire.Hosting.Kubernetes.Tests/KubernetesPublisherTests.cs
Labels: area-app-model

#8406 Davidfowl/fix emulators
  src/Aspire.Hosting.Azure.CosmosDB/AzureCosmosDBExtensions.cs
  src/Aspire.Hosting.Azure.CosmosDB/AzureCosmosDBResource.cs
  src/Aspire.Hosting.Azure.KeyVault/AzureKeyVaultResource.cs
  src/Aspire.Hosting.Azure.KeyVault/AzureKeyVaultSecretReference.cs
  src/Aspire.Hosting.Azure.PostgreSQL/AzurePostgresExtensions.cs
  src/Aspire.Hosting.Azure.Redis/AzureRedisExtensions.cs
  src/Aspire.Hosting.Azure/IKeyVaultResource.cs
  src/Aspire.Hosting.Azure/Provisioning/Provisioners/BicepProvisioner.cs
  tests/Aspire.Hosting.Azure.Tests/AzureBicepResourceTests.cs
  tests/Aspire.Hosting.Azure.Tests/AzureCosmosDBExtensionsTests.cs
  tests/Aspire.Hosting.Azure.Tests/AzurePostgresExtensionsTests.cs
  tests/Aspire.Hosting.Azure.Tests/AzureRedisExtensionsTests.cs
Labels: area-integrations, azure-cosmosdb, azure-keyvault

#8479 Add `NO-MERGE` label to auto created api-diff PR
  .github/workflows/generate-api-diffs.yml
Labels: area-engineering-systems, community-contribution

#8505 Branding updates for 9.3
  eng/Versions.props
Labels: area-codeflow

#8509 Remove Roslyn workaround
  src/Components/Directory.Build.props
Labels: area-integrations

#8508 [tests] Quarantine additional tests for issues open against them
  tests/Aspire.Hosting.Azure.Tests/AzureCosmosDBEmulatorFunctionalTests.cs
  tests/Aspire.Hosting.MySql.Tests/MySqlFunctionalTests.cs
  tests/Aspire.Hosting.Tests/MSBuildTests.cs
  tests/Aspire.Hosting.Tests/OperationModesTests.cs
  tests/Aspire.Hosting.Tests/WithHttpCommandTests.cs
Labels: area-app-model, testing ☑️

#8520 Interactive prompting for `aspire new`
  src/Aspire.Cli/Backchannel/AppHostBackchannel.cs
  src/Aspire.Cli/Commands/AddCommand.cs
  src/Aspire.Cli/Commands/NewCommand.cs
  src/Aspire.Cli/Commands/PublishCommand.cs
  src/Aspire.Cli/Commands/RunCommand.cs
  src/Aspire.Cli/DotNetCliRunner.cs
  src/Aspire.Cli/NuGetPackageCache.cs
  src/Aspire.Cli/Program.cs
  src/Aspire.Cli/Utils/PromptUtils.cs
Labels: area-cli

#8527 [release/9.2] Add 3rd party signing information for OpenTelemetry and Semver libraries
  eng/Signing.props
Labels: needs-area-label

#8532 Rename IKeyVaultResource and IKeyVaultSecretReference
  src/Aspire.Hosting.Azure.AppContainers/AzureContainerAppsInfrastructure.cs
  src/Aspire.Hosting.Azure.CosmosDB/AzureCosmosDBExtensions.cs
  src/Aspire.Hosting.Azure.CosmosDB/AzureCosmosDBResource.cs
  src/Aspire.Hosting.Azure.KeyVault/AzureKeyVaultResource.cs
  src/Aspire.Hosting.Azure.KeyVault/AzureKeyVaultSecretReference.cs
  src/Aspire.Hosting.Azure.PostgreSQL/AzurePostgresExtensions.cs
  src/Aspire.Hosting.Azure.PostgreSQL/AzurePostgresFlexibleServerResource.cs
  src/Aspire.Hosting.Azure.Redis/AzureRedisCacheResource.cs
  src/Aspire.Hosting.Azure.Redis/AzureRedisExtensions.cs
  src/Aspire.Hosting.Azure/AzureResourcePreparer.cs
  src/Aspire.Hosting.Azure/IAzureKeyVaultResource.cs
  src/Aspire.Hosting.Azure/IAzureKeyVaultSecretReference.cs
  src/Aspire.Hosting.Azure/Provisioning/Provisioners/BicepProvisioner.cs
Labels: area-app-model

#8529 Remove AzureContainerAppEnvironmentResource BicepOutputReferences from public API
  src/Aspire.Hosting.Azure.AppContainers/AzureContainerAppEnvironmentResource.cs
Labels: area-integrations

#8526 [outerloop] Run with `-ci` to match the other test runs on CI
  .github/workflows/tests-outerloop.yml
Labels: area-engineering-systems

#8535 Move database script annotations to their respective projects
  src/Aspire.Hosting.PostgreSQL/PostgresBuilderExtensions.cs
  src/Aspire.Hosting.PostgreSQL/PostgresCreateDatabaseScriptAnnotation.cs
  src/Aspire.Hosting.SqlServer/SqlServerBuilderExtensions.cs
  src/Aspire.Hosting.SqlServer/SqlServerCreateDatabaseScriptAnnotation.cs
  src/Aspire.Hosting/ApplicationModel/CreationScriptAnnotation.cs
Labels: area-app-model

#8540 Update tests-outerloop.yml run frequency
  .github/workflows/tests-outerloop.yml
Labels: area-engineering-systems

#8542 Improve path prompt for aspire new command.
  src/Aspire.Cli/Commands/NewCommand.cs
  src/Aspire.Cli/Commands/RunCommand.cs
  src/Aspire.Cli/DotNetCliRunner.cs
  src/Aspire.Cli/Utils/ProjectFileHelper.cs
Labels: area-cli

#8541 Retry resource stopping operation
  src/Aspire.Hosting/Dcp/DcpExecutor.cs
  tests/Aspire.Hosting.Tests/Dcp/TestKubernetesService.cs
Labels: area-app-model

#8544 Adding descriptions to all args/options in CLI.
  src/Aspire.Cli/Commands/AddCommand.cs
  src/Aspire.Cli/Commands/NewCommand.cs
  src/Aspire.Cli/Commands/PublishCommand.cs
  src/Aspire.Cli/Commands/RootCommand.cs
  src/Aspire.Cli/Commands/RunCommand.cs
Labels: area-cli

#8545 [tests] Quarantine, and un-quarantine some tests
  tests/Aspire.Dashboard.Components.Tests/Pages/TraceDetailsTests.cs
  tests/Aspire.Hosting.Testing.Tests/TestingFactoryTests.cs
Labels: area-integrations

#8548 [CI] Use an in-repo copy of devcerts installation script
  eng/pipelines/templates/BuildAndTest.yml
  tests/external-scripts/README.md
  tests/external-scripts/common.sh
  tests/external-scripts/ubuntu-create-dotnet-devcert.sh
  tests/helix/send-to-helix-inner.proj
Labels: area-engineering-systems

#8524 Change Redis Insights to use environment variables for preconfigured database connections
  src/Aspire.Hosting.Redis/RedisBuilderExtensions.cs
  src/Aspire.Hosting.Redis/RedisContainerImageTags.cs
  tests/Aspire.Hosting.Redis.Tests/AddRedisTests.cs
  tests/Aspire.Hosting.Redis.Tests/RedisFunctionalTests.cs
Labels: needs-area-label, community-contribution

#8557 Switch to null as default for owner and group in WithContainerFiles
  src/Aspire.Hosting/ApplicationModel/ContainerFileSystemCallbackAnnotation.cs
  src/Aspire.Hosting/ContainerResourceBuilderExtensions.cs
  src/Aspire.Hosting/Dcp/Model/Container.cs
  tests/Aspire.Hosting.PostgreSQL.Tests/AddPostgresTests.cs
Labels: area-app-model

#8560 [release/9.2] Bump the version of MEAI
  eng/Versions.props
  playground/OpenAIEndToEnd/OpenAIEndToEnd.WebStory/OpenAIEndToEnd.WebStory.csproj
  src/Components/Aspire.Azure.AI.OpenAI/Aspire.Azure.AI.OpenAI.csproj
  src/Components/Aspire.Microsoft.Data.SqlClient/Aspire.Microsoft.Data.SqlClient.csproj
  src/Components/Aspire.OpenAI/Aspire.OpenAI.csproj
  src/Components/Aspire.OpenAI/MEAIPackageOverrides.targets
  tests/Aspire.Azure.AI.OpenAI.Tests/Aspire.Azure.AI.OpenAI.Tests.csproj
  tests/Aspire.Microsoft.Data.SqlClient.Tests/Aspire.Microsoft.Data.SqlClient.Tests.csproj
  tests/Aspire.OpenAI.Tests/Aspire.OpenAI.Tests.csproj
Labels: area-integrations

#8507 Refactor AzurePublisher to enable usage in downstream publishers
  src/Aspire.Hosting.Azure/AzurePublisher.cs
  src/Aspire.Hosting.Azure/AzurePublishingContext.cs
  tests/Aspire.Hosting.Azure.Tests/AzurePublisherTests.cs
Labels: area-integrations

#8567 Split out build step in publisher.
  src/Aspire.Cli/Commands/PublishCommand.cs
  src/Aspire.Cli/Commands/RunCommand.cs
  src/Aspire.Cli/DotNetCliRunner.cs
  src/Aspire.Cli/Utils/AppHostHelper.cs
Labels: area-cli

#8571 PublishingActivityProgressReporter fixes
  playground/publishers/Publishers.AppHost/docker-compose.yaml
  src/Aspire.Cli/Commands/PublishCommand.cs
  src/Aspire.Hosting/Backchannel/AppHostRpcTarget.cs
  src/Aspire.Hosting/DistributedApplicationRunner.cs
  src/Aspire.Hosting/Publishing/PublishingActivityProgressReporter.cs
  src/Aspire.Hosting/Publishing/ResourceContainerImageBuilder.cs
Labels: area-app-model, area-cli

#8586 Update nightly references to daily
  docs/using-latest-daily.md
Labels: needs-area-label, community-contribution

#8577 Add RPC protocol compat check.
  src/Aspire.Cli/Backchannel/AppHostBackchannel.cs
  src/Aspire.Cli/Backchannel/AppHostIncompatibleException.cs
  src/Aspire.Cli/Commands/NewCommand.cs
  src/Aspire.Cli/Commands/PublishCommand.cs
  src/Aspire.Cli/Commands/RunCommand.cs
  src/Aspire.Cli/DotNetCliRunner.cs
  src/Aspire.Cli/ExitCodeConstants.cs
  src/Aspire.Cli/Utils/AppHostHelper.cs
  src/Aspire.Cli/Utils/InteractionUtils.cs
  src/Aspire.Hosting/Backchannel/AppHostRpcTarget.cs
Labels: area-cli

#8576 Constrain test-only dependencies to /tests folder
  Directory.Packages.props
  src/Components/Aspire.Microsoft.Data.SqlClient/Aspire.Microsoft.Data.SqlClient.csproj
  tests/Aspire.Microsoft.Data.SqlClient.Tests/Aspire.Microsoft.Data.SqlClient.Tests.csproj
  tests/Directory.Packages.props
Labels: area-engineering-systems

#8598 Rename IAzureKeyVaultResource.GetSecretReference to GetSecret
  src/Aspire.Hosting.Azure.CosmosDB/AzureCosmosDBExtensions.cs
  src/Aspire.Hosting.Azure.CosmosDB/AzureCosmosDBResource.cs
  src/Aspire.Hosting.Azure.KeyVault/AzureKeyVaultResource.cs
  src/Aspire.Hosting.Azure.PostgreSQL/AzurePostgresExtensions.cs
  src/Aspire.Hosting.Azure.PostgreSQL/AzurePostgresFlexibleServerResource.cs
  src/Aspire.Hosting.Azure.Redis/AzureRedisExtensions.cs
  src/Aspire.Hosting.Azure/IAzureKeyVaultResource.cs
Labels: area-integrations

#8536 mysql test timeouts
  tests/Aspire.Hosting.MySql.Tests/Aspire.Hosting.MySql.Tests.csproj
  tests/Aspire.Hosting.MySql.Tests/MySqlFunctionalTests.cs
  tests/Aspire.Hosting.Tests/Utils/LoggerNotificationExtensions.cs
  tests/Shared/AsyncTestHelpers.cs
Labels: area-app-model

#8585 Fix --watch hangs.
  src/Aspire.Cli/Commands/RunCommand.cs
  src/Aspire.Cli/DotNetCliRunner.cs
Labels: area-cli

#8603 update to include all d.p.p
  .github/workflows/update-dependencies.yml
Labels: area-engineering-systems

#8602 Address feedback to WithUrls()
  src/Aspire.Hosting/Dcp/ResourceSnapshotBuilder.cs
  src/Aspire.Hosting/Orchestrator/ApplicationOrchestrator.cs
  src/Aspire.Hosting/ResourceBuilderExtensions.cs
  tests/Aspire.Hosting.Tests/DistributedApplicationTests.cs
  tests/Aspire.Hosting.Tests/WithUrlsTests.cs
Labels: area-app-model

#8609 Fix a regression in endpoint resolution in environment variables
  src/Aspire.Hosting/ApplicationModel/ExpressionResolver.cs
  tests/Aspire.Hosting.Tests/ExpressionResolverTests.cs
Labels: area-app-model

#8612 Disable OTEL telemetry in CLI if not a debug build.
  src/Aspire.Cli/Program.cs
Labels: needs-area-label

#8606 AddAzureContainerAppEnvironment should use the environment name as a prefix
  playground/AzureContainerApps/AzureContainerApps.AppHost/infra.module.bicep
  src/Aspire.Hosting.Azure.AppContainers/AzdAzureContainerAppEnvironment.cs
  src/Aspire.Hosting.Azure.AppContainers/AzureContainerAppEnvironmentResource.cs
  src/Aspire.Hosting.Azure.AppContainers/AzureContainerAppExtensions.cs
  src/Aspire.Hosting.Azure.AppContainers/AzureContainerAppsInfrastructure.cs
  src/Aspire.Hosting.Azure.AppContainers/IAzureContainerAppEnvironment.cs
  tests/Aspire.Hosting.Azure.Tests/AzureContainerAppsTests.cs
Labels: area-integrations

#8518 Rename test env controlling and project test capabilities variables
  .github/actions/enumerate-tests/action.yml
  .github/workflows/run-tests.yml
  eng/Testing.props
  eng/Testing.targets
  eng/pipelines/templates/BuildAndTest.yml
  tests/Aspire.Cli.Tests/Aspire.Cli.Tests.csproj
  tests/Aspire.Dashboard.Tests/Aspire.Dashboard.Tests.csproj
  tests/Aspire.Elastic.Clients.Elasticsearch.Tests/Aspire.Elastic.Clients.Elasticsearch.Tests.csproj
  tests/Aspire.EndToEnd.Tests/Aspire.EndToEnd.Tests.csproj
  tests/Aspire.Hosting.Docker.Tests/Aspire.Hosting.Docker.Tests.csproj
  tests/Aspire.Hosting.Testing.Tests/Aspire.Hosting.Testing.Tests.csproj
  tests/Aspire.Hosting.Tests/Aspire.Hosting.Tests.csproj
  tests/Aspire.Oracle.EntityFrameworkCore.Tests/Aspire.Oracle.EntityFrameworkCore.Tests.csproj
  tests/Aspire.Playground.Tests/Aspire.Playground.Tests.csproj
  tests/Aspire.Templates.Tests/Aspire.Templates.Tests.csproj
  tests/Directory.Build.targets
  tests/README.md
  tests/Shared/RepoTesting/Aspire.RepoTesting.targets
Labels: area-engineering-systems

#8616 Look for shipping artifacts according to the build configuration
  tests/Shared/TemplatesTesting/BuildEnvironment.cs
  tests/Shared/TemplatesTesting/EnvironmentVariables.cs
Labels: area-templates

#8615 [tests] Re-enable some quarantined tests that haven't been failing
  .github/workflows/run-tests.yml
  tests/Aspire.Dashboard.Tests/Integration/Playwright/AppBarTests.cs
  tests/Aspire.Hosting.Testing.Tests/TestingBuilderTests.cs
  tests/Aspire.Hosting.Tests/DistributedApplicationTests.cs
  tests/Aspire.Hosting.Tests/Health/ResourceHealthCheckServiceTests.cs
  tests/Aspire.Hosting.Tests/OperationModesTests.cs
  tests/Aspire.Hosting.Tests/SlimTestProgramTests.cs
  tests/Aspire.Hosting.Tests/WithHttpCommandTests.cs
Labels: area-engineering-systems

#8631 Follow up from azd naming change
  src/Aspire.Hosting.Azure.AppContainers/AzureContainerAppExtensions.cs
  tests/Aspire.Hosting.Azure.Tests/AzureContainerAppsTests.cs
Labels: area-integrations

#8622 Fix existing resources with the azure publisher
  src/Aspire.Hosting.Azure/AzurePublishingContext.cs
  tests/Aspire.Hosting.Azure.Tests/AzurePublisherTests.cs
Labels: area-integrations

#8625 Introduce version selector for Aspire templates
  src/Aspire.Cli/Commands/AddCommand.cs
  src/Aspire.Cli/Commands/NewCommand.cs
  src/Aspire.Cli/NuGetPackageCache.cs
  src/Aspire.Cli/Utils/InteractionUtils.cs
Labels: area-cli

#8639 Obsolete AddAzureContainerAppsInfrastructure
  src/Aspire.Hosting.Azure.AppContainers/AzureContainerAppContainerExtensions.cs
  src/Aspire.Hosting.Azure.AppContainers/AzureContainerAppEnvironmentResource.cs
  src/Aspire.Hosting.Azure.AppContainers/AzureContainerAppExecutableExtensions.cs
  src/Aspire.Hosting.Azure.AppContainers/AzureContainerAppExtensions.cs
  src/Aspire.Hosting.Azure.AppContainers/AzureContainerAppProjectExtensions.cs
  src/Aspire.Hosting.Azure/AzureResourcePreparer.cs
  tests/Aspire.Hosting.Azure.Tests/AzureContainerAppsTests.cs
  tests/Aspire.Hosting.Azure.Tests/AzureCosmosDBExtensionsTests.cs
  tests/Aspire.Hosting.Azure.Tests/AzureFunctionsTests.cs
  tests/Aspire.Hosting.Azure.Tests/AzurePostgresExtensionsTests.cs
  tests/Aspire.Hosting.Azure.Tests/AzureRedisExtensionsTests.cs
  tests/Aspire.Hosting.Azure.Tests/AzureResourcePreparerTests.cs
  tests/Aspire.Hosting.Azure.Tests/AzureSqlExtensionsTests.cs
  tests/Aspire.Hosting.Azure.Tests/PublicApiTests/AppContainersPublicApiTests.cs
  tests/Aspire.Hosting.Azure.Tests/RoleAssignmentTests.cs
Labels: area-integrations

#8390 Add error handling for package updates in workflow
  .github/workflows/update-dependencies.yml
Labels: area-codeflow

#8643 Filter out tracing health endpoints in service defaults templates
  playground/TestShop/TestShop.AppHost/Program.cs
  playground/TestShop/TestShop.ServiceDefaults/Extensions.cs
  src/Aspire.ProjectTemplates/templates/aspire-empty/9.2/AspireApplication.1.ServiceDefaults/Extensions.cs
  src/Aspire.ProjectTemplates/templates/aspire-servicedefaults/9.2/Extensions.cs
  src/Aspire.ProjectTemplates/templates/aspire-starter/9.2/Aspire-StarterApplication.1.ServiceDefaults/Extensions.cs
Labels: area-templates

#8477 Show neutral icon for container exiting with status code 0
  src/Aspire.Dashboard/Extensions/ResourceViewModelExtensions.cs
  src/Aspire.Dashboard/Model/ResourceStateViewModel.cs
  tests/Aspire.Dashboard.Tests/Model/ResourceStateViewModelTests.cs
Labels: area-dashboard

#8647 [tests] Correctly mark Aspire.Dashboard.Tests.Integration.Playwright.AppBarTests with RequiresPlaywright
  tests/Aspire.Dashboard.Tests/Integration/Playwright/AppBarTests.cs
Labels: area-engineering-systems, testing ☑️

#8621 [tests] Skip generating Directory.Packages.Versions.props for Test
  tests/Shared/RepoTesting/Aspire.RepoTesting.targets
Labels: area-engineering-systems

#8654 Updating versions of .NET Servicing and Extensions and stabilize packages for 9.2
  eng/Version.Details.xml
  eng/Versions.props
  tests/Shared/RepoTesting/Aspire.RepoTesting.targets
  tests/Shared/RepoTesting/Directory.Packages.Helix.props
Labels: area-codeflow

#8661 Remove -w short option for --wait-for-debugger.
  src/Aspire.Cli/Commands/RootCommand.cs
Labels: area-cli

#8665 Mark Inspect operation as experimental and enhance AddPublisher API
  src/Aspire.Hosting.Azure/AzurePublisherExtensions.cs
  src/Aspire.Hosting.Docker/DockerComposePublisherExtensions.cs
  src/Aspire.Hosting.Kubernetes/KubernetesPublisherExtensions.cs
  src/Aspire.Hosting/DistributedApplicationExecutionContext.cs
  src/Aspire.Hosting/DistributedApplicationOperation.cs
  src/Aspire.Hosting/PublisherDistributedApplicationBuilderExtensions.cs
  tests/Aspire.Hosting.Tests/OperationModesTests.cs
Labels: area-app-model

#8498 Migrate from VSTest to Microsoft.Testing.Platform
  .github/workflows/run-tests.yml
  .github/workflows/tests.yml
  eng/.runsettings
  eng/Testing.props
  eng/Versions.props
  eng/Xunit3/Microsoft.Testing.Platform.targets
  eng/Xunit3/Xunit3.targets
  eng/testing/.runsettings
  tests/Aspire.Components.Common.Tests/Aspire.Components.Common.Tests.csproj
  tests/Aspire.EndToEnd.Tests/.runsettings
  tests/Aspire.EndToEnd.Tests/Aspire.EndToEnd.Tests.csproj
  tests/Aspire.Hosting.Containers.Tests/.runsettings
  tests/Aspire.Hosting.Keycloak.Tests/.runsettings
  tests/Aspire.Playground.Tests/.runsettings
  tests/Aspire.Playground.Tests/Aspire.Playground.Tests.csproj
  tests/Aspire.Templates.Tests/.runsettings
  tests/Aspire.Templates.Tests/Aspire.Templates.Tests.csproj
  tests/Directory.Build.props
  tests/Directory.Build.targets
  tests/Shared/RepoTesting/Aspire.RepoTesting.props
  tests/Shared/RepoTesting/Aspire.RepoTesting.targets
  tests/Shared/RepoTesting/Directory.Packages.Helix.props
  tests/Shared/TemplatesTesting/BuildEnvironment.cs
  tests/helix/send-to-helix-basictests.targets
  tests/helix/send-to-helix-buildonhelixtests.targets
  tests/helix/send-to-helix-endtoendtests.targets
  tests/helix/send-to-helix-inner.proj
  tests/helix/send-to-helix-templatestests.targets
Labels: area-engineering-systems

#8680 Update hardcoded name in playwright test
  tests/Aspire.Dashboard.Tests/Integration/Playwright/BrowserTokenAuthenticationTests.cs
Labels: area-dashboard

#8685 Log cli arguments as first entry
  eng/Xunit3/Microsoft.Testing.Platform.targets
Labels: area-engineering-systems

#8657 Minimal changes to improve CLI testability.
  src/Aspire.Cli/Commands/AddCommand.cs
  src/Aspire.Cli/Commands/NewCommand.cs
  src/Aspire.Cli/Commands/PublishCommand.cs
  src/Aspire.Cli/Commands/RootCommand.cs
  src/Aspire.Cli/Commands/RunCommand.cs
  src/Aspire.Cli/DotNetCliRunner.cs
  src/Aspire.Cli/NuGetPackageCache.cs
  src/Aspire.Cli/Program.cs
  src/Aspire.Cli/Utils/AppHostHelper.cs
  src/Aspire.Cli/Utils/CertificatesHelper.cs
  src/Aspire.Cli/Utils/InteractionUtils.cs
  src/Aspire.Hosting/ResourceBuilderExtensions.cs
  tests/Aspire.Cli.Tests/CliTestConstants.cs
  tests/Aspire.Cli.Tests/Commands/AddCommandTests.cs
  tests/Aspire.Cli.Tests/Commands/NewCommandTests.cs
  tests/Aspire.Cli.Tests/Commands/PublishCommandTests.cs
  tests/Aspire.Cli.Tests/Commands/RootCommandTests.cs
  tests/Aspire.Cli.Tests/Commands/RunCommandTests.cs
  tests/Aspire.Cli.Tests/Utils/CliTestHelper.cs
  tests/Aspire.Hosting.Tests/OperationModesTests.cs
Labels: area-cli

#8687 Fix outerloop issues
  .github/workflows/tests-outerloop.yml
  eng/Testing.targets
  tests/Aspire.Components.Common.Tests/Aspire.Components.Common.Tests.csproj
Labels: area-engineering-systems

#8691 Add context menu to resource graph, improve console logs actions
  src/Aspire.Dashboard/Components/Controls/AspireMenu.razor
  src/Aspire.Dashboard/Components/Controls/AspireMenu.razor.cs
  src/Aspire.Dashboard/Components/Controls/AspireMenuButton.razor
  src/Aspire.Dashboard/Components/Controls/AspireMenuButton.razor.cs
  src/Aspire.Dashboard/Components/Controls/ResourceActions.razor
  src/Aspire.Dashboard/Components/Controls/ResourceActions.razor.cs
  src/Aspire.Dashboard/Components/Pages/ConsoleLogs.razor
  src/Aspire.Dashboard/Components/Pages/ConsoleLogs.razor.cs
  src/Aspire.Dashboard/Components/Pages/Resources.razor
  src/Aspire.Dashboard/Components/Pages/Resources.razor.cs
  src/Aspire.Dashboard/Model/ResourceMenuItems.cs
  src/Aspire.Dashboard/Resources/ConsoleLogs.Designer.cs
  src/Aspire.Dashboard/Resources/ConsoleLogs.resx
  src/Aspire.Dashboard/Resources/xlf/ConsoleLogs.cs.xlf
  src/Aspire.Dashboard/Resources/xlf/ConsoleLogs.de.xlf
  src/Aspire.Dashboard/Resources/xlf/ConsoleLogs.es.xlf
  src/Aspire.Dashboard/Resources/xlf/ConsoleLogs.fr.xlf
  src/Aspire.Dashboard/Resources/xlf/ConsoleLogs.it.xlf
  src/Aspire.Dashboard/Resources/xlf/ConsoleLogs.ja.xlf
  src/Aspire.Dashboard/Resources/xlf/ConsoleLogs.ko.xlf
  src/Aspire.Dashboard/Resources/xlf/ConsoleLogs.pl.xlf
  src/Aspire.Dashboard/Resources/xlf/ConsoleLogs.pt-BR.xlf
  src/Aspire.Dashboard/Resources/xlf/ConsoleLogs.ru.xlf
  src/Aspire.Dashboard/Resources/xlf/ConsoleLogs.tr.xlf
  src/Aspire.Dashboard/Resources/xlf/ConsoleLogs.zh-Hans.xlf
  src/Aspire.Dashboard/Resources/xlf/ConsoleLogs.zh-Hant.xlf
  src/Aspire.Dashboard/wwwroot/js/app-resourcegraph.js
  tests/Aspire.Dashboard.Components.Tests/Pages/ConsoleLogsTests.cs
Labels: area-dashboard

#8618 Parallelise outerloop quarantined test execution
  .github/workflows/tests-outerloop.yml
  eng/AfterSolutionBuild.targets
  eng/QuarantinedTestRunsheetBuilder/QuarantinedTestRunsheetBuilder.targets
  tests/Aspire.Templates.Tests/Aspire.Templates.Tests.csproj
  tests/Shared/SolutionTests.proj
Labels: area-engineering-systems

#8703 Merging branch release/9.2 into main
  eng/Signing.props
  eng/Version.Details.xml
  eng/Versions.props
  playground/OpenAIEndToEnd/OpenAIEndToEnd.WebStory/OpenAIEndToEnd.WebStory.csproj
  src/Components/Aspire.Azure.AI.OpenAI/Aspire.Azure.AI.OpenAI.csproj
  src/Components/Aspire.OpenAI/Aspire.OpenAI.csproj
  src/Components/Aspire.OpenAI/MEAIPackageOverrides.targets
  tests/Aspire.Azure.AI.OpenAI.Tests/Aspire.Azure.AI.OpenAI.Tests.csproj
  tests/Aspire.OpenAI.Tests/Aspire.OpenAI.Tests.csproj
Labels: area-integrations

#8706 Outerloop enhancements
  .github/workflows/tests-outerloop.yml
  eng/QuarantinedTestRunsheetBuilder/QuarantinedTestRunsheetBuilder.targets
  eng/Testing.props
Labels: area-engineering-systems

#8743 Custom URLs improvements
  playground/TestShop/TestShop.AppHost/Program.cs
  src/Aspire.Dashboard/Components/Controls/ResourceDetails.razor
  src/Aspire.Dashboard/Resources/ControlsStrings.Designer.cs
  src/Aspire.Dashboard/Resources/ControlsStrings.resx
  src/Aspire.Dashboard/Resources/xlf/ControlsStrings.cs.xlf
  src/Aspire.Dashboard/Resources/xlf/ControlsStrings.de.xlf
  src/Aspire.Dashboard/Resources/xlf/ControlsStrings.es.xlf
  src/Aspire.Dashboard/Resources/xlf/ControlsStrings.fr.xlf
  src/Aspire.Dashboard/Resources/xlf/ControlsStrings.it.xlf
  src/Aspire.Dashboard/Resources/xlf/ControlsStrings.ja.xlf
  src/Aspire.Dashboard/Resources/xlf/ControlsStrings.ko.xlf
  src/Aspire.Dashboard/Resources/xlf/ControlsStrings.pl.xlf
  src/Aspire.Dashboard/Resources/xlf/ControlsStrings.pt-BR.xlf
  src/Aspire.Dashboard/Resources/xlf/ControlsStrings.ru.xlf
  src/Aspire.Dashboard/Resources/xlf/ControlsStrings.tr.xlf
  src/Aspire.Dashboard/Resources/xlf/ControlsStrings.zh-Hans.xlf
  src/Aspire.Dashboard/Resources/xlf/ControlsStrings.zh-Hant.xlf
  src/Aspire.Hosting/ApplicationModel/CustomResourceSnapshot.cs
  src/Aspire.Hosting/ApplicationModel/ResourceUrlAnnotation.cs
  src/Aspire.Hosting/ApplicationModel/ResourceUrlsCallbackContext.cs
  src/Aspire.Hosting/Dcp/ResourceSnapshotBuilder.cs
  src/Aspire.Hosting/Orchestrator/ApplicationOrchestrator.cs
  src/Aspire.Hosting/ResourceBuilderExtensions.cs
  tests/Aspire.Hosting.Tests/WithUrlsTests.cs
Labels: area-dashboard

#8723 [tests] Disable some Quarantined tests
  tests/Aspire.Hosting.NodeJs.Tests/NodeFunctionalTests.cs
  tests/Aspire.Hosting.Oracle.Tests/OracleFunctionalTests.cs
  tests/Aspire.Hosting.Tests/DistributedApplicationTests.cs
  tests/Aspire.TestUtilities/PlatformDetection.cs
Labels: area-integrations, testing ☑️

#8746 More CLI test automation plumbing.
  src/Aspire.Cli/Certificates/CertificatesHelper.cs
  src/Aspire.Cli/Commands/AddCommand.cs
  src/Aspire.Cli/Commands/NewCommand.cs
  src/Aspire.Cli/Commands/PublishCommand.cs
  src/Aspire.Cli/Commands/RootCommand.cs
  src/Aspire.Cli/Commands/RunCommand.cs
  src/Aspire.Cli/Interaction/IInteractionService.cs
  src/Aspire.Cli/Interaction/InteractionService.cs
  src/Aspire.Cli/Program.cs
  src/Aspire.Cli/Projects/ProjectLocator.cs
  src/Aspire.Cli/Utils/AppHostHelper.cs
  src/Aspire.Cli/Utils/CertificatesHelper.cs
  src/Aspire.Cli/Utils/IInteractionService.cs
  src/Aspire.Cli/Utils/InteractionService.cs
  src/Aspire.Cli/Utils/ProjectFileHelper.cs
  tests/Aspire.Cli.Tests/Commands/NewCommandTests.cs
  tests/Aspire.Cli.Tests/Utils/CliTestHelper.cs
Labels: area-cli

#8751 Fixed resolving secrets for keyvault references in run mode
  src/Aspire.Hosting.Azure/Provisioning/AzureProvisionerExtensions.cs
  src/Aspire.Hosting.Azure/Provisioning/Provisioners/AzureProvisioner.cs
  src/Aspire.Hosting.Azure/Provisioning/Provisioners/BicepProvisioner.cs
  src/Aspire.Hosting.Azure/Provisioning/Provisioners/TokenCredentialHolder.cs
Labels: area-app-model

#8749 More URL fixes
  src/Aspire.Dashboard/Components/Controls/ResourceDetails.razor
  src/Aspire.Dashboard/Model/ResourceGraph/ResourceGraphMapper.cs
  src/Aspire.Dashboard/Model/ResourceUrlHelpers.cs
Labels: area-dashboard

#8697 Make IPublishingActivityProgressReporter mockable
  src/Aspire.Hosting/Publishing/NullPublishingActivityProgressReporter.cs
  src/Aspire.Hosting/Publishing/PublishingActivityProgressReporter.cs
  tests/Aspire.Hosting.Tests/Publishing/NullPublishingActivityProgressReporterTests.cs
Labels: area-deployment

#8688 (Re)enable running tests from cli without specifying build infra
  eng/Testing.targets
Labels: area-engineering-systems

#8762 Update console logs rendering to skip default background color
  src/Aspire.Dashboard/Components/Pages/ConsoleLogs.razor.cs
  src/Aspire.Dashboard/ConsoleLogs/AnsiParser.cs
  src/Aspire.Dashboard/ConsoleLogs/LogParser.cs
  tests/Aspire.Dashboard.Tests/ConsoleLogsTests/LogEntriesTests.cs
Labels: area-dashboard

#8759 Add URLs to console logs actions and context menu
  src/Aspire.Dashboard/Components/Controls/ResourceActions.razor.cs
  src/Aspire.Dashboard/Components/Pages/ConsoleLogs.razor.cs
  src/Aspire.Dashboard/Components/Pages/Resources.razor.cs
  src/Aspire.Dashboard/Model/ResourceMenuItems.cs
  src/Aspire.Dashboard/wwwroot/js/app.js
Labels: area-dashboard

#8775 Turn on MTP and solution free workspace mode.
  .vscode/settings.json
Labels: needs-area-label

#8777 Fix not selecting resource when switching to graph for first time
  src/Aspire.Dashboard/Components/Pages/Resources.razor.cs
Labels: area-dashboard

#8563 Change PublisherOptions - Allow skipping image building?
  src/Aspire.Hosting.Docker/DockerComposePublisherOptions.cs
  src/Aspire.Hosting.Docker/DockerComposePublishingContext.cs
  tests/Aspire.Hosting.Docker.Tests/DockerComposePublisherTests.cs
Labels: area-app-model, community-contribution

#8738 Add more logging for database creation
  src/Aspire.Hosting.PostgreSQL/PostgresBuilderExtensions.cs
  src/Aspire.Hosting.SqlServer/SqlServerBuilderExtensions.cs
  tests/Aspire.Hosting.SqlServer.Tests/SqlServerFunctionalTests.cs
Labels: needs-area-label

#8776 Position the context menu inside the screen bounds
  src/Aspire.Dashboard/Components/Controls/AspireMenu.razor
  src/Aspire.Dashboard/Components/Controls/AspireMenu.razor.cs
  src/Aspire.Dashboard/Components/Pages/Resources.razor
  src/Aspire.Dashboard/Components/Pages/Resources.razor.cs
  src/Aspire.Dashboard/wwwroot/js/app-resourcegraph.js
Labels: area-dashboard

#8767 Testing improvements for the `aspire add` command.
  src/Aspire.Cli/Commands/AddCommand.cs
  src/Aspire.Cli/Interaction/InteractionService.cs
  src/Aspire.Cli/Program.cs
  tests/Aspire.Cli.Tests/Commands/AddCommandTests.cs
  tests/Aspire.Cli.Tests/Commands/NewCommandTests.cs
  tests/Aspire.Cli.Tests/Commands/PublishCommandTests.cs
  tests/Aspire.Cli.Tests/Commands/RootCommandTests.cs
  tests/Aspire.Cli.Tests/Commands/RunCommandTests.cs
  tests/Aspire.Cli.Tests/TestServices/TestDotNetCliRunner.cs
  tests/Aspire.Cli.Tests/Utils/CliTestHelper.cs
Labels: area-cli

#8718 Capture container registry information in CAE
  src/Aspire.Hosting.Azure.AppContainers/AzdAzureContainerAppEnvironment.cs
  src/Aspire.Hosting.Azure.AppContainers/AzureContainerAppEnvironmentResource.cs
  src/Aspire.Hosting.Azure.AppContainers/AzureContainerAppsInfrastructure.cs
  src/Aspire.Hosting.Azure.AppContainers/IAzureContainerAppEnvironment.cs
  src/Aspire.Hosting.Azure.AppContainers/IContainerRegistry.cs
  src/Aspire.Hosting.Azure/IAzureContainerRegistry.cs
  src/Aspire.Hosting/ApplicationModel/DeploymentTargetAnnotation.cs
  src/Aspire.Hosting/ApplicationModel/IContainerRegistry.cs
  tests/Aspire.Hosting.Azure.Tests/ContainerRegistryTests.cs
Labels: area-integrations

#8800 Don't fail for Azure role assignments in run mode
  src/Aspire.Hosting.Azure/AzureResourcePreparer.cs
  tests/Aspire.Hosting.Azure.Tests/AzureResourcePreparerTests.cs
Labels: area-integrations

#8804 Do not try to resolve .NET SDK location when using "system .NET" option
  tests/Shared/TemplatesTesting/BuildEnvironment.cs
Labels: area-engineering-systems

#8801 [tests] Unquarantine some tests because they haven't failed in the last 30+ runs
  tests/Aspire.Dashboard.Tests/Integration/Playwright/AppBarTests.cs
  tests/Aspire.Dashboard.Tests/Integration/Playwright/BrowserTokenAuthenticationTests.cs
  tests/Aspire.Hosting.Azure.Tests/AzureCosmosDBEmulatorFunctionalTests.cs
  tests/Aspire.Hosting.MongoDB.Tests/MongoDbFunctionalTests.cs
  tests/Aspire.Hosting.MySql.Tests/MySqlFunctionalTests.cs
  tests/Aspire.Hosting.Tests/WithHttpCommandTests.cs
Labels: area-integrations, testing ☑️

#8808 Copy config starting with ASPIRE_DASHBOARD to the dashboard
  src/Aspire.Hosting/Dashboard/DashboardLifecycleHook.cs
  tests/Aspire.Hosting.Tests/Dashboard/DashboardLifecycleHookTests.cs
  tests/Aspire.Hosting.Tests/Dashboard/DashboardResourceTests.cs
Labels: area-dashboard

#8705 [CI] Generate one combined report for Outerloop tests workflow
  .github/workflows/tests-outerloop.yml
Labels: area-engineering-systems

#8821 Added WithEnvironment overload supporting Keyvault secret refs
  src/Aspire.Hosting.Azure/AzureBicepResourceExtensions.cs
  tests/Aspire.Hosting.Azure.Tests/AzureBicepResourceTests.cs
  tests/Aspire.Hosting.Azure.Tests/AzureKeyVaultTests.cs
Labels: area-integrations

#8802 Revert "Migrate from VSTest to Microsoft.Testing.Platform (#8498)"
  .github/workflows/run-tests.yml
  .github/workflows/tests.yml
  eng/.runsettings
  eng/QuarantinedTestRunsheetBuilder/QuarantinedTestRunsheetBuilder.targets
  eng/Testing.props
  eng/Versions.props
  eng/Xunit3/Xunit3.targets
  eng/testing/.runsettings
  tests/Aspire.Components.Common.Tests/Aspire.Components.Common.Tests.csproj
  tests/Aspire.EndToEnd.Tests/.runsettings
  tests/Aspire.EndToEnd.Tests/Aspire.EndToEnd.Tests.csproj
  tests/Aspire.Hosting.Containers.Tests/.runsettings
  tests/Aspire.Hosting.Keycloak.Tests/.runsettings
  tests/Aspire.Playground.Tests/.runsettings
  tests/Aspire.Playground.Tests/Aspire.Playground.Tests.csproj
  tests/Aspire.Templates.Tests/.runsettings
  tests/Aspire.Templates.Tests/Aspire.Templates.Tests.csproj
  tests/Directory.Build.props
  tests/Directory.Build.targets
  tests/Shared/RepoTesting/Aspire.RepoTesting.props
  tests/Shared/RepoTesting/Aspire.RepoTesting.targets
  tests/Shared/RepoTesting/Directory.Packages.Helix.props
  tests/Shared/TemplatesTesting/BuildEnvironment.cs
  tests/helix/send-to-helix-basictests.targets
  tests/helix/send-to-helix-buildonhelixtests.targets
  tests/helix/send-to-helix-endtoendtests.targets
  tests/helix/send-to-helix-inner.proj
  tests/helix/send-to-helix-templatestests.targets
Labels: area-engineering-systems

#8825 Disable testing platform protocol mode in Workspace
  .vscode/settings.json
Labels: area-engineering-systems

#8806 bump overall test library timeout to 20m because of slow sqlserver tests
  eng/Testing.props
  tests/helix/send-to-helix-inner.proj
Labels: area-engineering-systems

#8820 Allow multiple compute environment resources in an app model
  src/Aspire.Hosting.Azure.AppContainers/AzureContainerAppEnvironmentResource.cs
  src/Aspire.Hosting.Azure.AppContainers/AzureContainerAppsInfrastructure.cs
  src/Aspire.Hosting.Azure/AzurePublishingContext.cs
  src/Aspire.Hosting/ApplicationModel/ComputeEnvironmentAnnotation.cs
  src/Aspire.Hosting/ApplicationModel/ContainerResource.cs
  src/Aspire.Hosting/ApplicationModel/DeploymentTargetAnnotation.cs
  src/Aspire.Hosting/ApplicationModel/ExecutableResource.cs
  src/Aspire.Hosting/ApplicationModel/IComputeEnvironmentResource.cs
  src/Aspire.Hosting/ApplicationModel/IComputeResource.cs
  src/Aspire.Hosting/ApplicationModel/ProjectResource.cs
  src/Aspire.Hosting/ApplicationModel/ResourceExtensions.cs
  src/Aspire.Hosting/Publishing/ManifestPublishingContext.cs
  src/Aspire.Hosting/ResourceBuilderExtensions.cs
  tests/Aspire.Hosting.Azure.Tests/AzureContainerAppsTests.cs
  tests/Aspire.Hosting.Tests/ResourceExtensionsTests.cs
Labels: area-app-model

#8828 Model Docker Compose as compute environment
  src/Aspire.Hosting.Docker/DockerComposeEnvironmentExtensions.cs
  src/Aspire.Hosting.Docker/DockerComposeEnvironmentResource.cs
  src/Aspire.Hosting.Docker/DockerComposeInfrastructure.cs
  src/Aspire.Hosting.Docker/DockerComposePublishingContext.cs
  src/Aspire.Hosting.Docker/DockerComposeServiceCustomizationAnnotation.cs
  src/Aspire.Hosting.Docker/DockerComposeServiceExtensions.cs
  src/Aspire.Hosting.Docker/DockerComposeServiceResource.cs
  src/Aspire.Hosting.Docker/DockerComposeServiceResourceExtensions.cs
  tests/Aspire.Hosting.Docker.Tests/DockerComposePublisherTests.cs
Labels: area-deployment

#8834 Follow-ups to Docker Compose as compute environment resource
  playground/publishers/Publishers.AppHost/Program.cs
  src/Aspire.Hosting.Docker/DockerComposeEnvironmentExtensions.cs
  src/Aspire.Hosting.Docker/DockerComposeEnvironmentResource.cs
  src/Aspire.Hosting.Docker/DockerComposePublishingContext.cs
  src/Aspire.Hosting.Docker/DockerComposeServiceExtensions.cs
  src/Aspire.Hosting.Docker/DockerComposeServiceResource.cs
  tests/Aspire.Hosting.Docker.Tests/DockerComposePublisherTests.cs
Labels: area-deployment

#8836 Split ACA infrastructure god class into multiple files
  src/Aspire.Hosting.Azure.AppContainers/AzureContainerAppsInfrastructure.cs
  src/Aspire.Hosting.Azure.AppContainers/ContainerAppContext.cs
  src/Aspire.Hosting.Azure.AppContainers/ContainerAppEnvironmentContext.cs
Labels: area-deployment

#8835 `aspire run` test coverage
  src/Aspire.Cli/Backchannel/AppHostBackchannel.cs
  src/Aspire.Cli/Commands/PublishCommand.cs
  src/Aspire.Cli/Commands/RunCommand.cs
  src/Aspire.Cli/DotNetCliRunner.cs
  src/Aspire.Cli/Interaction/InteractionService.cs
  src/Aspire.Cli/Program.cs
  src/Aspire.Cli/Utils/InteractionService.cs
  tests/Aspire.Cli.Tests/Commands/AddCommandTests.cs
  tests/Aspire.Cli.Tests/Commands/RunCommandTests.cs
  tests/Aspire.Cli.Tests/TestServices/TestAppHostBackchannel.cs
  tests/Aspire.Cli.Tests/TestServices/TestDotNetCliRunner.cs
  tests/Aspire.Cli.Tests/TestServices/TestProjectLocator.cs
  tests/Aspire.Cli.Tests/Utils/CliTestHelper.cs
Labels: area-cli

#8848 Update pull_request_template.md
  .github/pull_request_template.md
Labels: area-templates

#8843 Add compute environment annotation to Docker Compose service resources
  src/Aspire.Hosting.Docker/DockerComposeEnvironmentContext.cs
  src/Aspire.Hosting.Docker/DockerComposeInfrastructure.cs
  src/Aspire.Hosting.Docker/DockerComposeServiceResourceExtensions.cs
  tests/Aspire.Hosting.Docker.Tests/DockerComposeTests.cs
Labels: area-integrations

#8839 This change pushes container registry details to the outputs
  src/Aspire.Hosting.Azure/AzurePublishingContext.cs
  tests/Aspire.Hosting.Azure.Tests/AzurePublisherTests.cs
Labels: area-integrations

#8861 [tests] Quarantine OperationModesTests.VerifyExplicitRunModeWithPublisherInvocation
  tests/Aspire.Hosting.Tests/OperationModesTests.cs
Labels: area-app-model, testing ☑️

#8797 Fix AE in ExecutableResource
  src/Aspire.Hosting/ApplicationModel/ExecutableResource.cs
  tests/Aspire.Hosting.NodeJs.Tests/NodeJsPublicApiTests.cs
  tests/Aspire.Hosting.Python.Tests/PythonPublicApiTests.cs
  tests/Aspire.Hosting.Tests/ExecutableResourceTests.cs
Labels: area-app-model, NO-MERGE

#8850 `aspire publish` test cases
  src/Aspire.Cli/Commands/AddCommand.cs
  src/Aspire.Cli/Commands/PublishCommand.cs
  src/Aspire.Cli/Commands/RunCommand.cs
  src/Aspire.Cli/DotNetCliRunner.cs
  src/Aspire.Cli/Program.cs
  src/Aspire.Cli/Utils/ProjectFileHelper.cs
  tests/Aspire.Cli.Tests/Commands/PublishCommandTests.cs
  tests/Aspire.Cli.Tests/Commands/RunCommandTests.cs
  tests/Aspire.Cli.Tests/Utils/CliTestHelper.cs
Labels: area-cli

#8866 Respect the container name annotation for docker compose
  src/Aspire.Hosting.Docker/DockerComposeServiceResource.cs
  tests/Aspire.Hosting.Docker.Tests/DockerComposePublisherTests.cs
Labels: area-integrations

#8788 Hide keycloak management URL from summary
  src/Aspire.Hosting.Keycloak/KeycloakResourceBuilderExtensions.cs
Labels: area-app-model, community-contribution

#8869 Fix `Aspire.Hosting.Docker` description
  src/Aspire.Hosting.Docker/Aspire.Hosting.Docker.csproj
Labels: needs-area-label, community-contribution

#8840 Add display name for Qdrant's HTTP and GRPC endpoints
  src/Aspire.Hosting.Qdrant/QdrantBuilderExtensions.cs
  tests/Aspire.Hosting.Qdrant.Tests/QdrantFunctionalTests.cs
Labels: needs-area-label, community-contribution

#8881 Remove named overloads of publisher methods from Azure, Docker Compos…
  playground/publishers/Publishers.AppHost/Program.cs
  src/Aspire.Hosting.Azure/AzurePublisherExtensions.cs
  src/Aspire.Hosting.Azure/Provisioning/AzureProvisionerExtensions.cs
  src/Aspire.Hosting.Docker/DockerComposeEnvironmentExtensions.cs
  src/Aspire.Hosting.Docker/DockerComposePublisherExtensions.cs
  src/Aspire.Hosting.Kubernetes/KubernetesEnvironmentExtensions.cs
  src/Aspire.Hosting.Kubernetes/KubernetesPublisherExtensions.cs
  src/Aspire.Hosting/Publishing/PublisherAdvertisementEvent.cs
Labels: area-integrations

#8873 add description to CLI package
  src/Aspire.Cli/Aspire.Cli.csproj
Labels: area-cli

#8833 Revert to MTP and disable server capability as a workaround
  .github/workflows/run-tests.yml
  .github/workflows/tests.yml
  eng/.runsettings
  eng/QuarantinedTestRunsheetBuilder/QuarantinedTestRunsheetBuilder.targets
  eng/Testing.props
  eng/Versions.props
  eng/Xunit3/Xunit3.targets
  eng/testing/.runsettings
  tests/Aspire.Components.Common.Tests/Aspire.Components.Common.Tests.csproj
  tests/Aspire.EndToEnd.Tests/.runsettings
  tests/Aspire.EndToEnd.Tests/Aspire.EndToEnd.Tests.csproj
  tests/Aspire.Hosting.Containers.Tests/.runsettings
  tests/Aspire.Hosting.Keycloak.Tests/.runsettings
  tests/Aspire.Playground.Tests/.runsettings
  tests/Aspire.Playground.Tests/Aspire.Playground.Tests.csproj
  tests/Aspire.Templates.Tests/.runsettings
  tests/Aspire.Templates.Tests/Aspire.Templates.Tests.csproj
  tests/Directory.Build.props
  tests/Directory.Build.targets
  tests/Shared/RepoTesting/Aspire.RepoTesting.props
  tests/Shared/RepoTesting/Aspire.RepoTesting.targets
  tests/Shared/RepoTesting/Directory.Packages.Helix.props
  tests/Shared/TemplatesTesting/BuildEnvironment.cs
  tests/helix/send-to-helix-basictests.targets
  tests/helix/send-to-helix-buildonhelixtests.targets
  tests/helix/send-to-helix-endtoendtests.targets
  tests/helix/send-to-helix-inner.proj
  tests/helix/send-to-helix-templatestests.targets
Labels: area-engineering-systems

#8882 Add properties to DockerComposeEnvironmentResource
  src/Aspire.Hosting.Docker/DockerComposeEnvironmentExtensions.cs
  src/Aspire.Hosting.Docker/DockerComposeEnvironmentResource.cs
  src/Aspire.Hosting.Docker/DockerComposePublisherOptions.cs
  src/Aspire.Hosting.Docker/DockerComposePublishingContext.cs
  tests/Aspire.Hosting.Docker.Tests/DockerComposePublisherTests.cs
Labels: area-integrations

#8889 Order package versions in CLI.
  src/Aspire.Cli/Commands/AddCommand.cs
  src/Aspire.Cli/Commands/NewCommand.cs
  tests/Aspire.Cli.Tests/Commands/AddCommandTests.cs
  tests/Aspire.Cli.Tests/Commands/NewCommandTests.cs
Labels: area-cli

#8903 Update test files to show 9.2.1 patched version to fix tests
  tests/Shared/RepoTesting/Aspire.RepoTesting.targets
  tests/Shared/RepoTesting/Directory.Packages.Helix.props
Labels: area-integrations

#8900 change verbose logging of update details to a single line
  src/Aspire.Hosting/ApplicationModel/ResourceNotificationService.cs
  tests/Aspire.Hosting.Tests/Backchannel/AppHostBackchannelTests.cs
Labels: area-app-model

#8771 Ensure visible trace spans stay sorted by start time and fix Traces view expand/collapse icons
  playground/Stress/Stress.ApiService/Program.cs
  playground/Stress/Stress.AppHost/Program.cs
  src/Aspire.Dashboard/Components/Pages/TraceDetail.razor.cs
  tests/Aspire.Dashboard.Components.Tests/Pages/TraceDetailsTests.cs
Labels: area-dashboard

#8896 Add debug session configuration to apphost and dashboard
  src/Aspire.Dashboard/Configuration/DashboardOptions.cs
  src/Aspire.Dashboard/Configuration/ValidateDashboardOptions.cs
  src/Aspire.Dashboard/Model/DebugSessionHelpers.cs
  src/Aspire.Hosting/Dashboard/DashboardLifecycleHook.cs
  src/Aspire.Hosting/Dashboard/DashboardOptions.cs
  src/Shared/DashboardConfigNames.cs
  tests/Aspire.Dashboard.Tests/Integration/StartupTests.cs
  tests/Aspire.Hosting.Tests/Dashboard/DashboardLifecycleHookTests.cs
  tests/Shared/Telemetry/TelemetryTestHelpers.cs
Labels: area-dashboard

#8883 Treat uninstrumented outgoing peers are instrumented resources in dashboard UI
  src/Aspire.Dashboard/Components/Controls/ResourceDetails.razor
  src/Aspire.Dashboard/Components/Controls/ResourceDetails.razor.cs
  src/Aspire.Dashboard/Components/Pages/TraceDetail.razor.cs
  src/Aspire.Dashboard/Components/Pages/Traces.razor.cs
  src/Aspire.Dashboard/DashboardWebApplication.cs
  src/Aspire.Dashboard/Model/BrowserLinkOutgoingPeerResolver.cs
  src/Aspire.Dashboard/Model/IOutgoingPeerResolver.cs
  src/Aspire.Dashboard/Model/KnownPropertyLookup.cs
  src/Aspire.Dashboard/Model/Otlp/SpanWaterfallViewModel.cs
  src/Aspire.Dashboard/Model/Otlp/TelemetryFilter.cs
  src/Aspire.Dashboard/Model/ResourceOutgoingPeerResolver.cs
  src/Aspire.Dashboard/Model/ResourceViewModel.cs
  src/Aspire.Dashboard/Model/TraceHelpers.cs
  src/Aspire.Dashboard/Otlp/Model/OtlpApplication.cs
  src/Aspire.Dashboard/Otlp/Model/OtlpSpan.cs
  src/Aspire.Dashboard/Otlp/Storage/ApplicationKey.cs
  src/Aspire.Dashboard/Otlp/Storage/TelemetryRepository.cs
  src/Aspire.Dashboard/ResourceService/DashboardClient.cs
  src/Aspire.Dashboard/ResourceService/Partials.cs
  tests/Aspire.Dashboard.Components.Tests/Controls/StructuredLogDetailsTests.cs
  tests/Aspire.Dashboard.Tests/BrowserLinkOutgoingPeerResolverTests.cs
  tests/Aspire.Dashboard.Tests/Integration/DashboardClientAuthTests.cs
  tests/Aspire.Dashboard.Tests/Integration/Playwright/Infrastructure/DashboardServerFixture.cs
  tests/Aspire.Dashboard.Tests/Integration/Playwright/Infrastructure/MockDashboardClient.cs
  tests/Aspire.Dashboard.Tests/Model/ApplicationsSelectHelpersTests.cs
  tests/Aspire.Dashboard.Tests/Model/DashboardClientTests.cs
  tests/Aspire.Dashboard.Tests/Model/ResourceSourceViewModelTests.cs
  tests/Aspire.Dashboard.Tests/Model/ResourceStateViewModelTests.cs
  tests/Aspire.Dashboard.Tests/Model/ResourceViewModelTests.cs
  tests/Aspire.Dashboard.Tests/Model/SpanWaterfallViewModelTests.cs
  tests/Aspire.Dashboard.Tests/Model/TraceHelpersTests.cs
  tests/Aspire.Dashboard.Tests/ResourceOutgoingPeerResolverTests.cs
  tests/Aspire.Dashboard.Tests/TelemetryRepositoryTests/OtlpSpanTests.cs
  tests/Aspire.Dashboard.Tests/TelemetryRepositoryTests/TraceTests.cs
  tests/Shared/Telemetry/TelemetryTestHelpers.cs
Labels: area-dashboard

#8892 Improve apphost discovery.
  src/Aspire.Cli/Aspire.Cli.csproj
  src/Aspire.Cli/CliSettings.cs
  src/Aspire.Cli/Commands/AddCommand.cs
  src/Aspire.Cli/Commands/PublishCommand.cs
  src/Aspire.Cli/Commands/RunCommand.cs
  src/Aspire.Cli/JsonSourceGenerationContext.cs
  src/Aspire.Cli/Program.cs
  src/Aspire.Cli/Projects/ProjectLocator.cs
  tests/Aspire.Cli.Tests/Commands/RunCommandTests.cs
  tests/Aspire.Cli.Tests/Projects/ProjectLocatorTests.cs
  tests/Aspire.Cli.Tests/TestServices/TestProjectLocator.cs
  tests/Aspire.Cli.Tests/Utils/CliTestHelper.cs
  tests/Aspire.Cli.Tests/Utils/TemporaryRepo.cs
Labels: area-cli

#8910 Remove dashboard client status
  src/Aspire.Dashboard/DashboardWebApplication.cs
  src/Aspire.Dashboard/ResourceService/DashboardClient.cs
  src/Aspire.Dashboard/ResourceService/DashboardClientStatus.cs
  src/Aspire.Dashboard/ResourceService/IDashboardClient.cs
  src/Aspire.Dashboard/ResourceService/IDashboardClientStatus.cs
  tests/Aspire.Dashboard.Components.Tests/Controls/ApplicationNameTests.cs
  tests/Aspire.Dashboard.Tests/Integration/DashboardClientAuthTests.cs
  tests/Aspire.Dashboard.Tests/Integration/Playwright/Infrastructure/DashboardServerFixture.cs
  tests/Aspire.Dashboard.Tests/Integration/Playwright/Infrastructure/MockDashboardClient.cs
  tests/Aspire.Dashboard.Tests/Model/DashboardClientTests.cs
Labels: area-dashboard

#8924 [tests] Quarantine some flaky tests
  tests/Aspire.Hosting.NodeJs.Tests/NodeFunctionalTests.cs
  tests/Aspire.Hosting.Tests/DistributedApplicationTests.cs
Labels: area-app-model, area-integrations, testing ☑️

#8932 [tests] Quarantine flaky tests
  tests/Aspire.Dashboard.Components.Tests/Pages/ConsoleLogsTests.cs
  tests/Aspire.Hosting.Tests/DistributedApplicationTests.cs
Labels: testing ☑️

#8938 [tests] Flaky test: Use test container registry for MySqlFunctionalTests.MySql_WithPersistentLifetime_ReusesContainers
  tests/Aspire.Hosting.MySql.Tests/MySqlFunctionalTests.cs
Labels: area-integrations

#8935 Fix diagnostics URL error
  src/Aspire.Hosting.Analyzers/AppHostAnalyzer.Diagnostics.cs
Labels: needs-area-label

#8943 Improve error display when sub-processes fail.
  src/Aspire.Cli/Aspire.Cli.csproj
  src/Aspire.Cli/Certificates/CertificatesHelper.cs
  src/Aspire.Cli/Commands/AddCommand.cs
  src/Aspire.Cli/Commands/NewCommand.cs
  src/Aspire.Cli/Commands/PublishCommand.cs
  src/Aspire.Cli/Commands/RunCommand.cs
  src/Aspire.Cli/DotNetCliRunner.cs
  src/Aspire.Cli/Interaction/IInteractionService.cs
  src/Aspire.Cli/Interaction/InteractionService.cs
  src/Aspire.Cli/NuGetPackageCache.cs
  src/Aspire.Cli/Projects/ProjectLocator.cs
  src/Aspire.Cli/Utils/AppHostHelper.cs
  src/Aspire.Cli/Utils/OutputCollector.cs
  tests/Aspire.Cli.Tests/Commands/AddCommandTests.cs
  tests/Aspire.Cli.Tests/Commands/NewCommandTests.cs
  tests/Aspire.Cli.Tests/Commands/PublishCommandTests.cs
  tests/Aspire.Cli.Tests/Commands/RunCommandTests.cs
  tests/Aspire.Cli.Tests/Projects/ProjectLocatorTests.cs
  tests/Aspire.Cli.Tests/TestServices/TestDotNetCliRunner.cs
Labels: area-cli

#8947 Use assets collection to import blazor.web.js
  src/Aspire.ProjectTemplates/templates/aspire-starter/9.1/Aspire-StarterApplication.1.Web/Components/App.razor
  src/Aspire.ProjectTemplates/templates/aspire-starter/9.2/Aspire-StarterApplication.1.Web/Components/App.razor
Labels: area-templates

#8830 Updating Docker Image tags
  src/Aspire.Hosting.Azure.ServiceBus/ServiceBusEmulatorContainerImageTags.cs
  src/Aspire.Hosting.Elasticsearch/ElasticsearchContainerImageTags.cs
  src/Aspire.Hosting.Kafka/KafkaContainerImageTags.cs
  src/Aspire.Hosting.Keycloak/KeycloakContainerImageTags.cs
  src/Aspire.Hosting.Milvus/MilvusContainerImageTags.cs
  src/Aspire.Hosting.MySql/MySqlContainerImageTags.cs
  src/Aspire.Hosting.Nats/NatsContainerImageTags.cs
  src/Aspire.Hosting.Oracle/OracleContainerImageTags.cs
  src/Aspire.Hosting.PostgreSQL/PostgresContainerImageTags.cs
  src/Aspire.Hosting.Qdrant/QdrantContainerImageTags.cs
  src/Aspire.Hosting.RabbitMQ/RabbitMQContainerImageTags.cs
Labels: area-integrations

#8944 Fix resource relationship related bugs
  playground/Stress/Stress.AppHost/Program.cs
  src/Aspire.Dashboard/Components/Controls/ResourceDetails.razor
  src/Aspire.Dashboard/Components/Controls/ResourceDetails.razor.cs
  src/Aspire.Dashboard/Model/ResourceDetailRelationshipViewModel.cs
  src/Aspire.Dashboard/Model/ResourceGraph/ResourceGraphMapper.cs
  tests/Aspire.Dashboard.Tests/Model/ResourceGraphMapperTests.cs
  tests/Shared/DashboardModel/ModelTestHelpers.cs
Labels: area-dashboard

#8958 [tests] Fix flaky test Aspire.Hosting.Tests.DistributedApplicationTests.ProxylessAndProxiedEndpointBothWorkOnSameResource
  tests/Aspire.Hosting.Tests/DistributedApplicationTests.cs
Labels: area-app-model

#8959 [tests] Disable some quarantined tests with ActiveIssue
  tests/Aspire.Hosting.Testing.Tests/TestingFactoryTests.cs
  tests/Aspire.Hosting.Tests/Codespaces/CodespacesUrlRewriterTests.cs
  tests/Aspire.Hosting.Tests/MSBuildTests.cs
Labels: needs-area-label

#8960 [tests] MongoDbFunctionalTests.VerifyWithInitBindMount - create bindmount path before writing to it
  tests/Aspire.Hosting.MongoDB.Tests/MongoDbFunctionalTests.cs
Labels: area-app-model

#8973 [tests] Fix flaky DistributedApplicationTests.ProxylessAndProxiedEndpointBothWorkOnSameResource
  .github/workflows/tests-outerloop.yml
  tests/Aspire.Hosting.Tests/DistributedApplicationTests.cs
Labels: area-app-model, testing ☑️

#8986 Improve cancellation handling and add certificate exception class
  src/Aspire.Cli/Certificates/CertificateService.cs
  src/Aspire.Cli/Commands/AddCommand.cs
  src/Aspire.Cli/Commands/NewCommand.cs
  src/Aspire.Cli/Commands/PublishCommand.cs
  src/Aspire.Cli/Commands/RunCommand.cs
  src/Aspire.Cli/Interaction/IInteractionService.cs
  src/Aspire.Cli/Interaction/InteractionService.cs
  tests/Aspire.Cli.Tests/Commands/NewCommandTests.cs
  tests/Aspire.Cli.Tests/Commands/RunCommandTests.cs
Labels: area-cli

#8977 Implement IValueWithReferences in IAzureKeyVaultSecretReference
  src/Aspire.Hosting.Azure/IAzureKeyVaultSecretReference.cs
Labels: area-integrations

#8988 Fix path separators.
  src/Aspire.Cli/Projects/ProjectLocator.cs
  tests/Aspire.Cli.Tests/Projects/ProjectLocatorTests.cs
Labels: area-cli
