Repository dotnet/aspire, pull requests merged in 2025-10, with the labels that each got.

#11758 Fix GenAI visualizer when span is missing peer attribute
  playground/Stress/Stress.ApiService/Program.cs
  src/Aspire.Dashboard/Model/GenAI/GenAIVisualizerDialogViewModel.cs
  tests/Aspire.Dashboard.Components.Tests/Controls/GenAIVisualizerDialogTests.cs
Labels: area-dashboard

#11759 Fix console logs race condition
  src/Aspire.Dashboard/Components/Pages/ConsoleLogs.razor.cs
Labels: area-dashboard

#11752 Update retry in Kusto emulator actions to handle any non-permanent error
  src/Aspire.Hosting.Azure.Kusto/AzureKustoBuilderExtensions.cs
  src/Aspire.Hosting.Azure.Kusto/AzureKustoEmulatorResiliencePipelines.cs
  tests/Aspire.Hosting.Azure.Kusto.Tests/KustoResiliencePipelinesTests.cs
Labels: area-integrations, community-contribution

#11746 Add session message notification type to IDE protocol
  docs/specs/IDE-execution.md
Labels: area-tooling, area-orchestrator

#11831 Ensure OutputPath is created in ResourceContainerImageBuilder
  src/Aspire.Hosting/Publishing/ResourceContainerImageBuilder.cs
  tests/Aspire.Hosting.Tests/Publishing/ResourceContainerImageBuilderTests.cs
Labels: area-app-model

#11835 Fix message bar display when sidebar is open
  src/Aspire.Dashboard/Components/Layout/MainLayout.razor
  src/Aspire.Dashboard/Components/Layout/MainLayout.razor.css
  src/Aspire.Dashboard/wwwroot/css/app.css
Labels: area-dashboard

#11840 Add WithChildRelationship methods for parent-child relationships
  src/Aspire.Hosting/ResourceBuilderExtensions.cs
  tests/Aspire.Hosting.Tests/Orchestrator/ApplicationOrchestratorTests.cs
  tests/Aspire.Hosting.Tests/Orchestrator/RelationshipEvaluatorTests.cs
Labels: area-integrations, community-contribution

#11836 EndpointReference resolution waits for allocation to resolve values
  playground/DevTunnels/DevTunnels.AppHost/AppHost.cs
  src/Aspire.Hosting.DevTunnels/DevTunnelResource.cs
  src/Aspire.Hosting.DevTunnels/DevTunnelResourceBuilderExtensions.cs
  src/Aspire.Hosting/ApplicationModel/EndpointAnnotation.cs
  src/Aspire.Hosting/ApplicationModel/EndpointReference.cs
  src/Aspire.Hosting/ApplicationModel/ValueSnapshot.cs
  tests/Aspire.Hosting.DevTunnels.Tests/DevTunnelResourceBuilderExtensionsTests.cs
  tests/Aspire.Hosting.Tests/Dashboard/DashboardLifecycleHookTests.cs
  tests/Aspire.Hosting.Tests/EndpointReferenceTests.cs
  tests/Aspire.Hosting.Tests/ValueSnapshotTests.cs
Labels: breaking-change

#11876 Queue document update
  src/Aspire.Hosting.Azure.Storage/AzureQueueStorageQueueResource.cs
  src/Components/Aspire.Azure.Storage.Queues/AzureStorageQueueSettings.cs
  src/Components/Aspire.Azure.Storage.Queues/AzureStorageQueuesSettings.cs
  src/Components/Aspire.Azure.Storage.Queues/ConfigurationSchema.json
Labels: area-integrations, community-contribution

#11891 support single-file apphosts
  extension/src/dcp/types.ts
  extension/src/debugger/languages/dotnet.ts
  extension/src/debugger/languages/python.ts
  extension/src/server/interactionService.ts
  extension/src/test/dotnetDebugger.test.ts
  extension/src/utils/AspireTerminalProvider.ts
  src/Aspire.Cli/Commands/RunCommand.cs
  src/Aspire.Cli/Program.cs
Labels: area-extension

#11898 ignore focus out in string prompts
  extension/src/server/interactionService.ts
Labels: needs-area-label
