Repository dotnet/aspire, pull requests merged in 2025-02, with the labels that each got.

#4269 Update references to VS 2022 Preview to use version 17.11
  docs/machine-requirements.md
  docs/tips-and-known-issues.md
  docs/using-latest-daily.md
Labels: area-engineering-systems

#4681 Adding area-owners.md file
  docs/area-owners.md
  docs/contributing.md
Labels: area-engineering-systems

#6386 use nameof CallerArgumentExpression
  src/Vendoring/OpenTelemetry.Instrumentation.SqlClient/Shared/Guard.cs
  src/Vendoring/OpenTelemetry.Instrumentation.StackExchangeRedis/Shared/Guard.cs
  src/Vendoring/OpenTelemetry.Shared/Guard.cs
Labels: community-contribution

#6732 Add frameworks classifications for templates
  src/Aspire.ProjectTemplates/templates/aspire-mstest/.template.config/template.json
  src/Aspire.ProjectTemplates/templates/aspire-nunit/.template.config/template.json
  src/Aspire.ProjectTemplates/templates/aspire-starter/.template.config/template.json
  src/Aspire.ProjectTemplates/templates/aspire-xunit/.template.config/template.json
Labels: community-contribution

#6378 Put examples docs in remark to be visible in Visual Studio
  src/Aspire.Hosting.Elasticsearch/ElasticsearchBuilderExtensions.cs
  src/Aspire.Hosting.Garnet/GarnetBuilderExtensions.cs
  src/Aspire.Hosting.Keycloak/KeycloakResourceBuilderExtensions.cs
  src/Aspire.Hosting.Milvus/MilvusBuilderExtensions.cs
  src/Aspire.Hosting.PostgreSQL/PostgresBuilderExtensions.cs
  src/Aspire.Hosting.Python/PythonAppResourceBuilderExtensions.cs
  src/Aspire.Hosting.RabbitMQ/RabbitMQBuilderExtensions.cs
  src/Aspire.Hosting.Valkey/ValkeyBuilderExtensions.cs
Labels: community-contribution

#6975 Allow sorting resource attributes in resource details, don't sort masked values
  src/Aspire.Dashboard/Components/Controls/PropertyGrid.razor.cs
  src/Aspire.Dashboard/Components/Controls/ResourceDetails.razor
Labels: area-dashboard, needs-author-action

#7169 Rename projectDirectory to appDirectory in AddPythonApp
  src/Aspire.Hosting.Python/PythonAppResource.cs
  src/Aspire.Hosting.Python/PythonAppResourceBuilderExtensions.cs
  tests/Aspire.Hosting.Python.Tests/PythonPublicApiTests.cs
Labels: needs-author-action, community-contribution

#7449 Indenting in notification service logging
  src/Aspire.Hosting/ApplicationModel/ResourceNotificationService.cs
Labels: area-app-model

#7329 Re-execute envvar and arg callbacks when restarting resources
  src/Aspire.Hosting/Dcp/AppResource.cs
  src/Aspire.Hosting/Dcp/DcpExecutor.cs
  src/Aspire.Hosting/Dcp/Model/ModelCommon.cs
  src/Aspire.Hosting/Orchestrator/ApplicationOrchestrator.cs
  tests/Aspire.Hosting.Tests/Dcp/DcpExecutorTests.cs
  tests/Aspire.Hosting.Tests/Dcp/TestKubernetesService.cs
Labels: area-app-model

#7454 Shared helper method for masking in dashboard
  src/Aspire.Dashboard/Components/Controls/GridValue.razor
  src/Aspire.Dashboard/Components/ResourcesGridColumns/SourceColumnDisplay.razor
  src/Aspire.Dashboard/Utils/DashboardUIHelpers.cs
Labels: area-dashboard

#7458 Re-execute envvar and arg callbacks when restarting resources V2
  src/Aspire.Hosting/ApplicationModel/ResourceExtensions.cs
  src/Aspire.Hosting/Dcp/AppResource.cs
  src/Aspire.Hosting/Dcp/DcpExecutor.cs
  src/Aspire.Hosting/Dcp/Model/ModelCommon.cs
  src/Aspire.Hosting/Orchestrator/ApplicationOrchestrator.cs
  src/Aspire.Hosting/Publishing/ManifestPublishingContext.cs
  tests/Aspire.Hosting.Tests/Dcp/DcpExecutorTests.cs
  tests/Aspire.Hosting.Tests/Dcp/TestKubernetesService.cs
  tests/Aspire.Hosting.Tests/Utils/ArgumentEvaluator.cs
  tests/Aspire.Hosting.Tests/Utils/EnvironmentVariableEvaluator.cs
Labels: area-app-model

#7479 Line up grid column header with content
  src/Aspire.Dashboard/Resources/Commands.Designer.cs
  src/Aspire.Dashboard/wwwroot/css/app.css
Labels: area-dashboard

#7419 Clear button on ConsoleLogs page
  src/Aspire.Dashboard/Components/Controls/AspireMenuButton.razor
  src/Aspire.Dashboard/Components/Controls/AspireMenuButton.razor.cs
  src/Aspire.Dashboard/Components/Controls/ClearSignalsButton.razor.cs
  src/Aspire.Dashboard/Components/Pages/ConsoleLogs.razor
  src/Aspire.Dashboard/Components/Pages/ConsoleLogs.razor.cs
  src/Aspire.Dashboard/Model/MenuButtonItem.cs
  src/Aspire.Dashboard/Otlp/Storage/ApplicationKey.cs
  src/Aspire.Dashboard/Utils/BrowserStorageKeys.cs
  tests/Aspire.Dashboard.Components.Tests/Pages/ConsoleLogsTests.cs
  tests/Aspire.Dashboard.Components.Tests/Shared/TestTimeProvider.cs
Labels: area-dashboard, community-contribution

#6596 Update schema
  Aspire.sln
  src/Schema/aspire-8.0.json
Labels: area-app-model

#7490 Clear console logs from settings dialog
  src/Aspire.Dashboard/Components/Dialogs/SettingsDialog.razor
  src/Aspire.Dashboard/Components/Dialogs/SettingsDialog.razor.cs
  src/Aspire.Dashboard/Components/Pages/ConsoleLogs.razor.cs
  src/Aspire.Dashboard/DashboardWebApplication.cs
  src/Aspire.Dashboard/Model/ConsoleLogsFilters.cs
  src/Aspire.Dashboard/Model/ConsoleLogsManager.cs
  src/Aspire.Dashboard/Model/ThemeManager.cs
  src/Aspire.Dashboard/Resources/Dialogs.Designer.cs
  src/Aspire.Dashboard/Resources/Dialogs.resx
  src/Aspire.Dashboard/Resources/xlf/Dialogs.cs.xlf
  src/Aspire.Dashboard/Resources/xlf/Dialogs.de.xlf
  src/Aspire.Dashboard/Resources/xlf/Dialogs.es.xlf
  src/Aspire.Dashboard/Resources/xlf/Dialogs.fr.xlf
  src/Aspire.Dashboard/Resources/xlf/Dialogs.it.xlf
  src/Aspire.Dashboard/Resources/xlf/Dialogs.ja.xlf
  src/Aspire.Dashboard/Resources/xlf/Dialogs.ko.xlf
  src/Aspire.Dashboard/Resources/xlf/Dialogs.pl.xlf
  src/Aspire.Dashboard/Resources/xlf/Dialogs.pt-BR.xlf
  src/Aspire.Dashboard/Resources/xlf/Dialogs.ru.xlf
  src/Aspire.Dashboard/Resources/xlf/Dialogs.tr.xlf
  src/Aspire.Dashboard/Resources/xlf/Dialogs.zh-Hans.xlf
  src/Aspire.Dashboard/Resources/xlf/Dialogs.zh-Hant.xlf
  tests/Aspire.Dashboard.Components.Tests/Pages/ConsoleLogsTests.cs
Labels: area-dashboard

#7495 Fix thready safety issue on console logs page
  src/Aspire.Dashboard/Components/Pages/ConsoleLogs.razor.cs
Labels: area-dashboard

#7496 Improve error handling of health monitoring background tasks
  src/Aspire.Hosting/Health/ResourceHealthCheckService.cs
Labels: area-app-model

#7498 Don't add relationship to parent with WaitFor
  src/Aspire.Hosting/ResourceBuilderExtensions.cs
  tests/Aspire.Hosting.Tests/WaitForTests.cs
Labels: area-app-model

#7507 Support comments in user secrets
  src/Aspire.Hosting.Azure/Provisioning/Provisioners/AzureProvisioner.cs
Labels: community-contribution

#7497 Display launchSettings.json args in dashboard
  src/Aspire.Hosting/Dcp/DcpExecutor.cs
  src/Shared/LaunchProfiles/LaunchProfileExtensions.cs
  tests/Aspire.Hosting.Tests/Dcp/DcpExecutorTests.cs
  tests/testproject/TestProject.ServiceA/Properties/launchSettings.json
Labels: area-app-model

#7526 Fix dashboard formatting tests
  tests/Aspire.Dashboard.Components.Tests/Controls/PlotlyChartTests.cs
  tests/Aspire.Dashboard.Tests/FormatHelpersTests.cs
Labels: area-dashboard

#7608 Fix metrics instruments not updating in mobile view
  src/Aspire.Dashboard/Components/Controls/TreeMetricSelector.razor.cs
  src/Aspire.Dashboard/Components/Pages/Metrics.razor.cs
  src/Aspire.Dashboard/Components/Pages/Metrics.razor.css
Labels: area-dashboard

#7639 Fix console logs menu buttons not updated with resource
  src/Aspire.Dashboard/Components/Pages/ConsoleLogs.razor
  src/Aspire.Dashboard/Components/Pages/ConsoleLogs.razor.cs
  tests/Aspire.Dashboard.Components.Tests/Pages/ConsoleLogsTests.cs
  tests/Shared/DashboardModel/ModelTestHelpers.cs
Labels: area-dashboard

#7659 [release/9.1] Bump the azure group with 5 updates (#7646)
  Directory.Packages.props
Labels: Servicing-approved

#7657 [release/9.1] Update Microsoft.Extensions.AI to 9.3.0-preview.1.25114.11 (#7643)
  Directory.Packages.props
  eng/Versions.props
  global.json
  playground/OpenAIEndToEnd/OpenAIEndToEnd.WebStory/Components/Pages/UseIChatClient.razor
  src/Components/Aspire.OpenAI/MEAIPackageOverrides.targets
  tests/Aspire.Azure.AI.OpenAI.Tests/AspireAzureOpenAIClientBuilderChatClientExtensionsTests.cs
  tests/Aspire.Azure.AI.OpenAI.Tests/AspireAzureOpenAIClientBuilderEmbeddingGeneratorExtensionsTests.cs
  tests/Aspire.OpenAI.Tests/AspireOpenAIClientBuilderChatClientExtensionsTests.cs
  tests/Aspire.OpenAI.Tests/AspireOpenAIClientBuilderEmbeddingGeneratorExtensionsTests.cs
Labels: Servicing-approved

#7635 fix casing of CosmosDB
  playground/AzureFunctionsEndToEnd/AzureFunctionsEndToEnd.AppHost/AzureFunctionsEndToEnd.AppHost.csproj
Labels: area-engineering-systems

#7661 [release/9.1] Localized file check-in by OneLocBuild Task: Build definition ID 1309…
  src/Aspire.ProjectTemplates/templates/aspire-starter/.template.config/localize/templatestrings.ko.json
  src/Aspire.ProjectTemplates/templates/aspire-xunit/.template.config/localize/templatestrings.zh-Hant.json
Labels: Servicing-approved

#7650 Add WaitBehavior to WaitForResourceHealthyAsync
  src/Aspire.Hosting/ApplicationModel/ResourceNotificationService.cs
  tests/Aspire.Hosting.Tests/WaitForTests.cs
Labels: area-app-model, area-app-testing

#7668 Mitchdenny/wait-behavior-follow-up
  src/Aspire.Hosting/ApplicationModel/ResourceNotificationService.cs
  src/Aspire.Hosting/ApplicationModel/WaitAnnotation.cs
  src/Aspire.Hosting/DistributedApplicationBuilder.cs
  src/Aspire.Hosting/ResourceBuilderExtensions.cs
  tests/Aspire.Hosting.Tests/WaitForTests.cs
Labels: area-app-testing

#7671 Create Login page EditContext before async work
  src/Aspire.Dashboard/Components/Pages/Login.razor.cs
  tests/Aspire.Dashboard.Components.Tests/Pages/LoginTests.cs
Labels: area-dashboard

#7626 Refactor AspireStore APIs
  src/Aspire.Hosting.Azure.EventHubs/AzureEventHubsExtensions.cs
  src/Aspire.Hosting.Azure.ServiceBus/AzureServiceBusExtensions.cs
  src/Aspire.Hosting/ApplicationModel/AspireStore.cs
  src/Aspire.Hosting/ApplicationModel/AspireStoreExtensions.cs
  src/Aspire.Hosting/ApplicationModel/IAspireStore.cs
  src/Aspire.Hosting/Aspire.Hosting.csproj
  src/Aspire.Hosting/DistributedApplicationBuilder.cs
  src/Aspire.Hosting/Utils/HashDigestStream.cs
  tests/Aspire.Hosting.Tests/AspireStoreTests.cs
Labels: area-app-model

#7630 Correct `ResourceReadyEvent` filename
  src/Aspire.Hosting/ApplicationModel/ResourceReadyEvent.cs
Labels: community-contribution

#7629 Add `EndpointProperty.HostAndPort`
  src/Aspire.Hosting.Azure.EventHubs/AzureEventHubsResource.cs
  src/Aspire.Hosting.Azure.ServiceBus/AzureServiceBusResource.cs
  src/Aspire.Hosting.Elasticsearch/ElasticsearchResource.cs
  src/Aspire.Hosting.Garnet/GarnetResource.cs
  src/Aspire.Hosting.Kafka/KafkaBuilderExtensions.cs
  src/Aspire.Hosting.Kafka/KafkaServerResource.cs
  src/Aspire.Hosting.MongoDB/MongoDBServerResource.cs
  src/Aspire.Hosting.Nats/NatsServerResource.cs
  src/Aspire.Hosting.Oracle/OracleDatabaseServerResource.cs
  src/Aspire.Hosting.RabbitMQ/RabbitMQServerResource.cs
  src/Aspire.Hosting.Redis/RedisResource.cs
  src/Aspire.Hosting.Valkey/ValkeyResource.cs
  src/Aspire.Hosting/ApplicationModel/EndpointReference.cs
  src/Aspire.Hosting/ApplicationModel/ExpressionResolver.cs
  tests/Aspire.Hosting.Azure.Tests/AzureProvisioningResourceExtensionsTests.cs
  tests/Aspire.Hosting.Tests/ExpressionResolverTests.cs
Labels: community-contribution

#7704 Improve default codespace experience with devcontainer.json location change
  .devcontainer/devcontainer.json
Labels: area-engineering-systems

#7662 Hide secrets in source tooltip, correct ExpressionResolver logic for non-containers
  src/Aspire.Dashboard/Components/Controls/GridValue.razor
  src/Aspire.Dashboard/Components/ResourcesGridColumns/SourceColumnDisplay.razor
  src/Aspire.Dashboard/Model/ResourceSourceViewModel.cs
  src/Aspire.Dashboard/Utils/DashboardUIHelpers.cs
  src/Aspire.Hosting/ApplicationModel/ExpressionResolver.cs
  src/Aspire.Hosting/ApplicationModel/ReferenceExpression.cs
  tests/Aspire.Dashboard.Tests/Model/ResourceSourceViewModelTests.cs
  tests/Aspire.Hosting.Tests/ExpressionResolverTests.cs
Labels: area-dashboard, security 🔐

#7711 Fix arg annotations when running in IDE mode
  src/Aspire.Hosting/Dcp/DcpExecutor.cs
  tests/Aspire.Hosting.Tests/Dcp/DcpExecutorTests.cs
Labels: area-app-model

#7716 Resolve DistributedApplicationResourceBuilder<ResourceWithConnectionStringSurrogate> correctly in args evaluation
  src/Aspire.Hosting/ApplicationModel/ResourceExtensions.cs
  tests/Aspire.Hosting.Tests/ResourceExtensionsTests.cs
Labels: area-app-model

#7712 Fix DCP logs ending with a new line
  src/Aspire.Hosting/Dcp/DcpHost.cs
Labels: area-app-model

#7709 Update WaitForResourceHealthyAsync to use DefaultWaitBehavior
  src/Aspire.Hosting/ApplicationModel/ResourceNotificationService.cs
  tests/Aspire.Hosting.Tests/WaitForTests.cs
Labels: community-contribution

#7741 fix access to a static member of a type via a derived type
  src/Aspire.Hosting/Devcontainers/Codespaces/CodespacesOptions.cs
  src/Aspire.Hosting/Devcontainers/Codespaces/CodespacesUrlRewriter.cs
  src/Aspire.Hosting/Devcontainers/DevcontainerSettingsWriter.cs
  src/Aspire.Hosting/DistributedApplicationBuilderExtensions.cs
Labels: community-contribution

#7754 docs: fix a typo in comment
  src/Aspire.Dashboard/Authentication/OpenIdConnect/AuthorizationPolicyBuilderExtensions.cs
Labels: community-contribution

#7599 Reapply Redis password
  playground/AzureContainerApps/AzureContainerApps.AppHost/api.module.bicep
  playground/AzureContainerApps/AzureContainerApps.AppHost/aspire-manifest.json
  playground/AzureContainerApps/AzureContainerApps.AppHost/cache.module.bicep
  playground/ProxylessEndToEnd/ProxylessEndToEnd.AppHost/aspire-manifest.json
  playground/Redis/Redis.AppHost/Program.cs
  playground/Redis/Redis.AppHost/aspire-manifest.json
  playground/TestShop/TestShop.AppHost/aspire-manifest.json
  src/Aspire.Hosting.Azure.AppContainers/AzureContainerAppsInfrastructure.cs
  src/Aspire.Hosting.Redis/RedisBuilderExtensions.cs
  src/Aspire.Hosting.Redis/RedisResource.cs
  tests/Aspire.Hosting.Azure.Tests/AzureBicepResourceTests.cs
  tests/Aspire.Hosting.Azure.Tests/AzureContainerAppsTests.cs
  tests/Aspire.Hosting.Azure.Tests/AzureRedisExtensionsTests.cs
  tests/Aspire.Hosting.Redis.Tests/AddRedisTests.cs
  tests/Aspire.Hosting.Redis.Tests/RedisFunctionalTests.cs
  tests/Aspire.Hosting.Tests/DistributedApplicationTests.cs
  tests/Aspire.Hosting.Tests/ManifestGenerationTests.cs
Labels: area-integrations, community-contribution, security 🔐

#7784 Add metrics overflow warning to the dashboard
  playground/Stress/Stress.ApiService/Program.cs
  playground/Stress/Stress.ApiService/TestMetrics.cs
  playground/Stress/Stress.AppHost/Program.cs
  src/Aspire.Dashboard/Components/Controls/Chart/ChartContainer.razor
  src/Aspire.Dashboard/Components/Controls/Chart/ChartContainer.razor.cs
  src/Aspire.Dashboard/Components/Controls/Chart/ChartContainer.razor.css
  src/Aspire.Dashboard/Components/Controls/Chart/ChartFilters.razor.cs
  src/Aspire.Dashboard/Otlp/Model/OtlpInstrument.cs
  src/Aspire.Dashboard/Otlp/Storage/TelemetryRepository.cs
  src/Aspire.Dashboard/Resources/ControlsStrings.Designer.cs
  src/Aspire.Dashboard/Resources/ControlsStrings.resx
  src/Aspire.Dashboard/Resources/xlf/ControlsStrings.cs.xlf
  src/Aspire.Dashboard/Resources/xlf/ControlsStrings.de.xlf
  src/Aspire.Dashboard/Resources/xlf/ControlsStrings.es.xlf
  src/Aspire.Dashboard/Resources/xlf/ControlsStrings.fr.xlf
  src/Aspire.Dashboard/Resources/xlf/ControlsStrings.it.xlf
  src/Aspire.Dashboard/Resources/xlf/ControlsStrings.ja.xlf
  src/Aspire.Dashboard/Resources/xlf/ControlsStrings.ko.xlf
  src/Aspire.Dashboard/Resources/xlf/ControlsStrings.pl.xlf
  src/Aspire.Dashboard/Resources/xlf/ControlsStrings.pt-BR.xlf
  src/Aspire.Dashboard/Resources/xlf/ControlsStrings.ru.xlf
  src/Aspire.Dashboard/Resources/xlf/ControlsStrings.tr.xlf
  src/Aspire.Dashboard/Resources/xlf/ControlsStrings.zh-Hans.xlf
  src/Aspire.Dashboard/Resources/xlf/ControlsStrings.zh-Hant.xlf
  tests/Aspire.Dashboard.Tests/TelemetryRepositoryTests/MetricsTests.cs
Labels: area-dashboard

#7798 Report health checks error from CheckHealthAsync to the user
  src/Aspire.Hosting/Health/ResourceHealthCheckService.cs
  tests/Aspire.Hosting.Tests/Health/ResourceHealthCheckServiceTests.cs
Labels: area-app-model

#7821 Implement AppHost runner and cleanup temporary files
  src/Aspire.Cli/AppHostRunner.cs
  src/Aspire.Cli/Aspire.Cli.csproj
  src/Aspire.Cli/ExitCodeConstants.cs
  src/Aspire.Cli/Program.cs
Labels: area-cli

#7800 Resources graph
  src/Aspire.Dashboard/Components/Controls/Chart/ChartContainer.razor.css
  src/Aspire.Dashboard/Components/Layout/DesktopNavMenu.razor
  src/Aspire.Dashboard/Components/Layout/DesktopNavMenu.razor.cs
  src/Aspire.Dashboard/Components/Pages/Resources.razor
  src/Aspire.Dashboard/Components/Pages/Resources.razor.cs
  src/Aspire.Dashboard/Components/Pages/Resources.razor.css
  src/Aspire.Dashboard/Model/ResourceGraph/IconDto.cs
  src/Aspire.Dashboard/Model/ResourceGraph/ResourceDto.cs
  src/Aspire.Dashboard/Model/ResourceGraph/ResourceGraphMapper.cs
  src/Aspire.Dashboard/Model/ResourceStateViewModel.cs
  src/Aspire.Dashboard/Utils/DashboardUrls.cs
  src/Aspire.Dashboard/wwwroot/js/app-resourcegraph.js
  src/Aspire.Dashboard/wwwroot/js/app.js
  src/Aspire.Dashboard/wwwroot/js/d3.v7.min.js
  src/Aspire.Hosting.Redis/RedisBuilderExtensions.cs
  tests/Aspire.Dashboard.Components.Tests/Shared/MetricsSetupHelpers.cs
  tests/Aspire.Dashboard.Components.Tests/Shared/ResourceSetupHelpers.cs
Labels: area-dashboard

#7782 Hide limit reached messages on remove
  playground/Stress/Stress.ApiService/Program.cs
  playground/Stress/Stress.ApiService/TraceCreator.cs
  src/Aspire.Dashboard/Components/Pages/StructuredLogs.razor.cs
  src/Aspire.Dashboard/Components/Pages/Traces.razor.cs
  src/Aspire.Dashboard/Otlp/Model/OtlpHelpers.cs
  src/Aspire.Dashboard/Otlp/Storage/PagedResult.cs
  src/Aspire.Dashboard/Otlp/Storage/TelemetryRepository.cs
  src/Aspire.Dashboard/Utils/DashboardUIHelpers.cs
Labels: area-dashboard

#7309 Support multiple domains via ConfigureCustomDomain
  src/Aspire.Hosting.Azure.AppContainers/ContainerAppExtensions.cs
  tests/Aspire.Hosting.Azure.Tests/AzureContainerAppsTests.cs
Labels: community-contribution

#7527 Reduce thrown exceptions
  src/Aspire.Hosting/Dcp/DcpExecutor.cs
  src/Aspire.Hosting/Dcp/DcpPipelineBuilder.cs
  src/Aspire.Hosting/Health/ResourceHealthCheckService.cs
  tests/Aspire.Hosting.Tests/Dcp/DcpExecutorTests.cs
Labels: area-app-model
